/* AUTO-GENERATED by tools/prepare-content-packs.mjs. Do not edit manually. */
export const CONTENT_PACK_CATALOG = {
  "fit-awena": {
    "version": "2026.09.01.1",
    "totalBytes": 6394409,
    "files": [
      {
        "path": "exercise-media/bench/awena-step-00-setup.webp",
        "bytes": 100963
      },
      {
        "path": "exercise-media/bench/awena-step-01-start.webp",
        "bytes": 267018
      },
      {
        "path": "exercise-media/bench/awena-step-02-descent.webp",
        "bytes": 292833
      },
      {
        "path": "exercise-media/bench/awena-step-03-bottom.webp",
        "bytes": 271190
      },
      {
        "path": "exercise-media/bench/awena-step-04-press.webp",
        "bytes": 272238
      },
      {
        "path": "exercise-media/burpee/awena-01.webp",
        "bytes": 62139
      },
      {
        "path": "exercise-media/burpee/awena-02.webp",
        "bytes": 59887
      },
      {
        "path": "exercise-media/burpee/awena-03.webp",
        "bytes": 116321
      },
      {
        "path": "exercise-media/burpee/awena-04.webp",
        "bytes": 71097
      },
      {
        "path": "exercise-media/burpee/awena-05.webp",
        "bytes": 62446
      },
      {
        "path": "exercise-media/pushup/awena-high.webp",
        "bytes": 50028
      },
      {
        "path": "exercise-media/pushup/awena-low.webp",
        "bytes": 43612
      },
      {
        "path": "exercise-media/pushup/awena-step-01-start.webp",
        "bytes": 90623
      },
      {
        "path": "exercise-media/pushup/awena-step-02-descent.webp",
        "bytes": 74574
      },
      {
        "path": "exercise-media/pushup/awena-step-03-bottom.webp",
        "bytes": 69437
      },
      {
        "path": "exercise-media/pushup/awena-step-04-press.webp",
        "bytes": 78255
      },
      {
        "path": "motions/awena/premium/bench/frames/frame-01.webp",
        "bytes": 54111
      },
      {
        "path": "motions/awena/premium/bench/frames/frame-02.webp",
        "bytes": 48022
      },
      {
        "path": "motions/awena/premium/bench/frames/frame-03.webp",
        "bytes": 54667
      },
      {
        "path": "motions/awena/premium/bench/frames/frame-04.webp",
        "bytes": 52342
      },
      {
        "path": "motions/awena/premium/bench/frames/frame-05.webp",
        "bytes": 49506
      },
      {
        "path": "motions/awena/premium/bench/motion.mp4",
        "bytes": 362170
      },
      {
        "path": "motions/awena/premium/bench/poster.webp",
        "bytes": 267018
      },
      {
        "path": "motions/awena/premium/burpee/motion.webm",
        "bytes": 31016
      },
      {
        "path": "motions/awena/premium/burpee/poster.webp",
        "bytes": 62139
      },
      {
        "path": "motions/awena/premium/curl/frames/frame-01.webp",
        "bytes": 41270
      },
      {
        "path": "motions/awena/premium/curl/frames/frame-02.webp",
        "bytes": 38728
      },
      {
        "path": "motions/awena/premium/curl/frames/frame-03.webp",
        "bytes": 41337
      },
      {
        "path": "motions/awena/premium/curl/frames/frame-04.webp",
        "bytes": 38459
      },
      {
        "path": "motions/awena/premium/curl/frames/frame-05.webp",
        "bytes": 40911
      },
      {
        "path": "motions/awena/premium/curl/poster.webp",
        "bytes": 41270
      },
      {
        "path": "motions/awena/premium/deadlift/poster.webp",
        "bytes": 41157
      },
      {
        "path": "motions/awena/premium/pushup/motion.webm",
        "bytes": 160291
      },
      {
        "path": "motions/awena/premium/pushup/poster.webp",
        "bytes": 5238
      },
      {
        "path": "motions/awena/premium/squat/motion.mp4",
        "bytes": 159802
      },
      {
        "path": "motions/awena/premium/squat/poster.webp",
        "bytes": 14133
      },
      {
        "path": "tickers/free-awena.webp",
        "bytes": 499894
      },
      {
        "path": "tickers/full-awena.webp",
        "bytes": 543394
      },
      {
        "path": "tickers/legs-awena.webp",
        "bytes": 631229
      },
      {
        "path": "tickers/pull-awena.webp",
        "bytes": 575650
      },
      {
        "path": "tickers/push-awena.webp",
        "bytes": 557994
      }
    ]
  },
  "navigation-music": {
    "version": "2026.09.01.1",
    "totalBytes": 37651950,
    "files": [
      {
        "path": "arena_uprising_nav.webm",
        "bytes": 1561365
      },
      {
        "path": "bass_bet_nav.webm",
        "bytes": 1507685
      },
      {
        "path": "bass_nebula_nav.webm",
        "bytes": 2320763
      },
      {
        "path": "bet_bass_nav.webm",
        "bytes": 970576
      },
      {
        "path": "darts_vanguard_nav.webm",
        "bytes": 1128215
      },
      {
        "path": "distorted_bed_nav.webm",
        "bytes": 1452683
      },
      {
        "path": "dreamwave_horizon_nav.webm",
        "bytes": 1121473
      },
      {
        "path": "garage_impact_nav.webm",
        "bytes": 985531
      },
      {
        "path": "heartwave_anthem_nav.webm",
        "bytes": 1208648
      },
      {
        "path": "linear_skyline_nav.webm",
        "bytes": 1336073
      },
      {
        "path": "midnight_enigma_nav.webm",
        "bytes": 1016308
      },
      {
        "path": "ms_electrodyn_2_nav.webm",
        "bytes": 1203710
      },
      {
        "path": "ms_electrodyn_nav.webm",
        "bytes": 1360459
      },
      {
        "path": "neon_caravan_nav.webm",
        "bytes": 1306372
      },
      {
        "path": "night_drive_nav.webm",
        "bytes": 2205340
      },
      {
        "path": "obsidian_flow_nav.webm",
        "bytes": 1678321
      },
      {
        "path": "orbital_echo_nav.webm",
        "bytes": 1641439
      },
      {
        "path": "oriental_surge_nav.webm",
        "bytes": 973666
      },
      {
        "path": "pixel_ascension_nav.webm",
        "bytes": 1279390
      },
      {
        "path": "scoring_overture_nav.webm",
        "bytes": 1333372
      },
      {
        "path": "shadow_frequency_nav.webm",
        "bytes": 1267834
      },
      {
        "path": "steel_reactor_nav.webm",
        "bytes": 1393399
      },
      {
        "path": "stellar_riot_nav.webm",
        "bytes": 1439607
      },
      {
        "path": "stone_reverie_nav.webm",
        "bytes": 1625365
      },
      {
        "path": "temporal_drive_nav.webm",
        "bytes": 1889542
      },
      {
        "path": "temporal_resolve_nav.webm",
        "bytes": 744999
      },
      {
        "path": "titan_groove_nav.webm",
        "bytes": 1699815
      }
    ]
  },
  "collectible-cards": {
    "version": "2026.09.01.1",
    "totalBytes": 27790969,
    "files": [
      {
        "path": "awena-argent.webp",
        "bytes": 253239
      },
      {
        "path": "awena-bronze.webp",
        "bytes": 253056
      },
      {
        "path": "awena-diamant.webp",
        "bytes": 295393
      },
      {
        "path": "awena-or.webp",
        "bytes": 310168
      },
      {
        "path": "awena-platine.webp",
        "bytes": 248322
      },
      {
        "path": "firefighter-aero-argent.webp",
        "bytes": 500850
      },
      {
        "path": "firefighter-aero-bronze.webp",
        "bytes": 538618
      },
      {
        "path": "firefighter-aero-diamant.webp",
        "bytes": 428471
      },
      {
        "path": "firefighter-aero-or.webp",
        "bytes": 543355
      },
      {
        "path": "firefighter-aero-platine.webp",
        "bytes": 542778
      },
      {
        "path": "firefighter-aero-presentation.webp",
        "bytes": 559537
      },
      {
        "path": "firefighter-aero.webp",
        "bytes": 213500
      },
      {
        "path": "firefighter-braze-argent.webp",
        "bytes": 445791
      },
      {
        "path": "firefighter-braze-bronze.webp",
        "bytes": 397060
      },
      {
        "path": "firefighter-braze-diamant.webp",
        "bytes": 483888
      },
      {
        "path": "firefighter-braze-or.webp",
        "bytes": 478086
      },
      {
        "path": "firefighter-braze-platine.webp",
        "bytes": 478739
      },
      {
        "path": "firefighter-braze-presentation.webp",
        "bytes": 414602
      },
      {
        "path": "firefighter-braze.webp",
        "bytes": 212890
      },
      {
        "path": "firefighter-kael-argent.webp",
        "bytes": 335788
      },
      {
        "path": "firefighter-kael-bronze.webp",
        "bytes": 345862
      },
      {
        "path": "firefighter-kael-diamant.webp",
        "bytes": 476001
      },
      {
        "path": "firefighter-kael-or.webp",
        "bytes": 278397
      },
      {
        "path": "firefighter-kael-platine.webp",
        "bytes": 393578
      },
      {
        "path": "firefighter-kael-presentation.webp",
        "bytes": 313996
      },
      {
        "path": "firefighter-kael.webp",
        "bytes": 193176
      },
      {
        "path": "firefighter-lyna-argent.webp",
        "bytes": 451654
      },
      {
        "path": "firefighter-lyna-bronze.webp",
        "bytes": 452273
      },
      {
        "path": "firefighter-lyna-diamant.webp",
        "bytes": 407620
      },
      {
        "path": "firefighter-lyna-or.webp",
        "bytes": 361695
      },
      {
        "path": "firefighter-lyna-platine.webp",
        "bytes": 361431
      },
      {
        "path": "firefighter-lyna-presentation.webp",
        "bytes": 459499
      },
      {
        "path": "firefighter-lyna.webp",
        "bytes": 186410
      },
      {
        "path": "firefighter-malysia-argent.webp",
        "bytes": 410612
      },
      {
        "path": "firefighter-malysia-bronze.webp",
        "bytes": 416794
      },
      {
        "path": "firefighter-malysia-diamant.webp",
        "bytes": 440448
      },
      {
        "path": "firefighter-malysia-or.webp",
        "bytes": 367283
      },
      {
        "path": "firefighter-malysia-platine.webp",
        "bytes": 475828
      },
      {
        "path": "firefighter-malysia-presentation.webp",
        "bytes": 414005
      },
      {
        "path": "firefighter-malysia.webp",
        "bytes": 253777
      },
      {
        "path": "firefighter-zephyr-argent.webp",
        "bytes": 682105
      },
      {
        "path": "firefighter-zephyr-bronze.webp",
        "bytes": 660307
      },
      {
        "path": "firefighter-zephyr-diamant.webp",
        "bytes": 764763
      },
      {
        "path": "firefighter-zephyr-or.webp",
        "bytes": 688825
      },
      {
        "path": "firefighter-zephyr-platine.webp",
        "bytes": 714969
      },
      {
        "path": "firefighter-zephyr-presentation.webp",
        "bytes": 705628
      },
      {
        "path": "firefighter-zephyr.webp",
        "bytes": 203562
      },
      {
        "path": "killer-batuga.webp",
        "bytes": 387954
      },
      {
        "path": "killer-brat.webp",
        "bytes": 415440
      },
      {
        "path": "killer-brutus.webp",
        "bytes": 385692
      },
      {
        "path": "killer-djuno.webp",
        "bytes": 377886
      },
      {
        "path": "killer-miasma.webp",
        "bytes": 375875
      },
      {
        "path": "killer-morrow.webp",
        "bytes": 331359
      },
      {
        "path": "killer-noz.webp",
        "bytes": 393851
      },
      {
        "path": "killer-raze.webp",
        "bytes": 398756
      },
      {
        "path": "killer-skull.webp",
        "bytes": 486092
      },
      {
        "path": "killer-thorn.webp",
        "bytes": 379902
      },
      {
        "path": "killer-velvet.webp",
        "bytes": 387249
      },
      {
        "path": "killer-viper.webp",
        "bytes": 426407
      },
      {
        "path": "killer-west.webp",
        "bytes": 430366
      },
      {
        "path": "killer-zeno.webp",
        "bytes": 392299
      },
      {
        "path": "loterie-ace.webp",
        "bytes": 344561
      },
      {
        "path": "loterie-fortuna.webp",
        "bytes": 354589
      },
      {
        "path": "loterie-jack.webp",
        "bytes": 326358
      },
      {
        "path": "loterie-jinx.webp",
        "bytes": 304671
      },
      {
        "path": "loterie-lucky.webp",
        "bytes": 366283
      },
      {
        "path": "loterie-midas.webp",
        "bytes": 363501
      },
      {
        "path": "loterie-vega.webp",
        "bytes": 347249
      }
    ]
  }
} as const;
export type GeneratedContentPackId = keyof typeof CONTENT_PACK_CATALOG;
