/* AUTO-GENERATED by tools/prepare-content-packs.mjs. Do not edit manually. */
export const CONTENT_PACK_CATALOG = {
  "fit-awena": {
    "version": "2026.09.01.3",
    "totalBytes": 2835987,
    "files": [
      {
        "path": "exercise-media/bench/awena-step-00-setup.webp",
        "bytes": 47736
      },
      {
        "path": "exercise-media/bench/awena-step-01-start.webp",
        "bytes": 195548
      },
      {
        "path": "exercise-media/bench/awena-step-02-descent.webp",
        "bytes": 204796
      },
      {
        "path": "exercise-media/bench/awena-step-03-bottom.webp",
        "bytes": 189212
      },
      {
        "path": "exercise-media/bench/awena-step-04-press.webp",
        "bytes": 193678
      },
      {
        "path": "exercise-media/burpee/awena-01.webp",
        "bytes": 67170
      },
      {
        "path": "exercise-media/burpee/awena-02.webp",
        "bytes": 65202
      },
      {
        "path": "exercise-media/burpee/awena-03.webp",
        "bytes": 124304
      },
      {
        "path": "exercise-media/burpee/awena-04.webp",
        "bytes": 75846
      },
      {
        "path": "exercise-media/burpee/awena-05.webp",
        "bytes": 66006
      },
      {
        "path": "exercise-media/pushup/awena-high.webp",
        "bytes": 40860
      },
      {
        "path": "exercise-media/pushup/awena-low.webp",
        "bytes": 35812
      },
      {
        "path": "exercise-media/pushup/awena-step-01-start.webp",
        "bytes": 52224
      },
      {
        "path": "exercise-media/pushup/awena-step-02-descent.webp",
        "bytes": 42828
      },
      {
        "path": "exercise-media/pushup/awena-step-03-bottom.webp",
        "bytes": 40688
      },
      {
        "path": "exercise-media/pushup/awena-step-04-press.webp",
        "bytes": 45028
      },
      {
        "path": "motions/awena/premium/bench/frames/frame-01.webp",
        "bytes": 53374
      },
      {
        "path": "motions/awena/premium/bench/frames/frame-02.webp",
        "bytes": 46782
      },
      {
        "path": "motions/awena/premium/bench/frames/frame-03.webp",
        "bytes": 55982
      },
      {
        "path": "motions/awena/premium/bench/frames/frame-04.webp",
        "bytes": 51568
      },
      {
        "path": "motions/awena/premium/bench/frames/frame-05.webp",
        "bytes": 50828
      },
      {
        "path": "motions/awena/premium/bench/motion.mp4",
        "bytes": 89698
      },
      {
        "path": "motions/awena/premium/bench/poster.webp",
        "bytes": 195548
      },
      {
        "path": "motions/awena/premium/burpee/motion.webm",
        "bytes": 31016
      },
      {
        "path": "motions/awena/premium/burpee/poster.webp",
        "bytes": 67170
      },
      {
        "path": "motions/awena/premium/curl/frames/frame-01.webp",
        "bytes": 38522
      },
      {
        "path": "motions/awena/premium/curl/frames/frame-02.webp",
        "bytes": 35970
      },
      {
        "path": "motions/awena/premium/curl/frames/frame-03.webp",
        "bytes": 38912
      },
      {
        "path": "motions/awena/premium/curl/frames/frame-04.webp",
        "bytes": 36174
      },
      {
        "path": "motions/awena/premium/curl/frames/frame-05.webp",
        "bytes": 38096
      },
      {
        "path": "motions/awena/premium/curl/poster.webp",
        "bytes": 38522
      },
      {
        "path": "motions/awena/premium/deadlift/poster.webp",
        "bytes": 40074
      },
      {
        "path": "motions/awena/premium/pushup/motion.webm",
        "bytes": 75158
      },
      {
        "path": "motions/awena/premium/pushup/poster.webp",
        "bytes": 6352
      },
      {
        "path": "motions/awena/premium/squat/motion.mp4",
        "bytes": 155507
      },
      {
        "path": "motions/awena/premium/squat/poster.webp",
        "bytes": 16918
      },
      {
        "path": "tickers/free-awena.webp",
        "bytes": 37414
      },
      {
        "path": "tickers/full-awena.webp",
        "bytes": 35506
      },
      {
        "path": "tickers/legs-awena.webp",
        "bytes": 39002
      },
      {
        "path": "tickers/pull-awena.webp",
        "bytes": 42832
      },
      {
        "path": "tickers/push-awena.webp",
        "bytes": 32124
      }
    ]
  },
  "navigation-music": {
    "version": "2026.09.01.3",
    "totalBytes": 38526085,
    "files": [
      {
        "path": "arena_uprising_nav.webm",
        "bytes": 1574351
      },
      {
        "path": "bass_bet_nav.webm",
        "bytes": 1492836
      },
      {
        "path": "bass_nebula_nav.webm",
        "bytes": 2257234
      },
      {
        "path": "bet_bass_nav.webm",
        "bytes": 1005369
      },
      {
        "path": "darts_vanguard_nav.webm",
        "bytes": 1153911
      },
      {
        "path": "distorted_bed_nav.webm",
        "bytes": 1428996
      },
      {
        "path": "dreamwave_horizon_nav.webm",
        "bytes": 1143720
      },
      {
        "path": "garage_impact_nav.webm",
        "bytes": 996466
      },
      {
        "path": "heartwave_anthem_nav.webm",
        "bytes": 1261447
      },
      {
        "path": "linear_skyline_nav.webm",
        "bytes": 1360895
      },
      {
        "path": "midnight_enigma_nav.webm",
        "bytes": 1067599
      },
      {
        "path": "ms_electrodyn_2_nav.webm",
        "bytes": 1218291
      },
      {
        "path": "ms_electrodyn_nav.webm",
        "bytes": 1364658
      },
      {
        "path": "neon_caravan_nav.webm",
        "bytes": 1414763
      },
      {
        "path": "night_drive_nav.webm",
        "bytes": 2253594
      },
      {
        "path": "obsidian_flow_nav.webm",
        "bytes": 1805688
      },
      {
        "path": "orbital_echo_nav.webm",
        "bytes": 1621137
      },
      {
        "path": "oriental_surge_nav.webm",
        "bytes": 964992
      },
      {
        "path": "pixel_ascension_nav.webm",
        "bytes": 1307041
      },
      {
        "path": "scoring_overture_nav.webm",
        "bytes": 1308273
      },
      {
        "path": "shadow_frequency_nav.webm",
        "bytes": 1342240
      },
      {
        "path": "steel_reactor_nav.webm",
        "bytes": 1452984
      },
      {
        "path": "stellar_riot_nav.webm",
        "bytes": 1461235
      },
      {
        "path": "stone_reverie_nav.webm",
        "bytes": 1733932
      },
      {
        "path": "temporal_drive_nav.webm",
        "bytes": 1990412
      },
      {
        "path": "temporal_resolve_nav.webm",
        "bytes": 786764
      },
      {
        "path": "titan_groove_nav.webm",
        "bytes": 1757257
      }
    ]
  },
  "collectible-cards": {
    "version": "2026.09.01.3",
    "totalBytes": 23069432,
    "files": [
      {
        "path": "awena-argent.webp",
        "bytes": 176712
      },
      {
        "path": "awena-bronze.webp",
        "bytes": 160864
      },
      {
        "path": "awena-diamant.webp",
        "bytes": 208694
      },
      {
        "path": "awena-or.webp",
        "bytes": 206788
      },
      {
        "path": "awena-platine.webp",
        "bytes": 174708
      },
      {
        "path": "firefighter-aero-argent.webp",
        "bytes": 445954
      },
      {
        "path": "firefighter-aero-bronze.webp",
        "bytes": 460772
      },
      {
        "path": "firefighter-aero-diamant.webp",
        "bytes": 349782
      },
      {
        "path": "firefighter-aero-or.webp",
        "bytes": 485470
      },
      {
        "path": "firefighter-aero-platine.webp",
        "bytes": 450984
      },
      {
        "path": "firefighter-aero-presentation.webp",
        "bytes": 484074
      },
      {
        "path": "firefighter-aero.webp",
        "bytes": 151058
      },
      {
        "path": "firefighter-braze-argent.webp",
        "bytes": 418300
      },
      {
        "path": "firefighter-braze-bronze.webp",
        "bytes": 365192
      },
      {
        "path": "firefighter-braze-diamant.webp",
        "bytes": 453868
      },
      {
        "path": "firefighter-braze-or.webp",
        "bytes": 450924
      },
      {
        "path": "firefighter-braze-platine.webp",
        "bytes": 450428
      },
      {
        "path": "firefighter-braze-presentation.webp",
        "bytes": 387894
      },
      {
        "path": "firefighter-braze.webp",
        "bytes": 152232
      },
      {
        "path": "firefighter-kael-argent.webp",
        "bytes": 294948
      },
      {
        "path": "firefighter-kael-bronze.webp",
        "bytes": 311966
      },
      {
        "path": "firefighter-kael-diamant.webp",
        "bytes": 433198
      },
      {
        "path": "firefighter-kael-or.webp",
        "bytes": 221300
      },
      {
        "path": "firefighter-kael-platine.webp",
        "bytes": 351340
      },
      {
        "path": "firefighter-kael-presentation.webp",
        "bytes": 276788
      },
      {
        "path": "firefighter-kael.webp",
        "bytes": 136120
      },
      {
        "path": "firefighter-lyna-argent.webp",
        "bytes": 410270
      },
      {
        "path": "firefighter-lyna-bronze.webp",
        "bytes": 419472
      },
      {
        "path": "firefighter-lyna-diamant.webp",
        "bytes": 323164
      },
      {
        "path": "firefighter-lyna-or.webp",
        "bytes": 290878
      },
      {
        "path": "firefighter-lyna-platine.webp",
        "bytes": 290914
      },
      {
        "path": "firefighter-lyna-presentation.webp",
        "bytes": 436142
      },
      {
        "path": "firefighter-lyna.webp",
        "bytes": 129494
      },
      {
        "path": "firefighter-malysia-argent.webp",
        "bytes": 351938
      },
      {
        "path": "firefighter-malysia-bronze.webp",
        "bytes": 372300
      },
      {
        "path": "firefighter-malysia-diamant.webp",
        "bytes": 347576
      },
      {
        "path": "firefighter-malysia-or.webp",
        "bytes": 281960
      },
      {
        "path": "firefighter-malysia-platine.webp",
        "bytes": 439192
      },
      {
        "path": "firefighter-malysia-presentation.webp",
        "bytes": 369690
      },
      {
        "path": "firefighter-malysia.webp",
        "bytes": 172818
      },
      {
        "path": "firefighter-zephyr-argent.webp",
        "bytes": 635218
      },
      {
        "path": "firefighter-zephyr-bronze.webp",
        "bytes": 612136
      },
      {
        "path": "firefighter-zephyr-diamant.webp",
        "bytes": 733844
      },
      {
        "path": "firefighter-zephyr-or.webp",
        "bytes": 646106
      },
      {
        "path": "firefighter-zephyr-platine.webp",
        "bytes": 684280
      },
      {
        "path": "firefighter-zephyr-presentation.webp",
        "bytes": 682876
      },
      {
        "path": "firefighter-zephyr.webp",
        "bytes": 144332
      },
      {
        "path": "killer-batuga.webp",
        "bytes": 293970
      },
      {
        "path": "killer-brat.webp",
        "bytes": 313380
      },
      {
        "path": "killer-brutus.webp",
        "bytes": 289014
      },
      {
        "path": "killer-djuno.webp",
        "bytes": 290602
      },
      {
        "path": "killer-miasma.webp",
        "bytes": 290868
      },
      {
        "path": "killer-morrow.webp",
        "bytes": 252122
      },
      {
        "path": "killer-noz.webp",
        "bytes": 308648
      },
      {
        "path": "killer-raze.webp",
        "bytes": 300378
      },
      {
        "path": "killer-skull.webp",
        "bytes": 404172
      },
      {
        "path": "killer-thorn.webp",
        "bytes": 293044
      },
      {
        "path": "killer-velvet.webp",
        "bytes": 290848
      },
      {
        "path": "killer-viper.webp",
        "bytes": 318798
      },
      {
        "path": "killer-west.webp",
        "bytes": 329064
      },
      {
        "path": "killer-zeno.webp",
        "bytes": 305002
      },
      {
        "path": "loterie-ace.webp",
        "bytes": 226050
      },
      {
        "path": "loterie-fortuna.webp",
        "bytes": 230802
      },
      {
        "path": "loterie-jack.webp",
        "bytes": 205196
      },
      {
        "path": "loterie-jinx.webp",
        "bytes": 196020
      },
      {
        "path": "loterie-lucky.webp",
        "bytes": 240520
      },
      {
        "path": "loterie-midas.webp",
        "bytes": 237480
      },
      {
        "path": "loterie-vega.webp",
        "bytes": 218496
      }
    ]
  },
  "theme-textures": {
    "version": "2026.09.01.3",
    "totalBytes": 3820496,
    "files": [
      {
        "path": "graffiti-atelier-spray.webp",
        "bytes": 204720
      },
      {
        "path": "graffiti-beton-pastel.webp",
        "bytes": 164542
      },
      {
        "path": "graffiti-blackbook-riot.webp",
        "bytes": 193516
      },
      {
        "path": "graffiti-bleu-lilas.webp",
        "bytes": 172614
      },
      {
        "path": "graffiti-chaos-primaire.webp",
        "bytes": 257672
      },
      {
        "path": "graffiti-collage-chrome.webp",
        "bytes": 287490
      },
      {
        "path": "graffiti-eclat-cyan.webp",
        "bytes": 57742
      },
      {
        "path": "graffiti-explosion-blanche.webp",
        "bytes": 54794
      },
      {
        "path": "graffiti-line-love.webp",
        "bytes": 157144
      },
      {
        "path": "graffiti-mur-pop.webp",
        "bytes": 206946
      },
      {
        "path": "graffiti-peace-love.webp",
        "bytes": 209044
      },
      {
        "path": "graffiti-rose-hero.webp",
        "bytes": 213346
      },
      {
        "path": "graffiti-rouge-underground.webp",
        "bytes": 31698
      },
      {
        "path": "graffiti-ruelle.webp",
        "bytes": 77042
      },
      {
        "path": "graffiti-splash-acidule.webp",
        "bytes": 215278
      },
      {
        "path": "graffiti-tags-nocturnes.webp",
        "bytes": 11410
      },
      {
        "path": "postapoc-aube-des-ruines.webp",
        "bytes": 80362
      },
      {
        "path": "postapoc-avenue-silence.webp",
        "bytes": 90086
      },
      {
        "path": "postapoc-beton-gris.webp",
        "bytes": 116450
      },
      {
        "path": "postapoc-chute-finale.webp",
        "bytes": 66572
      },
      {
        "path": "postapoc-cracked-concrete.webp",
        "bytes": 61296
      },
      {
        "path": "postapoc-cracks-overlay.svg",
        "bytes": 2055
      },
      {
        "path": "postapoc-crepuscule-corbeau.webp",
        "bytes": 68824
      },
      {
        "path": "postapoc-eden-perdu.webp",
        "bytes": 108148
      },
      {
        "path": "postapoc-horizon-cendre.webp",
        "bytes": 89486
      },
      {
        "path": "postapoc-panel-concrete.svg",
        "bytes": 1967
      },
      {
        "path": "postapoc-pluie-neon.webp",
        "bytes": 231994
      },
      {
        "path": "postapoc-rusted-steel.webp",
        "bytes": 177118
      },
      {
        "path": "postapoc-tour-brisee.webp",
        "bytes": 190592
      },
      {
        "path": "postapoc-worn-frame.webp",
        "bytes": 20548
      }
    ]
  },
  "character-portraits": {
    "version": "2026.09.01.3",
    "totalBytes": 2440170,
    "files": [
      {
        "path": "firefighter-bots/aero.webp",
        "bytes": 88942
      },
      {
        "path": "firefighter-bots/braze.webp",
        "bytes": 78704
      },
      {
        "path": "firefighter-bots/kael.webp",
        "bytes": 81724
      },
      {
        "path": "firefighter-bots/lyna.webp",
        "bytes": 85266
      },
      {
        "path": "firefighter-bots/malysia.webp",
        "bytes": 89386
      },
      {
        "path": "firefighter-bots/zephyr.webp",
        "bytes": 94966
      },
      {
        "path": "killer-bots/batuzia.webp",
        "bytes": 99072
      },
      {
        "path": "killer-bots/brams.webp",
        "bytes": 131752
      },
      {
        "path": "killer-bots/brutes.webp",
        "bytes": 91850
      },
      {
        "path": "killer-bots/djuno.webp",
        "bytes": 91472
      },
      {
        "path": "killer-bots/marron.webp",
        "bytes": 72886
      },
      {
        "path": "killer-bots/miasma.webp",
        "bytes": 96582
      },
      {
        "path": "killer-bots/noz.webp",
        "bytes": 127106
      },
      {
        "path": "killer-bots/raze.webp",
        "bytes": 96088
      },
      {
        "path": "killer-bots/sqwal.webp",
        "bytes": 133570
      },
      {
        "path": "killer-bots/thorn.webp",
        "bytes": 100274
      },
      {
        "path": "killer-bots/verveine.webp",
        "bytes": 95466
      },
      {
        "path": "killer-bots/viperine.webp",
        "bytes": 157044
      },
      {
        "path": "killer-bots/west.webp",
        "bytes": 118872
      },
      {
        "path": "killer-bots/zeno.webp",
        "bytes": 77218
      },
      {
        "path": "loterie-bots/ace.webp",
        "bytes": 56218
      },
      {
        "path": "loterie-bots/fortuna.webp",
        "bytes": 66718
      },
      {
        "path": "loterie-bots/jack.webp",
        "bytes": 59146
      },
      {
        "path": "loterie-bots/jinx.webp",
        "bytes": 60486
      },
      {
        "path": "loterie-bots/lucky.webp",
        "bytes": 60688
      },
      {
        "path": "loterie-bots/midas.webp",
        "bytes": 69346
      },
      {
        "path": "loterie-bots/vega.webp",
        "bytes": 59328
      }
    ]
  }
} as const;
export type GeneratedContentPackId = keyof typeof CONTENT_PACK_CATALOG;
