// src/lib/teamAutoShuffle.ts
// Génération d'équipes temporaires : brassage aléatoire ou équilibré.
// Pensé pour être réutilisé par tous les modes qui utilisent le sélecteur d'équipes X01.

import { TEAM_LOGO_LIBRARY, teamLogoMatchesCategory, type TeamLogoCategory, type TeamLogoTemplate } from "../assets/teamLogoLibrary";

export type TeamShuffleMode = "random" | "balanced";

export type AutoShufflePlayer = {
  id?: string | number | null;
  profileId?: string | number | null;
  playerId?: string | number | null;
  localProfileId?: string | number | null;
  name?: string | null;
  displayName?: string | null;
  label?: string | null;
  nickname?: string | null;
  level?: number | string | null;
  stars?: number | string | null;
  rating?: number | string | null;
  botLevel?: number | string | null;
  botTeamLevel?: number | string | null;
  stats?: any;
  x01Stats?: any;
  [key: string]: any;
};

export type GeneratedTeam = {
  id: string;
  baseTeamId: string;
  sourceTeamId: string;
  teamRefId: string;
  name: string;
  originalName: string;
  logoDataUrl: string;
  logoUrl?: string | null;
  logoLibraryId?: string | null;
  logoLibraryFileName?: string | null;
  logoCategory?: string | null;
  playerIds: string[];
  generated: true;
  temporary: true;
  autoGenerated: true;
  shuffleMode: TeamShuffleMode;
  teamPower: number;
  createdAt: number;
  updatedAt: number;
  sport?: string;
  allSports?: boolean;
  sportIds?: string[];
  teamKind?: "leisure" | "club" | string;
};

type GenerateOptions = {
  players: AutoShufflePlayer[];
  teamSize?: number;
  teamCount?: number;
  mode?: TeamShuffleMode;
  sport?: string;
  seed?: string | number;
  accent?: string;
};

const GENERATED_TEAMS_KEY = "dc-generated-temp-teams-v1";
const STORED_TEAMS_KEY = "dc-teams-v1";

const ADJECTIVES = [
  "Foudroyants", "Dorés", "Sauvages", "Nocturnes", "Brûlants", "Aiguisés", "Royaux", "Cosmiques", "Furieux", "Légendaires",
  "Tactiques", "Atomiques", "Épiques", "Indomptables", "Turbo", "Mystiques", "Solides", "Panthères", "Titans", "Invincibles",
];

const NOUNS = [
  "Titans", "Snipers", "Loups", "Phénix", "Dragons", "Ninjas", "Vikings", "Météores", "Requins", "Cobras",
  "Rockets", "Guerriers", "Flèches", "Cyclones", "Spartiates", "Pirates", "Falcons", "Bulls", "Jokers", "Lynx",
];

const LOGO_SYMBOLS = ["⚡", "🎯", "★", "◆", "✦", "♛", "🔥", "☄", "⬢", "✹", "☣", "✪"];
const LOGO_PALETTE = [
  ["#22e6ff", "#1e3cff", "#eafcff"],
  ["#ffcf4a", "#ff6b00", "#fff4c2"],
  ["#ff4fd8", "#7424ff", "#ffe1fb"],
  ["#9dff3c", "#00a86b", "#edffd9"],
  ["#ff5d7d", "#650014", "#ffe0e7"],
  ["#c7b7ff", "#2e1a7a", "#f0eaff"],
  ["#ffffff", "#6f768f", "#f7f9ff"],
  ["#ff9b3d", "#4b1800", "#ffe6c9"],
];

function hashString(input: string): number {
  let h = 2166136261;
  for (let i = 0; i < input.length; i += 1) {
    h ^= input.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function seededRandom(seed: string | number) {
  let state = typeof seed === "number" ? seed >>> 0 : hashString(String(seed || Date.now()));
  return () => {
    state += 0x6D2B79F5;
    let t = state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function clamp(n: number, min: number, max: number) {
  return Math.max(min, Math.min(max, n));
}

function numeric(value: any): number {
  if (typeof value === "number" && Number.isFinite(value)) return value;
  const raw = String(value ?? "").replace(",", ".").trim();
  if (!raw) return 0;
  const match = raw.match(/-?\d+(?:\.\d+)?/);
  const n = match ? Number(match[0]) : 0;
  return Number.isFinite(n) ? n : 0;
}

export function playerIdOf(player: any): string {
  return String(player?.id ?? player?.profileId ?? player?.playerId ?? player?.localProfileId ?? "").trim();
}

export function playerNameOf(player: any): string {
  return String(player?.name || player?.displayName || player?.nickname || player?.label || "Joueur").trim() || "Joueur";
}

function profileFieldLevel(player: any): number {
  // Le niveau d'équilibrage doit d'abord suivre les étoiles visibles du profil.
  // On couvre les clés utilisées dans les écrans Profils/X01 et les variantes legacy.
  const direct = [
    player?.profileStarring,
    player?.profileStars,
    player?.profileStarRating,
    player?.starring,
    player?.stars,
    player?.levelStars,
    player?.x01ProfileStarring,
    player?.dartsProfileStarring,
    player?.autoBalanceLevel,
    player?.balanceLevel,
    player?.level,
    player?.rating,
    player?.botLevel,
    player?.botTeamLevel,
    player?.profileLevel,
    player?.skillLevel,
    player?.stats?.profileStarring,
    player?.stats?.profileStars,
    player?.stats?.stars,
    player?.stats?.levelStars,
    player?.stats?.x01?.profileStarring,
    player?.stats?.x01?.stars,
    player?.stats?.darts?.profileStarring,
    player?.stats?.darts?.stars,
    player?.x01?.profileStarring,
    player?.x01?.stars,
    player?.x01Stats?.profileStarring,
    player?.x01Stats?.stars,
    player?.privateInfo?.profileStarring,
    player?.privateInfo?.profileStars,
    player?.privateInfo?.stars,
    player?.privateInfo?.x01ProfileStarring,
    player?.privateInfo?.dartsProfileStarring,
    player?.private_info?.profileStarring,
    player?.private_info?.profileStars,
    player?.private_info?.stars,
    player?.private_info?.x01ProfileStarring,
    player?.preferences?.profileStarring,
    player?.preferences?.profileStars,
    player?.preferences?.stars,
    player?.preferences?.x01ProfileStarring,
    player?.profile?.profileStarring,
    player?.profile?.profileStars,
    player?.profile?.stars,
    player?.profile?.stats?.profileStarring,
    player?.profile?.stats?.stars,
  ];
  for (const value of direct) {
    const n = numeric(value);
    if (n > 0) return n > 5 ? n / 20 : n;
  }
  const raw = String(player?.levelName || player?.rank || player?.tier || "").toLowerCase();
  if (/legend|légende|legende|elite|élite/.test(raw)) return 5;
  if (/pro|expert|master/.test(raw)) return 4.5;
  if (/challenger|confirm/.test(raw)) return 4;
  if (/mixte|interm|medium|moyen|normal/.test(raw)) return 3;
  if (/debut|début|beginner|rookie|facile|easy/.test(raw)) return 1.5;
  return 0;
}

function statsLevel(player: any): number {
  const stats = player?.stats || player?.x01Stats || player?.dartsStats || player?.summary || {};
  const avg3 = numeric(stats.avg3 ?? stats.avg3d ?? stats.avg3D ?? stats.average3 ?? stats.threeDartAverage);
  if (avg3 > 0) return clamp(avg3 / 20, 0.5, 5); // 100 avg3 => 5 étoiles
  const winRate = numeric(stats.winRate ?? stats.winsPct ?? stats.winPct ?? stats.victoryRate);
  if (winRate > 0) return clamp((winRate > 1 ? winRate / 100 : winRate) * 5, 0.5, 5);
  const games = numeric(stats.games ?? stats.matches ?? stats.played);
  const wins = numeric(stats.wins ?? stats.victories);
  if (games > 0 && wins >= 0) return clamp((wins / Math.max(1, games)) * 5, 0.5, 5);
  return 0;
}

function quickStatsLevelFromStorage(id: string): number {
  if (!id || typeof window === "undefined") return 0;
  const keys = ["dc-quick-stats", "dc_x01_profile_stats", "dc-profile-stats-cache"];
  for (const key of keys) {
    try {
      const raw = window.localStorage?.getItem(key);
      if (!raw) continue;
      const bag = JSON.parse(raw);
      const stats = bag?.[id] || bag?.profiles?.[id] || bag?.stats?.[id];
      if (!stats) continue;
      const level = statsLevel({ stats });
      if (level > 0) return level;
    } catch {}
  }
  return 0;
}

export function playerBalanceLevel(player: AutoShufflePlayer): number {
  const fromProfile = profileFieldLevel(player);
  if (fromProfile > 0) return clamp(fromProfile, 0.5, 5);
  const fromStats = statsLevel(player);
  if (fromStats > 0) return clamp(fromStats, 0.5, 5);
  const fromStorage = quickStatsLevelFromStorage(playerIdOf(player));
  if (fromStorage > 0) return clamp(fromStorage, 0.5, 5);
  return 2.5; // niveau neutre si aucune donnée exploitable
}

function uniquePlayers(players: AutoShufflePlayer[]): AutoShufflePlayer[] {
  const seen = new Set<string>();
  const out: AutoShufflePlayer[] = [];
  for (const player of players || []) {
    const id = playerIdOf(player);
    if (!id || seen.has(id)) continue;
    seen.add(id);
    out.push(player);
  }
  return out;
}

function shuffle<T>(items: T[], rnd: () => number): T[] {
  const out = [...items];
  for (let i = out.length - 1; i > 0; i -= 1) {
    const j = Math.floor(rnd() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

function distributeBalanced(players: AutoShufflePlayer[], teamCount: number, teamSize: number, rnd: () => number): AutoShufflePlayer[][] {
  const teams = Array.from({ length: teamCount }, () => [] as AutoShufflePlayer[]);
  const totals = Array.from({ length: teamCount }, () => 0);
  const ordered = shuffle(players, rnd).sort((a, b) => playerBalanceLevel(b) - playerBalanceLevel(a));

  for (const player of ordered) {
    let best = -1;
    for (let i = 0; i < teams.length; i += 1) {
      if (teams[i].length >= teamSize) continue;
      if (best < 0 || totals[i] < totals[best] || (totals[i] === totals[best] && teams[i].length < teams[best].length)) best = i;
    }
    if (best < 0) continue;
    teams[best].push(player);
    totals[best] += playerBalanceLevel(player);
  }
  return teams;
}

function distributeRandom(players: AutoShufflePlayer[], teamCount: number, teamSize: number, rnd: () => number): AutoShufflePlayer[][] {
  const ordered = shuffle(players, rnd).slice(0, teamCount * teamSize);
  const teams = Array.from({ length: teamCount }, () => [] as AutoShufflePlayer[]);
  ordered.forEach((player, index) => {
    teams[Math.floor(index / teamSize)]?.push(player);
  });
  return teams;
}

function randomName(index: number, rnd: () => number): string {
  const a = ADJECTIVES[Math.floor(rnd() * ADJECTIVES.length)] || "Foudroyants";
  const n = NOUNS[Math.floor(rnd() * NOUNS.length)] || "Titans";
  return `Les ${n} ${a}`.replace(/\s+/g, " ").trim() || `Équipe ${index + 1}`;
}

function normalizeLogoText(value: any): string {
  return String(value || "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

function deterministicPick<T>(items: T[], seed: string | number): T | null {
  if (!items.length) return null;
  const rnd = seededRandom(seed);
  return items[Math.floor(rnd() * items.length)] || items[0] || null;
}

function logoKeywordsForTeamName(name: string): string[] {
  const base = normalizeLogoText(name).split(/\s+/).filter((x) => x.length >= 3);
  const joined = ` ${normalizeLogoText(name)} `;
  const extra: string[] = [];
  const add = (...items: string[]) => extra.push(...items);
  if (/\bloup|loups|wolf|wolves\b/.test(joined)) add("loup", "wolf", "meute");
  if (/\bdragon/.test(joined)) add("dragon");
  if (/\bninja/.test(joined)) add("ninja", "samourai", "guerrier");
  if (/\bviking/.test(joined)) add("viking", "guerrier");
  if (/\btaureau|bull|bulls\b/.test(joined)) add("taureau", "bull");
  if (/\bcobra|serpent|snake\b/.test(joined)) add("cobra", "serpent", "snake");
  if (/\brequin|shark\b/.test(joined)) add("requin", "shark");
  if (/\bphenix|phoenix\b/.test(joined)) add("phenix", "phoenix", "feu");
  if (/\bfl[eè]che|fleches|sniper|darts?\b/.test(joined)) add("dart", "darts", "fleche", "cible", "fléchettes");
  if (/\bmeteor|cosmi|rocket|cyclone|foudre|eclair\b/.test(joined)) add("element", "energie", "foudre", "feu", "cosmique");
  if (/\bjoker/.test(joined)) add("joker", "fun", "mascotte");
  if (/\broyal|couronne|titan|spartiate|pirate|guerrier\b/.test(joined)) add("blason", "couronne", "guerrier", "trophee");
  return Array.from(new Set([...base, ...extra]));
}

export function pickTeamLogoForGeneratedName(name: string, sport: TeamLogoCategory | "all" = "darts", seed?: string | number): TeamLogoTemplate | null {
  const keywords = logoKeywordsForTeamName(name);
  // Règle importante : quand un sport est fourni (X01 => darts), on ne pioche
  // JAMAIS dans un autre sport. Les mots du nom servent uniquement à départager
  // les logos compatibles avec le sport, pas à basculer sur pétanque/foot/etc.
  const strictSportPool = sport && sport !== "all"
    ? TEAM_LOGO_LIBRARY.filter((logo) => teamLogoMatchesCategory(logo, sport))
    : TEAM_LOGO_LIBRARY;
  const pool = strictSportPool.length ? strictSportPool : TEAM_LOGO_LIBRARY;

  const scored = pool
    .map((logo) => {
      const haystack = normalizeLogoText([logo.label, logo.category, logo.fileName, ...(logo.tags || [])].join(" "));
      const keywordScore = keywords.reduce((sum, word) => sum + (word && haystack.includes(normalizeLogoText(word)) ? 1 : 0), 0);
      const popularBonus = (logo.tags || []).includes("popular") ? 1 : 0;
      return { logo, score: keywordScore * 3 + popularBonus };
    })
    .sort((a, b) => b.score - a.score);

  const bestScore = scored[0]?.score ?? 0;
  const best = scored.filter((item) => item.score === bestScore).map((item) => item.logo);
  if (best.length) return deterministicPick(best, seed || name);

  const fallback = pool.filter((logo) => (logo.tags || []).includes("popular"));
  return deterministicPick(fallback.length ? fallback : pool, seed || name);
}

export function createRandomTeamLogo(seed: string | number, label = "TEAM"): string {
  const rnd = seededRandom(seed);
  const palette = LOGO_PALETTE[Math.floor(rnd() * LOGO_PALETTE.length)] || LOGO_PALETTE[0];
  const symbol = LOGO_SYMBOLS[Math.floor(rnd() * LOGO_SYMBOLS.length)] || "★";
  const rotation = Math.round(rnd() * 40 - 20);
  const initials = String(label || "TEAM")
    .trim()
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((x) => x[0])
    .join("")
    .toUpperCase()
    .slice(0, 3) || "T";

  const svg = `
  <svg xmlns="http://www.w3.org/2000/svg" width="256" height="256" viewBox="0 0 256 256">
    <defs>
      <radialGradient id="g" cx="35%" cy="25%" r="82%">
        <stop offset="0%" stop-color="${palette[0]}"/>
        <stop offset="100%" stop-color="${palette[1]}"/>
      </radialGradient>
      <filter id="glow" x="-50%" y="-50%" width="200%" height="200%">
        <feGaussianBlur stdDeviation="6" result="blur"/>
        <feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge>
      </filter>
    </defs>
    <circle cx="128" cy="128" r="116" fill="rgba(2,6,16,1)"/>
    <circle cx="128" cy="128" r="108" fill="url(#g)" stroke="${palette[2]}" stroke-width="6" filter="url(#glow)"/>
    <circle cx="128" cy="128" r="82" fill="rgba(0,0,0,.20)" stroke="rgba(255,255,255,.32)" stroke-width="2"/>
    <text x="128" y="122" text-anchor="middle" dominant-baseline="central" font-family="Arial, Helvetica, sans-serif" font-size="72" font-weight="900" fill="rgba(255,255,255,.94)" transform="rotate(${rotation} 128 128)">${symbol}</text>
    <text x="128" y="184" text-anchor="middle" font-family="Arial, Helvetica, sans-serif" font-size="34" font-weight="900" letter-spacing="2" fill="rgba(255,255,255,.92)">${initials}</text>
  </svg>`.trim();
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
}

export function generateShuffledTeams(options: GenerateOptions): GeneratedTeam[] {
  const mode = options.mode === "balanced" ? "balanced" : "random";
  const allPlayers = uniquePlayers(options.players || []);
  const teamSize = Math.max(1, Math.floor(Number(options.teamSize || 2)));
  const teamCount = Math.max(1, Math.floor(Number(options.teamCount || Math.floor(allPlayers.length / teamSize))));
  const required = teamSize * teamCount;
  const seed = options.seed ?? `${Date.now()}-${Math.random()}`;
  const rnd = seededRandom(seed);
  const pool = allPlayers.slice(0, required);
  const buckets = mode === "balanced"
    ? distributeBalanced(pool, teamCount, teamSize, rnd)
    : distributeRandom(pool, teamCount, teamSize, rnd);
  const now = Date.now();

  return buckets.map((players, index) => {
    const name = randomName(index, rnd);
    const id = `tmp_shuffle_${now}_${index}_${Math.floor(rnd() * 100000)}`;
    const teamPower = players.reduce((sum, player) => sum + playerBalanceLevel(player), 0);
    const logoTemplate = pickTeamLogoForGeneratedName(name, (options.sport || "darts") as TeamLogoCategory, `${seed}-${index}-${name}`);
    const logoSrc = logoTemplate?.src || createRandomTeamLogo(`${seed}-${index}-${name}`, name);
    return {
      id,
      baseTeamId: id,
      sourceTeamId: id,
      teamRefId: id,
      name,
      originalName: name,
      logoDataUrl: logoSrc,
      logoUrl: logoSrc,
      logoLibraryId: logoTemplate?.id || null,
      logoLibraryFileName: logoTemplate?.fileName || null,
      logoCategory: logoTemplate?.category || null,
      playerIds: players.map(playerIdOf).filter(Boolean),
      generated: true,
      temporary: true,
      autoGenerated: true,
      shuffleMode: mode,
      teamPower: Math.round(teamPower * 10) / 10,
      createdAt: now,
      updatedAt: now,
      sport: options.sport || "darts",
      allSports: false,
      sportIds: options.sport ? [String(options.sport)] : [],
      teamKind: "leisure",
    };
  });
}

function safeParseArray(raw: string | null): any[] {
  if (!raw) return [];
  try {
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

export function rememberGeneratedTeams(teams: any[]) {
  if (typeof window === "undefined") return;
  try {
    // Important : ce stockage sert uniquement à résoudre les équipes temporaires
    // validées pour la partie en cours. On remplace donc l'ancien brassage au lieu
    // de l'empiler, sinon des anciens joueurs réapparaissent dans le brassage auto.
    const clean = (teams || []).filter((team) => String(team?.id || team?.baseTeamId || "").trim());
    window.sessionStorage.setItem(GENERATED_TEAMS_KEY, JSON.stringify(clean.slice(-80)));
  } catch {}
}

export function loadRememberedGeneratedTeams(): any[] {
  if (typeof window === "undefined") return [];
  try {
    return safeParseArray(window.sessionStorage.getItem(GENERATED_TEAMS_KEY));
  } catch {
    return [];
  }
}

export function findRememberedGeneratedTeam(id: any): any | null {
  const wanted = String(id || "").split("__slot_")[0];
  if (!wanted) return null;
  return loadRememberedGeneratedTeams().find((team) => String(team?.id || team?.baseTeamId || "") === wanted) || null;
}

export function saveGeneratedTeamsToTeamStore(teams: any[], sport = "darts") {
  if (typeof window === "undefined") return [];
  const now = Date.now();
  const clean = (teams || []).map((team: any) => ({
    ...team,
    id: String(team?.id || `team_${now}_${Math.random().toString(36).slice(2, 8)}`),
    name: String(team?.name || "Équipe").trim() || "Équipe",
    sport: String(team?.sport || sport || "darts"),
    allSports: team?.allSports === true,
    sportIds: Array.isArray(team?.sportIds) && team.sportIds.length ? team.sportIds.map(String) : [String(team?.sport || sport || "darts")],
    playerIds: Array.isArray(team?.playerIds) ? team.playerIds.map(String).filter(Boolean) : [],
    logoDataUrl: team?.logoDataUrl || null,
    logoUrl: team?.logoUrl || team?.logoDataUrl || null,
    logoLibraryId: team?.logoLibraryId || null,
    logoLibraryFileName: team?.logoLibraryFileName || null,
    logoCategory: team?.logoCategory || null,
    temporary: false,
    generated: true,
    autoGenerated: true,
    teamKind: "leisure",
    createdAt: Number(team?.createdAt || 0) || now,
    updatedAt: now,
  }));

  try {
    const previous = safeParseArray(window.localStorage.getItem(STORED_TEAMS_KEY));
    const byId = new Map<string, any>();
    clean.forEach((team) => byId.set(String(team.id), team));
    previous.forEach((team) => {
      const id = String(team?.id || "").trim();
      if (id && !byId.has(id)) byId.set(id, team);
    });
    window.localStorage.setItem(STORED_TEAMS_KEY, JSON.stringify(Array.from(byId.values())));
    try { window.dispatchEvent(new Event("dc-teams-updated")); } catch {}
    try { window.dispatchEvent(new Event("dc:teams-changed")); } catch {}
  } catch {}
  return clean;
}

export function rerollGeneratedTeamLogo(team: any): any {
  const name = String(team?.name || "Équipe");
  const sport = String(team?.sport || (Array.isArray(team?.sportIds) ? team.sportIds[0] : "darts") || "darts") as TeamLogoCategory;
  const logoTemplate = pickTeamLogoForGeneratedName(name, sport, `${Date.now()}-${Math.random()}-${name}`);
  const logoSrc = logoTemplate?.src || createRandomTeamLogo(`${Date.now()}-${Math.random()}-${name}`, name);
  return {
    ...team,
    logoDataUrl: logoSrc,
    logoUrl: logoSrc,
    logoLibraryId: logoTemplate?.id || null,
    logoLibraryFileName: logoTemplate?.fileName || null,
    logoCategory: logoTemplate?.category || null,
    updatedAt: Date.now(),
  };
}
