// @ts-nocheck
import type { GameDart, Player } from "../types-game";
export type CallThreeBotLevel="easy"|"normal"|"hard";
export type CallThreeConfigPayload={mode:"call_three";selectedIds:string[];players:number;playersList?:any[];botIds?:string[];botsEnabled?:boolean;botLevel:CallThreeBotLevel;randomOrder?:boolean;scoreInputMethod?:"keypad"|"dartboard";seriesWins:1|2|3;rules:{rounds:number;callerMode:"next"|"random";orderedTargets:boolean;bullAllowed:boolean;multiplierScoring:boolean;}};
export type CallTarget = { kind:"number"; number:number } | { kind:"bull" };
export type CallThreeStats={darts:number; visits:number; points:number; hits:number; misses:number; perfectRounds:number; callsMade:number; legsWon:number;};
export type CallThreeVisit={id:string;playerId:string;callerId:string|null;leg:number;round:number;darts:GameDart[];calls:CallTarget[];before:number;after:number;gained:number;hits:number;events:string[];};
export type CallThreeState={sport:"darts";mode:"call_three";config:CallThreeConfigPayload;players:Player[];scores:Record<string,number>;legWins:Record<string,number>;statsByPlayer:Record<string,CallThreeStats>;activePlayerIndex:number;roundIndex:number;legIndex:number;turnIndex:number;phase:"playing"|"finished";winnerId:string|null;lastLegWinnerId:string|null;currentCallerId:string|null;currentCalls:CallTarget[];visits:CallThreeVisit[];startedAt:number;finishedAt?:number;};
const clone=<T,>(v:T):T=>JSON.parse(JSON.stringify(v)); const uid=(p='ct3')=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`; const blank=():CallThreeStats=>({darts:0,visits:0,points:0,hits:0,misses:0,perfectRounds:0,callsMade:0,legsWon:0});
const seqNumbers=[20,1,18,4,13,6,10,15,2,17,3,19,7,16,8,11,14,9,12,5];
const callLabel=(c:CallTarget)=>c.kind==='bull'?'BULL':String(c.number);
const scoreOfHit=(d:GameDart)=>!d||d.bed==='MISS'?0:d.bed==='IB'?3:d.bed==='OB'?2:(d.bed==='T'?3:d.bed==='D'?2:1);
const matches=(d:GameDart,c:CallTarget)=> c.kind==='bull' ? d?.bed==='OB'||d?.bed==='IB' : (d?.bed==='S'||d?.bed==='D'||d?.bed==='T') && Number(d.number||0)===c.number;
function randomCalls(allowBull:boolean, seed:number){ const pool=seqNumbers.slice(); const out:CallTarget[]=[]; let cursor=(seed*7)%pool.length; for(let i=0;i<3;i++){ if(allowBull && i===2 && (seed+i)%7===0) out.push({kind:'bull'}); else { const idx=cursor%pool.length; const number=pool.splice(idx,1)[0]||((idx%20)+1); out.push({kind:'number',number}); cursor+=3; } } return out; }
export function normalizeCallThreeConfig(raw:any):CallThreeConfigPayload{ const r=raw?.rules||{}; const ids=Array.isArray(raw?.selectedIds)?raw.selectedIds.map(String):[]; return {mode:'call_three',selectedIds:ids,players:Math.max(1,Number(raw?.players||ids.length||1)),playersList:Array.isArray(raw?.playersList)?raw.playersList:[],botIds:Array.isArray(raw?.botIds)?raw.botIds.map(String):[],botsEnabled:Boolean(raw?.botsEnabled),botLevel:raw?.botLevel==='easy'||raw?.botLevel==='hard'?raw.botLevel:'normal',randomOrder:raw?.randomOrder!==false,scoreInputMethod:raw?.scoreInputMethod==='dartboard'?'dartboard':'keypad',seriesWins:raw?.seriesWins===2||raw?.seriesWins===3?raw.seriesWins:1,rules:{rounds:[5,10,15].includes(Number(r?.rounds))?Number(r.rounds):10,callerMode:r?.callerMode==='random'?'random':'next',orderedTargets:r?.orderedTargets!==false,bullAllowed:r?.bullAllowed!==false,multiplierScoring:r?.multiplierScoring!==false}}; }
function chooseCaller(players:Player[], activeIndex:number, mode:'next'|'random'){ if(!players.length) return null; if(players.length===1) return players[0].id; if(mode==='next') return players[(activeIndex+1)%players.length]?.id||players[0].id; const pool=players.filter((_,i)=>i!==activeIndex); return pool[Math.floor(Math.random()*pool.length)]?.id||players[0].id; }
function generateCalls(s:CallThreeState,activeIndex:number,roundIndex:number){ const callerId=chooseCaller(s.players,activeIndex,s.config.rules.callerMode); const callerIndex=Math.max(0,s.players.findIndex(p=>p.id===callerId)); const seed=(roundIndex+1)*13 + activeIndex*5 + callerIndex; return {callerId, calls:randomCalls(s.config.rules.bullAllowed, seed)}; }
export function createCallThreeState(players:Player[],raw:any):CallThreeState{ const config=normalizeCallThreeConfig(raw); const ps=(players||[]).map((p,i)=>({id:String(p?.id||`p${i+1}`),name:String(p?.name||`Joueur ${i+1}`)})); const base:any={sport:'darts',mode:'call_three',config,players:ps,scores:Object.fromEntries(ps.map(p=>[p.id,0])),legWins:Object.fromEntries(ps.map(p=>[p.id,0])),statsByPlayer:Object.fromEntries(ps.map(p=>[p.id,blank()])),activePlayerIndex:0,roundIndex:0,legIndex:0,turnIndex:0,phase:'playing',winnerId:null,lastLegWinnerId:null,currentCallerId:null,currentCalls:[],visits:[],startedAt:Date.now()}; const first=generateCalls(base,0,0); base.currentCallerId=first.callerId;base.currentCalls=first.calls; if(first.callerId) base.statsByPlayer[first.callerId].callsMade++; return base; }
export const cloneCallThreeState=(s:CallThreeState):CallThreeState=>clone(s);
function leadersAtTopScore(s:CallThreeState){ const best=Math.max(...s.players.map(p=>Number(s.scores[p.id]||0))); return s.players.filter(p=>Number(s.scores[p.id]||0)===best).map(p=>p.id); }
function resetLeg(s:CallThreeState){ s.legIndex++; s.turnIndex=0; s.roundIndex=0; s.activePlayerIndex=0; s.scores=Object.fromEntries(s.players.map(p=>[p.id,0])); const g=generateCalls(s,0,0); s.currentCallerId=g.callerId; s.currentCalls=g.calls; if(g.callerId) s.statsByPlayer[g.callerId].callsMade++; }
function awardLeg(s:CallThreeState,winnerId:string){ s.lastLegWinnerId=winnerId; s.legWins[winnerId]=Number(s.legWins[winnerId]||0)+1; s.statsByPlayer[winnerId].legsWon++; if(s.legWins[winnerId]>=s.config.seriesWins){ s.phase='finished'; s.winnerId=winnerId; s.finishedAt=Date.now(); return; } resetLeg(s); }
export function playCallThreeVisit(input:CallThreeState,dartsRaw:GameDart[]):CallThreeState{ const s=cloneCallThreeState(input); if(s.phase!=='playing'||!s.players.length) return s; const p=s.players[s.activePlayerIndex]; if(!p) return s; const darts=(dartsRaw||[]).slice(0,3); const st=s.statsByPlayer[p.id]||(s.statsByPlayer[p.id]=blank()); st.visits++; const before=Number(s.scores[p.id]||0); let gained=0, hits=0; const events:string[]=[]; if(s.config.rules.orderedTargets){ for(let i=0;i<Math.min(3,darts.length);i++){ st.darts++; const d=darts[i]; const c=s.currentCalls[i]; if(matches(d,c)){ const pts=s.config.rules.multiplierScoring?scoreOfHit(d):1; gained+=pts; hits++; st.hits++; events.push(`${callLabel(c)} réussi +${pts}`); } else st.misses++; } } else { const remaining=s.currentCalls.map((c,idx)=>({c,idx})); for(const d of darts){ st.darts++; const idx=remaining.findIndex(x=>matches(d,x.c)); if(idx>=0){ const c=remaining[idx].c; const pts=s.config.rules.multiplierScoring?scoreOfHit(d):1; gained+=pts; hits++; st.hits++; events.push(`${callLabel(c)} réussi +${pts}`); remaining.splice(idx,1); } else st.misses++; } }
  if(hits===3){ st.perfectRounds++; events.push('FULL CALL : les 3 cibles sont réussies'); }
  st.points+=gained; s.scores[p.id]=before+gained; const callerId=s.currentCallerId; s.visits.push({id:uid('ct3v'),playerId:p.id,callerId,leg:s.legIndex+1,round:s.roundIndex+1,darts,calls:clone(s.currentCalls),before,after:s.scores[p.id],gained,hits,events}); s.turnIndex++;
  if(s.activePlayerIndex>=s.players.length-1){
    if(s.roundIndex+1>=s.config.rules.rounds){
      const leaders=leadersAtTopScore(s);
      if(leaders.length===1){ awardLeg(s,leaders[0]); return s; }
      const last=s.visits[s.visits.length-1]; if(last?.events) last.events.push('Égalité : round supplémentaire');
      s.roundIndex+=1; s.activePlayerIndex=0;
    } else { s.roundIndex+=1; s.activePlayerIndex=0; }
  } else s.activePlayerIndex+=1;
  const next=generateCalls(s,s.activePlayerIndex,s.roundIndex); s.currentCallerId=next.callerId; s.currentCalls=next.calls; if(next.callerId) s.statsByPlayer[next.callerId].callsMade++; return s; }
function chance(level:CallThreeBotLevel){return level==='hard'?.80:level==='easy'?.42:.62;}
function dartForCall(c:CallTarget,good:boolean):GameDart{ if(!good){ if(Math.random()<.18) return {bed:'MISS'}; const n=c.kind==='bull'? (1+Math.floor(Math.random()*20)) : (((c.number+Math.floor(Math.random()*9))%20)+1); return {bed:Math.random()<.18?'D':'S',number:n}; } if(c.kind==='bull') return {bed:Math.random()<.45?'IB':'OB'}; const bed=Math.random()<.20?'T':Math.random()<.45?'D':'S'; return {bed,number:c.number}; }
export function pickCallThreeBotDarts(input:CallThreeState, level:CallThreeBotLevel='normal'):GameDart[]{ const s=cloneCallThreeState(input); const prob=chance(level); const out:GameDart[]=[]; if(s.config.rules.orderedTargets){ for(let i=0;i<3;i++) out.push(dartForCall(s.currentCalls[i],Math.random()<prob)); } else { const arr=clone(s.currentCalls); for(let i=0;i<3;i++){ const c=arr[i%arr.length]; out.push(dartForCall(c,Math.random()<prob)); } } return out.slice(0,3); }
export const callThreeLabel=(c:CallTarget)=>callLabel(c);
