// @ts-nocheck
// =============================================================
// CRADOS — moteur pur
// Contamination de secteurs, jauge de crasse, douche Bull et BO.
// =============================================================
import type { GameDart, Player } from "../types-game";
export type CradosBotLevel="easy"|"normal"|"hard";
export type CradosConfigPayload={mode:"crados";selectedIds:string[];players:number;playersList?:any[];botIds?:string[];botsEnabled?:boolean;botLevel:CradosBotLevel;randomOrder?:boolean;scoreInputMethod?:"keypad"|"dartboard";seriesWins:1|2|3;rules:{dirtLimit:10|15|20;layersToOwn:2|3|4;bullWash:boolean;stealMode:"block"|"flip";}};
export type CradosSector={ownerId:string|null;claimantId:string|null;layers:number;};
export type CradosPlayerStats={darts:number;visits:number;layersPlaced:number;sectorsClaimed:number;sectorsStolen:number;dirtTaken:number;dirtWashed:number;legsWon:number;};
export type CradosVisit={id:string;playerId:string;leg:number;turn:number;darts:GameDart[];events:string[];dirtBefore:number;dirtAfter:number;};
export type CradosState={sport:"darts";mode:"crados";config:CradosConfigPayload;players:Player[];dirt:Record<string,number>;eliminated:Record<string,boolean>;sectors:Record<number,CradosSector>;legWins:Record<string,number>;statsByPlayer:Record<string,CradosPlayerStats>;activePlayerIndex:number;legIndex:number;turnIndex:number;phase:"playing"|"finished";winnerId:string|null;lastLegWinnerId:string|null;visits:CradosVisit[];startedAt:number;finishedAt?:number;};
function clone<T>(v:T):T{return JSON.parse(JSON.stringify(v));}function id(p="crados"){return`${p}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;}function blankStats():CradosPlayerStats{return{darts:0,visits:0,layersPlaced:0,sectorsClaimed:0,sectorsStolen:0,dirtTaken:0,dirtWashed:0,legsWon:0};}function power(d:GameDart){return d?.bed==="T"?3:d?.bed==="D"?2:1;}function numberOf(d:GameDart){return d?.bed==="S"||d?.bed==="D"||d?.bed==="T"?Number(d.number||0):0;}function aliveIds(s:CradosState){return s.players.filter(p=>!s.eliminated[p.id]).map(p=>p.id);}function nextAliveIndex(s:CradosState,from:number){for(let k=1;k<=s.players.length;k++){const i=(from+k)%s.players.length;const p=s.players[i];if(p&&!s.eliminated[p.id])return i;}return from;}function blankSectors(){const o:any={};for(let n=1;n<=20;n++)o[n]={ownerId:null,claimantId:null,layers:0};return o;}
export function normalizeCradosConfig(raw:any):CradosConfigPayload{const r=raw?.rules||{},ids=Array.isArray(raw?.selectedIds)?raw.selectedIds.map(String):[];return{mode:"crados",selectedIds:ids,players:Math.max(2,Number(raw?.players||ids.length||2)),playersList:Array.isArray(raw?.playersList)?raw.playersList:[],botIds:Array.isArray(raw?.botIds)?raw.botIds.map(String):[],botsEnabled:Boolean(raw?.botsEnabled),botLevel:raw?.botLevel==="easy"||raw?.botLevel==="hard"?raw.botLevel:"normal",randomOrder:raw?.randomOrder!==false,scoreInputMethod:raw?.scoreInputMethod==="dartboard"?"dartboard":"keypad",seriesWins:raw?.seriesWins===2||raw?.seriesWins===3?raw.seriesWins:1,rules:{dirtLimit:r?.dirtLimit===15||r?.dirtLimit===20?r.dirtLimit:10,layersToOwn:r?.layersToOwn===2||r?.layersToOwn===4?r.layersToOwn:3,bullWash:r?.bullWash!==false,stealMode:r?.stealMode==="flip"?"flip":"block"}};}
function resetLeg(s:CradosState,starter:number){s.legIndex+=1;s.turnIndex=0;s.dirt=Object.fromEntries(s.players.map(p=>[p.id,0]));s.eliminated=Object.fromEntries(s.players.map(p=>[p.id,false]));s.sectors=blankSectors();s.activePlayerIndex=starter;s.phase="playing";}
function winLeg(s:CradosState,winnerId:string){s.lastLegWinnerId=winnerId;s.legWins[winnerId]=Number(s.legWins[winnerId]||0)+1;s.statsByPlayer[winnerId].legsWon+=1;if(s.legWins[winnerId]>=s.config.seriesWins){s.phase="finished";s.winnerId=winnerId;s.finishedAt=Date.now();return s;}const wi=Math.max(0,s.players.findIndex(p=>p.id===winnerId));resetLeg(s,(wi+1)%s.players.length);return s;}
export function createCradosState(players:Player[],rawConfig:any):CradosState{const c=normalizeCradosConfig(rawConfig),ps=(players||[]).map((p,i)=>({id:String(p?.id||`p${i+1}`),name:String(p?.name||`Joueur ${i+1}`)}));return{sport:"darts",mode:"crados",config:c,players:ps,dirt:Object.fromEntries(ps.map(p=>[p.id,0])),eliminated:Object.fromEntries(ps.map(p=>[p.id,false])),sectors:blankSectors(),legWins:Object.fromEntries(ps.map(p=>[p.id,0])),statsByPlayer:Object.fromEntries(ps.map(p=>[p.id,blankStats()])),activePlayerIndex:0,legIndex:0,turnIndex:0,phase:"playing",winnerId:null,lastLegWinnerId:null,visits:[],startedAt:Date.now()};}
export function cloneCradosState(s:CradosState):CradosState{return clone(s);}
export function playCradosVisit(input:CradosState,dartsRaw:GameDart[]):CradosState{const s=cloneCradosState(input);if(s.phase!=="playing")return s;const p=s.players[s.activePlayerIndex];if(!p)return s;const ds=(dartsRaw||[]).slice(0,3),st=s.statsByPlayer[p.id]||(s.statsByPlayer[p.id]=blankStats()),before=Number(s.dirt[p.id]||0),events:string[]=[];st.visits+=1;
 for(const d of ds){st.darts+=1;if(!d||d.bed==="MISS")continue;if(d.bed==="OB"||d.bed==="IB"){if(s.config.rules.bullWash){const wash=d.bed==="IB"?3:1,old=Number(s.dirt[p.id]||0),next=Math.max(0,old-wash),done=old-next;s.dirt[p.id]=next;st.dirtWashed+=done;events.push(`${d.bed==="IB"?"DBULL":"BULL"} DOUCHE : −${done} crasse`);}continue;}const n=numberOf(d);if(!n)continue;const pow=power(d),sec=s.sectors[n]||(s.sectors[n]={ownerId:null,claimantId:null,layers:0});if(!sec.ownerId){if(sec.claimantId===p.id)sec.layers+=pow;else{sec.claimantId=p.id;sec.layers=pow;}st.layersPlaced+=pow;if(sec.layers>=s.config.rules.layersToOwn){sec.layers=s.config.rules.layersToOwn;sec.ownerId=p.id;sec.claimantId=p.id;st.sectorsClaimed+=1;events.push(`N°${n} devient CRADO pour ${p.name}`);}else events.push(`N°${n} : ${sec.layers}/${s.config.rules.layersToOwn} couches`);continue;}if(sec.ownerId===p.id){events.push(`N°${n} est déjà à toi`);continue;}if(s.config.rules.stealMode==="flip"){const oldOwner=sec.ownerId;sec.layers-=pow;if(sec.layers<=0){const overflow=Math.abs(sec.layers);sec.ownerId=p.id;sec.claimantId=p.id;sec.layers=Math.min(s.config.rules.layersToOwn,1+overflow);st.sectorsStolen+=1;events.push(`N°${n} VOLÉ à ${s.players.find(x=>x.id===oldOwner)?.name||"un adversaire"}`);}else events.push(`N°${n} attaqué : ${sec.layers} couche${sec.layers>1?"s":""}`);}else{s.dirt[p.id]=Number(s.dirt[p.id]||0)+pow;st.dirtTaken+=pow;events.push(`N°${n} adverse : +${pow} CRASSE`);if(s.dirt[p.id]>=s.config.rules.dirtLimit){s.dirt[p.id]=s.config.rules.dirtLimit;s.eliminated[p.id]=true;events.push(`${p.name} est trop CRADO : éliminé`);break;}}}
 s.visits.push({id:id("crados-visit"),playerId:p.id,leg:s.legIndex+1,turn:s.turnIndex+1,darts:ds,events,dirtBefore:before,dirtAfter:Number(s.dirt[p.id]||0)});s.turnIndex+=1;const alive=aliveIds(s);if(alive.length===1)return winLeg(s,alive[0]);s.activePlayerIndex=nextAliveIndex(s,s.activePlayerIndex);return s;}
function chance(level:CradosBotLevel){return level==="hard"?.82:level==="easy"?.48:.66;}export function pickCradosBotDarts(s:CradosState,level:CradosBotLevel="normal"):GameDart[]{const p=s.players[s.activePlayerIndex];if(!p)return[];if(s.config.rules.bullWash&&Number(s.dirt[p.id]||0)>=s.config.rules.dirtLimit*.6&&Math.random()<chance(level)*.45)return[{bed:Math.random()<chance(level)*.35?"IB":"OB"},{bed:"S",number:1+Math.floor(Math.random()*20)},{bed:"S",number:1+Math.floor(Math.random()*20)}];const sectors=Object.entries(s.sectors),enemy=sectors.filter(([,x]:any)=>x.ownerId&&x.ownerId!==p.id).map(([n])=>Number(n)),free=sectors.filter(([,x]:any)=>!x.ownerId).map(([n])=>Number(n)),own=sectors.filter(([,x]:any)=>x.ownerId===p.id).map(([n])=>Number(n));const pool=s.config.rules.stealMode==="flip"&&enemy.length?enemy:free.length?free:own.length?own:Array.from({length:20},(_,i)=>i+1);return Array.from({length:3},()=>{if(Math.random()>chance(level))return{bed:Math.random()<.12?"MISS":"S",number:1+Math.floor(Math.random()*20)} as GameDart;const r=Math.random(),bed=level==="hard"?(r<.30?"T":r<.56?"D":"S"):level==="easy"?(r<.07?"T":r<.18?"D":"S"):(r<.17?"T":r<.39?"D":"S");return{bed,number:pool[Math.floor(Math.random()*pool.length)]||20} as GameDart;});}
