// @ts-nocheck
import type { GameDart, Player } from "../types-game";

export type FiftyOneByFiveBotLevel = "easy" | "normal" | "hard";
export type FiftyOneByFiveConfigPayload = {
  mode: "fifty_one_by_five";
  selectedIds: string[];
  players: number;
  playersList?: any[];
  botIds?: string[];
  botsEnabled?: boolean;
  botLevel: FiftyOneByFiveBotLevel;
  randomOrder?: boolean;
  scoreInputMethod?: "keypad" | "dartboard";
  seriesWins: 1 | 2 | 3;
  rules: { target: number; divisor: number; requireThreeScoringDarts: boolean; bustRule: "hold" | "zero"; exactFinish: boolean; };
};
export type FiftyOneByFiveStats = { darts:number; visits:number; validVisits:number; invalidVisits:number; busts:number; rawPoints:number; quotientPoints:number; highestRaw:number; finishes:number; legsWon:number; misses:number; bulls:number; };
export type FiftyOneByFiveVisit = { id:string; playerId:string; leg:number; turn:number; darts:GameDart[]; rawTotal:number; dividedScore:number; before:number; after:number; valid:boolean; bust:boolean; events:string[]; };
export type FiftyOneByFiveState = { sport:"darts"; mode:"fifty_one_by_five"; config:FiftyOneByFiveConfigPayload; players:Player[]; scores:Record<string,number>; legWins:Record<string,number>; statsByPlayer:Record<string,FiftyOneByFiveStats>; activePlayerIndex:number; legIndex:number; turnIndex:number; phase:"playing"|"finished"; winnerId:string|null; lastLegWinnerId:string|null; visits:FiftyOneByFiveVisit[]; startedAt:number; finishedAt?:number; };
const clone=<T,>(v:T):T=>JSON.parse(JSON.stringify(v));
const uid=(p='51x5')=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;
const blankStats=():FiftyOneByFiveStats=>({darts:0,visits:0,validVisits:0,invalidVisits:0,busts:0,rawPoints:0,quotientPoints:0,highestRaw:0,finishes:0,legsWon:0,misses:0,bulls:0});
const scoreOf=(d:GameDart)=>!d||d.bed==="MISS"?0:d.bed==="OB"?25:d.bed==="IB"?50:(Number(d.number||0)*(d.bed==="D"?2:d.bed==="T"?3:1));
function scorePlan(targetRaw:number){ let rem=Math.max(0,Math.min(180,Math.round(targetRaw))); const out:GameDart[]=[]; for(let i=0;i<3;i++){ if(rem<=0) break; if(rem>=60){ out.push({bed:"T",number:20}); rem-=60; continue; } if(rem===50){ out.push({bed:"IB"}); rem=0; continue; } if(rem===25){ out.push({bed:"OB"}); rem=0; continue; } if(rem%3===0 && rem/3<=20){ out.push({bed:"T",number:rem/3}); rem=0; continue; } if(rem%2===0 && rem/2<=20){ out.push({bed:"D",number:rem/2}); rem=0; continue; } out.push({bed:"S",number:Math.min(20,rem)}); rem-=Math.min(20,rem);} while(out.length<3) out.push({bed:"MISS"}); return out.slice(0,3); }
export function normalizeFiftyOneByFiveConfig(raw:any):FiftyOneByFiveConfigPayload{ const r=raw?.rules||{}; const ids=Array.isArray(raw?.selectedIds)?raw.selectedIds.map(String):[]; return { mode:"fifty_one_by_five", selectedIds:ids, players:Math.max(1,Number(raw?.players||ids.length||1)), playersList:Array.isArray(raw?.playersList)?raw.playersList:[], botIds:Array.isArray(raw?.botIds)?raw.botIds.map(String):[], botsEnabled:Boolean(raw?.botsEnabled), botLevel:raw?.botLevel==="easy"||raw?.botLevel==="hard"?raw.botLevel:"normal", randomOrder:raw?.randomOrder!==false, scoreInputMethod:raw?.scoreInputMethod==="dartboard"?"dartboard":"keypad", seriesWins:raw?.seriesWins===2||raw?.seriesWins===3?raw.seriesWins:1, rules:{ target:[31,51,71,101].includes(Number(r?.target))?Number(r.target):51, divisor:Number(r?.divisor)===5?5:5, requireThreeScoringDarts:r?.requireThreeScoringDarts!==false, bustRule:r?.bustRule==="zero"?"zero":"hold", exactFinish:r?.exactFinish!==false } }; }
export function createFiftyOneByFiveState(players:Player[], raw:any):FiftyOneByFiveState{ const config=normalizeFiftyOneByFiveConfig(raw); const ps=(players||[]).map((p,i)=>({id:String(p?.id||`p${i+1}`), name:String(p?.name||`Joueur ${i+1}`)})); return { sport:"darts", mode:"fifty_one_by_five", config, players:ps, scores:Object.fromEntries(ps.map(p=>[p.id,0])), legWins:Object.fromEntries(ps.map(p=>[p.id,0])), statsByPlayer:Object.fromEntries(ps.map(p=>[p.id,blankStats()])), activePlayerIndex:0, legIndex:0, turnIndex:0, phase:"playing", winnerId:null, lastLegWinnerId:null, visits:[], startedAt:Date.now() }; }
export const cloneFiftyOneByFiveState=(s:FiftyOneByFiveState):FiftyOneByFiveState=>clone(s);
function resetForNextLeg(s:FiftyOneByFiveState){ s.legIndex++; s.turnIndex=0; s.activePlayerIndex=0; s.scores=Object.fromEntries(s.players.map(p=>[p.id,0])); }
function awardLeg(s:FiftyOneByFiveState,winnerId:string){ s.lastLegWinnerId=winnerId; s.legWins[winnerId]=Number(s.legWins[winnerId]||0)+1; const st=s.statsByPlayer[winnerId]||(s.statsByPlayer[winnerId]=blankStats()); st.legsWon++; st.finishes++; if(s.legWins[winnerId]>=s.config.seriesWins){ s.phase="finished"; s.winnerId=winnerId; s.finishedAt=Date.now(); return; } resetForNextLeg(s); }
export function playFiftyOneByFiveVisit(input:FiftyOneByFiveState, dartsRaw:GameDart[]):FiftyOneByFiveState{ const s=cloneFiftyOneByFiveState(input); if(s.phase!=="playing"||!s.players.length) return s; const darts=(dartsRaw||[]).slice(0,3); const p=s.players[s.activePlayerIndex]; if(!p) return s; const st=s.statsByPlayer[p.id]||(s.statsByPlayer[p.id]=blankStats()); st.visits++; const before=Number(s.scores[p.id]||0); let rawTotal=0; let nonZero=0; for(const d of darts){ st.darts++; const sc=scoreOf(d); rawTotal+=sc; if(sc>0) nonZero++; if(!d||d.bed==="MISS") st.misses++; if(d?.bed==="OB"||d?.bed==="IB") st.bulls++; }
  st.highestRaw=Math.max(st.highestRaw,rawTotal); let valid= rawTotal>0 && rawTotal % s.config.rules.divisor === 0; if(s.config.rules.requireThreeScoringDarts) valid = valid && darts.length===3 && nonZero===3; const divided= valid ? Math.floor(rawTotal / s.config.rules.divisor) : 0; let after=before; let bust=false; const events:string[]=[]; if(valid){ const tentative=before + divided; if(s.config.rules.exactFinish && tentative > s.config.rules.target){ bust=true; st.busts++; st.invalidVisits++; after=s.config.rules.bustRule==="zero"?0:before; if(s.config.rules.bustRule==="zero") events.push(`${p.name} dépasse ${s.config.rules.target} : retour à 0`); else events.push(`${p.name} dépasse ${s.config.rules.target} : score conservé`); } else { after=tentative; st.validVisits++; st.rawPoints+=rawTotal; st.quotientPoints+=divided; events.push(`${rawTotal} ÷ ${s.config.rules.divisor} = +${divided}`); if(after===s.config.rules.target){ s.scores[p.id]=after; s.visits.push({id:uid('51v'),playerId:p.id,leg:s.legIndex+1,turn:s.turnIndex+1,darts,rawTotal,dividedScore:divided,before,after,valid:true,bust:false,events}); s.turnIndex++; awardLeg(s,p.id); return s; } } } else { st.invalidVisits++; events.push(`Volée non divisible par ${s.config.rules.divisor}`); }
  s.scores[p.id]=after; s.visits.push({id:uid('51v'),playerId:p.id,leg:s.legIndex+1,turn:s.turnIndex+1,darts,rawTotal,dividedScore:divided,before,after,valid,bust,events}); s.turnIndex++; s.activePlayerIndex=(s.activePlayerIndex+1)%s.players.length; return s; }
function hitProb(level:FiftyOneByFiveBotLevel){ return level==="hard"?.86:level==="easy"?.45:.66; }
function nearMultipleOf5(raw:number){ return Math.max(5, Math.min(180, raw - (raw%5))); }
export function pickFiftyOneByFiveBotDarts(input:FiftyOneByFiveState, level:FiftyOneByFiveBotLevel="normal"):GameDart[]{ const s=cloneFiftyOneByFiveState(input); const p=s.players[s.activePlayerIndex]; if(!p) return []; const needPoints=Math.max(0,s.config.rules.target - Number(s.scores[p.id]||0)); let rawGoal=nearMultipleOf5(Math.min(180, needPoints*5)); if(rawGoal===0) rawGoal=25; if(Math.random()>hitProb(level)) rawGoal=nearMultipleOf5(Math.max(5, rawGoal - (10+Math.floor(Math.random()*45)))); const plan=scorePlan(rawGoal); if(s.config.rules.requireThreeScoringDarts){ for(let i=0;i<plan.length;i++){ if(plan[i].bed==="MISS") plan[i]={bed:"S",number:1}; } }
  return plan.slice(0,3);
}
