// @ts-nocheck
// =============================================================
// HARE & HOUNDS — moteur pur
// Poursuite sur l'ordre physique des secteurs du dartboard.
// =============================================================
import type { GameDart, Player } from "../types-game";
export type HareBotLevel="easy"|"normal"|"hard";
export type HareConfigPayload={mode:"hare_hounds";selectedIds:string[];players:number;playersList?:any[];botIds?:string[];botsEnabled?:boolean;botLevel:HareBotLevel;randomOrder?:boolean;scoreInputMethod?:"keypad"|"dartboard";seriesWins:1|2|3;rules:{houndStart:5|12;targetZone:"any"|"double"|"triple";roleMode:"first"|"random"|"rotate";direction:"clockwise"|"counter";hareStart:20}};
export type HareStats={darts:number;visits:number;validHits:number;misses:number;steps:number;catches:number;escapes:number;legsWon:number;};
export type HareVisit={id:string;playerId:string;role:"hare"|"hound";leg:number;darts:GameDart[];startSegment:number;endSegment:number;steps:number;events:string[];};
export type HareState={sport:"darts";mode:"hare_hounds";config:HareConfigPayload;players:Player[];harePlayerId:string;startIndexByPlayer:Record<string,number>;progressByPlayer:Record<string,number>;legWins:Record<string,number>;statsByPlayer:Record<string,HareStats>;activePlayerIndex:number;legIndex:number;turnIndex:number;phase:"playing"|"finished";winnerId:string|null;lastLegWinnerId:string|null;visits:HareVisit[];startedAt:number;finishedAt?:number;};
const CW=[20,1,18,4,13,6,10,15,2,17,3,19,7,16,8,11,14,9,12,5];
function clone<T>(v:T):T{return JSON.parse(JSON.stringify(v));}
function uid(prefix="hare"){return`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;}
function blankStats():HareStats{return{darts:0,visits:0,validHits:0,misses:0,steps:0,catches:0,escapes:0,legsWon:0};}
export function normalizeHareConfig(raw:any):HareConfigPayload{const r=raw?.rules||{};const ids=Array.isArray(raw?.selectedIds)?raw.selectedIds.map(String):[];return{mode:"hare_hounds",selectedIds:ids,players:Math.max(2,Number(raw?.players||ids.length||2)),playersList:Array.isArray(raw?.playersList)?raw.playersList:[],botIds:Array.isArray(raw?.botIds)?raw.botIds.map(String):[],botsEnabled:Boolean(raw?.botsEnabled),botLevel:raw?.botLevel==="easy"||raw?.botLevel==="hard"?raw.botLevel:"normal",randomOrder:raw?.randomOrder!==false,scoreInputMethod:raw?.scoreInputMethod==="dartboard"?"dartboard":"keypad",seriesWins:raw?.seriesWins===2||raw?.seriesWins===3?raw.seriesWins:1,rules:{houndStart:Number(r?.houndStart)===12?12:5,targetZone:r?.targetZone==="double"||r?.targetZone==="triple"?r.targetZone:"any",roleMode:r?.roleMode==="random"||r?.roleMode==="rotate"?r.roleMode:"first",direction:r?.direction==="counter"?"counter":"clockwise",hareStart:20}};}
export function hareSequence(direction:"clockwise"|"counter"="clockwise"){return direction==="clockwise"?[...CW]:[20,...CW.slice(1).reverse()];}
function chooseHare(players:Player[],config:HareConfigPayload,leg:number,previous?:string):string{if(!players.length)return"";if(config.rules.roleMode==="first")return players[0].id;if(config.rules.roleMode==="rotate")return players[leg%players.length].id;const pool=players.filter(p=>p.id!==previous);return(pool.length?pool:players)[Math.floor(Math.random()*(pool.length?pool.length:players.length))]?.id||players[0].id;}
function setupLeg(s:HareState,previousHare?:string){const seq=hareSequence(s.config.rules.direction);s.harePlayerId=chooseHare(s.players,s.config,s.legIndex,previousHare);const houndIdx=Math.max(0,seq.indexOf(s.config.rules.houndStart));s.startIndexByPlayer=Object.fromEntries(s.players.map(p=>[p.id,p.id===s.harePlayerId?0:houndIdx]));s.progressByPlayer=Object.fromEntries(s.players.map(p=>[p.id,0]));s.activePlayerIndex=0;s.turnIndex=0;}
export function createHareState(players:Player[],raw:any):HareState{const config=normalizeHareConfig(raw);const ps=(players||[]).map((p,i)=>({id:String(p?.id||`p${i+1}`),name:String(p?.name||`Joueur ${i+1}`)}));const s:HareState={sport:"darts",mode:"hare_hounds",config,players:ps,harePlayerId:"",startIndexByPlayer:{},progressByPlayer:{},legWins:Object.fromEntries(ps.map(p=>[p.id,0])),statsByPlayer:Object.fromEntries(ps.map(p=>[p.id,blankStats()])),activePlayerIndex:0,legIndex:0,turnIndex:0,phase:"playing",winnerId:null,lastLegWinnerId:null,visits:[],startedAt:Date.now()};setupLeg(s);return s;}
export function cloneHareState(s:HareState):HareState{return clone(s);}
export function hareCurrentIndex(s:HareState,pid:string){const start=Number(s.startIndexByPlayer[pid]||0);const prog=Number(s.progressByPlayer[pid]||0);return((start+prog)%20+20)%20;}
export function hareCurrentSegment(s:HareState,pid:string){const seq=hareSequence(s.config.rules.direction);return seq[hareCurrentIndex(s,pid)]||20;}
function dartHitsTarget(d:GameDart,target:number,zone:HareConfigPayload["rules"]["targetZone"]){if(!d||d.bed==="MISS"||d.bed==="OB"||d.bed==="IB")return false;if(Number(d.number||0)!==target)return false;if(zone==="double")return d.bed==="D";if(zone==="triple")return d.bed==="T";return d.bed==="S"||d.bed==="D"||d.bed==="T";}
function awardLeg(s:HareState,winnerId:string){s.lastLegWinnerId=winnerId;s.legWins[winnerId]=Number(s.legWins[winnerId]||0)+1;s.statsByPlayer[winnerId].legsWon++;if(winnerId===s.harePlayerId)s.statsByPlayer[winnerId].escapes++;else s.statsByPlayer[winnerId].catches++;if(s.legWins[winnerId]>=s.config.seriesWins){s.phase="finished";s.winnerId=winnerId;s.finishedAt=Date.now();return;}const oldHare=s.harePlayerId;s.legIndex++;setupLeg(s,oldHare);}
export function playHareVisit(input:HareState,dartsRaw:GameDart[]):HareState{const s=cloneHareState(input);if(s.phase!=="playing"||!s.players.length)return s;const darts=(dartsRaw||[]).slice(0,3);const p=s.players[s.activePlayerIndex];const role=p.id===s.harePlayerId?"hare":"hound";const st=s.statsByPlayer[p.id]||(s.statsByPlayer[p.id]=blankStats());st.visits++;const startSeg=hareCurrentSegment(s,p.id);let steps=0;let winner:string|null=null;const events:string[]=[];for(const d of darts){st.darts++;const target=hareCurrentSegment(s,p.id);if(dartHitsTarget(d,target,s.config.rules.targetZone)){s.progressByPlayer[p.id]=Number(s.progressByPlayer[p.id]||0)+1;st.validHits++;st.steps++;steps++;events.push(`${p.name} avance sur ${hareCurrentSegment(s,p.id)}`);if(role==="hare"&&Number(s.progressByPlayer[p.id]||0)>=20){winner=p.id;events.push("Le Lièvre boucle le tour !");break;}if(role==="hound"&&hareCurrentIndex(s,p.id)===hareCurrentIndex(s,s.harePlayerId)){winner=p.id;events.push(`${p.name} rattrape le Lièvre !`);break;}}else st.misses++;}
  const endSeg=hareCurrentSegment(s,p.id);s.visits.push({id:uid("hare-visit"),playerId:p.id,role,leg:s.legIndex+1,darts,startSegment:startSeg,endSegment:endSeg,steps,events});s.turnIndex++;if(winner){awardLeg(s,winner);return s;}s.activePlayerIndex=(s.activePlayerIndex+1)%s.players.length;return s;}
export function hareDartLabel(d:GameDart){if(!d||d.bed==="MISS")return"MISS";if(d.bed==="IB")return"DBULL";if(d.bed==="OB")return"BULL";return`${d.bed}${d.number||""}`;}
function chance(level:HareBotLevel){return level==="hard"?.88:level==="easy"?.50:.70;}
export function pickHareBotDarts(input:HareState,level:HareBotLevel="normal"):GameDart[]{const s=cloneHareState(input);const p=s.players[s.activePlayerIndex];if(!p)return[];const out:GameDart[]=[];for(let i=0;i<3;i++){const target=hareCurrentSegment(s,p.id);const hit=Math.random()<chance(level);if(!hit){out.push(Math.random()<.15?{bed:"MISS"}:{bed:"S",number:((target+Math.floor(Math.random()*7)+19)%20)+1});continue;}const bed=s.config.rules.targetZone==="double"?"D":s.config.rules.targetZone==="triple"?"T":level==="hard"&&Math.random()<.34?"T":Math.random()<.28?"D":"S";const d={bed,number:target} as GameDart;out.push(d);s.progressByPlayer[p.id]=Number(s.progressByPlayer[p.id]||0)+1;if(p.id===s.harePlayerId&&s.progressByPlayer[p.id]>=20)break;if(p.id!==s.harePlayerId&&hareCurrentIndex(s,p.id)===hareCurrentIndex(s,s.harePlayerId))break;}return out;}
