// @ts-nocheck
import type { GameDart, Player } from "../types-game";
export type LooperBotLevel="easy"|"normal"|"hard";
export type LooperConfigPayload={mode:"looper";selectedIds:string[];players:number;playersList?:any[];botIds?:string[];botsEnabled?:boolean;botLevel:LooperBotLevel;randomOrder?:boolean;scoreInputMethod?:"keypad"|"dartboard";seriesWins:1|2|3;rules:{lives:number;startTarget:"offhand"|"random";exactSegment:boolean;numberLoopsEnabled:boolean;setterShield:boolean;}};
export type LooperStats={darts:number;visits:number;hits:number;misses:number;lifeLosses:number;shieldsUsed:number;shieldsEarned:number;targetsSet:number;loopsSurvived:number;legsWon:number;};
export type LooperVisit={id:string;playerId:string;leg:number;turn:number;darts:GameDart[];targetBefore:number;targetAfter:number;beforeLives:Record<string,number>;afterLives:Record<string,number>;hit:boolean;events:string[];};
export type LooperState={sport:"darts";mode:"looper";config:LooperConfigPayload;players:Player[];lives:Record<string,number>;shields:Record<string,number>;legWins:Record<string,number>;statsByPlayer:Record<string,LooperStats>;activePlayerIndex:number;legIndex:number;turnIndex:number;phase:"assignment"|"playing"|"finished";winnerId:string|null;lastLegWinnerId:string|null;currentTarget:number;setterId:string|null;visits:LooperVisit[];startedAt:number;finishedAt?:number;};
const clone=<T,>(v:T):T=>JSON.parse(JSON.stringify(v)); const uid=(p='looper')=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`; const blank=():LooperStats=>({darts:0,visits:0,hits:0,misses:0,lifeLosses:0,shieldsUsed:0,shieldsEarned:0,targetsSet:0,loopsSurvived:0,legsWon:0});
const numOf=(d:GameDart)=>d?.bed==='S'||d?.bed==='D'||d?.bed==='T'?Number(d.number||0):0;
export function normalizeLooperConfig(raw:any):LooperConfigPayload{const r=raw?.rules||{}; const ids=Array.isArray(raw?.selectedIds)?raw.selectedIds.map(String):[]; return {mode:"looper",selectedIds:ids,players:Math.max(2,Number(raw?.players||ids.length||2)),playersList:Array.isArray(raw?.playersList)?raw.playersList:[],botIds:Array.isArray(raw?.botIds)?raw.botIds.map(String):[],botsEnabled:Boolean(raw?.botsEnabled),botLevel:raw?.botLevel==="easy"||raw?.botLevel==="hard"?raw.botLevel:"normal",randomOrder:raw?.randomOrder!==false,scoreInputMethod:raw?.scoreInputMethod==="dartboard"?"dartboard":"keypad",seriesWins:raw?.seriesWins===2||raw?.seriesWins===3?raw.seriesWins:1,rules:{lives:[3,4,5].includes(Number(r?.lives))?Number(r.lives):5,startTarget:r?.startTarget==="random"?"random":"offhand",exactSegment:r?.exactSegment!==false,numberLoopsEnabled:r?.numberLoopsEnabled!==false,setterShield:r?.setterShield!==false}};}
function aliveIds(s:LooperState){return s.players.filter(p=>Number(s.lives[p.id]||0)>0).map(p=>p.id);} function nextAliveIndex(s:LooperState,from:number){const total=s.players.length||1; for(let step=1;step<=total;step++){ const idx=(from+step)%total; if(Number(s.lives[s.players[idx].id]||0)>0) return idx; } return from; }
export function createLooperState(players:Player[],raw:any):LooperState{const config=normalizeLooperConfig(raw); const ps=(players||[]).map((p,i)=>({id:String(p?.id||`p${i+1}`),name:String(p?.name||`Joueur ${i+1}`)})); const randomTarget=1+Math.floor(Math.random()*20); return {sport:"darts",mode:"looper",config,players:ps,lives:Object.fromEntries(ps.map(p=>[p.id,config.rules.lives])),shields:Object.fromEntries(ps.map(p=>[p.id,0])),legWins:Object.fromEntries(ps.map(p=>[p.id,0])),statsByPlayer:Object.fromEntries(ps.map(p=>[p.id,blank()])),activePlayerIndex:0,legIndex:0,turnIndex:0,phase:config.rules.startTarget==="offhand"?"assignment":"playing",winnerId:null,lastLegWinnerId:null,currentTarget:randomTarget,setterId:null,visits:[],startedAt:Date.now()};}
export const cloneLooperState=(s:LooperState):LooperState=>clone(s);
export function assignLooperTarget(input:LooperState,dart:GameDart):LooperState{const s=cloneLooperState(input); if(s.phase!=="assignment") return s; const n=numOf(dart); s.currentTarget=n>=1&&n<=20?n:(1+Math.floor(Math.random()*20)); s.phase="playing"; return s; }
function resetLeg(s:LooperState){ s.legIndex++; s.turnIndex=0; s.activePlayerIndex=0; s.phase=s.config.rules.startTarget==="offhand"?"assignment":"playing"; s.currentTarget=1+Math.floor(Math.random()*20); s.setterId=null; s.lives=Object.fromEntries(s.players.map(p=>[p.id,s.config.rules.lives])); s.shields=Object.fromEntries(s.players.map(p=>[p.id,0])); }
function awardLeg(s:LooperState,winnerId:string){ s.lastLegWinnerId=winnerId; s.legWins[winnerId]=Number(s.legWins[winnerId]||0)+1; s.statsByPlayer[winnerId].legsWon++; if(s.legWins[winnerId]>=s.config.seriesWins){ s.phase="finished"; s.winnerId=winnerId; s.finishedAt=Date.now(); return; } resetLeg(s); }
export function playLooperVisit(input:LooperState,dartsRaw:GameDart[]):LooperState{const s=cloneLooperState(input); if(s.phase!=="playing"||!s.players.length) return s; const p=s.players[s.activePlayerIndex]; if(!p||Number(s.lives[p.id]||0)<=0) return s; const darts=(dartsRaw||[]).slice(0,3); const beforeLives=clone(s.lives); const st=s.statsByPlayer[p.id]||(s.statsByPlayer[p.id]=blank()); st.visits++; let hit=false; let lastNumber=0; const events:string[]=[]; const targetBefore=s.currentTarget; for(const d of darts){ st.darts++; const n=numOf(d); if(n===s.currentTarget){ hit=true; st.hits++; lastNumber=n; events.push(`${p.name} boucle ${n}`); } else if(n){ st.misses++; lastNumber=n; } else st.misses++; }
  if(hit){ st.loopsSurvived++; let nextTarget=lastNumber||s.currentTarget; if(!s.config.rules.numberLoopsEnabled && nextTarget===s.currentTarget) nextTarget=(nextTarget%20)+1; s.currentTarget=nextTarget; s.setterId=p.id; st.targetsSet++; if(s.config.rules.setterShield){ s.shields[p.id]=Number(s.shields[p.id]||0)+1; st.shieldsEarned++; events.push(`Bouclier +1`); } }
  else { if(Number(s.shields[p.id]||0)>0){ s.shields[p.id]=Number(s.shields[p.id]||0)-1; st.shieldsUsed++; events.push(`${p.name} consomme un bouclier`); } else { s.lives[p.id]=Math.max(0,Number(s.lives[p.id]||0)-1); st.lifeLosses++; events.push(`${p.name} perd 1 vie`); } }
  const alive=aliveIds(s); if(alive.length===1){ s.visits.push({id:uid('loopv'),playerId:p.id,leg:s.legIndex+1,turn:s.turnIndex+1,darts,targetBefore,targetAfter:s.currentTarget,beforeLives,afterLives:clone(s.lives),hit,events}); s.turnIndex++; awardLeg(s,alive[0]); return s; }
  s.visits.push({id:uid('loopv'),playerId:p.id,leg:s.legIndex+1,turn:s.turnIndex+1,darts,targetBefore,targetAfter:s.currentTarget,beforeLives,afterLives:clone(s.lives),hit,events}); s.turnIndex++; s.activePlayerIndex=nextAliveIndex(s,s.activePlayerIndex); return s; }
function chance(level:LooperBotLevel){return level==="hard"?.82:level==="easy"?.44:.63;}
function randMiss(target:number):GameDart{ if(Math.random()<.2) return {bed:"MISS"}; const n=((target+Math.floor(Math.random()*8)+1)%20)+1; return {bed:Math.random()<.22?"D":Math.random()<.08?"T":"S",number:n}; }
export function pickLooperBotDarts(input:LooperState,level:LooperBotLevel="normal"):GameDart[]{ const s=cloneLooperState(input); if(s.phase==="assignment"){ return [{bed:"S",number:1+Math.floor(Math.random()*20)}]; } const p=s.players[s.activePlayerIndex]; if(!p) return []; const out:GameDart[]=[]; const good=Math.random()<chance(level); for(let i=0;i<3;i++){ if(good && (i===0 || Math.random()<0.72)){ out.push({bed:Math.random()<.25?"D":"S",number:s.currentTarget}); } else if(good && i===2){ const hardSet=[20,1,18,4,13,6,10,15,2,17]; out.push({bed:"S",number:hardSet[Math.floor(Math.random()*hardSet.length)]}); } else out.push(randMiss(s.currentTarget)); } return out.slice(0,3); }
