// @ts-nocheck
// =============================================================
// MENTEUR — moteur pur
// Enchères, appel MENTEUR, tentative du contrat, vies et BO.
// =============================================================
import type { GameDart, Player } from "../types-game";
export type MenteurBotLevel="easy"|"normal"|"hard"; export type MenteurCondition="none"|"double"|"triple"|"bull"|"distinct";
export type MenteurConfigPayload={mode:"menteur";selectedIds:string[];players:number;playersList?:any[];botIds?:string[];botsEnabled?:boolean;botLevel:MenteurBotLevel;randomOrder?:boolean;scoreInputMethod?:"keypad"|"dartboard";seriesWins:1|2|3;rules:{lives:3|5|7;contractDeck:"score"|"mixed"|"advanced";raiseStep:5|10|20;bullAllowed:boolean;}};
export type MenteurPlayerStats={darts:number;visits:number;raises:number;liarCalls:number;contractsProven:number;liesCaught:number;livesLost:number;legsWon:number;bestVisit:number;};
export type MenteurAction={id:string;kind:"raise"|"call"|"resolution";playerId:string;leg:number;turn:number;bid:number;condition:MenteurCondition;darts?:GameDart[];score?:number;success?:boolean;events:string[];};
export type MenteurState={sport:"darts";mode:"menteur";config:MenteurConfigPayload;players:Player[];lives:Record<string,number>;eliminated:Record<string,boolean>;legWins:Record<string,number>;statsByPlayer:Record<string,MenteurPlayerStats>;activePlayerIndex:number;bid:number;condition:MenteurCondition;lastBidderId:string|null;challengerId:string|null;challengedId:string|null;legIndex:number;turnIndex:number;phase:"auction"|"challenge"|"finished";winnerId:string|null;lastLegWinnerId:string|null;visits:MenteurAction[];startedAt:number;finishedAt?:number;};
function clone<T>(v:T):T{return JSON.parse(JSON.stringify(v));}function id(p="menteur"){return`${p}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;}function blankStats():MenteurPlayerStats{return{darts:0,visits:0,raises:0,liarCalls:0,contractsProven:0,liesCaught:0,livesLost:0,legsWon:0,bestVisit:0};}
function scoreDart(d:GameDart){if(!d||d.bed==="MISS")return 0;if(d.bed==="IB")return 50;if(d.bed==="OB")return 25;return Number(d.number||0)*(d.bed==="T"?3:d.bed==="D"?2:1);}function scoreVisit(ds:GameDart[]){return(ds||[]).slice(0,3).reduce((s,d)=>s+scoreDart(d),0);}function aliveIds(s:MenteurState){return s.players.filter(p=>!s.eliminated[p.id]).map(p=>p.id);}function nextAliveIndex(s:MenteurState,from:number){for(let k=1;k<=s.players.length;k++){const i=(from+k)%s.players.length;const p=s.players[i];if(p&&!s.eliminated[p.id])return i;}return from;}
export function normalizeMenteurConfig(raw:any):MenteurConfigPayload{const r=raw?.rules||{},ids=Array.isArray(raw?.selectedIds)?raw.selectedIds.map(String):[];return{mode:"menteur",selectedIds:ids,players:Math.max(2,Number(raw?.players||ids.length||2)),playersList:Array.isArray(raw?.playersList)?raw.playersList:[],botIds:Array.isArray(raw?.botIds)?raw.botIds.map(String):[],botsEnabled:Boolean(raw?.botsEnabled),botLevel:raw?.botLevel==="easy"||raw?.botLevel==="hard"?raw.botLevel:"normal",randomOrder:raw?.randomOrder!==false,scoreInputMethod:raw?.scoreInputMethod==="dartboard"?"dartboard":"keypad",seriesWins:raw?.seriesWins===2||raw?.seriesWins===3?raw.seriesWins:1,rules:{lives:r?.lives===3||r?.lives===7?r.lives:5,contractDeck:["mixed","advanced"].includes(r?.contractDeck)?r.contractDeck:"score",raiseStep:r?.raiseStep===10||r?.raiseStep===20?r.raiseStep:5,bullAllowed:r?.bullAllowed!==false}};}
export function randomMenteurCondition(configOrRules:any):MenteurCondition{const r=configOrRules?.rules||configOrRules||{};if(r.contractDeck==="score")return"none";const pool:MenteurCondition[]=r.contractDeck==="advanced"?["none","double","triple","distinct",...(r.bullAllowed!==false?["bull"]:[])]:["none","double","triple"];return pool[Math.floor(Math.random()*pool.length)]||"none";}
export function menteurConditionLabel(c:MenteurCondition){return c==="double"?"+ 1 DOUBLE":c==="triple"?"+ 1 TRIPLE":c==="bull"?"+ 1 BULL":c==="distinct"?"+ 3 NUMÉROS DIFFÉRENTS":"SCORE LIBRE";}
function resetAuction(s:MenteurState,opener:number){s.activePlayerIndex=opener;s.bid=0;s.condition=randomMenteurCondition(s.config);s.lastBidderId=null;s.challengerId=null;s.challengedId=null;s.phase="auction";return s;}
function resetLeg(s:MenteurState,starter:number){s.legIndex+=1;s.turnIndex=0;s.lives=Object.fromEntries(s.players.map(p=>[p.id,s.config.rules.lives]));s.eliminated=Object.fromEntries(s.players.map(p=>[p.id,false]));resetAuction(s,starter);}
function winLeg(s:MenteurState,winnerId:string){s.lastLegWinnerId=winnerId;s.legWins[winnerId]=Number(s.legWins[winnerId]||0)+1;s.statsByPlayer[winnerId].legsWon+=1;if(s.legWins[winnerId]>=s.config.seriesWins){s.phase="finished";s.winnerId=winnerId;s.finishedAt=Date.now();return s;}const wi=Math.max(0,s.players.findIndex(p=>p.id===winnerId));resetLeg(s,(wi+1)%s.players.length);return s;}
export function createMenteurState(players:Player[],rawConfig:any):MenteurState{const c=normalizeMenteurConfig(rawConfig),ps=(players||[]).map((p,i)=>({id:String(p?.id||`p${i+1}`),name:String(p?.name||`Joueur ${i+1}`)}));return{sport:"darts",mode:"menteur",config:c,players:ps,lives:Object.fromEntries(ps.map(p=>[p.id,c.rules.lives])),eliminated:Object.fromEntries(ps.map(p=>[p.id,false])),legWins:Object.fromEntries(ps.map(p=>[p.id,0])),statsByPlayer:Object.fromEntries(ps.map(p=>[p.id,blankStats()])),activePlayerIndex:0,bid:0,condition:randomMenteurCondition(c),lastBidderId:null,challengerId:null,challengedId:null,legIndex:0,turnIndex:0,phase:"auction",winnerId:null,lastLegWinnerId:null,visits:[],startedAt:Date.now()};}
export function cloneMenteurState(s:MenteurState):MenteurState{return clone(s);}
export function raiseMenteurBid(input:MenteurState,amount:number):MenteurState{const s=cloneMenteurState(input);if(s.phase!=="auction")return s;const p=s.players[s.activePlayerIndex];if(!p)return s;const step=s.config.rules.raiseStep,inc=Math.max(step,Number(amount||step));const next=s.lastBidderId==null?Math.min(180,Math.max(30,inc)):Math.min(180,s.bid+inc);const ev=[`${p.name} annonce ${next} points`];s.bid=next;s.lastBidderId=p.id;s.challengerId=null;s.challengedId=null;s.statsByPlayer[p.id].raises+=1;s.visits.push({id:id("menteur-raise"),kind:"raise",playerId:p.id,leg:s.legIndex+1,turn:s.turnIndex+1,bid:s.bid,condition:s.condition,events:ev});s.turnIndex+=1;s.activePlayerIndex=nextAliveIndex(s,s.activePlayerIndex);return s;}
export function callMenteur(input:MenteurState):MenteurState{const s=cloneMenteurState(input);if(s.phase!=="auction"||!s.lastBidderId)return s;const challenger=s.players[s.activePlayerIndex],challenged=s.players.find(p=>p.id===s.lastBidderId);if(!challenger||!challenged)return s;s.challengerId=challenger.id;s.challengedId=challenged.id;s.phase="challenge";s.activePlayerIndex=Math.max(0,s.players.findIndex(p=>p.id===challenged.id));s.statsByPlayer[challenger.id].liarCalls+=1;s.visits.push({id:id("menteur-call"),kind:"call",playerId:challenger.id,leg:s.legIndex+1,turn:s.turnIndex+1,bid:s.bid,condition:s.condition,events:[`${challenger.name} crie MENTEUR ! ${challenged.name} doit prouver ${s.bid}`]});s.turnIndex+=1;return s;}
function visitSuccess(s:MenteurState,ds:GameDart[]){if(scoreVisit(ds)<s.bid)return false;if(s.condition==="double")return ds.some(d=>d?.bed==="D"||d?.bed==="IB");if(s.condition==="triple")return ds.some(d=>d?.bed==="T");if(s.condition==="bull")return ds.some(d=>d?.bed==="OB"||d?.bed==="IB");if(s.condition==="distinct")return new Set(ds.filter(d=>d?.bed!=="MISS").map(d=>d?.bed==="OB"||d?.bed==="IB"?25:Number(d?.number||0)).filter(Boolean)).size>=3;return true;}
export function playMenteurVisit(input:MenteurState,dartsRaw:GameDart[]):MenteurState{const s=cloneMenteurState(input);if(s.phase!=="challenge"||!s.challengedId||!s.challengerId)return s;const ds=(dartsRaw||[]).slice(0,3),challenged=s.players.find(p=>p.id===s.challengedId),challenger=s.players.find(p=>p.id===s.challengerId);if(!challenged||!challenger)return s;const ok=visitSuccess(s,ds),loser=ok?challenger:challenged,st=s.statsByPlayer[challenged.id];st.visits+=1;st.darts+=ds.length;st.bestVisit=Math.max(st.bestVisit,scoreVisit(ds));if(ok)st.contractsProven+=1;else s.statsByPlayer[challenger.id].liesCaught+=1;s.lives[loser.id]=Math.max(0,Number(s.lives[loser.id]||0)-1);s.statsByPlayer[loser.id].livesLost+=1;const events=[ok?`${challenged.name} PROUVE son annonce : ${scoreVisit(ds)} pts`:`${challenged.name} est pris en flagrant mensonge : ${scoreVisit(ds)} pts`,`${loser.name} perd 1 vie`];if(s.lives[loser.id]<=0){s.eliminated[loser.id]=true;events.push(`${loser.name} est éliminé`);}s.visits.push({id:id("menteur-resolution"),kind:"resolution",playerId:challenged.id,leg:s.legIndex+1,turn:s.turnIndex+1,bid:s.bid,condition:s.condition,darts:ds,score:scoreVisit(ds),success:ok,events});s.turnIndex+=1;const alive=aliveIds(s);if(alive.length===1)return winLeg(s,alive[0]);const loserIdx=Math.max(0,s.players.findIndex(p=>p.id===loser.id));const opener=s.eliminated[loser.id]?nextAliveIndex(s,loserIdx):loserIdx;return resetAuction(s,opener);}
function skill(level:MenteurBotLevel){return level==="hard"?.78:level==="easy"?.35:.58;}function randomDart():GameDart{const n=1+Math.floor(Math.random()*20),r=Math.random();return{bed:r<.72?"S":r<.91?"D":"T",number:n} as GameDart;}
export function pickMenteurBotAction(s:MenteurState,level:MenteurBotLevel="normal"):{type:"raise";amount:number}|{type:"liar"}{const step=s.config.rules.raiseStep;if(!s.lastBidderId)return{type:"raise",amount:Math.max(30,step*(level==="hard"?8:level==="easy"?5:6))};const base=level==="hard"?116:level==="easy"?70:92,pen=s.condition==="none"?0:s.condition==="distinct"?18:10,threshold=base-pen+(Math.random()-.5)*26;if(s.bid>=threshold||s.bid>=175)return{type:"liar"};const m=Math.random()<.18?3:Math.random()<.5?2:1;return{type:"raise",amount:step*m};}
export function pickMenteurBotDarts(s:MenteurState,level:MenteurBotLevel="normal"):GameDart[]{const ok=Math.random()<skill(level);if(!ok)return[randomDart(),{bed:"MISS"},randomDart()];if(s.condition==="double")return[{bed:"D",number:20},{bed:"T",number:20},{bed:"T",number:20}];if(s.condition==="triple")return[{bed:"T",number:20},{bed:"T",number:20},{bed:"T",number:20}];if(s.condition==="bull")return[{bed:"IB"},{bed:"T",number:20},{bed:"T",number:20}];if(s.condition==="distinct")return[{bed:"T",number:20},{bed:"T",number:19},{bed:"T",number:18}];return[{bed:"T",number:20},{bed:"T",number:20},{bed:"T",number:20}];}
