// @ts-nocheck
import type { GameDart, Player } from "../types-game";
export type SteeplechaseBotLevel='easy'|'normal'|'hard';
export type SteeplechaseConfigPayload={mode:'steeplechase';selectedIds:string[];players:number;playersList?:any[];botIds?:string[];botsEnabled?:boolean;botLevel:SteeplechaseBotLevel;randomOrder?:boolean;scoreInputMethod?:'keypad'|'dartboard';seriesWins:1|2|3;rules:{direction:'clockwise'|'counter';innerSingleOnly:boolean;fencesEnabled:boolean;fences:number[];finishBull:'any'|'double';}};
export type SteepleStats={darts:number;visits:number;hits:number;misses:number;fencesCleared:number;bullFinishes:number;steps:number;legsWon:number;};
export type SteepleVisit={id:string;playerId:string;leg:number;turn:number;darts:GameDart[];startStep:number;endStep:number;events:string[];};
export type SteeplechaseState={sport:'darts';mode:'steeplechase';config:SteeplechaseConfigPayload;players:Player[];stepByPlayer:Record<string,number>;legWins:Record<string,number>;statsByPlayer:Record<string,SteepleStats>;activePlayerIndex:number;legIndex:number;turnIndex:number;phase:'playing'|'finished';winnerId:string|null;lastLegWinnerId:string|null;visits:SteepleVisit[];startedAt:number;finishedAt?:number;};
const clone=<T,>(v:T):T=>JSON.parse(JSON.stringify(v)); const uid=(p='steeple')=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`; const blank=():SteepleStats=>({darts:0,visits:0,hits:0,misses:0,fencesCleared:0,bullFinishes:0,steps:0,legsWon:0});
const CW=[20,1,18,4,13,6,10,15,2,17,3,19,7,16,8,11,14,9,12,5];
export function steepleSequence(direction:'clockwise'|'counter'='clockwise'){ return direction==='clockwise'?[...CW]:[20,...CW.slice(1).reverse()]; }
export function normalizeSteeplechaseConfig(raw:any):SteeplechaseConfigPayload{ const r=raw?.rules||{}; const ids=Array.isArray(raw?.selectedIds)?raw.selectedIds.map(String):[]; return {mode:'steeplechase',selectedIds:ids,players:Math.max(1,Number(raw?.players||ids.length||1)),playersList:Array.isArray(raw?.playersList)?raw.playersList:[],botIds:Array.isArray(raw?.botIds)?raw.botIds.map(String):[],botsEnabled:Boolean(raw?.botsEnabled),botLevel:raw?.botLevel==='easy'||raw?.botLevel==='hard'?raw.botLevel:'normal',randomOrder:raw?.randomOrder!==false,scoreInputMethod:raw?.scoreInputMethod==='dartboard'?'dartboard':'keypad',seriesWins:raw?.seriesWins===2||raw?.seriesWins===3?raw.seriesWins:1,rules:{direction:r?.direction==='counter'?'counter':'clockwise',innerSingleOnly:r?.innerSingleOnly!==false,fencesEnabled:r?.fencesEnabled!==false,fences:Array.isArray(r?.fences)&&r.fences.length?r.fences.map(Number):[13,17,8,5],finishBull:r?.finishBull==='double'?'double':'any'}}; }
export function createSteeplechaseState(players:Player[],raw:any):SteeplechaseState{ const config=normalizeSteeplechaseConfig(raw); const ps=(players||[]).map((p,i)=>({id:String(p?.id||`p${i+1}`),name:String(p?.name||`Joueur ${i+1}`)})); return {sport:'darts',mode:'steeplechase',config,players:ps,stepByPlayer:Object.fromEntries(ps.map(p=>[p.id,0])),legWins:Object.fromEntries(ps.map(p=>[p.id,0])),statsByPlayer:Object.fromEntries(ps.map(p=>[p.id,blank()])),activePlayerIndex:0,legIndex:0,turnIndex:0,phase:'playing',winnerId:null,lastLegWinnerId:null,visits:[],startedAt:Date.now()}; }
export const cloneSteeplechaseState=(s:SteeplechaseState):SteeplechaseState=>clone(s);
export function currentSteepleTarget(s:SteeplechaseState,pid:string){ const seq=steepleSequence(s.config.rules.direction); const step=Number(s.stepByPlayer[pid]||0); if(step>=seq.length) return {kind:'bull', label:s.config.rules.finishBull==='double'?'DBULL':'BULL'}; const n=seq[step]; const fence=s.config.rules.fencesEnabled && s.config.rules.fences.includes(n); return {kind:'number', number:n, fence, label:fence?`T${n}`:s.config.rules.innerSingleOnly?`s${n}`:`S${n}`}; }
function hitsTarget(d:GameDart,target:any,innerSingleOnly:boolean,finishBull:'any'|'double'){ if(target.kind==='bull') return finishBull==='double' ? d?.bed==='IB' : d?.bed==='OB'||d?.bed==='IB'; if(!d||!(d.bed==='S'||d.bed==='D'||d.bed==='T')||Number(d.number||0)!==target.number) return false; if(target.fence) return d.bed==='T'; if(innerSingleOnly) return d.bed==='S'; return d.bed==='S'; }
function awardLeg(s:SteeplechaseState,winnerId:string){ s.lastLegWinnerId=winnerId; s.legWins[winnerId]=Number(s.legWins[winnerId]||0)+1; s.statsByPlayer[winnerId].legsWon++; if(s.legWins[winnerId]>=s.config.seriesWins){ s.phase='finished'; s.winnerId=winnerId; s.finishedAt=Date.now(); return; } s.legIndex++; s.turnIndex=0; s.activePlayerIndex=0; s.stepByPlayer=Object.fromEntries(s.players.map(p=>[p.id,0])); }
export function playSteeplechaseVisit(input:SteeplechaseState,dartsRaw:GameDart[]):SteeplechaseState{ const s=cloneSteeplechaseState(input); if(s.phase!=='playing'||!s.players.length) return s; const p=s.players[s.activePlayerIndex]; if(!p) return s; const darts=(dartsRaw||[]).slice(0,3); const st=s.statsByPlayer[p.id]||(s.statsByPlayer[p.id]=blank()); st.visits++; const start=Number(s.stepByPlayer[p.id]||0); const events:string[]=[]; for(const d of darts){ st.darts++; const target=currentSteepleTarget(s,p.id); if(hitsTarget(d,target,s.config.rules.innerSingleOnly,s.config.rules.finishBull)){ s.stepByPlayer[p.id]=Number(s.stepByPlayer[p.id]||0)+1; st.hits++; st.steps++; if(target.fence) st.fencesCleared++; if(target.kind==='bull') st.bullFinishes++; events.push(`${p.name} franchit ${target.label}`); if(target.kind==='bull'){ s.visits.push({id:uid('steeplev'),playerId:p.id,leg:s.legIndex+1,turn:s.turnIndex+1,darts,startStep:start,endStep:Number(s.stepByPlayer[p.id]||0),events}); s.turnIndex++; awardLeg(s,p.id); return s; } } else st.misses++; }
  s.visits.push({id:uid('steeplev'),playerId:p.id,leg:s.legIndex+1,turn:s.turnIndex+1,darts,startStep:start,endStep:Number(s.stepByPlayer[p.id]||0),events}); s.turnIndex++; s.activePlayerIndex=(s.activePlayerIndex+1)%s.players.length; return s; }
function chance(level:SteeplechaseBotLevel){return level==='hard'?.82:level==='easy'?.44:.64;}
export function pickSteeplechaseBotDarts(input:SteeplechaseState, level:SteeplechaseBotLevel='normal'):GameDart[]{ const s=cloneSteeplechaseState(input); const p=s.players[s.activePlayerIndex]; if(!p) return []; const out:GameDart[]=[]; for(let i=0;i<3;i++){ const target=currentSteepleTarget(s,p.id); const good=Math.random()<chance(level); if(!good){ out.push(Math.random()<.15?{bed:'MISS'}:{bed:'S',number:1+Math.floor(Math.random()*20)}); continue; } if(target.kind==='bull'){ out.push({bed:s.config.rules.finishBull==='double'||Math.random()<.45?'IB':'OB'}); s.stepByPlayer[p.id]=Number(s.stepByPlayer[p.id]||0)+1; break; } out.push({bed:target.fence?'T':'S',number:target.number}); s.stepByPlayer[p.id]=Number(s.stepByPlayer[p.id]||0)+1; } while(out.length<3) out.push({bed:'MISS'}); return out.slice(0,3); }
