// @ts-nocheck
import React from "react";
import BackDot from "../components/BackDot";
import InfoDot from "../components/InfoDot";
import PageHeader from "../components/PageHeader";
import tickerCallThree from "../assets/tickers/ticker_call_three.webp";
import { useFullscreenPlay } from "../hooks/useFullscreenPlay";
import { History } from "../lib/history";
import type { Dart as UIDart } from "../lib/types";
import { callThreeLabel, cloneCallThreeState, createCallThreeState, normalizeCallThreeConfig, pickCallThreeBotDarts, playCallThreeVisit, type CallThreeState } from "../lib/gameEngines/callThreeEngine";
import { ModeEndPanel, NewModeInput, PlayerCard, actionStyle, isBotProfile, lastEvents, panelStyle, playerName, resolveModeProfiles, SOFT, uiToGameDart } from "./newModes/newModePlayShared";
const ACCENT="#ffb13b", ACCENT2="#ffd56d", RED="#ff6d6d";
function Rules({config}:any){return <div style={{display:"grid",gap:10,fontSize:12.5,lineHeight:1.5}}><div><b style={{color:ACCENT}}>BUT</b><br/>Réussir un maximum d’appels sur <b>{config.rules.rounds}</b> rounds.</div><div><b style={{color:ACCENT2}}>APPEL</b><br/>Le <b>{config.rules.callerMode==='next'?'joueur suivant':'caller aléatoire'}</b> annonce 3 cibles. Chaque fléchette vaut S=1, D=2, T=3.</div><div><b style={{color:ACCENT}}>ORDRE</b><br/>{config.rules.orderedTargets?"Les 3 cibles doivent être frappées dans l’ordre exact.":"Les 3 cibles peuvent être validées dans n’importe quel ordre."}</div><div><b style={{color:RED}}>BONUS</b><br/>Réaliser les 3 appels sur la même volée donne un bonus de +2.</div></div>}
export default function CallThreePlay(props:any){
  useFullscreenPlay({enabled:true,lockBodyScroll:false});
  const go=props?.go??props?.setTab, store=props?.store, onFinish=props?.onFinish, resumeRecord=props?.params?.rec||props?.params?.record||props?.params?.match||null;
  const config=React.useMemo(()=>normalizeCallThreeConfig(props?.params?.config||resumeRecord?.resume?.config||resumeRecord?.payload?.config||{}),[]);
  const profiles=React.useMemo(()=>resolveModeProfiles(config,store),[config,store]); const players=React.useMemo(()=>profiles.map((p:any,i:number)=>({id:String(p.id||`p${i+1}`),name:playerName(p,i)})),[profiles]);
  const botIds=React.useMemo(()=>new Set((config.botIds||[]).map(String)),[config.botIds]);
  const restored=resumeRecord?.resume?.state||resumeRecord?.payload?.stateSnapshot||resumeRecord?.payload?.state||null;
  const [state,setState]=React.useState<CallThreeState>(()=>restored?.mode==="call_three"?cloneCallThreeState(restored):createCallThreeState(players,config));
  const [currentThrow,setCurrentThrow]=React.useState<UIDart[]>([]), [multiplier,setMultiplier]=React.useState<1|2|3>(1), [undo,setUndo]=React.useState<CallThreeState[]>([]), [notice,setNotice]=React.useState("");
  const botBusy=React.useRef(false), finishedRef=React.useRef(false), matchIdRef=React.useRef(String(resumeRecord?.id||resumeRecord?.matchId||`call-three-${Date.now()}-${Math.random().toString(36).slice(2,8)}`));
  const profileById=React.useMemo(()=>new Map(profiles.map((p:any)=>[String(p.id),p])),[profiles]);
  const activePlayer=state.players[state.activePlayerIndex], activeProfile=activePlayer?profileById.get(String(activePlayer.id))||activePlayer:null, activeIsBot=!!activeProfile&&isBotProfile(activeProfile,botIds);
  const buildRecord=React.useCallback((s:CallThreeState,status:"in_progress"|"finished")=>{ const rows=profiles.map((p:any)=>({id:String(p.id),name:playerName(p),avatarDataUrl:p.avatarDataUrl??null})); return {id:matchIdRef.current,matchId:matchIdRef.current,resumeId:matchIdRef.current,kind:"call_three",mode:"call_three",sport:"darts",status,createdAt:s.startedAt,updatedAt:Date.now(),finishedAt:status==="finished"?(s.finishedAt||Date.now()):undefined,winnerId:s.winnerId,players:rows,game:{mode:"call_three",rounds:s.config.rules.rounds,seriesWins:s.config.seriesWins},summary:{mode:"call_three",finished:status==="finished",winnerId:s.winnerId,legWins:s.legWins,round:s.roundIndex+1,config:s.config,perPlayer:Object.fromEntries(Object.entries(s.statsByPlayer).map(([id,st]:any)=>[id,{...st,score:Number(s.scores[id]||0),wins:Number(s.legWins[id]||0)}]))},resume:{mode:"call_three",config:s.config,state:cloneCallThreeState(s),updatedAt:Date.now()},payload:{kind:"call_three",mode:"call_three",sport:"darts",config:s.config,stateSnapshot:cloneCallThreeState(s),visits:s.visits,visitHistory:s.visits,stats:{mode:"call_three",players:s.statsByPlayer,legWins:s.legWins}}}; },[profiles]);
  const persist=React.useCallback((s:CallThreeState)=>{ if(s.phase==="finished"){ if(finishedRef.current) return; finishedRef.current=true; const rec=buildRecord(s,"finished"); if(typeof onFinish==="function") onFinish(rec,{navigate:false}); else void History.upsert(rec);} else void History.upsert(buildRecord(s,"in_progress")).catch(()=>{}); },[buildRecord,onFinish]);
  const commit=(next:CallThreeState,previous=state)=>{ setUndo(u=>[...u.slice(-39),cloneCallThreeState(previous)]); setState(next); setCurrentThrow([]); setMultiplier(1); const ev=lastEvents(next.visits); setNotice(ev.length?ev.join(" · "):""); persist(next); };
  const validate=()=>{ if(!currentThrow.length||state.phase==="finished"||activeIsBot) return; commit(playCallThreeVisit(state,currentThrow.map(uiToGameDart))); };
  const doUndo=()=>setUndo(u=>{ if(!u.length) return u; const prev=u[u.length-1]; setState(cloneCallThreeState(prev)); setCurrentThrow([]); setMultiplier(1); setNotice("Dernière volée annulée"); finishedRef.current=false; persist(prev); return u.slice(0,-1); });
  React.useEffect(()=>{ if(!activeIsBot||state.phase==="finished"||botBusy.current) return; botBusy.current=true; const t=window.setTimeout(()=>{ try{ commit(playCallThreeVisit(state,pickCallThreeBotDarts(state,config.botLevel))); } finally{ botBusy.current=false; } },650); return ()=>window.clearTimeout(t); },[state,activeIsBot,activePlayer?.id]);
  function replay(){ matchIdRef.current=`call-three-${Date.now()}-${Math.random().toString(36).slice(2,8)}`; finishedRef.current=false; setUndo([]); setNotice(""); setCurrentThrow([]); setState(createCallThreeState(players,config)); }
  const legTarget=config.seriesWins*2-1; const caller=state.players.find(p=>p.id===state.currentCallerId);
  return <div style={{minHeight:"calc(var(--vh, 1vh) * 100)",paddingBottom:18,background:"radial-gradient(circle at 50% 0%,rgba(255,177,59,.12),transparent 35%)"}}>
    <PageHeader tickerSrc={tickerCallThree} tickerAlt="CALL THREE" left={<BackDot onClick={()=>go?.("call_three_config")} color={ACCENT} glow={`${ACCENT}88`}/>} right={<InfoDot title="Règles CALL THREE" color={ACCENT} glow={`${ACCENT}77`} content={<Rules config={config}/>}/>} />
    <div style={{padding:"7px 8px 18px",maxWidth:980,margin:"0 auto",display:"grid",gap:8}}>
      <div style={{...panelStyle(ACCENT+"50"),padding:9,display:"grid",gridTemplateColumns:"1fr auto",gap:9,alignItems:"center"}}><div><div style={{color:ACCENT,fontSize:10,fontWeight:1100,letterSpacing:1}}>MANCHE {state.legIndex+1} · ROUND {state.roundIndex+1}/{config.rules.rounds} · BO{legTarget}</div><div style={{marginTop:3,color:"#fff",fontSize:14,fontWeight:1000}}>{state.phase==="finished"?"Match terminé":`${activePlayer?.name||"—"} doit répondre à l'appel`}</div></div><button type="button" onClick={doUndo} disabled={!undo.length} style={actionStyle(ACCENT,!undo.length)}>↶ UNDO</button></div>
      {notice?<div style={{borderRadius:12,padding:"7px 10px",background:"rgba(255,177,59,.10)",border:"1px solid rgba(255,177,59,.24)",color:"#ffe2b1",fontSize:10.5,fontWeight:900}}>{notice}</div>:null}
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:7}}>{state.players.map((p:any,i:number)=>{ const prof=profileById.get(String(p.id))||p; const score=Number(state.scores[p.id]||0); return <PlayerCard key={p.id} profile={prof} active={state.phase!=="finished"&&state.activePlayerIndex===i} accent={ACCENT} value={score} subValue={`${state.statsByPlayer[p.id]?.hits||0} hits · ${state.statsByPlayer[p.id]?.perfectRounds||0} full call`} badge={`PTS`} wins={state.legWins[p.id]||0}/> })}</div>
      {state.phase!=="finished"?<>
        <div style={{...panelStyle("rgba(255,255,255,.10)"),padding:10}}>
          <div style={{display:"flex",justifyContent:"space-between",gap:8,alignItems:"center",flexWrap:"wrap"}}><div><div style={{color:ACCENT,fontSize:10,fontWeight:1100}}>APPEL EN COURS</div><div style={{marginTop:4,color:SOFT,fontSize:10.5}}>Annonce de <b style={{color:"#fff"}}>{caller?.name||"—"}</b> · {config.rules.orderedTargets?"ordre strict":"ordre libre"}</div></div><div style={{fontSize:28}}>📣</div></div>
          <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,marginTop:10}}>{state.currentCalls.map((c:any,idx:number)=><div key={idx} style={{borderRadius:14,padding:"14px 10px",textAlign:"center",background:"rgba(255,255,255,.05)",border:`1px solid ${ACCENT}55`,boxShadow:`0 0 18px ${ACCENT}14`}}><div style={{color:ACCENT,fontSize:10,fontWeight:1100}}>CIBLE {idx+1}</div><div style={{marginTop:4,color:"#fff",fontSize:28,fontWeight:1100,lineHeight:1}}>{callThreeLabel(c)}</div></div>)}</div>
          <div style={{marginTop:8,color:SOFT,fontSize:9.5}}>Simple = 1 point · Double = 2 · Triple = 3 · Réussir les 3 appels sur la même volée = bonus +2.</div>
        </div>
        {!activeIsBot?<NewModeInput currentThrow={currentThrow} setCurrentThrow={setCurrentThrow} multiplier={multiplier} setMultiplier={setMultiplier} onValidate={validate} preferredMethod={config.scoreInputMethod} validateLabel="VALIDER LA VOLÉE" accent={ACCENT}/>:<div style={{...panelStyle(ACCENT+"33"),textAlign:"center",color:SOFT,fontSize:11,padding:14}}><b style={{color:ACCENT}}>{activePlayer?.name}</b> répond à l'appel…</div>}
      </>:<ModeEndPanel title="CALL THREE" winner={state.winnerId} profiles={profiles} legWins={state.legWins} accent={ACCENT} onReplay={replay} onConfig={()=>go?.("call_three_config")} onGames={()=>go?.("games",{gamesView:"all"})} extra={<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(120px,1fr))",gap:6}}>{profiles.map((p:any)=>{const st=state.statsByPlayer[p.id]||{}; return <div key={p.id} style={{padding:8,borderRadius:12,background:"rgba(255,255,255,.04)",border:"1px solid rgba(255,255,255,.08)",fontSize:9.5,color:SOFT}}><b style={{color:"#fff"}}>{playerName(p)}</b><br/>{st.points||0} pts · {st.perfectRounds||0} full call</div>})}</div>}/>} 
    </div>
  </div>;
}
