import * as React from "react";
import { useFriendRequests } from "../hooks/useFriendRequests";
const shell: React.CSSProperties = { minHeight: "100dvh", padding: "16px 14px 96px", color: "#fff", background: "linear-gradient(180deg,#101016,#060609)" };
const card: React.CSSProperties = { borderRadius: 18, padding: 12, background: "rgba(255,255,255,.06)", border: "1px solid rgba(255,255,255,.12)", display: "grid", gap: 8 };
const btn: React.CSSProperties = { border: 0, borderRadius: 12, padding: "9px 11px", fontWeight: 900, background: "linear-gradient(180deg,#ffd76b,#df9f37)", color: "#1b1204" };
const ghost: React.CSSProperties = { borderRadius: 12, padding: "9px 11px", fontWeight: 900, background: "rgba(255,255,255,.06)", color: "#fff", border: "1px solid rgba(255,255,255,.13)" };
function userName(u: any) { return u?.displayName || u?.nickname || "Joueur"; }
export default function FriendRequestsPage({ go }: { go?: (tab: string) => void }) {
  const { requests, incoming, outgoing, loading, error, refresh, respond } = useFriendRequests();
  const history = requests.filter((r) => r.status !== "pending").slice(0, 30);
  return <div style={shell}><div style={{ maxWidth: 760, margin: "0 auto", display: "grid", gap: 14 }}><header style={{ display: "flex", alignItems: "center", gap: 10 }}><button style={ghost} onClick={() => go?.("friends")}>← Online</button><div style={{ flex: 1 }}><h1 style={{ margin: 0 }}>Demandes d’amis</h1><div style={{ fontSize: 12, opacity: .7 }}>{loading ? "Synchronisation…" : "Entrantes, sortantes et historique"}</div></div><button style={ghost} onClick={refresh}>Rafraîchir</button></header>{error ? <div style={{ color: "#ffb3b3" }}>{error}</div> : null}<section style={card}><b>Reçues</b>{incoming.length === 0 ? <span style={{ opacity: .7 }}>Aucune demande reçue.</span> : incoming.map((r) => <div key={r.id} style={{ display: "flex", gap: 10, alignItems: "center" }}><div style={{ flex: 1 }}><b>{userName(r.fromUser)}</b><div style={{ fontSize: 12, opacity: .72 }}>{r.message || "Souhaite t’ajouter en ami."}</div></div><button style={btn} onClick={() => respond(r.id, "accepted")}>Accepter</button><button style={ghost} onClick={() => respond(r.id, "rejected")}>Refuser</button></div>)}</section><section style={card}><b>Envoyées</b>{outgoing.length === 0 ? <span style={{ opacity: .7 }}>Aucune demande en attente.</span> : outgoing.map((r) => <div key={r.id}><b>{userName(r.toUser)}</b><div style={{ fontSize: 12, opacity: .72 }}>En attente depuis {r.createdAt ? new Date(r.createdAt).toLocaleString() : "—"}</div></div>)}</section><section style={card}><b>Historique</b>{history.length === 0 ? <span style={{ opacity: .7 }}>Aucun historique.</span> : history.map((r) => <div key={r.id} style={{ display: "flex", justifyContent: "space-between", gap: 10 }}><span>{r.direction === "incoming" ? userName(r.fromUser) : userName(r.toUser)}</span><b style={{ color: r.status === "accepted" ? "#55df88" : "#ffb3b3" }}>{r.status}</b></div>)}</section></div></div>;
}
