// @ts-nocheck
import React from "react";
import BackDot from "../components/BackDot";
import InfoDot from "../components/InfoDot";
import PageHeader from "../components/PageHeader";
import tickerLooper from "../assets/tickers/ticker_looper.png";
import { useFullscreenPlay } from "../hooks/useFullscreenPlay";
import { History } from "../lib/history";
import type { Dart as UIDart } from "../lib/types";
import { assignLooperTarget, cloneLooperState, createLooperState, normalizeLooperConfig, pickLooperBotDarts, playLooperVisit, type LooperState } from "../lib/gameEngines/looperEngine";
import { ModeEndPanel, NewModeInput, PlayerCard, actionStyle, isBotProfile, lastEvents, panelStyle, playerName, resolveModeProfiles, SOFT, uiToGameDart } from "./newModes/newModePlayShared";
const ACCENT="#8ff7ff", ACCENT2="#56d6ff", DANGER="#ff6a77";
function Rules({config}:any){return <div style={{display:"grid",gap:10,fontSize:12.5,lineHeight:1.5}}><div><b style={{color:ACCENT}}>BUT</b><br/>Rester en vie. Il faut toucher le <b>secteur exact</b> demandé.</div><div><b style={{color:ACCENT2}}>BOUCLE</b><br/>Quand tu réussis la cible, la <b>dernière zone numérotée</b> de ta volée fixe la prochaine cible globale.</div><div><b style={{color:DANGER}}>ÉCHEC</b><br/>Si tu ne touches pas la cible sur la volée, tu perds 1 vie{config.rules.setterShield?" sauf si tu as un bouclier.":"."}</div><div><b style={{color:ACCENT2}}>VARIANTES</b><br/>{config.rules.numberLoopsEnabled?"Les mêmes numéros peuvent se répéter.":"Une même cible ne peut pas se reboucler immédiatement."}</div></div>}
export default function LooperPlay(props:any){
  useFullscreenPlay({enabled:true,lockBodyScroll:false});
  const go=props?.go??props?.setTab, store=props?.store, onFinish=props?.onFinish, resumeRecord=props?.params?.rec||props?.params?.record||props?.params?.match||null;
  const config=React.useMemo(()=>normalizeLooperConfig(props?.params?.config||resumeRecord?.resume?.config||resumeRecord?.payload?.config||{}),[]);
  const profiles=React.useMemo(()=>resolveModeProfiles(config,store),[config,store]); const players=React.useMemo(()=>profiles.map((p:any,i:number)=>({id:String(p.id||`p${i+1}`),name:playerName(p,i)})),[profiles]);
  const botIds=React.useMemo(()=>new Set((config.botIds||[]).map(String)),[config.botIds]);
  const restored=resumeRecord?.resume?.state||resumeRecord?.payload?.stateSnapshot||resumeRecord?.payload?.state||null;
  const [state,setState]=React.useState<LooperState>(()=>restored?.mode==="looper"?cloneLooperState(restored):createLooperState(players,config));
  const [currentThrow,setCurrentThrow]=React.useState<UIDart[]>([]), [multiplier,setMultiplier]=React.useState<1|2|3>(1), [undo,setUndo]=React.useState<LooperState[]>([]), [notice,setNotice]=React.useState("");
  const botBusy=React.useRef(false), finishedRef=React.useRef(false), matchIdRef=React.useRef(String(resumeRecord?.id||resumeRecord?.matchId||`looper-${Date.now()}-${Math.random().toString(36).slice(2,8)}`));
  const profileById=React.useMemo(()=>new Map(profiles.map((p:any)=>[String(p.id),p])),[profiles]);
  const activePlayer=state.players[state.activePlayerIndex], activeProfile=activePlayer?profileById.get(String(activePlayer.id))||activePlayer:null, activeIsBot=!!activeProfile&&isBotProfile(activeProfile,botIds);
  const buildRecord=React.useCallback((s:LooperState,status:"in_progress"|"finished")=>{ const rows=profiles.map((p:any)=>({id:String(p.id),name:playerName(p),avatarDataUrl:p.avatarDataUrl??null})); return {id:matchIdRef.current,matchId:matchIdRef.current,resumeId:matchIdRef.current,kind:"looper",mode:"looper",sport:"darts",status,createdAt:s.startedAt,updatedAt:Date.now(),finishedAt:status==="finished"?(s.finishedAt||Date.now()):undefined,winnerId:s.winnerId,players:rows,game:{mode:"looper",lives:s.config.rules.lives,seriesWins:s.config.seriesWins},summary:{mode:"looper",finished:status==="finished",winnerId:s.winnerId,legWins:s.legWins,currentTarget:s.currentTarget,config:s.config,perPlayer:Object.fromEntries(Object.entries(s.statsByPlayer).map(([id,st]:any)=>[id,{...st,lives:Number(s.lives[id]||0),shields:Number(s.shields[id]||0),wins:Number(s.legWins[id]||0)}]))},resume:{mode:"looper",config:s.config,state:cloneLooperState(s),updatedAt:Date.now()},payload:{kind:"looper",mode:"looper",sport:"darts",config:s.config,stateSnapshot:cloneLooperState(s),visits:s.visits,visitHistory:s.visits,stats:{mode:"looper",players:s.statsByPlayer,legWins:s.legWins}}}; },[profiles]);
  const persist=React.useCallback((s:LooperState)=>{ if(s.phase==="finished"){ if(finishedRef.current) return; finishedRef.current=true; const rec=buildRecord(s,"finished"); if(typeof onFinish==="function") onFinish(rec,{navigate:false}); else void History.upsert(rec);} else void History.upsert(buildRecord(s,"in_progress")).catch(()=>{}); },[buildRecord,onFinish]);
  const commit=(next:LooperState,previous=state)=>{ setUndo(u=>[...u.slice(-39),cloneLooperState(previous)]); setState(next); setCurrentThrow([]); setMultiplier(1); const ev=lastEvents(next.visits); setNotice(ev.length?ev.join(" · "):""); persist(next); };
  const validate=()=>{ if(!currentThrow.length||state.phase==="finished"||activeIsBot) return; if(state.phase==="assignment"){ commit(assignLooperTarget(state,uiToGameDart(currentThrow[0]))); return; } commit(playLooperVisit(state,currentThrow.map(uiToGameDart))); };
  const doUndo=()=>setUndo(u=>{ if(!u.length) return u; const prev=u[u.length-1]; setState(cloneLooperState(prev)); setCurrentThrow([]); setMultiplier(1); setNotice("Dernière action annulée"); finishedRef.current=false; persist(prev); return u.slice(0,-1); });
  React.useEffect(()=>{ if(!activeIsBot||state.phase==="finished"||botBusy.current) return; botBusy.current=true; const t=window.setTimeout(()=>{ try{ if(state.phase==="assignment") commit(assignLooperTarget(state,pickLooperBotDarts(state,config.botLevel)[0])); else commit(playLooperVisit(state,pickLooperBotDarts(state,config.botLevel))); } finally{ botBusy.current=false; } },650); return ()=>window.clearTimeout(t); },[state,activeIsBot,activePlayer?.id]);
  function replay(){ matchIdRef.current=`looper-${Date.now()}-${Math.random().toString(36).slice(2,8)}`; finishedRef.current=false; setUndo([]); setNotice(""); setCurrentThrow([]); setState(createLooperState(players,config)); }
  const legTarget=config.seriesWins*2-1;
  return <div style={{minHeight:"calc(var(--vh, 1vh) * 100)",paddingBottom:18,background:"radial-gradient(circle at 50% 0%,rgba(143,247,255,.10),transparent 35%)"}}>
    <PageHeader tickerSrc={tickerLooper} tickerAlt="LOOPER" left={<BackDot onClick={()=>go?.("looper_config")} color={ACCENT} glow={`${ACCENT}88`}/>} right={<InfoDot title="Règles LOOPER" color={ACCENT} glow={`${ACCENT}77`} content={<Rules config={config}/>}/>} />
    <div style={{padding:"7px 8px 18px",maxWidth:980,margin:"0 auto",display:"grid",gap:8}}>
      <div style={{...panelStyle(ACCENT+"50"),padding:9,display:"grid",gridTemplateColumns:"1fr auto",gap:9,alignItems:"center"}}><div><div style={{color:ACCENT,fontSize:10,fontWeight:1100,letterSpacing:1}}>MANCHE {state.legIndex+1} · BO{legTarget}</div><div style={{marginTop:3,color:"#fff",fontSize:14,fontWeight:1000}}>{state.phase==="assignment"?`${activePlayer?.name||"—"} fixe la cible de départ`:state.phase==="finished"?"Match terminé":`${activePlayer?.name||"—"} vise le ${state.currentTarget}`}</div></div><button type="button" onClick={doUndo} disabled={!undo.length} style={actionStyle(ACCENT,!undo.length)}>↶ UNDO</button></div>
      {notice?<div style={{borderRadius:12,padding:"7px 10px",background:"rgba(143,247,255,.10)",border:"1px solid rgba(143,247,255,.24)",color:"#bffbff",fontSize:10.5,fontWeight:900}}>{notice}</div>:null}
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:7}}>{state.players.map((p:any,i:number)=>{ const prof=profileById.get(String(p.id))||p; const lives=Number(state.lives[p.id]||0); const shields=Number(state.shields[p.id]||0); return <PlayerCard key={p.id} profile={prof} active={state.phase!=="finished"&&state.activePlayerIndex===i} accent={lives>1?ACCENT:DANGER} value={lives} subValue={`Boucliers ${shields} · cible ${state.currentTarget}`} badge={lives>0?`♥ ${lives}`:"OUT"} wins={state.legWins[p.id]||0} muted={lives<=0}/> })}</div>
      {state.phase!=="finished"?<>
        <div style={{...panelStyle("rgba(255,255,255,.10)"),padding:10}}><div style={{display:"grid",gridTemplateColumns:"1fr auto",gap:12,alignItems:"center"}}><div><div style={{color:ACCENT,fontSize:10,fontWeight:1100}}>{state.phase==="assignment"?"DÉPART DE LA BOUCLE":"CIBLE GLOBALE"}</div><div style={{marginTop:3,color:"#fff",fontSize:34,fontWeight:1100,lineHeight:1}}>{state.phase==="assignment"?"?":state.currentTarget}</div><div style={{marginTop:5,color:SOFT,fontSize:9.5}}>{state.phase==="assignment"?"1 fléchette : le secteur touché devient la première cible de la manche.":"Toucher au moins une fois le secteur exact. La dernière zone numérotée fixe la prochaine cible."}</div></div><div style={{width:88,height:88,borderRadius:999,border:`3px solid ${ACCENT}`,display:"grid",placeItems:"center",background:"radial-gradient(circle,rgba(255,255,255,.08),rgba(0,0,0,.6))",fontSize:26,color:ACCENT}}>∞</div></div></div>
        {!activeIsBot?<NewModeInput currentThrow={currentThrow} setCurrentThrow={setCurrentThrow} multiplier={multiplier} setMultiplier={setMultiplier} onValidate={validate} preferredMethod={config.scoreInputMethod} validateLabel={state.phase==="assignment"?"FIXER LA CIBLE":"VALIDER LA VOLÉE"} accent={ACCENT}/>:<div style={{...panelStyle(ACCENT+"33"),textAlign:"center",color:SOFT,fontSize:11,padding:14}}><b style={{color:ACCENT}}>{activePlayer?.name}</b> prépare sa boucle…</div>}
      </>:<ModeEndPanel title="LOOPER" winner={state.winnerId} profiles={profiles} legWins={state.legWins} accent={ACCENT} onReplay={replay} onConfig={()=>go?.("looper_config")} onGames={()=>go?.("games",{gamesView:"all"})} extra={<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(120px,1fr))",gap:6}}>{profiles.map((p:any)=>{const st=state.statsByPlayer[p.id]||{}; return <div key={p.id} style={{padding:8,borderRadius:12,background:"rgba(255,255,255,.04)",border:"1px solid rgba(255,255,255,.08)",fontSize:9.5,color:SOFT}}><b style={{color:"#fff"}}>{playerName(p)}</b><br/>{st.hits||0} touches · {st.lifeLosses||0} vie(s) perdues</div>})}</div>}/>} 
    </div>
  </div>;
}
