import * as React from "react";
import { searchUsers, type OnlineFriendUser } from "../lib/friendsApi";
import { useOnlineFriends } from "../hooks/useOnlineFriends";
import { useFriendRequests } from "../hooks/useFriendRequests";
import { usePresence } from "../hooks/usePresence";
import { useSharedOnlineItems } from "../hooks/useSharedOnlineItems";

type Props = { store?: any; update?: (patch: any) => void; go?: (tab: string, params?: any) => void };
const shell: React.CSSProperties = { minHeight: "100dvh", padding: "16px 14px 96px", color: "#fff", background: "radial-gradient(circle at 20% 0%, rgba(255,213,106,.18), transparent 32%), linear-gradient(180deg,#101016,#060609)" };
const card: React.CSSProperties = { borderRadius: 20, padding: 14, background: "linear-gradient(180deg,rgba(255,255,255,.08),rgba(255,255,255,.035))", border: "1px solid rgba(255,255,255,.12)", boxShadow: "0 14px 32px rgba(0,0,0,.42)" };
const btn: React.CSSProperties = { border: 0, borderRadius: 14, padding: "10px 12px", fontWeight: 900, background: "linear-gradient(180deg,#ffd76b,#df9f37)", color: "#1b1204" };
const ghost: React.CSSProperties = { borderRadius: 14, padding: "10px 12px", fontWeight: 900, background: "rgba(255,255,255,.06)", color: "#fff", border: "1px solid rgba(255,255,255,.13)" };
function nameOf(u?: OnlineFriendUser | null) { return u?.displayName || u?.nickname || "Joueur"; }
function initials(name: string) { return name.trim().slice(0, 2).toUpperCase() || "?"; }
function Avatar({ user, size = 44 }: { user?: OnlineFriendUser | null; size?: number }) { const name = nameOf(user); return user?.avatarUrl ? <img src={user.avatarUrl} alt="" style={{ width: size, height: size, borderRadius: 999, objectFit: "cover", border: "1px solid rgba(255,255,255,.18)" }} /> : <div style={{ width: size, height: size, borderRadius: 999, display: "grid", placeItems: "center", background: "rgba(255,213,106,.18)", border: "1px solid rgba(255,213,106,.35)", fontWeight: 950 }}>{initials(name)}</div>; }
function Status({ s }: { s?: string }) { const color = s === "online" ? "#43d676" : s === "away" ? "#ffb13d" : "#85858f"; const label = s === "online" ? "En ligne" : s === "away" ? "Absent" : "Hors ligne"; return <span style={{ display: "inline-flex", alignItems: "center", gap: 6, fontSize: 12, opacity: .9 }}><i style={{ width: 8, height: 8, borderRadius: 99, background: color, boxShadow: `0 0 12px ${color}` }} />{label}</span>; }

export default function OnlineHub({ go }: Props) {
  const { friends, loading: friendsLoading, error: friendsError, refresh: refreshFriends, removeFriend } = useOnlineFriends();
  const { incoming, error: requestsError, refresh: refreshRequests, send } = useFriendRequests();
  const { items, error: sharedError, refresh: refreshShared } = useSharedOnlineItems();
  const { status, error: presenceError, setPresence } = usePresence();
  const [query, setQuery] = React.useState("");
  const [results, setResults] = React.useState<OnlineFriendUser[]>([]);
  const [searching, setSearching] = React.useState(false);
  const unread = items.filter((i) => i.direction === "incoming" && !i.readAt).length;
  async function runSearch() { if (query.trim().length < 2) return setResults([]); setSearching(true); try { setResults(await searchUsers(query)); } finally { setSearching(false); } }
  React.useEffect(() => { const id = window.setTimeout(runSearch, 350); return () => window.clearTimeout(id); }, [query]);
  async function refreshAll() { await Promise.allSettled([refreshFriends(), refreshRequests(), refreshShared(), setPresence("online")]); }
  return <div style={shell}><div style={{ maxWidth: 760, margin: "0 auto", display: "grid", gap: 14 }}>
    <header style={{ display: "flex", alignItems: "center", gap: 12 }}><div style={{ flex: 1 }}><div style={{ fontSize: 28, fontWeight: 1000, letterSpacing: 1 }}>ONLINE</div><div style={{ fontSize: 12, opacity: .78 }}>Amis · demandes · présence · partages NAS</div></div><button style={ghost} onClick={refreshAll}>Rafraîchir</button></header>
    <section style={{ ...card, display: "grid", gap: 12 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 10, alignItems: "center" }}><div><b>Présence</b><div style={{ marginTop: 4 }}><Status s={status} /></div></div><div style={{ display: "flex", gap: 8 }}><button style={ghost} onClick={() => setPresence("online")}>Online</button><button style={ghost} onClick={() => setPresence("away")}>Absent</button></div></div>{[presenceError, friendsError, requestsError, sharedError].filter(Boolean).map((e) => <div key={String(e)} style={{ color: "#ffb3b3", fontSize: 12 }}>{String(e)}</div>)}</section>
    <section style={{ ...card, display: "grid", gap: 12 }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10 }}><div><b>Résumé social</b><div style={{ fontSize: 12, opacity: .72 }}>Polling léger toutes les 20–30s.</div></div><div style={{ display: "flex", gap: 8, flexWrap: "wrap", justifyContent: "flex-end" }}><button style={ghost} onClick={() => go?.("friend_requests")}>Demandes {incoming.length ? `(${incoming.length})` : ""}</button><button style={ghost} onClick={() => go?.("shared_online")}>Partages {unread ? `(${unread})` : ""}</button></div></div><div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 10 }}>{[["Amis", friends.length], ["Demandes", incoming.length], ["Partages non lus", unread]].map(([k,v]) => <div key={String(k)} style={{ borderRadius: 16, padding: 12, background: "rgba(0,0,0,.24)", border: "1px solid rgba(255,255,255,.08)" }}><div style={{ fontSize: 11, opacity: .68 }}>{k}</div><div style={{ fontSize: 24, fontWeight: 1000 }}>{v}</div></div>)}</div></section>
    <section style={{ ...card, display: "grid", gap: 12 }}><b>Ajouter un ami</b><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Pseudo ou email…" style={{ width: "100%", boxSizing: "border-box", borderRadius: 14, padding: 12, color: "#fff", background: "rgba(0,0,0,.28)", border: "1px solid rgba(255,255,255,.14)", outline: "none" }} />{searching ? <div style={{ opacity: .72, fontSize: 12 }}>Recherche…</div> : null}<div style={{ display: "grid", gap: 8 }}>{results.map((u) => <div key={u.id || u.userId} style={{ display: "flex", alignItems: "center", gap: 10, padding: 10, borderRadius: 16, background: "rgba(255,255,255,.045)", border: "1px solid rgba(255,255,255,.09)" }}><Avatar user={u} /><div style={{ flex: 1, minWidth: 0 }}><b>{nameOf(u)}</b><div><Status s={u.status} /></div></div><button style={btn} onClick={() => send(String(u.userId || u.id))}>Inviter</button></div>)}</div></section>
    <section style={{ ...card, display: "grid", gap: 10 }}><div style={{ display: "flex", justifyContent: "space-between" }}><b>Mes amis</b><span style={{ opacity: .7, fontSize: 12 }}>{friendsLoading ? "Chargement…" : `${friends.length} ami(s)`}</span></div>{friends.length === 0 ? <div style={{ opacity: .7, fontSize: 13 }}>Aucun ami pour le moment.</div> : friends.map((f) => <div key={f.userId || f.id} style={{ display: "flex", alignItems: "center", gap: 10, padding: 10, borderRadius: 16, background: "rgba(255,255,255,.045)", border: "1px solid rgba(255,255,255,.09)" }}><Avatar user={f} /><div style={{ flex: 1, minWidth: 0 }}><b>{nameOf(f)}</b><div><Status s={f.status} /></div></div><button style={ghost} onClick={() => go?.("shared_online", { targetUserId: f.userId || f.id })}>Partager</button><button style={{ ...ghost, color: "#ffb3b3" }} onClick={() => removeFriend(String(f.userId || f.id))}>Retirer</button></div>)}</section>
  </div></div>;
}
