import * as React from "react";
import { useOnlineFriends } from "../hooks/useOnlineFriends";
import { useSharedOnlineItems } from "../hooks/useSharedOnlineItems";
const shell: React.CSSProperties = { minHeight: "100dvh", padding: "16px 14px 96px", color: "#fff", background: "linear-gradient(180deg,#101016,#060609)" };
const card: React.CSSProperties = { borderRadius: 18, padding: 12, background: "rgba(255,255,255,.06)", border: "1px solid rgba(255,255,255,.12)", display: "grid", gap: 9 };
const ghost: React.CSSProperties = { borderRadius: 12, padding: "9px 11px", fontWeight: 900, background: "rgba(255,255,255,.06)", color: "#fff", border: "1px solid rgba(255,255,255,.13)" };
const btn: React.CSSProperties = { border: 0, borderRadius: 12, padding: "9px 11px", fontWeight: 900, background: "linear-gradient(180deg,#ffd76b,#df9f37)", color: "#1b1204" };
function nameOf(u: any) { return u?.displayName || u?.nickname || "Joueur"; }
export default function SharedPage({ go, params }: { go?: (tab: string) => void; params?: any }) {
  const { friends } = useOnlineFriends(30000);
  const { items, loading, error, refresh, markRead, share } = useSharedOnlineItems();
  const [target, setTarget] = React.useState(String(params?.targetUserId || ""));
  const [title, setTitle] = React.useState("Partage Multisports Scoring");
  const incoming = items.filter((i) => i.direction === "incoming");
  const outgoing = items.filter((i) => i.direction === "outgoing");
  async function sharePing() { if (!target) return; await share({ targetUserId: target, type: "stats", title, sport: "multi", payload: { kind: "manual_share", at: new Date().toISOString() } }); }
  return <div style={shell}><div style={{ maxWidth: 760, margin: "0 auto", display: "grid", gap: 14 }}><header style={{ display: "flex", alignItems: "center", gap: 10 }}><button style={ghost} onClick={() => go?.("friends")}>← Online</button><div style={{ flex: 1 }}><h1 style={{ margin: 0 }}>Partages</h1><div style={{ fontSize: 12, opacity: .7 }}>{loading ? "Synchronisation…" : "Matchs, stats et snapshots reçus/envoyés"}</div></div><button style={ghost} onClick={refresh}>Rafraîchir</button></header>{error ? <div style={{ color: "#ffb3b3" }}>{error}</div> : null}<section style={card}><b>Partager rapidement</b><select value={target} onChange={(e) => setTarget(e.target.value)} style={{ borderRadius: 12, padding: 10, color: "#fff", background: "#15151b", border: "1px solid rgba(255,255,255,.13)" }}><option value="">Choisir un ami…</option>{friends.map((f) => <option key={f.userId || f.id} value={f.userId || f.id}>{nameOf(f)}</option>)}</select><input value={title} onChange={(e) => setTitle(e.target.value)} style={{ borderRadius: 12, padding: 10, color: "#fff", background: "#15151b", border: "1px solid rgba(255,255,255,.13)" }} /><button style={btn} onClick={sharePing}>Envoyer un partage test</button></section><section style={card}><b>Reçus</b>{incoming.length === 0 ? <span style={{ opacity: .7 }}>Aucun partage reçu.</span> : incoming.map((i) => <div key={i.id} style={{ borderRadius: 14, padding: 10, background: "rgba(0,0,0,.22)", border: "1px solid rgba(255,255,255,.08)" }}><div style={{ display: "flex", justifyContent: "space-between", gap: 10 }}><b>{i.title || i.type}</b><span style={{ opacity: .7, fontSize: 12 }}>{i.sport || "multi"}</span></div><div style={{ fontSize: 12, opacity: .75 }}>De {nameOf(i.ownerUser)} · {i.createdAt ? new Date(i.createdAt).toLocaleString() : "—"}</div>{!i.readAt ? <button style={{ ...ghost, marginTop: 8 }} onClick={() => markRead(i.id)}>Marquer lu</button> : null}</div>)}</section><section style={card}><b>Envoyés</b>{outgoing.length === 0 ? <span style={{ opacity: .7 }}>Aucun partage envoyé.</span> : outgoing.map((i) => <div key={i.id}><b>{i.title || i.type}</b><div style={{ fontSize: 12, opacity: .72 }}>{i.createdAt ? new Date(i.createdAt).toLocaleString() : "—"}</div></div>)}</section></div></div>;
}
