import type { EsportsGameDefinition } from "./types";

export const ESPORTS_GAMES: EsportsGameDefinition[] = [
  { id: "rocket-league", name: "Rocket League", shortName: "RL", publisher: "Psyonix / Epic", genre: "sports", platforms: ["pc","playstation","xbox","switch","crossplay"], crossplay: true, matchShape: "team", teamSizes: [1,2,3], maxPlayers: 6, resultKind: "score", bestOf: [1,3,5,7], statKeys: ["goals","assists","saves","shots"], accent: "#3ea6ff", icon: "🚗", featured: true },
  { id: "valorant", name: "VALORANT", shortName: "VAL", publisher: "Riot Games", genre: "fps", platforms: ["pc","playstation","xbox"], crossplay: false, matchShape: "team", teamSizes: [5], maxPlayers: 10, resultKind: "rounds", bestOf: [1,3,5], statKeys: ["kills","deaths","assists","acs"], accent: "#ff4655", icon: "V", featured: true },
  { id: "counter-strike-2", name: "Counter-Strike 2", shortName: "CS2", publisher: "Valve", genre: "fps", platforms: ["pc"], crossplay: false, matchShape: "team", teamSizes: [5], maxPlayers: 10, resultKind: "rounds", bestOf: [1,3,5], statKeys: ["kills","deaths","assists","adr"], accent: "#f4a340", icon: "🎯", featured: true },
  { id: "league-of-legends", name: "League of Legends", shortName: "LoL", publisher: "Riot Games", genre: "moba", platforms: ["pc"], crossplay: false, matchShape: "team", teamSizes: [5], maxPlayers: 10, resultKind: "maps", bestOf: [1,3,5], statKeys: ["kills","deaths","assists","cs"], accent: "#c89b3c", icon: "⚔️", featured: true },
  { id: "fortnite", name: "Fortnite", shortName: "FN", publisher: "Epic Games", genre: "battle_royale", platforms: ["pc","playstation","xbox","switch","mobile","crossplay"], crossplay: true, matchShape: "battle_royale", teamSizes: [1,2,4], maxPlayers: 100, resultKind: "points", bestOf: [1,3,5,6,10], statKeys: ["placement","eliminations","damage","points"], accent: "#8b5cf6", icon: "🪂", featured: true },
  { id: "ea-sports-fc", name: "EA SPORTS FC", shortName: "FC", publisher: "EA Sports", genre: "sports", platforms: ["pc","playstation","xbox","switch","crossplay"], crossplay: true, matchShape: "1v1", teamSizes: [1], maxPlayers: 2, resultKind: "score", bestOf: [1,3,5], statKeys: ["goals","shots","possession","passes"], accent: "#60d394", icon: "⚽", featured: true },
  { id: "call-of-duty", name: "Call of Duty", shortName: "COD", publisher: "Activision", genre: "fps", platforms: ["pc","playstation","xbox","crossplay"], crossplay: true, matchShape: "team", teamSizes: [4,5,6], maxPlayers: 12, resultKind: "maps", bestOf: [1,3,5,7], statKeys: ["kills","deaths","assists","score"], accent: "#9ca3af", icon: "🪖", featured: true },
  { id: "overwatch-2", name: "Overwatch 2", shortName: "OW2", publisher: "Blizzard", genre: "fps", platforms: ["pc","playstation","xbox","switch","crossplay"], crossplay: true, matchShape: "team", teamSizes: [5], maxPlayers: 10, resultKind: "maps", bestOf: [1,3,5], statKeys: ["eliminations","deaths","assists","damage"], accent: "#f59e0b", icon: "⭕", featured: true },
  { id: "rainbow-six-siege", name: "Rainbow Six Siege", shortName: "R6", publisher: "Ubisoft", genre: "fps", platforms: ["pc","playstation","xbox"], crossplay: true, matchShape: "team", teamSizes: [5], maxPlayers: 10, resultKind: "rounds", bestOf: [1,3,5], statKeys: ["kills","deaths","assists","plants"], accent: "#d1d5db", icon: "🛡️" },
  { id: "apex-legends", name: "Apex Legends", shortName: "APEX", publisher: "EA / Respawn", genre: "battle_royale", platforms: ["pc","playstation","xbox","switch","crossplay"], crossplay: true, matchShape: "battle_royale", teamSizes: [1,2,3], maxPlayers: 60, resultKind: "points", bestOf: [1,3,6,10], statKeys: ["placement","kills","damage","points"], accent: "#ef4444", icon: "▲" },
  { id: "pubg", name: "PUBG: Battlegrounds", shortName: "PUBG", publisher: "Krafton", genre: "battle_royale", platforms: ["pc","playstation","xbox"], crossplay: true, matchShape: "battle_royale", teamSizes: [1,2,4], maxPlayers: 100, resultKind: "points", bestOf: [1,3,5,6], statKeys: ["placement","kills","damage","points"], accent: "#f2a900", icon: "🪖" },
  { id: "dota-2", name: "Dota 2", shortName: "DOTA", publisher: "Valve", genre: "moba", platforms: ["pc"], crossplay: false, matchShape: "team", teamSizes: [5], maxPlayers: 10, resultKind: "maps", bestOf: [1,3,5], statKeys: ["kills","deaths","assists","lastHits"], accent: "#c23c2a", icon: "◆" },
  { id: "street-fighter-6", name: "Street Fighter 6", shortName: "SF6", publisher: "Capcom", genre: "fighting", platforms: ["pc","playstation","xbox"], crossplay: true, matchShape: "1v1", teamSizes: [1], maxPlayers: 2, resultKind: "sets", bestOf: [1,3,5,7], statKeys: ["rounds","perfects"], accent: "#2563eb", icon: "🥊", featured: true },
  { id: "tekken-8", name: "Tekken 8", shortName: "T8", publisher: "Bandai Namco", genre: "fighting", platforms: ["pc","playstation","xbox"], crossplay: true, matchShape: "1v1", teamSizes: [1], maxPlayers: 2, resultKind: "sets", bestOf: [1,3,5,7], statKeys: ["rounds","perfects"], accent: "#ec4899", icon: "👊", featured: true },
  { id: "super-smash-bros-ultimate", name: "Super Smash Bros. Ultimate", shortName: "SSBU", publisher: "Nintendo", genre: "fighting", platforms: ["switch"], crossplay: false, matchShape: "1v1", teamSizes: [1,2], maxPlayers: 4, resultKind: "sets", bestOf: [1,3,5,7], statKeys: ["stocks","damage"], accent: "#ef4444", icon: "⭐" },
  { id: "mario-kart-8-deluxe", name: "Mario Kart 8 Deluxe", shortName: "MK8D", publisher: "Nintendo", genre: "racing", platforms: ["switch"], crossplay: false, matchShape: "ffa", teamSizes: [1], maxPlayers: 12, resultKind: "points", bestOf: [1,4,8,12], statKeys: ["points","wins","podiums"], accent: "#22c55e", icon: "🏎️", featured: true },
  { id: "gran-turismo-7", name: "Gran Turismo 7", shortName: "GT7", publisher: "Sony", genre: "racing", platforms: ["playstation"], crossplay: false, matchShape: "ffa", teamSizes: [1], maxPlayers: 16, resultKind: "placement", bestOf: [1,3,5], statKeys: ["position","bestLap","penalties"], accent: "#2563eb", icon: "🏁" },
  { id: "iracing", name: "iRacing", shortName: "iRacing", publisher: "iRacing.com", genre: "racing", platforms: ["pc"], crossplay: false, matchShape: "ffa", teamSizes: [1], maxPlayers: 60, resultKind: "placement", bestOf: [1,3,5], statKeys: ["position","bestLap","incidents"], accent: "#0ea5e9", icon: "🏁" },
  { id: "teamfight-tactics", name: "Teamfight Tactics", shortName: "TFT", publisher: "Riot Games", genre: "strategy", platforms: ["pc","mobile"], crossplay: true, matchShape: "ffa", teamSizes: [1], maxPlayers: 8, resultKind: "placement", bestOf: [1,3,5], statKeys: ["placement","points"], accent: "#f59e0b", icon: "♟️" },
  { id: "hearthstone", name: "Hearthstone", shortName: "HS", publisher: "Blizzard", genre: "strategy", platforms: ["pc","mobile"], crossplay: true, matchShape: "1v1", teamSizes: [1], maxPlayers: 2, resultKind: "sets", bestOf: [1,3,5], statKeys: ["gamesWon"], accent: "#f59e0b", icon: "🌀" },
  { id: "brawl-stars", name: "Brawl Stars", shortName: "BS", publisher: "Supercell", genre: "moba", platforms: ["mobile"], crossplay: true, matchShape: "team", teamSizes: [3], maxPlayers: 6, resultKind: "sets", bestOf: [1,3,5], statKeys: ["wins","kills","damage"], accent: "#fde047", icon: "💥" },
  { id: "clash-royale", name: "Clash Royale", shortName: "CR", publisher: "Supercell", genre: "strategy", platforms: ["mobile"], crossplay: true, matchShape: "1v1", teamSizes: [1,2], maxPlayers: 4, resultKind: "score", bestOf: [1,3,5], statKeys: ["crowns","towerDamage"], accent: "#3b82f6", icon: "👑" },
  { id: "mobile-legends", name: "Mobile Legends: Bang Bang", shortName: "MLBB", publisher: "Moonton", genre: "moba", platforms: ["mobile"], crossplay: true, matchShape: "team", teamSizes: [5], maxPlayers: 10, resultKind: "maps", bestOf: [1,3,5,7], statKeys: ["kills","deaths","assists"], accent: "#38bdf8", icon: "⚔️" },
  { id: "pokemon-unite", name: "Pokémon UNITE", shortName: "UNITE", publisher: "TiMi / Pokémon", genre: "moba", platforms: ["switch","mobile"], crossplay: true, matchShape: "team", teamSizes: [5], maxPlayers: 10, resultKind: "score", bestOf: [1,3,5], statKeys: ["points","kills","assists"], accent: "#a855f7", icon: "⚡" },
  { id: "age-of-empires-iv", name: "Age of Empires IV", shortName: "AoE IV", publisher: "Xbox Game Studios", genre: "strategy", platforms: ["pc","xbox"], crossplay: true, matchShape: "1v1", teamSizes: [1,2,3,4], maxPlayers: 8, resultKind: "maps", bestOf: [1,3,5,7], statKeys: ["wins","duration"], accent: "#d4a373", icon: "🏰" },
  { id: "starcraft-2", name: "StarCraft II", shortName: "SC2", publisher: "Blizzard", genre: "strategy", platforms: ["pc"], crossplay: false, matchShape: "1v1", teamSizes: [1,2,3,4], maxPlayers: 8, resultKind: "maps", bestOf: [1,3,5,7], statKeys: ["wins","duration"], accent: "#60a5fa", icon: "🚀" },
  { id: "fall-guys", name: "Fall Guys", shortName: "FG", publisher: "Epic Games", genre: "party", platforms: ["pc","playstation","xbox","switch","crossplay"], crossplay: true, matchShape: "ffa", teamSizes: [1,2,4], maxPlayers: 40, resultKind: "placement", bestOf: [1,3,5], statKeys: ["placement","crowns"], accent: "#f472b6", icon: "🏆" },
];

export const ESPORTS_GAME_BY_ID = new Map(ESPORTS_GAMES.map((game) => [game.id, game]));

export function getEsportsGame(id: unknown): EsportsGameDefinition {
  return ESPORTS_GAME_BY_ID.get(String(id || "")) || ESPORTS_GAMES[0];
}
