import React from "react";
import type { RunningRouteTemplate } from "../../activity/runningRoutes";
import {
  createOutdoorRouteOuting,
  fetchOutdoorRouteSocialFeed,
  joinOutdoorRouteOuting,
  postOutdoorRouteCondition,
  postOutdoorRouteHazard,
  submitOutdoorRouteReview,
  uploadOutdoorRouteCommunityPhoto,
  type RouteConditionKind,
  type RouteHazardKind,
  type RouteOutingPace,
  type RouteSocialFeed,
} from "../../activity/outdoorRouteSocial";
import { RunningSurface } from "./RunningUi";
import "./runningResponsive.css";

const EMPTY: RouteSocialFeed = { available: true, summary: { reviewCount: 0, ratingAvg: null, difficultyAvg: null, recentCondition: null }, reviews: [], conditions: [], hazards: [], outings: [], photos: [] };
const CONDITION_ICONS: Record<RouteConditionKind, string> = { good: "✅", dry: "☀️", wet: "💧", muddy: "🟤", snow: "❄️", icy: "🧊", blocked: "⛔" };
const HAZARD_ICONS: Record<RouteHazardKind, string> = { obstacle: "🪵", works: "🚧", flood: "🌊", danger: "⚠️", closure: "⛔", other: "📍" };

export default function OutdoorRouteSocialPanel({ route, lang, accent, textSoft }: { route: RunningRouteTemplate; lang: string; accent: string; textSoft: string }) {
  const [feed, setFeed] = React.useState<RouteSocialFeed>(EMPTY);
  const [tab, setTab] = React.useState<"reviews" | "condition" | "outings" | "photos">("reviews");
  const [busy, setBusy] = React.useState(false);
  const [message, setMessage] = React.useState("");
  const [rating, setRating] = React.useState(5);
  const [difficulty, setDifficulty] = React.useState(3);
  const [reviewText, setReviewText] = React.useState("");
  const [condition, setCondition] = React.useState<RouteConditionKind>("good");
  const [conditionNote, setConditionNote] = React.useState("");
  const [hazard, setHazard] = React.useState<RouteHazardKind>("obstacle");
  const [hazardSeverity, setHazardSeverity] = React.useState(1);
  const [hazardNote, setHazardNote] = React.useState("");
  const [outingAt, setOutingAt] = React.useState(() => { const d = new Date(Date.now() + 24 * 3600_000); d.setMinutes(0, 0, 0); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}T${String(d.getHours()).padStart(2,"0")}:00`; });
  const [outingPace, setOutingPace] = React.useState<RouteOutingPace>("easy");
  const [outingMax, setOutingMax] = React.useState(6);
  const [outingNote, setOutingNote] = React.useState("");
  const [photoCaption, setPhotoCaption] = React.useState("");

  const refresh = React.useCallback(async () => setFeed(await fetchOutdoorRouteSocialFeed(route)), [route]);
  React.useEffect(() => { setFeed(EMPTY); setMessage(""); void refresh(); }, [refresh]);

  const copy = lang.startsWith("fr") ? {
    title: "COMMUNAUTÉ DU PARCOURS", reviews: "AVIS", condition: "ÉTAT", outings: "SORTIES", photos: "PHOTOS", reviewTitle: "TON AVIS", rating: "NOTE", difficulty: "DIFFICULTÉ RESSENTIE", publish: "PUBLIER", conditionTitle: "ÉTAT DU TERRAIN", report: "SIGNALER UN PROBLÈME", outingTitle: "ORGANISER UNE SORTIE", join: "REJOINDRE", leave: "QUITTER", people: "participants", photoTitle: "PHOTOS DES UTILISATEURS", choose: "AJOUTER UNE PHOTO", empty: "Rien n'a encore été publié pour ce parcours.", install: "Le backend communauté Running V2 n'est pas encore installé sur Supabase.", saved: "Publié !", failed: "Publication impossible pour le moment.", reviewPlaceholder: "Ton avis sur ce parcours…", notePlaceholder: "Précision utile (facultatif)…", outingPlaceholder: "Ex : sortie tranquille, frontale recommandée…", caption: "Légende de la photo…",
  } : lang.startsWith("es") ? {
    title: "COMUNIDAD DE LA RUTA", reviews: "OPINIONES", condition: "ESTADO", outings: "SALIDAS", photos: "FOTOS", reviewTitle: "TU OPINIÓN", rating: "NOTA", difficulty: "DIFICULTAD PERCIBIDA", publish: "PUBLICAR", conditionTitle: "ESTADO DEL TERRENO", report: "SEÑALAR UN PROBLEMA", outingTitle: "ORGANIZAR UNA SALIDA", join: "UNIRSE", leave: "SALIR", people: "participantes", photoTitle: "FOTOS DE USUARIOS", choose: "AÑADIR FOTO", empty: "Todavía no se ha publicado nada para esta ruta.", install: "El backend de comunidad Running V2 aún no está instalado en Supabase.", saved: "¡Publicado!", failed: "No se puede publicar ahora.", reviewPlaceholder: "Tu opinión sobre esta ruta…", notePlaceholder: "Detalle útil (opcional)…", outingPlaceholder: "Ej.: salida tranquila, frontal recomendado…", caption: "Pie de foto…",
  } : {
    title: "ROUTE COMMUNITY", reviews: "REVIEWS", condition: "CONDITION", outings: "OUTINGS", photos: "PHOTOS", reviewTitle: "YOUR REVIEW", rating: "RATING", difficulty: "PERCEIVED DIFFICULTY", publish: "PUBLISH", conditionTitle: "TRAIL CONDITION", report: "REPORT A PROBLEM", outingTitle: "PLAN AN OUTING", join: "JOIN", leave: "LEAVE", people: "participants", photoTitle: "USER PHOTOS", choose: "ADD A PHOTO", empty: "Nothing has been published for this route yet.", install: "The Running community V2 backend is not installed on Supabase yet.", saved: "Published!", failed: "Unable to publish right now.", reviewPlaceholder: "Your thoughts about this route…", notePlaceholder: "Useful detail (optional)…", outingPlaceholder: "E.g. easy outing, headlamp recommended…", caption: "Photo caption…",
  };

  const run = async (fn: () => Promise<any>, after?: () => void) => { setBusy(true); setMessage(""); const result = await fn(); setBusy(false); if (result?.ok) { setMessage(copy.saved); after?.(); await refresh(); } else setMessage(result?.reason === "backend-not-installed" ? copy.install : copy.failed); };
  const conditionLabel = (kind: RouteConditionKind) => ({ good: "OK", dry: lang.startsWith("fr") ? "SEC" : "DRY", wet: lang.startsWith("fr") ? "HUMIDE" : "WET", muddy: lang.startsWith("fr") ? "BOUE" : "MUD", snow: lang.startsWith("fr") ? "NEIGE" : "SNOW", icy: lang.startsWith("fr") ? "VERGLAS" : "ICE", blocked: lang.startsWith("fr") ? "BLOQUÉ" : "BLOCKED" }[kind]);
  const paceLabel = (pace: RouteOutingPace) => pace === "easy" ? (lang.startsWith("fr") ? "TRANQUILLE" : "EASY") : pace === "steady" ? (lang.startsWith("fr") ? "MODÉRÉ" : "STEADY") : (lang.startsWith("fr") ? "SPORTIF" : "SPORTY");

  return <RunningSurface accent={accent} style={{ marginTop: 8 }}>
    <div style={{ display: "grid", gridTemplateColumns: "1fr auto", gap: 8, alignItems: "center" }}><div><div style={{ color: accent, fontSize: 9, fontWeight: 1000, letterSpacing: .5 }}>{copy.title}</div><div style={{ marginTop: 3, color: textSoft, fontSize: 7.6 }}>{feed.summary.reviewCount ? `★ ${feed.summary.ratingAvg?.toFixed(1) || "—"}/5 · ${feed.summary.reviewCount} · ${copy.difficulty} ${feed.summary.difficultyAvg?.toFixed(1) || "—"}/5` : copy.empty}</div></div><button className="btn" onClick={() => void refresh()} style={{ minHeight: 29, padding: "4px 8px", fontSize: 7.2 }}>↻</button></div>
    {!feed.available ? <div style={{ marginTop: 8, fontSize: 8.1, color: textSoft, lineHeight: 1.4 }}>{copy.install}</div> : null}
    <div style={{ marginTop: 8, display: "grid", gridTemplateColumns: "repeat(4,minmax(0,1fr))", gap: 5 }}>{([['reviews', copy.reviews], ['condition', copy.condition], ['outings', copy.outings], ['photos', copy.photos]] as const).map(([id,label]) => <button key={id} className="btn" onClick={() => setTab(id)} style={{ minHeight: 32, padding: 3, fontSize: 7, fontWeight: 1000, color: tab === id ? accent : undefined, borderColor: tab === id ? `${accent}66` : undefined }}>{label}</button>)}</div>
    {message ? <div style={{ marginTop: 7, fontSize: 7.8, color: message === copy.saved ? accent : textSoft }}>{message}</div> : null}

    {tab === "reviews" ? <div style={{ marginTop: 8 }}><div style={{ fontSize: 8.2, color: accent, fontWeight: 1000 }}>{copy.reviewTitle}</div><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 7, marginTop: 7 }}><ScorePicker label={copy.rating} value={rating} onChange={setRating} accent={accent}/><ScorePicker label={copy.difficulty} value={difficulty} onChange={setDifficulty} accent={accent}/></div><textarea value={reviewText} onChange={(e) => setReviewText(e.target.value.slice(0,600))} placeholder={copy.reviewPlaceholder} style={textareaStyle}/><button className="btn" disabled={busy} onClick={() => void run(() => submitOutdoorRouteReview(route,{rating,difficulty,text:reviewText}), () => setReviewText(""))} style={primaryButton(accent)}>{copy.publish}</button><div style={{ marginTop: 9, display: "grid", gap: 6 }}>{feed.reviews.length ? feed.reviews.slice(0,8).map((row) => <CommunityRow key={row.id} name={row.displayName} avatar={row.avatarUrl} meta={`★ ${row.rating}/5 · ${copy.difficulty} ${row.difficulty}/5`} text={row.text} textSoft={textSoft}/>) : <Empty text={copy.empty} color={textSoft}/>}</div></div> : null}

    {tab === "condition" ? <div style={{ marginTop: 8 }}><div style={{ fontSize: 8.2, color: accent, fontWeight: 1000 }}>{copy.conditionTitle}</div><div className="running-metrics-4" style={{ marginTop: 7 }}>{(Object.keys(CONDITION_ICONS) as RouteConditionKind[]).map((kind) => <button key={kind} className="btn" onClick={() => setCondition(kind)} style={{ minHeight: 36, padding: 3, fontSize: 7, color: condition === kind ? accent : undefined, borderColor: condition === kind ? `${accent}66` : undefined }}>{CONDITION_ICONS[kind]} {conditionLabel(kind)}</button>)}</div><input value={conditionNote} onChange={(e) => setConditionNote(e.target.value.slice(0,300))} placeholder={copy.notePlaceholder} style={inputStyle}/><button className="btn" disabled={busy} onClick={() => void run(() => postOutdoorRouteCondition(route,condition,conditionNote), () => setConditionNote(""))} style={primaryButton(accent)}>{copy.publish}</button><div style={{ marginTop: 9, display: "grid", gap: 5 }}>{feed.conditions.slice(0,6).map((row) => <CommunityRow key={row.id} name={row.displayName} meta={`${CONDITION_ICONS[row.kind]} ${conditionLabel(row.kind)} · ${formatDate(row.createdAt)}`} text={row.note} textSoft={textSoft}/>)}</div><div style={{ marginTop: 11, fontSize: 8.2, color: "#ffb46a", fontWeight: 1000 }}>{copy.report}</div><div style={{ display: "grid", gridTemplateColumns: "repeat(3,minmax(0,1fr))", gap: 5, marginTop: 7 }}>{(["obstacle","works","flood","danger","closure","other"] as RouteHazardKind[]).map((kind) => <button key={kind} className="btn" onClick={() => setHazard(kind)} style={{ minHeight: 34, padding: 3, fontSize: 7, color: hazard === kind ? "#ffb46a" : undefined, borderColor: hazard === kind ? "#ffb46a66" : undefined }}>{HAZARD_ICONS[kind]} {kind.toUpperCase()}</button>)}</div><div style={{ display: "grid", gridTemplateColumns: "1fr auto", gap: 7, alignItems: "center", marginTop: 7 }}><input value={hazardNote} onChange={(e) => setHazardNote(e.target.value.slice(0,400))} placeholder={copy.notePlaceholder} style={{...inputStyle,marginTop:0}}/><select value={hazardSeverity} onChange={(e) => setHazardSeverity(Number(e.target.value))} style={selectStyle}><option value={1}>⚠</option><option value={2}>⚠⚠</option><option value={3}>⚠⚠⚠</option></select></div><button className="btn" disabled={busy} onClick={() => void run(() => postOutdoorRouteHazard(route,hazard,hazardSeverity,hazardNote), () => setHazardNote(""))} style={{...primaryButton(accent),color:"#ffb46a",borderColor:"#ffb46a66"}}>{copy.report}</button>{feed.hazards.length ? <div style={{ marginTop: 8, display:"grid",gap:5 }}>{feed.hazards.slice(0,6).map((row)=><CommunityRow key={row.id} name={row.displayName} meta={`${HAZARD_ICONS[row.kind]} ${row.kind.toUpperCase()} · ${"⚠".repeat(row.severity)} · ${formatDate(row.createdAt)}`} text={row.note} textSoft={textSoft}/>)}</div> : null}</div> : null}

    {tab === "outings" ? <div style={{ marginTop: 8 }}><div style={{ fontSize: 8.2, color: accent, fontWeight: 1000 }}>{copy.outingTitle}</div><input type="datetime-local" value={outingAt} onChange={(e) => setOutingAt(e.target.value)} style={inputStyle}/><div style={{ display: "grid", gridTemplateColumns: "repeat(3,minmax(0,1fr))", gap: 5, marginTop: 7 }}>{(["easy","steady","sporty"] as RouteOutingPace[]).map((pace)=><button key={pace} className="btn" onClick={()=>setOutingPace(pace)} style={{minHeight:33,fontSize:7,color:outingPace===pace?accent:undefined,borderColor:outingPace===pace?`${accent}66`:undefined}}>{paceLabel(pace)}</button>)}</div><div style={{ display:"grid",gridTemplateColumns:"1fr 90px",gap:7 }}><input value={outingNote} onChange={(e)=>setOutingNote(e.target.value.slice(0,400))} placeholder={copy.outingPlaceholder} style={inputStyle}/><input type="number" min={2} max={30} value={outingMax} onChange={(e)=>setOutingMax(Math.max(2,Math.min(30,Number(e.target.value)||2)))} style={inputStyle}/></div><button className="btn" disabled={busy || !outingAt} onClick={()=>void run(()=>createOutdoorRouteOuting(route,{startsAt:outingAt,pace:outingPace,maxPeople:outingMax,note:outingNote}),()=>setOutingNote(""))} style={primaryButton(accent)}>{copy.publish}</button><div style={{ marginTop:9,display:"grid",gap:6 }}>{feed.outings.length ? feed.outings.map((row)=><div key={row.id} style={cardStyle}><div style={{display:"grid",gridTemplateColumns:"34px 1fr auto",gap:7,alignItems:"center"}}><div style={{width:32,height:32,borderRadius:999,overflow:"hidden",display:"grid",placeItems:"center",background:"rgba(255,255,255,.04)"}}>{row.ownerAvatarUrl?<img src={row.ownerAvatarUrl} alt="" style={{width:"100%",height:"100%",objectFit:"cover"}}/>:"👟"}</div><div><div style={{fontSize:8.4,fontWeight:1000}}>{row.ownerDisplayName}</div><div style={{fontSize:7,color:textSoft,marginTop:2}}>{new Date(row.startsAt).toLocaleString()} · {paceLabel(row.pace)} · {row.participants}/{row.maxPeople} {copy.people}</div>{row.note?<div style={{fontSize:7.4,color:textSoft,marginTop:3}}>{row.note}</div>:null}</div><button className="btn" disabled={busy || (!row.joined && row.participants>=row.maxPeople)} onClick={()=>void run(()=>joinOutdoorRouteOuting(row.id,!row.joined))} style={{minHeight:31,padding:"3px 7px",fontSize:7,color:row.joined?"#ff9b9b":accent,borderColor:row.joined?"#ff9b9b66":`${accent}55`}}>{row.joined?copy.leave:copy.join}</button></div></div>) : <Empty text={copy.empty} color={textSoft}/>}</div></div> : null}

    {tab === "photos" ? <div style={{marginTop:8}}><div style={{fontSize:8.2,color:accent,fontWeight:1000}}>{copy.photoTitle}</div><input value={photoCaption} onChange={(e)=>setPhotoCaption(e.target.value.slice(0,300))} placeholder={copy.caption} style={inputStyle}/><label className="btn" style={{...primaryButton(accent),display:"grid",placeItems:"center",cursor:"pointer"}}>{busy?"…":copy.choose}<input type="file" accept="image/*" style={{display:"none"}} onChange={(e)=>{const file=e.target.files?.[0]; if(file) void run(()=>uploadOutdoorRouteCommunityPhoto(route,file,photoCaption),()=>setPhotoCaption("")); e.currentTarget.value="";}}/></label><div style={{marginTop:9,display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:7}}>{feed.photos.length ? feed.photos.map((photo)=><a key={photo.id} href={photo.url} target="_blank" rel="noreferrer" style={{...cardStyle,textDecoration:"none",color:"inherit",padding:0,overflow:"hidden"}}><div style={{aspectRatio:"4/3",overflow:"hidden",background:"rgba(0,0,0,.2)"}}><img src={photo.url} alt={photo.caption||""} loading="lazy" style={{width:"100%",height:"100%",objectFit:"cover",display:"block"}}/></div><div style={{padding:7}}><div style={{fontSize:7.6,fontWeight:1000}}>{photo.displayName}</div>{photo.caption?<div style={{marginTop:2,fontSize:7,color:textSoft}}>{photo.caption}</div>:null}</div></a>) : <Empty text={copy.empty} color={textSoft}/>}</div></div> : null}
  </RunningSurface>;
}

function ScorePicker({label,value,onChange,accent}:{label:string;value:number;onChange:(value:number)=>void;accent:string}) { return <div style={cardStyle}><div style={{fontSize:7,color:"rgba(255,255,255,.55)",fontWeight:1000}}>{label}</div><div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:2,marginTop:5}}>{[1,2,3,4,5].map((score)=><button key={score} type="button" onClick={()=>onChange(score)} style={{border:0,background:"transparent",padding:1,color:score<=value?accent:"rgba(255,255,255,.2)",fontSize:15,cursor:"pointer"}}>★</button>)}</div></div>; }
function CommunityRow({name,avatar,meta,text,textSoft}:{name:string;avatar?:string|null;meta:string;text?:string;textSoft:string}) { return <div style={{...cardStyle,display:"grid",gridTemplateColumns:"32px 1fr",gap:7,alignItems:"start"}}><div style={{width:30,height:30,borderRadius:999,overflow:"hidden",background:"rgba(255,255,255,.04)",display:"grid",placeItems:"center"}}>{avatar?<img src={avatar} alt="" style={{width:"100%",height:"100%",objectFit:"cover"}}/>:"🏃"}</div><div><div style={{fontSize:8.2,fontWeight:1000}}>{name}</div><div style={{marginTop:2,fontSize:7,color:textSoft}}>{meta}</div>{text?<div style={{marginTop:4,fontSize:7.5,lineHeight:1.4,color:textSoft}}>{text}</div>:null}</div></div>; }
function Empty({text,color}:{text:string;color:string}) { return <div style={{fontSize:8,color,lineHeight:1.45,padding:"8px 0"}}>{text}</div>; }
function formatDate(value:string){try{return new Date(value).toLocaleDateString();}catch{return "";}}
const cardStyle: React.CSSProperties={padding:8,borderRadius:12,border:"1px solid rgba(255,255,255,.06)",background:"rgba(255,255,255,.025)"};
const inputStyle: React.CSSProperties={width:"100%",boxSizing:"border-box",marginTop:7,minHeight:36,borderRadius:10,border:"1px solid rgba(255,255,255,.1)",background:"rgba(0,0,0,.2)",color:"inherit",padding:"7px 8px",fontSize:8};
const textareaStyle: React.CSSProperties={...inputStyle,minHeight:64,resize:"vertical"};
const selectStyle: React.CSSProperties={...inputStyle,width:72,marginTop:0};
const primaryButton=(accent:string):React.CSSProperties=>({width:"100%",minHeight:36,marginTop:7,color:accent,borderColor:`${accent}66`,fontSize:7.8,fontWeight:1000});
