import type { AwenaProcedureEntry } from "./AwenaProceduralAcademy";

export const AWENA_V89_PROCEDURES: AwenaProcedureEntry[] = [
  {
    id: "v89-signup-account",
    domain: "account",
    title: "Créer un compte en ligne proprement",
    aliases: ["creer compte en ligne", "inscription compte", "signup compte", "nouveau compte"],
    route: "auth_v7_signup",
    purpose: "Créer un compte sans confondre identité en ligne et profils joueurs locaux.",
    prerequisites: ["Une adresse email accessible.", "Un mot de passe conforme aux règles affichées."],
    steps: ["Ouvre le parcours de création de compte.", "Saisis l’adresse email et le mot de passe demandés.", "Valide les éventuels champs complémentaires ou code d’invitation si l’écran le réclame.", "Envoie le formulaire.", "Ouvre le mail de confirmation si une confirmation est demandée.", "Reviens dans l’application puis connecte-toi avec le compte créé."],
    verify: ["L’application affiche un compte connecté.", "Les profils joueurs locaux restent distincts du compte en ligne."],
    troubleshooting: ["Email déjà utilisé : utilise Connexion ou Mot de passe oublié au lieu de recréer un compte.", "Mail de confirmation absent : vérifie spam puis relance l’envoi depuis le parcours prévu."],
    warnings: ["Ne partage jamais ton mot de passe ou un lien de réinitialisation."],
    related: ["Connexion", "Mot de passe oublié", "Compte vs profil"],
  },
  {
    id: "v89-login-account",
    domain: "account",
    title: "Se connecter sans perdre ses données locales",
    aliases: ["connexion compte", "login compte", "me connecter"],
    route: "auth_v7_login",
    purpose: "Ouvrir la session en ligne tout en conservant les profils/historiques locaux existants.",
    prerequisites: ["Le compte existe déjà."],
    steps: ["Ouvre Connexion.", "Saisis l’email du compte.", "Saisis le mot de passe.", "Valide.", "Attends la confirmation de session.", "Vérifie ensuite le profil actif et les données locales avant toute importation/synchronisation."],
    verify: ["Le statut du compte passe à connecté.", "Les profils locaux restent visibles."],
    troubleshooting: ["Identifiants refusés : vérifie email puis utilise Mot de passe oublié.", "Session qui saute : vérifie réseau et validité du compte avant de toucher au stockage local."],
    warnings: ["Ne supprime pas les données locales pour résoudre un simple problème de connexion."],
    related: ["Mot de passe oublié", "Sync & Partage"],
  },
  {
    id: "v89-forgot-password",
    domain: "account",
    title: "Récupérer un mot de passe oublié",
    aliases: ["mot de passe oublie", "recuperer mot de passe", "forgot password"],
    route: "auth_forgot",
    purpose: "Demander un lien de récupération sans créer un doublon de compte.",
    prerequisites: ["Accès à l’adresse email du compte."],
    steps: ["Ouvre Mot de passe oublié.", "Saisis l’email du compte.", "Demande l’envoi du lien.", "Ouvre le message reçu depuis une source attendue.", "Suis le lien de réinitialisation.", "Choisis un nouveau mot de passe puis reconnecte-toi."],
    verify: ["Le nouveau mot de passe permet une connexion normale."],
    troubleshooting: ["Lien expiré : demande un nouveau lien.", "Aucun email : vérifie adresse et dossier spam avant de multiplier les demandes."],
    warnings: ["Ne communique pas le lien de reset."],
    related: ["Connexion", "Réinitialisation du mot de passe"],
  },
  {
    id: "v89-reset-password",
    domain: "account",
    title: "Réinitialiser le mot de passe",
    aliases: ["reset password", "nouveau mot de passe"],
    route: "auth_reset",
    purpose: "Remplacer un ancien mot de passe après validation du parcours de récupération.",
    prerequisites: ["Un lien/token de récupération valide."],
    steps: ["Ouvre le lien de récupération.", "Laisse l’application ouvrir l’écran de reset prévu.", "Saisis le nouveau mot de passe.", "Confirme-le si demandé.", "Valide la modification.", "Reconnecte le compte si la session n’est pas reprise automatiquement."],
    verify: ["La connexion fonctionne avec le nouveau mot de passe."],
    troubleshooting: ["Token invalide/expiré : recommence depuis Mot de passe oublié."],
    warnings: ["N’utilise pas le même mot de passe qu’un compte sensible ailleurs."],
    related: ["Mot de passe oublié", "Connexion"],
  },
  {
    id: "v89-build-aab",
    domain: "android",
    title: "Générer un AAB Android propre",
    aliases: ["generer aab", "faire bundle android", "android play aab", "bundle release"],
    route: "settings",
    purpose: "Construire le fichier Android App Bundle destiné à Google Play à partir de la base actuelle.",
    prerequisites: ["Projet de référence à jour.", "Dépendances installées.", "Version Android prête.", "Keystore/signing disponibles si requis par le build."],
    steps: ["Sauvegarde le ZIP de référence actuel.", "Mets à jour versionName/versionCode avec les scripts du projet.", "Lance typecheck et les tests de release pertinents.", "Lance la commande Android AAB prévue par le package.json du projet.", "Attends la fin de Gradle sans interrompre.", "Localise le fichier .aab généré dans les outputs Android.", "Vérifie l’AAB avec la commande de vérification prévue par le projet."],
    verify: ["La tâche Gradle bundleRelease se termine sans erreur.", "Le fichier .aab existe et le script de vérification l’accepte."],
    troubleshooting: ["versionCode refusé : incrémente-le au-dessus de la version déjà téléversée.", "Erreur signing : vérifie keystore, alias et configuration de signature.", "Erreur Gradle : utilise le message exact plutôt que de modifier plusieurs build.gradle au hasard."],
    warnings: ["Ne publie pas un AAB construit depuis une base différente de celle testée."],
    related: ["Google Play Console", "versionCode", "Signature Android"],
  },
  {
    id: "v89-upload-play-test",
    domain: "android",
    title: "Mettre à jour les testeurs Google Play",
    aliases: ["mettre a jour testeurs", "envoyer nouvelle version test ferme", "publier aab testeurs", "update closed testing"],
    route: "settings",
    purpose: "Téléverser un nouvel AAB sur la bonne piste de test sans faire réinstaller manuellement l’application.",
    prerequisites: ["AAB release valide.", "Accès à Play Console.", "versionCode supérieur à la version déjà utilisée."],
    steps: ["Ouvre Play Console et sélectionne MULTISPORTS SCORING.", "Ouvre la piste utilisée par les testeurs : interne ou test fermé selon ton programme actuel.", "Crée une nouvelle release.", "Téléverse le nouvel AAB.", "Ajoute les notes de version.", "Enregistre puis passe les contrôles affichés par Play Console.", "Lance le déploiement sur la piste.", "Attends que Google Play rende la release disponible au compte testeur.", "Sur le téléphone du testeur, ouvre Google Play avec le même compte que celui inscrit au test puis lance la mise à jour."],
    verify: ["Play Console affiche la release active sur la piste.", "Le téléphone affiche le nouveau versionName/versionCode après mise à jour."],
    troubleshooting: ["Le téléphone reste sur une ancienne version : vérifie compte Google, piste rejointe, versionCode et propagation Play.", "AAB refusé : lis l’erreur Play Console avant de reconstruire."],
    warnings: ["Ne supprime pas l’application du téléphone si tu veux préserver les données locales non sauvegardées."],
    related: ["Générer un AAB Android propre", "Diagnostiquer une ancienne version Android"],
  },
  {
    id: "v89-old-android-version",
    domain: "android",
    title: "Diagnostiquer une ancienne version Android",
    aliases: ["ancienne version android", "play installe vieille version", "mauvaise version play store", "rc ancienne version"],
    route: "settings",
    purpose: "Comprendre pourquoi Google Play installe ou conserve une version plus ancienne que celle attendue.",
    prerequisites: ["Connaître le versionName/versionCode installé.", "Connaître la piste Google Play visée."],
    steps: ["Dans l’application, relève la version installée.", "Dans Play Console, relève le versionCode de la release active sur la piste du testeur.", "Vérifie que le compte Google du téléphone est bien inscrit à cette piste.", "Vérifie qu’aucune autre piste plus restrictive ne prend le dessus pour ce compte.", "Ouvre la fiche Google Play et cherche le bouton Mettre à jour.", "Si la release vient d’être publiée, laisse le temps de propagation puis recontrôle."],
    verify: ["La version installée correspond au versionCode attendu."],
    troubleshooting: ["Même versionName mais mauvais contenu : vérifie que l’AAB a été construit depuis le bon ZIP de référence.", "Aucune mise à jour proposée : compare impérativement les versionCode."],
    warnings: ["Évite de désinstaller avant d’avoir une sauvegarde Recovery."],
    related: ["Mettre à jour les testeurs Google Play", "versionCode"],
  },
  {
    id: "v89-internal-test-release",
    domain: "android",
    title: "Publier sur la piste de test interne",
    aliases: ["test interne play", "internal track release"],
    route: "settings",
    purpose: "Distribuer rapidement un build à un petit groupe de comptes testeurs.",
    prerequisites: ["AAB signé et versionCode inédit.", "Liste de testeurs configurée."],
    steps: ["Ouvre Test > Test interne dans Play Console.", "Crée une release.", "Ajoute l’AAB.", "Valide les contrôles.", "Publie la release interne.", "Vérifie que les comptes testeurs sont dans la liste.", "Partage ou ouvre le lien d’opt-in si nécessaire."],
    verify: ["Le testeur voit l’application ou sa mise à jour dans Google Play."],
    troubleshooting: ["Testeur non éligible : vérifie l’adresse Google exacte et son opt-in."],
    warnings: ["Le test interne ne remplace pas les exigences éventuelles d’un test fermé pour l’accès Production."],
    related: ["Test fermé Google Play"],
  },
  {
    id: "v89-closed-test-release",
    domain: "android",
    title: "Préparer correctement un test fermé Google Play",
    aliases: ["test ferme play", "closed testing", "14 jours test google play"],
    route: "settings",
    purpose: "Maintenir une piste de test fermé cohérente pour les testeurs et les exigences Google Play applicables.",
    prerequisites: ["Groupe/listes de testeurs configurés.", "Release compatible avec la piste."],
    steps: ["Ouvre le test fermé concerné.", "Vérifie la liste/groupe de testeurs.", "Vérifie le lien d’opt-in.", "Publie une release avec versionCode supérieur.", "Demande aux testeurs d’utiliser le même compte Google que celui inscrit.", "Contrôle l’activité du test et les éventuels messages Play Console."],
    verify: ["Les testeurs peuvent installer la release depuis Google Play."],
    troubleshooting: ["Le testeur n’est pas compté : vérifie qu’il a réellement rejoint le programme et installé via la piste."],
    warnings: ["Les règles d’éligibilité Google Play peuvent évoluer ; suis les messages actuels de Play Console."],
    related: ["Mettre à jour les testeurs Google Play"],
  },
  {
    id: "v89-android-debug-build",
    domain: "android",
    title: "Créer un build Android de debug",
    aliases: ["build debug android", "apk debug", "tester android studio"],
    route: "settings",
    purpose: "Compiler une version de développement pour diagnostiquer l’application sur appareil sans la publier sur Google Play.",
    prerequisites: ["Dépendances installées.", "Projet Android synchronisé."],
    steps: ["Lance la synchronisation Capacitor prévue par le projet.", "Lance la commande de build debug du package.json.", "Installe l’APK debug sur l’appareil de test ou utilise Android Studio.", "Reproduis le problème.", "Observe Logcat pendant l’action."],
    verify: ["assembleDebug se termine avec succès et l’APK est généré."],
    troubleshooting: ["Erreur de plugin : relance cap sync et vérifie Gradle.", "Différence avec la version Play : compare configuration release/debug."],
    warnings: ["Un build debug n’est pas la release distribuée aux testeurs Play."],
    related: ["Logcat", "Crash Android"],
  },
  {
    id: "v89-capacitor-sync",
    domain: "android",
    title: "Synchroniser Capacitor avant un build",
    aliases: ["cap sync", "capacitor sync android", "android sync"],
    route: "settings",
    purpose: "Copier le build Web et les plugins dans le projet Android avant compilation native.",
    prerequisites: ["Build Web réalisable.", "Projet Android présent."],
    steps: ["Lance le script android:sync du projet plutôt qu’une suite manuelle partielle.", "Laisse le build Web se terminer.", "Laisse cap sync copier assets et plugins.", "Laisse les scripts de configuration Android du projet s’exécuter.", "Contrôle la fin du script et les éventuels avertissements."],
    verify: ["Le projet Android contient le build Web récent et les plugins sont reconnus."],
    troubleshooting: ["Fonction Web récente absente sur Android : un cap sync manquant ou un mauvais build source est une cause fréquente."],
    warnings: ["Évite de modifier manuellement des fichiers générés si un script du projet les recrée."],
    related: ["Générer un AAB Android propre"],
  },
  {
    id: "v89-logcat-crash",
    domain: "android",
    title: "Diagnostiquer un crash Android avec Logcat",
    aliases: ["logcat crash", "voir erreur android", "diagnostiquer crash natif"],
    route: "settings",
    purpose: "Capturer la vraie exception au moment d’un crash au lieu de corriger à l’aveugle.",
    prerequisites: ["Téléphone connecté ou Android Studio ouvert.", "Build reproduisant le crash."],
    steps: ["Ouvre Logcat pour le processus de l’application.", "Efface ou marque le début du journal.", "Reproduis exactement le crash.", "Repère FATAL EXCEPTION, AndroidRuntime ou le nom du plugin concerné.", "Copie la stack trace pertinente avec quelques lignes avant/après.", "Relie la classe/méthode au fichier source avant de modifier quoi que ce soit."],
    verify: ["Tu disposes d’une exception précise et d’un point d’entrée identifiable."],
    troubleshooting: ["Trop de logs : filtre par package de l’application.", "Aucune exception Web : regarde aussi console WebView/Capacitor."],
    warnings: ["Masque tokens, emails et secrets avant de partager des logs."],
    related: ["Crash Android", "Stack trace"],
  },
  {
    id: "v89-anr-diagnostic",
    domain: "android",
    title: "Diagnostiquer un freeze ou ANR Android",
    aliases: ["anr android", "application ne repond pas", "freeze android", "ecran fige android"],
    route: "settings",
    purpose: "Identifier une tâche qui bloque trop longtemps l’interface Android/WebView.",
    prerequisites: ["Pouvoir reproduire le freeze."],
    steps: ["Note l’action exacte qui déclenche le freeze.", "Observe CPU/mémoire et Logcat pendant l’action.", "Vérifie si une opération lourde tourne sur le thread principal.", "Cherche gros décodage média, boucle JavaScript, transaction ou bridge natif synchrone.", "Mesure avant de modifier.", "Déplace ou fractionne le travail lourd selon la cause."],
    verify: ["L’action reste réactive et aucun ANR n’est généré."],
    troubleshooting: ["Freeze seulement après longue utilisation : cherche fuite mémoire.", "Freeze à l’ouverture d’un écran lourd : cherche chargement massif ou médias."],
    warnings: ["Ajouter des délais artificiels n’est pas une correction d’ANR."],
    related: ["Profiler", "Thread principal"],
  },
  {
    id: "v89-restore-purchases",
    domain: "billing",
    title: "Restaurer un achat ou droit Premium",
    aliases: ["restaurer achat", "premium disparu", "restore purchase"],
    route: "settings",
    purpose: "Récupérer les droits associés au compte Google sans racheter immédiatement.",
    prerequisites: ["Être connecté au même compte Google Play que lors de l’achat."],
    steps: ["Ouvre la section Compte/Boutique concernée.", "Utilise la fonction de restauration si elle est disponible.", "Laisse Google Play renvoyer les achats connus.", "Vérifie le statut du produit et du droit dans l’application.", "Si le droit n’est pas restauré, note le produit et le statut retourné."],
    verify: ["Le droit Premium redevient actif sans nouveau paiement."],
    troubleshooting: ["Achat absent : vérifie le compte Google utilisé.", "Achat pending/refunded : ne force pas le droit localement."],
    warnings: ["Ne rachète pas avant d’avoir vérifié l’historique Google Play."],
    related: ["Achat en attente", "Entitlement"],
  },
  {
    id: "v89-billing-locked",
    domain: "billing",
    title: "Diagnostiquer une fonction Premium encore verrouillée",
    aliases: ["premium verrouille", "achat reconnu mais fonction bloquee", "entitlement ne marche pas"],
    route: "settings",
    purpose: "Distinguer achat réel, transaction en attente et problème de synchronisation du droit.",
    prerequisites: ["Connaître le compte Google et le produit acheté."],
    steps: ["Vérifie l’achat dans Google Play.", "Vérifie s’il est terminé, pending, annulé ou remboursé.", "Lance la restauration des achats.", "Reconnecte le compte de l’application si le droit dépend aussi d’une session.", "Ferme/réouvre seulement l’écran concerné avant d’envisager des actions plus lourdes."],
    verify: ["Le statut d’entitlement correspond à la transaction Google Play."],
    troubleshooting: ["Achat payé mais non reconnu : récupère le message Billing exact et le Product ID."],
    warnings: ["Ne débloque pas manuellement une fonction payante dans les données locales."],
    related: ["Restaurer un achat ou droit Premium"],
  },
  {
    id: "v89-admob-no-fill",
    domain: "ads",
    title: "Diagnostiquer AdMob No Fill",
    aliases: ["admob no fill", "pub ne charge pas", "aucune annonce disponible"],
    route: "settings",
    purpose: "Comprendre une absence d’annonce sans confondre manque d’inventaire et bug d’intégration.",
    prerequisites: ["Connexion réseau.", "Configuration publicitaire active selon les réglages et consentements."],
    steps: ["Vérifie d’abord avec une unité publicitaire de test si tu es en développement.", "Lis le code/message d’erreur AdMob.", "Vérifie le consentement UMP.", "Vérifie l’Ad Unit ID réellement utilisé.", "Si le message est No Fill, reteste plus tard sans modifier l’intégration."],
    verify: ["Une annonce de test s’affiche et l’intégration fonctionne."],
    troubleshooting: ["Annonce test OK mais production No Fill : c’est souvent un problème d’inventaire/éligibilité, pas de code."],
    warnings: ["Ne clique jamais sur tes propres annonces de production."],
    related: ["UMP", "Ad Unit ID"],
  },
  {
    id: "v89-ad-consent",
    domain: "ads",
    title: "Comprendre et tester le consentement publicitaire",
    aliases: ["consentement pub", "ump consent", "rgpd pub"],
    route: "settings",
    purpose: "Vérifier que les publicités respectent le choix de consentement et que le SDK peut demander les annonces autorisées.",
    prerequisites: ["Écran Confidentialité/Consentement accessible."],
    steps: ["Ouvre les réglages de confidentialité/publicité.", "Affiche ou renouvelle le formulaire UMP si le parcours le permet.", "Effectue le choix utilisateur.", "Reviens dans la section Pub.", "Vérifie l’état de consentement et les diagnostics de chargement."],
    verify: ["Le statut de consentement est connu et cohérent avec la région/choix utilisateur."],
    troubleshooting: ["Formulaire absent : il peut ne pas être requis dans ce contexte ; regarde le statut UMP plutôt que de forcer son affichage."],
    warnings: ["Le consentement ne doit pas être simulé ou pré-coché à la place de l’utilisateur."],
    related: ["UMP", "Confidentialité"],
  },
  {
    id: "v89-app-ads-txt",
    domain: "ads",
    title: "Vérifier app-ads.txt",
    aliases: ["app ads txt", "verifier app-ads.txt", "admob domaine app ads"],
    route: "settings",
    purpose: "Confirmer que le domaine déclaré par la fiche store expose le fichier attendu par les réseaux publicitaires.",
    prerequisites: ["Domaine officiel de l’application configuré dans la fiche store si requis."],
    steps: ["Identifie le domaine officiel associé à l’application.", "Ouvre le fichier app-ads.txt à la racine du domaine.", "Vérifie la ligne correspondant à l’éditeur/réseau.", "Vérifie que la fiche Google Play référence le bon domaine.", "Laisse ensuite le temps aux robots de revérifier le fichier."],
    verify: ["AdMob ne signale plus un fichier absent/invalide après actualisation."],
    troubleshooting: ["Fichier correct mais statut ancien : attends la nouvelle vérification du réseau publicitaire."],
    warnings: ["N’ajoute pas de vendeurs que tu n’utilises pas."],
    related: ["AdMob No Fill"],
  },
  {
    id: "v89-verify-backup",
    domain: "data",
    title: "Vérifier qu’une sauvegarde est réellement exploitable",
    aliases: ["tester sauvegarde", "verifier backup", "backup valide"],
    route: "settings",
    purpose: "S’assurer qu’un fichier de sauvegarde existe, est lisible et correspond à la bonne version avant d’en avoir besoin.",
    prerequisites: ["Une sauvegarde a déjà été créée."],
    steps: ["Repère le fichier dans l’emplacement choisi.", "Vérifie sa date et sa taille.", "Utilise l’inspection de sauvegarde si l’application la propose.", "Vérifie le rapport : version, nombre d’éléments, éventuelles erreurs.", "Conserve au moins une copie sur un autre support si les données sont importantes."],
    verify: ["Le fichier est retrouvable et son inspection ne signale pas de format corrompu."],
    troubleshooting: ["Fichier de taille anormalement faible : recrée une sauvegarde.", "Version incompatible : utilise le parcours de migration/restauration prévu."],
    warnings: ["Ne teste pas une restauration destructrice sur l’unique copie de tes données."],
    related: ["Recovery", "Inspecter une sauvegarde avant restauration"],
  },
  {
    id: "v89-sync-conflict",
    domain: "data",
    title: "Résoudre un conflit de synchronisation",
    aliases: ["conflit sync", "deux appareils donnees differentes", "merge conflit"],
    route: "settings",
    purpose: "Éviter d’écraser silencieusement une version plus récente lorsqu’un même profil a évolué sur plusieurs appareils.",
    prerequisites: ["Identifier les deux appareils/sources concernés.", "Faire une sauvegarde des deux côtés si possible."],
    steps: ["Arrête les modifications simultanées le temps du diagnostic.", "Compare dates, nombre de parties et profil actif sur chaque appareil.", "Crée une sauvegarde de chaque état.", "Utilise l’outil de fusion/import prévu plutôt qu’un remplacement manuel aveugle.", "Lis le rapport de fusion/doublons.", "Vérifie Historique et profils après l’opération."],
    verify: ["Les données attendues sont présentes sans doublons évidents."],
    troubleshooting: ["Même match en double : vérifie les identifiants stables et la déduplication.", "Éléments manquants : reviens aux sauvegardes source au lieu de relancer plusieurs imports."],
    warnings: ["Ne choisis pas “écraser” sans avoir identifié quelle source est la plus complète."],
    related: ["Peer Sync", "Rapport d’import"],
  },
  {
    id: "v89-import-duplicates",
    domain: "data",
    title: "Diagnostiquer des doublons après import",
    aliases: ["doublons import", "parties en double", "profils dupliques import"],
    route: "settings",
    purpose: "Comprendre pourquoi un import a créé des éléments similaires au lieu de les fusionner.",
    prerequisites: ["Conserver le rapport d’import si disponible."],
    steps: ["Note quels objets sont dupliqués : profils, matchs ou équipes.", "Compare leurs identifiants et dates, pas seulement leurs noms.", "Vérifie si l’import venait d’une ancienne version de schéma.", "Utilise les outils de déduplication/merge prévus si disponibles.", "Contrôle ensuite Historique et statistiques."],
    verify: ["Chaque entité logique n’est comptée qu’une fois."],
    troubleshooting: ["Noms identiques mais IDs différents : ne supprime pas au hasard sans vérifier les parties liées."],
    warnings: ["Fais une sauvegarde avant toute suppression de doublons."],
    related: ["Import JSON local", "Clé de déduplication"],
  },
  {
    id: "v89-cloud-session-expired",
    domain: "data",
    title: "Réparer une session Cloud expirée",
    aliases: ["token expire cloud", "session supabase expiree", "401 cloud"],
    route: "settings",
    purpose: "Rétablir l’authentification cloud sans toucher aux données locales.",
    prerequisites: ["Connexion réseau.", "Compte en ligne existant."],
    steps: ["Observe le code d’erreur ; 401 indique souvent un problème d’authentification.", "Déconnecte/reconnecte proprement le compte si le refresh ne se fait pas.", "Relance ensuite uniquement l’opération Cloud.", "Vérifie que l’Historique local n’a pas été modifié par cette reconnexion."],
    verify: ["La requête cloud fonctionne avec une nouvelle session."],
    troubleshooting: ["403 après reconnexion : vérifie les droits/politiques plutôt qu’un mot de passe."],
    warnings: ["Ne copie pas un token brut dans un message public."],
    related: ["Session", "Token"],
  },
  {
    id: "v89-r2-backup-fail",
    domain: "data",
    title: "Diagnostiquer un backup R2 qui échoue",
    aliases: ["r2 backup erreur", "cloudflare r2 ne marche pas", "backup cloud echec"],
    route: "settings",
    purpose: "Isoler authentification, réseau, quota et format lors d’un échec de sauvegarde R2.",
    prerequisites: ["Fonction R2 disponible pour le plan/compte concerné."],
    steps: ["Vérifie le statut du compte et l’éligibilité de la fonction.", "Lance un backup manuel.", "Note le code HTTP ou message exact.", "Vérifie réseau et session.", "Si la requête atteint le service, vérifie bucket/clé/politique côté backend.", "Relance une fois après correction et vérifie que le fichier distant existe."],
    verify: ["La sauvegarde apparaît dans le stockage distant et peut être inspectée/restaurée."],
    troubleshooting: ["401/403 : authentification/droits.", "413 ou taille : vérifie compression/limites.", "5xx : évite de répéter en boucle et réessaie plus tard."],
    warnings: ["R2 ne doit pas être activé pour un utilisateur non éligible si cela génère des coûts inattendus."],
    related: ["Cloudflare R2", "Sauvegarde Recovery complète"],
  },
  {
    id: "v89-slow-profiles",
    domain: "performance",
    title: "Diagnostiquer des profils locaux lents",
    aliases: ["profils lents", "navigation profils lente", "avatars chargent lentement"],
    route: "profiles",
    purpose: "Identifier si la lenteur vient d’IndexedDB, des avatars, d’un re-render ou d’une réhydratation tardive.",
    prerequisites: ["Pouvoir reproduire la lenteur sur l’écran Profils."],
    steps: ["Chronomètre mentalement l’action exacte : ouverture, scroll, sélection ou image.", "Vérifie si les cartes apparaissent avant les avatars.", "Vérifie si les avatars disparaissent après réhydratation.", "Mesure les lectures IndexedDB et le nombre de renders si tu développes.", "Vérifie la taille/décodage des médias.", "Corrige cache et priorité de source avant d’ajouter des délais."],
    verify: ["La liste apparaît immédiatement ou progressivement sans bloquer la navigation."],
    troubleshooting: ["Images apparaissent puis disparaissent : suspecte un état tardif qui écrase le cache.", "Tout l’écran freeze : cherche tâche synchrone/lecture massive."],
    warnings: ["Ne supprime pas les profils pour tester une optimisation."],
    related: ["Réhydratation", "Cache"],
  },
  {
    id: "v89-slow-dartsets",
    domain: "performance",
    title: "Diagnostiquer un sélecteur de dartsets lent",
    aliases: ["dartsets lents", "selection flechettes lente", "images dartsets lentes"],
    route: "x01_config_v3",
    purpose: "Accélérer l’affichage des dartsets sans perdre les associations profil/set.",
    prerequisites: ["Dartsets existants avec images."],
    steps: ["Compare l’écran Profils et le sélecteur X01 pour le même dartset.", "Vérifie si les deux utilisent la même source/cache d’image.", "Vérifie le poids et le décodage des images.", "Évite de relire tous les médias à chaque render.", "Précharge ou mémorise les aperçus utiles.", "Reteste navigation et changement de joueur."],
    verify: ["Les miniatures apparaissent sans délai notable et restent stables."],
    troubleshooting: ["Visible dans Profils mais absent dans X01 : source ou clé d’association différente.", "Double apparition : vérifie déduplication par ID."],
    warnings: ["Ne change pas les IDs des dartsets lors d’une simple optimisation média."],
    related: ["Cache", "Profil actif"],
  },
  {
    id: "v89-avatar-disappears",
    domain: "performance",
    title: "Diagnostiquer un avatar qui apparaît puis disparaît",
    aliases: ["avatar disparait", "photo profil disparait", "image apparait puis disparait"],
    route: "profiles",
    purpose: "Trouver une réhydratation ou source d’image qui écrase une valeur valide après le premier rendu.",
    prerequisites: ["Un profil avec avatar reproduit le problème."],
    steps: ["Note si l’image apparaît immédiatement depuis cache puis disparaît après chargement.", "Compare les valeurs d’avatar avant/après réhydratation.", "Vérifie priorité entre Blob, URL, fallback et donnée héritée.", "Vérifie que l’effet de chargement n’écrit pas null sur une valeur déjà valide.", "Reteste après navigation aller-retour."],
    verify: ["L’avatar reste visible et cohérent sur tous les écrans."],
    troubleshooting: ["Seulement sur un écran : compare son sélecteur de données aux autres."],
    warnings: ["Ne supprime pas l’image source tant que tu n’as pas identifié l’écrasement."],
    related: ["Réhydratation", "Object URL"],
  },
  {
    id: "v89-double-input",
    domain: "performance",
    title: "Diagnostiquer une double saisie sur interface lente",
    aliases: ["double saisie x01", "clic enregistre deux fois", "score double clic"],
    route: "x01_play_v3",
    purpose: "Empêcher qu’une action utilisateur unique crée deux événements de score.",
    prerequisites: ["Pouvoir reproduire le retard de feedback."],
    steps: ["Observe si le premier clic est enregistré mais affiché tard.", "Vérifie si le bouton reste actif pendant l’écriture.", "Vérifie handlers dupliqués ou événement tactile + clic.", "Ajoute une protection idempotente ou verrou court autour de l’action réellement critique.", "Rends le feedback visuel immédiat.", "Teste Undo et statistiques après correction."],
    verify: ["Un clic produit exactement une saisie, même sous charge."],
    troubleshooting: ["Deux handlers appelés : corrige la source plutôt qu’un délai.", "Une seule écriture mais double affichage : problème de rendu/merge."],
    warnings: ["Un debounce trop long rendrait le scoring désagréable."],
    related: ["Idempotence", "Double saisie"],
  },
  {
    id: "v89-big-app-size",
    domain: "performance",
    title: "Réduire la taille de l’application sans supprimer de fonctions",
    aliases: ["application trop lourde", "reduire taille app", "350 mo app", "optimiser assets"],
    route: "settings",
    purpose: "Réduire poids installable/téléchargé en optimisant médias et bundle tout en conservant les fonctions.",
    prerequisites: ["Copie de sauvegarde du projet.", "Inventaire des assets lourds."],
    steps: ["Mesure les plus gros fichiers du projet.", "Sépare images, audio, vidéo et bundle JS.", "Convertis les images compatibles vers un format plus efficace et mets à jour toutes leurs références.", "Réencode audio/vidéo uniquement après test qualité.", "Supprime uniquement les doublons réellement inutilisés, pas des fonctions.", "Active lazy loading/code splitting pour les gros modules non critiques.", "Reconstruis et compare taille avant/après.", "Teste les écrans qui utilisent chaque asset modifié."],
    verify: ["Le build est plus léger et tous les médias se chargent encore aux bons endroits."],
    troubleshooting: ["Image manquante après conversion : une référence d’extension n’a pas été mise à jour.", "Build peu réduit : les vidéos/audio dominent peut-être la taille."],
    warnings: ["Ne supprime jamais un asset parce qu’il semble inutilisé sans rechercher ses références dynamiques."],
    related: ["Compression d’assets", "Code splitting"],
  },
  {
    id: "v89-cast-lan-advanced",
    domain: "network",
    title: "Diagnostiquer Cast sur un réseau local compliqué",
    aliases: ["cast reseau local", "chromecast meme wifi mais invisible", "mdns cast"],
    route: "cast_host",
    purpose: "Comprendre les cas où les appareils ont Internet mais ne se découvrent pas en local.",
    prerequisites: ["Téléphone et appareil Cast allumés."],
    steps: ["Vérifie que les deux sont sur le même SSID/réseau logique.", "Évite un réseau invité qui isole les clients.", "Vérifie que le Wi-Fi n’active pas isolation AP/client.", "Vérifie mDNS/multicast si le routeur propose ces réglages.", "Désactive temporairement VPN sur le téléphone pour tester.", "Relance la découverte Cast."],
    verify: ["L’appareil Cast apparaît dans le sélecteur et accepte la session."],
    troubleshooting: ["Internet fonctionne mais Cast invisible : suspecte isolation LAN/mDNS.", "Visible sur une autre app mais pas ici : vérifie initialisation SDK/session."],
    warnings: ["Ne modifie pas le routeur sans noter les réglages actuels."],
    related: ["mDNS", "Découverte réseau"],
  },
  {
    id: "v89-viewer-reconnect",
    domain: "network",
    title: "Récupérer un Viewer après une coupure réseau",
    aliases: ["viewer reconnexion", "viewer perd connexion", "tablette se reconnecte pas"],
    route: "viewer_display",
    purpose: "Restaurer le flux live après perte Wi-Fi sans recréer inutilement toutes les données de partie.",
    prerequisites: ["Session Viewer encore valide ou recréable."],
    steps: ["Vérifie que la tablette a retrouvé Internet/réseau.", "Observe l’état connecté/hors ligne du Viewer.", "Attends une tentative de reconnexion automatique si prévue.", "Si la session a expiré, recrée seulement la session Viewer depuis l’hôte.", "Rouvre le lien/code sur la tablette.", "Vérifie qu’un nouveau snapshot arrive."],
    verify: ["Le score courant se réaffiche et recommence à évoluer."],
    troubleshooting: ["Score ancien après reconnexion : vérifie que l’hôte publie un snapshot récent.", "Code refusé : la session a probablement expiré."],
    warnings: ["Ne restaure pas une sauvegarde de partie pour réparer une simple session Viewer."],
    related: ["Créer un Viewer tablette", "Heartbeat"],
  },
  {
    id: "v89-phone-camera-network",
    domain: "network",
    title: "Diagnostiquer le téléphone compagnon caméra",
    aliases: ["telephone compagnon ne se connecte pas", "camera second telephone hors ligne", "qr camera ne marche pas"],
    route: "x01_device_camera",
    purpose: "Rétablir la liaison entre l’appareil de scoring et le téléphone qui filme la cible.",
    prerequisites: ["Deux appareils disponibles.", "Permissions caméra accordées sur le téléphone compagnon."],
    steps: ["Vérifie que les deux appareils ont accès au réseau requis par le parcours.", "Recrée le QR/code de liaison si la session a expiré.", "Sur le téléphone compagnon, vérifie la permission caméra.", "Vérifie que le flux vidéo démarre avant la calibration.", "Reviens sur l’appareil principal et confirme que les frames/événements arrivent.", "Relance la calibration si le cadrage a changé."],
    verify: ["L’appareil principal reçoit le flux ou les événements de détection."],
    troubleshooting: ["Caméra noire : permission ou caméra occupée par une autre app.", "Session liée mais pas de données : vérifie réseau et état de publication."],
    warnings: ["N’utilise pas un flux instable pour valider automatiquement un score sans fallback manuel."],
    related: ["Téléphone compagnon", "Calibration caméra"],
  },
  {
    id: "v89-stats-discrepancy",
    domain: "stats",
    title: "Diagnostiquer deux statistiques qui ne correspondent pas",
    aliases: ["stats differentes", "moyenne differente entre ecrans", "home stats vs hub"],
    route: "stats",
    purpose: "Déterminer si l’écart vient des filtres, du périmètre ou d’un calcul réellement incohérent.",
    prerequisites: ["Identifier les deux écrans comparés."],
    steps: ["Note le même joueur, mode et période sur les deux écrans.", "Vérifie filtres actifs et nombre de matchs inclus.", "Vérifie si un écran calcule par leg et l’autre par match.", "Compare la donnée source dans Historique.", "Recalcule manuellement un petit exemple si nécessaire.", "Corrige le calcul ou le libellé seulement après avoir identifié la différence de définition."],
    verify: ["À périmètre identique, les deux écrans donnent la même valeur ou expliquent clairement une définition différente."],
    troubleshooting: ["Écart uniquement sur les anciennes parties : données historiques moins détaillées.", "Écart après filtre : état de filtre non synchronisé."],
    warnings: ["Ne remplace pas des données historiques pour faire “coller” un affichage."],
    related: ["Source de vérité", "AVG3"],
  },
  {
    id: "v89-stats-empty-deep",
    domain: "stats",
    title: "Diagnostiquer des statistiques vides malgré des parties",
    aliases: ["stats vides avec historique", "aucune statistique pourtant parties", "dashboard vide"],
    route: "stats",
    purpose: "Identifier pourquoi des matchs existent mais ne sont pas inclus ou calculables.",
    prerequisites: ["Au moins une partie visible dans Historique."],
    steps: ["Vérifie le profil/joueur sélectionné.", "Vérifie le mode et la période du filtre.", "Vérifie que les parties ont bien un statut terminé/enregistré attendu par les stats.", "Vérifie les identifiants de joueur liés aux matchs.", "Vérifie si le mode ancien enregistrait les métriques nécessaires.", "Réinitialise seulement les filtres d’affichage, pas les données."],
    verify: ["Les matchs éligibles apparaissent dans les agrégats."],
    troubleshooting: ["Historique visible mais aucune métrique détaillée : le mode/version peut ne pas avoir stocké assez de détails."],
    warnings: ["Ne recrée pas de fausses statistiques à partir d’informations absentes."],
    related: ["Historique", "Filtre statistique"],
  },
  {
    id: "v89-x01-advanced-config",
    domain: "x01",
    title: "Configurer un X01 avancé sans se tromper",
    aliases: ["x01 configuration avancee", "reglages x01 expert", "config complete x01"],
    route: "x01_config_v3",
    purpose: "Passer en revue les réglages qui changent réellement les règles et le déroulement du match.",
    prerequisites: ["Joueurs ou équipes sélectionnables."],
    steps: ["Choisis joueurs/équipes.", "Choisis 301/501/701/901.", "Choisis IN : simple, double ou master selon le match.", "Choisis OUT : simple, double ou master.", "Choisis legs/sets et la logique Best Of ou First To.", "Choisis l’ordre de départ.", "Choisis la méthode de saisie : keypad, cible, presets, voix ou source externe selon les options disponibles.", "Relis le résumé avant de lancer."],
    verify: ["Le résumé correspond exactement au format voulu."],
    troubleshooting: ["Partie démarre avec mauvaises règles : vérifie preset et paramètres visibles avant Start."],
    warnings: ["Les règles actives de cette partie priment sur une règle “habituelle” différente."],
    related: ["Configuration guidée", "Best Of"],
  },
  {
    id: "v89-x01-bust",
    domain: "x01",
    title: "Comprendre et corriger un bust X01",
    aliases: ["bust x01", "score bust", "pourquoi ma volee est annulee"],
    route: "x01_play_v3",
    purpose: "Comprendre pourquoi une volée ne compte pas en fin de leg selon la règle OUT.",
    prerequisites: ["Partie X01 en cours."],
    steps: ["Relève le score avant la volée.", "Relève les fléchettes jouées dans l’ordre.", "Vérifie la règle OUT active.", "Identifie la fléchette qui a rendu la sortie invalide ou le score impossible.", "Confirme que l’application restaure le score au début de la volée selon la règle appliquée.", "Utilise Undo uniquement si la saisie elle-même était erronée."],
    verify: ["Le score après bust correspond au score de début de volée."],
    troubleshooting: ["Double Out : finir sur un simple n’est pas une sortie valide.", "Score négatif ou reste 1 en Double Out : la volée est bust."],
    warnings: ["Ne corrige pas un bust valide avec un faux score manuel."],
    related: ["Checkout phase", "Undo"],
  },
  {
    id: "v89-x01-external-scoring",
    domain: "x01",
    title: "Passer d’un scoring externe au manuel sans casser la partie",
    aliases: ["scolia tombe en partie", "bridge perdu x01", "revenir keypad en match"],
    route: "x01_play_v3",
    purpose: "Continuer une partie quand la source externe de scoring devient indisponible.",
    prerequisites: ["Partie active et score courant visible."],
    steps: ["Note le score courant et le joueur actif.", "Désactive ou déconnecte la source externe si elle envoie des événements erratiques.", "Passe au mode de saisie manuelle prévu par l’interface.", "Saisis uniquement les fléchettes non encore enregistrées.", "Vérifie score, joueur actif et historique de volée.", "Rebranche la source externe seulement quand elle est stable."],
    verify: ["La partie continue sans doublon de volée."],
    troubleshooting: ["Événements externes arrivent encore : coupe réellement la source avant saisie manuelle."],
    warnings: ["Ne rejoue pas une volée déjà enregistrée par l’appareil externe."],
    related: ["Fallback manuel", "Scolia"],
  },
  {
    id: "v89-tournament-correct-result",
    domain: "competition",
    title: "Corriger un résultat de tournoi sans casser le tableau",
    aliases: ["corriger resultat tournoi", "mauvais vainqueur tournoi", "modifier score bracket"],
    route: "tournament_view",
    purpose: "Corriger une saisie erronée en tenant compte des matchs suivants déjà générés.",
    prerequisites: ["Identifier le match erroné et savoir si le tour suivant a déjà commencé."],
    steps: ["Ouvre le tournoi et localise le match erroné.", "Vérifie si son vainqueur a déjà été propagé au tour suivant.", "Si l’application propose une correction, utilise ce parcours plutôt qu’une modification de données brute.", "Corrige score/vainqueur.", "Vérifie les participants des matchs dépendants.", "Si un match suivant a déjà été joué, traite le conflit explicitement avant de poursuivre."],
    verify: ["Le bracket et le classement reflètent le résultat corrigé."],
    troubleshooting: ["Le tour suivant contient encore l’ancien vainqueur : la propagation doit être recalculée."],
    warnings: ["Fais une sauvegarde avant une correction tardive dans un tournoi important."],
    related: ["Élimination directe", "Tableau à élimination"],
  },
  {
    id: "v89-tournament-forfeit",
    domain: "competition",
    title: "Enregistrer un forfait proprement",
    aliases: ["forfait tournoi", "joueur absent competition", "walkover tournoi"],
    route: "tournament_view",
    purpose: "Faire avancer la compétition sans inventer un faux score si le format prévoit un forfait.",
    prerequisites: ["Connaître la règle de forfait du tournoi."],
    steps: ["Ouvre le match concerné.", "Utilise l’option forfait/WO si elle existe.", "Sélectionne le participant qui avance.", "Ajoute éventuellement la raison si le système le permet.", "Vérifie le bracket et le classement."],
    verify: ["Le vainqueur avance sans statistiques de jeu fictives."],
    troubleshooting: ["Aucune fonction forfait dédiée : n’invente pas un score sans connaître la convention prévue."],
    warnings: ["Distingue forfait et victoire réellement jouée dans les statistiques."],
    related: ["Forfait", "Tableau à élimination"],
  },
  {
    id: "v89-language-reset",
    domain: "settings",
    title: "Diagnostiquer une langue qui revient toute seule",
    aliases: ["langue revient francais", "anglais repasse francais", "langue se reinitialise"],
    route: "settings",
    purpose: "Trouver quel stockage ou profil réécrit la langue après navigation.",
    prerequisites: ["Pouvoir reproduire le retour de langue."],
    steps: ["Change la langue dans Settings.", "Vérifie immédiatement la préférence du profil actif.", "Navigue vers l’écran qui déclenche le retour.", "Vérifie si cet écran recharge les préférences du profil.", "Assure-toi que Settings et Mon Profil écrivent la même source de vérité.", "Reteste après redémarrage."],
    verify: ["La langue reste identique sur navigation et redémarrage."],
    troubleshooting: ["Retour au clic Profils : suspecte une préférence profil qui écrase la préférence globale."],
    warnings: ["Ne duplique pas deux sources de langue sans règle de priorité claire."],
    related: ["Profil actif", "Persistance"],
  },
  {
    id: "v89-theme-reset",
    domain: "settings",
    title: "Diagnostiquer un thème qui se réinitialise",
    aliases: ["theme revient par defaut", "theme change tout seul"],
    route: "settings",
    purpose: "Aligner préférence globale, profil actif et thème réellement appliqué.",
    prerequisites: ["Un thème personnalisé sélectionné."],
    steps: ["Sélectionne le thème.", "Vérifie que la préférence est enregistrée.", "Vérifie la préférence du profil actif.", "Navigue vers l’écran déclencheur.", "Repère si un chargement profil réapplique une ancienne valeur.", "Corrige la priorité de source puis reteste le démarrage."],
    verify: ["Le thème reste sélectionné sur tous les écrans et après relance."],
    troubleshooting: ["Un seul écran ignore le thème : ce composant peut utiliser des valeurs codées en dur."],
    warnings: ["Un pack premium doit aussi respecter son état d’achat/activation."],
    related: ["Profil actif", "Thème ou pack premium"],
  },
  {
    id: "v89-safe-update",
    domain: "data",
    title: "Mettre l’application à jour sans risquer ses données",
    aliases: ["mettre a jour sans perdre donnees", "update android securisee", "avant mise a jour app"],
    route: "settings",
    purpose: "Réduire le risque avant une mise à jour Android ou une grosse migration.",
    prerequisites: ["Version actuelle encore accessible."],
    steps: ["Crée une sauvegarde Recovery complète.", "Vérifie que le fichier est retrouvable et inspectable.", "Note la version actuelle.", "Installe la mise à jour par Google Play sans désinstaller l’application.", "Ouvre l’application et laisse les éventuelles migrations se terminer.", "Vérifie profils, Historique et Settings.", "Ne supprime l’ancienne sauvegarde qu’après validation."],
    verify: ["Les données et la nouvelle version sont toutes deux présentes."],
    troubleshooting: ["Données absentes après mise à jour : n’écris pas massivement de nouvelles données avant diagnostic/restauration."],
    warnings: ["Désinstaller avant une mise à jour peut supprimer le stockage local."],
    related: ["Sauvegarde Recovery complète", "Google Play Console"],
  },
  {
    id: "v89-device-change",
    domain: "data",
    title: "Migrer vers un nouveau téléphone proprement",
    aliases: ["changer telephone migration", "nouveau mobile conserver donnees", "transferer app nouveau telephone"],
    route: "settings",
    purpose: "Transférer les données sans supposer qu’une simple connexion de compte restaure tout le stockage local.",
    prerequisites: ["Ancien téléphone encore disponible si possible.", "Nouvelle installation de l’application."],
    steps: ["Sur l’ancien téléphone, crée une sauvegarde Recovery complète.", "Vérifie-la.", "Installe la même ou une version compatible de l’application sur le nouveau téléphone.", "Connecte le compte si nécessaire.", "Importe/restaure via le parcours prévu.", "Vérifie profils, Historique, dartsets et préférences.", "Garde l’ancien appareil intact jusqu’à validation."],
    verify: ["Le nouveau téléphone contient les données attendues et les statistiques se reconstruisent."],
    troubleshooting: ["Connexion seule mais données absentes : elles étaient probablement locales et nécessitent un transfert."],
    warnings: ["Ne réinitialise pas l’ancien appareil avant contrôle du nouveau."],
    related: ["Recovery", "Peer Sync"],
  },
  {
    id: "v89-bug-report",
    domain: "dev",
    title: "Préparer un rapport de bug vraiment exploitable",
    aliases: ["faire rapport bug", "comment signaler bug", "bug reproductible"],
    route: "settings",
    purpose: "Fournir assez d’éléments pour corriger rapidement un problème sans deviner.",
    prerequisites: ["Pouvoir reproduire le problème au moins une fois."],
    steps: ["Note la version exacte de l’application et le modèle/appareil.", "Décris le chemin depuis l’écran de départ.", "Liste les actions une par une.", "Indique ce qui était attendu.", "Indique ce qui s’est réellement produit.", "Ajoute capture/vidéo si le bug est visuel.", "Ajoute message exact/logs si crash.", "Précise si le bug est systématique ou intermittent."],
    verify: ["Une autre personne peut reproduire le problème avec ton rapport."],
    troubleshooting: ["Bug intermittent : note l’état précédent, réseau, profil actif et durée d’utilisation."],
    warnings: ["Masque données personnelles et tokens dans les captures/logs."],
    related: ["Cas minimal reproductible", "Logs de diagnostic"],
  },
];
export function awenaProceduralV89Count() { return AWENA_V89_PROCEDURES.length; }
export function awenaProceduralV89StepCount() { return AWENA_V89_PROCEDURES.reduce((s,e)=>s+e.steps.length,0); }
