import type { AwenaReply, AwenaRuntimeContext } from "./awena.types";

type GuideProEntry = { id: string; domain: string; title: string; aliases: string[]; simple: string; deep: string; practical: string; pitfalls: string; };

const STOP = new Set(["a","au","aux","avec","ce","ces","cette","de","des","du","dans","et","est","en","je","la","le","les","ma","mes","mon","ne","nous","on","ou","pour","que","quel","quelle","quels","quelles","qui","quoi","se","son","sur","ta","te","tes","ton","tu","un","une","vos","votre","comment","pourquoi","faire","sert","signifie","veut","dire","fonctionne","explique","expliquer","moi","application","appli","awena"]);
function norm(value: string) { return String(value || "").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[’']/g, " ").replace(/[_/\\.-]+/g, " ").replace(/[^a-z0-9+%\s]/g, " ").replace(/\s+/g, " ").trim(); }
function tokens(value: string) { return norm(value).split(" ").filter((t) => t.length > 1 && !STOP.has(t)); }

const ENTRIES: GuideProEntry[] = [
  {
    id: "app-route",
    domain: "app",
    title: "Route",
    aliases: ["route application", "route ecran", "navigation interne"],
    simple: "Une route est l’identifiant interne d’un écran de l’application.",
    deep: "Elle permet au routeur d’afficher le bon composant et à Awéna de savoir où se trouve l’utilisateur. Une route n’est pas forcément une URL publique.",
    practical: "Quand tu me demandes « où suis-je ? », je peux utiliser la route courante pour contextualiser mon aide.",
    pitfalls: "Ne change pas une route technique au hasard : un mauvais identifiant peut ouvrir le mauvais écran.",
  },
  {
    id: "app-screen",
    domain: "app",
    title: "Écran",
    aliases: ["ecran", "page application"],
    simple: "Un écran est une vue fonctionnelle affichée dans l’application.",
    deep: "Un même écran peut contenir plusieurs cartes, onglets, contrôles et états. Awéna peut utiliser le contexte de l’écran pour expliquer ce qui est visible.",
    practical: "Demande « que puis-je faire ici ? » pour une aide liée à l’écran actuel.",
    pitfalls: "Ne confonds pas écran et mode de jeu : plusieurs écrans peuvent appartenir au même mode.",
  },
  {
    id: "app-card",
    domain: "app",
    title: "Carte UI",
    aliases: ["carte interface", "bloc carte"],
    simple: "Une carte est un bloc visuel qui regroupe une fonction ou une information.",
    deep: "Les cartes servent à segmenter une page : réglage, KPI, sélection, aperçu, publicité ou aide.",
    practical: "Si une page est chargée, cherche d’abord la carte correspondant à ton objectif.",
    pitfalls: "Une carte décorative n’est pas forcément cliquable.",
  },
  {
    id: "app-tab",
    domain: "app",
    title: "Onglet",
    aliases: ["onglet", "tab interface"],
    simple: "Un onglet change de sous-section sans quitter forcément la page.",
    deep: "Il permet de répartir une fonction complexe en vues : dashboard, historique, équipes, records, diagnostics, etc.",
    practical: "Vérifie l’onglet actif avant de conclure qu’une donnée manque.",
    pitfalls: "Un filtre dans un onglet peut rester actif et masquer des données.",
  },
  {
    id: "app-ticker",
    domain: "app",
    title: "Ticker",
    aliases: ["ticker application", "bandeau jeu"],
    simple: "Un ticker est un bandeau visuel de titre, état ou ambiance associé à un mode ou une section.",
    deep: "Dans MULTISPORTS SCORING il sert souvent d’identité visuelle et peut aussi signaler un état de jeu.",
    practical: "Utilise le ticker comme repère pour vérifier que tu es dans le bon mode.",
    pitfalls: "Le ticker n’est pas toujours un bouton.",
  },
  {
    id: "app-bottomnav",
    domain: "app",
    title: "BottomNav",
    aliases: ["barre navigation bas", "bottom nav"],
    simple: "La BottomNav est la barre de navigation principale placée en bas.",
    deep: "Elle donne accès aux grandes sections comme Jeux, Profils, Online, Stats et Settings selon la configuration actuelle.",
    practical: "Si tu es perdu, reviens à une section principale par la BottomNav.",
    pitfalls: "Une partie active peut volontairement limiter ou masquer certains accès.",
  },
  {
    id: "app-infodot",
    domain: "app",
    title: "InfoDot",
    aliases: ["info dot", "bouton info", "icone information"],
    simple: "InfoDot est l’aide contextuelle historique d’un écran.",
    deep: "Awéna peut reprendre ce contenu et, sur les écrans complexes, remplacer ou enrichir l’aide statique par un tutoriel conversationnel.",
    practical: "Appuie sur l’aide/Awéna lorsque tu ne comprends pas une option précise.",
    pitfalls: "L’aide explique l’écran ; elle ne modifie pas automatiquement tes données.",
  },
  {
    id: "app-backdot",
    domain: "app",
    title: "BackDot",
    aliases: ["backdot", "bouton retour"],
    simple: "BackDot est un contrôle de retour contextuel.",
    deep: "Il doit revenir à l’écran précédent prévu par le parcours plutôt qu’envoyer arbitrairement vers l’accueil.",
    practical: "Utilise-le pour sortir d’un sous-écran sans perdre le fil du parcours.",
    pitfalls: "Dans une configuration non enregistrée, vérifie si revenir en arrière conserve ou abandonne les choix.",
  },
  {
    id: "app-active-profile",
    domain: "app",
    title: "Profil actif",
    aliases: ["profil actif", "mon profil actif"],
    simple: "Le profil actif est l’identité locale principale utilisée pour les préférences et certaines statistiques.",
    deep: "Il est différent du joueur actuellement sélectionné dans une partie : une partie peut contenir plusieurs profils alors qu’un seul profil est actif dans l’application.",
    practical: "Si langue, thème ou préférences semblent revenir, vérifie le profil actif.",
    pitfalls: "Ne confonds pas compte en ligne, profil actif et joueur actif.",
  },
  {
    id: "app-active-player",
    domain: "app",
    title: "Joueur actif",
    aliases: ["joueur actif", "tour joueur"],
    simple: "Le joueur actif est celui dont c’est le tour dans une partie.",
    deep: "L’écran de jeu doit mettre en évidence ce joueur afin d’éviter d’attribuer une saisie au mauvais participant.",
    practical: "Avant chaque saisie, vérifie nom/avatar et indicateur de tour.",
    pitfalls: "Si l’interface est lente, ne double-clique pas : tu risques d’enregistrer deux actions.",
  },
  {
    id: "app-preset",
    domain: "app",
    title: "Preset",
    aliases: ["preset", "preconfiguration", "préconfiguration"],
    simple: "Un preset est un ensemble de réglages préenregistrés.",
    deep: "Il accélère une configuration répétitive en appliquant plusieurs options d’un coup.",
    practical: "Après application, relis le résumé pour vérifier qu’il correspond au match voulu.",
    pitfalls: "Un preset peut écraser une valeur que tu viens de choisir manuellement.",
  },
  {
    id: "app-mode-phase",
    domain: "app",
    title: "Phase de mode",
    aliases: ["phase config play summary", "menu config play"],
    simple: "Un mode passe généralement par menu, configuration, jeu puis résumé/fin.",
    deep: "Cette séparation permet à Awéna de donner une aide différente selon le moment : régler avant la partie, jouer pendant, analyser après.",
    practical: "Si une question concerne un réglage, pose-la de préférence sur l’écran de configuration.",
    pitfalls: "Une option de configuration n’est pas forcément modifiable pendant le jeu.",
  },
  {
    id: "app-source-truth",
    domain: "app",
    title: "Source de vérité",
    aliases: ["source de verite", "source vérité", "historique source"],
    simple: "La source de vérité est l’endroit de référence lorsqu’une même information existe sous plusieurs formes.",
    deep: "Pour les résultats et statistiques, l’Historique persistant doit être privilégié par rapport à un cache d’affichage temporaire.",
    practical: "En cas d’écart entre deux écrans de stats, vérifie d’abord la donnée enregistrée dans l’Historique.",
    pitfalls: "Un cache rapide peut être obsolète sans que la donnée durable soit perdue.",
  },
  {
    id: "app-cache",
    domain: "app",
    title: "Cache",
    aliases: ["cache application", "cache local"],
    simple: "Un cache est une copie optimisée destinée à accélérer l’affichage.",
    deep: "Il peut stocker des avatars, médias ou calculs déjà préparés afin d’éviter de relire/recalculer à chaque navigation.",
    practical: "Si un avatar réapparaît après rechargement, le problème peut venir du cache/rehydrate plutôt que du fichier source.",
    pitfalls: "Effacer un cache n’est pas la même chose qu’effacer l’Historique ou les profils.",
  },
  {
    id: "app-rehydration",
    domain: "app",
    title: "Réhydratation",
    aliases: ["rehydrate", "rehydratation profil", "chargement stockage"],
    simple: "La réhydratation recharge l’état persistant dans l’application au démarrage ou à l’ouverture d’un écran.",
    deep: "Elle permet à l’interface React de reconstruire profils, préférences ou caches depuis IndexedDB/local storage.",
    practical: "Quand une donnée apparaît puis disparaît, une réhydratation tardive ou un état qui écrase l’autre peut être en cause.",
    pitfalls: "Ne corrige pas ce type de problème en supprimant les données utilisateur sans diagnostic.",
  },
  {
    id: "security-account-profile",
    domain: "security",
    title: "Compte vs profil",
    aliases: ["compte vs profil", "difference compte profil"],
    simple: "Le compte identifie l’utilisateur en ligne ; le profil représente un joueur dans l’application.",
    deep: "Un même compte peut gérer plusieurs profils locaux de joueurs, chacun avec avatar, dartset et statistiques selon les fonctions disponibles.",
    practical: "Pour changer de joueur, passe par Profils ; pour connexion/email, passe par Compte.",
    pitfalls: "Supprimer un profil ne doit pas être confondu avec supprimer le compte.",
  },
  {
    id: "security-login",
    domain: "security",
    title: "Connexion",
    aliases: ["connexion compte", "login"],
    simple: "La connexion ouvre une session avec les identifiants du compte.",
    deep: "Elle peut être nécessaire aux fonctions cloud/online, mais une partie des données et usages restent locaux selon l’architecture de l’app.",
    practical: "Vérifie email, mot de passe, réseau et confirmation du compte en cas d’échec.",
    pitfalls: "Évite de créer un nouveau compte uniquement parce que le mot de passe est oublié.",
  },
  {
    id: "security-signup",
    domain: "security",
    title: "Création de compte",
    aliases: ["creer compte", "inscription", "signup"],
    simple: "La création de compte enregistre une nouvelle identité en ligne.",
    deep: "Elle peut demander email, mot de passe et éventuellement code d’invitation selon le parcours actuel.",
    practical: "Utilise une adresse email accessible pour pouvoir confirmer ou récupérer le compte.",
    pitfalls: "Ne réutilise pas un code d’invitation destiné à quelqu’un d’autre.",
  },
  {
    id: "security-email-confirm",
    domain: "security",
    title: "Confirmation email",
    aliases: ["confirmation email", "email confirmation"],
    simple: "La confirmation email prouve que l’adresse utilisée appartient à l’utilisateur.",
    deep: "Elle sécurise la création de compte et peut conditionner certaines connexions.",
    practical: "Si le mail n’arrive pas, vérifie spam puis utilise le renvoi prévu par l’écran.",
    pitfalls: "Ne clique pas sur des liens de confirmation provenant d’un expéditeur inattendu.",
  },
  {
    id: "security-forgot",
    domain: "security",
    title: "Mot de passe oublié",
    aliases: ["mot de passe oublie", "forgot password"],
    simple: "Le parcours Mot de passe oublié permet de demander un lien de récupération.",
    deep: "Il évite de deviner le mot de passe et protège mieux le compte.",
    practical: "Demande le lien puis ouvre-le sur l’appareil prévu par le parcours.",
    pitfalls: "Un ancien lien peut expirer ; redemande-en un plutôt que d’insister.",
  },
  {
    id: "security-reset",
    domain: "security",
    title: "Réinitialisation du mot de passe",
    aliases: ["reset password", "reinitialiser mot de passe"],
    simple: "La réinitialisation remplace l’ancien mot de passe après validation du lien de récupération.",
    deep: "Elle doit être distinguée de la simple connexion ou d’un changement de préférence locale.",
    practical: "Choisis un mot de passe nouveau puis reconnecte-toi si la session n’est pas reprise automatiquement.",
    pitfalls: "Ne communique jamais le lien de reset ou le nouveau mot de passe.",
  },
  {
    id: "security-session",
    domain: "security",
    title: "Session",
    aliases: ["session utilisateur", "session compte"],
    simple: "Une session est l’état authentifié temporaire qui prouve que l’utilisateur est connecté.",
    deep: "Elle peut expirer, être rafraîchie ou être fermée par déconnexion.",
    practical: "Si Online/Cloud refuse une action, vérifie d’abord que la session est toujours valide.",
    pitfalls: "Une session perdue ne signifie pas que les données locales ont disparu.",
  },
  {
    id: "security-token",
    domain: "security",
    title: "Jeton / token",
    aliases: ["token", "jeton authentification"],
    simple: "Un token est une preuve technique temporaire utilisée par une API pour autoriser une requête.",
    deep: "Il évite d’envoyer le mot de passe à chaque opération et possède souvent une durée de vie limitée.",
    practical: "Quand un diagnostic cloud parle de token expiré, reconnecte le compte plutôt que de modifier les données locales.",
    pitfalls: "Un token est sensible : ne le copie pas dans un message public.",
  },
  {
    id: "security-invitation",
    domain: "security",
    title: "Code d’invitation",
    aliases: ["code invitation", "invitation privee"],
    simple: "Un code d’invitation peut limiter l’accès à une phase privée ou à un groupe.",
    deep: "Il est vérifié lors du parcours prévu et n’est pas un mot de passe utilisateur.",
    practical: "Saisis-le exactement comme fourni.",
    pitfalls: "Ne publie pas un code privé si son but est de restreindre l’accès.",
  },
  {
    id: "security-permission",
    domain: "security",
    title: "Permission Android",
    aliases: ["permission android", "autorisation application"],
    simple: "Une permission autorise l’application à utiliser une ressource sensible comme micro, caméra ou Bluetooth.",
    deep: "Android peut mémoriser un refus ; l’application doit alors redemander quand c’est possible ou guider vers Réglages système.",
    practical: "Accorde uniquement la permission nécessaire à la fonction que tu veux utiliser.",
    pitfalls: "Refuser une permission peut désactiver la fonction sans casser le reste de l’application.",
  },
  {
    id: "security-privacy",
    domain: "security",
    title: "Confidentialité",
    aliases: ["confidentialite", "vie privee"],
    simple: "La confidentialité regroupe les choix liés aux données, services externes et consentements.",
    deep: "Elle doit permettre de comprendre ce qui reste local et ce qui part vers un service cloud/online/publicitaire.",
    practical: "Consulte la carte Confidentialité si tu veux revoir les options.",
    pitfalls: "Ne confonds pas consentement publicitaire et autorisation de compte/cloud.",
  },
  {
    id: "security-consent",
    domain: "security",
    title: "Consentement",
    aliases: ["consentement", "ump consent"],
    simple: "Le consentement publicitaire exprime les choix de l’utilisateur pour les traitements liés aux annonces lorsque requis.",
    deep: "UMP est une couche dédiée au recueil/gestion de ce consentement dans l’écosystème Google Mobile Ads.",
    practical: "Tu peux revoir le choix depuis l’interface prévue si elle est disponible.",
    pitfalls: "Le consentement n’est pas une garantie qu’une annonce sera toujours affichée.",
  },
  {
    id: "data-indexeddb",
    domain: "data",
    title: "IndexedDB",
    aliases: ["indexeddb", "base locale navigateur"],
    simple: "IndexedDB est une base de données locale du navigateur/WebView.",
    deep: "Elle convient aux données structurées plus volumineuses que de simples préférences : historique, profils, médias référencés ou états persistants.",
    practical: "Elle permet un fonctionnement offline-first.",
    pitfalls: "Effacer les données du site/appareil peut supprimer IndexedDB : fais une sauvegarde avant une opération système destructive.",
  },
  {
    id: "data-localstorage",
    domain: "data",
    title: "localStorage",
    aliases: ["localstorage", "stockage cle valeur"],
    simple: "localStorage conserve de petites valeurs clé/valeur dans le navigateur/WebView.",
    deep: "Il est adapté à des préférences simples, pas à une grande base relationnelle.",
    practical: "Utilise-le conceptuellement pour des réglages légers, tandis qu’IndexedDB porte les données plus riches.",
    pitfalls: "Un localStorage persistant reste local à l’application/origine.",
  },
  {
    id: "data-persistence",
    domain: "data",
    title: "Persistance",
    aliases: ["persistance donnees", "donnees persistantes"],
    simple: "La persistance signifie qu’une donnée survit à la navigation ou au redémarrage.",
    deep: "Elle repose sur un stockage durable, contrairement à un simple état React en mémoire.",
    practical: "Après un réglage important, change d’écran puis reviens pour vérifier qu’il est persistant.",
    pitfalls: "Une valeur visible immédiatement n’est pas la preuve qu’elle est sauvegardée.",
  },
  {
    id: "data-snapshot",
    domain: "data",
    title: "Snapshot",
    aliases: ["snapshot donnees", "instantane"],
    simple: "Un snapshot est une photographie de l’état à un instant donné.",
    deep: "Il peut servir à un Viewer, à une synchronisation ou à une sauvegarde, mais son contenu dépend du contexte.",
    practical: "Vérifie toujours si le snapshot contient seulement l’affichage ou toutes les données.",
    pitfalls: "Un snapshot Viewer n’est pas une sauvegarde complète de l’application.",
  },
  {
    id: "data-backup",
    domain: "data",
    title: "Sauvegarde",
    aliases: ["backup", "sauvegarde donnees"],
    simple: "Une sauvegarde est une copie de sécurité destinée à restaurer des données après incident.",
    deep: "Elle doit idéalement être séparée de l’appareil principal et identifiable par date/version.",
    practical: "Avant une grosse mise à jour ou restauration, crée une sauvegarde récente.",
    pitfalls: "Synchroniser deux appareils n’est pas équivalent à conserver une sauvegarde historique.",
  },
  {
    id: "data-recovery",
    domain: "data",
    title: "Recovery",
    aliases: ["recovery backup", "sauvegarde recovery"],
    simple: "Recovery désigne le parcours de sauvegarde/restauration complète prévu pour récupérer l’application après problème.",
    deep: "Il doit préserver autant que possible profils, historique et données nécessaires à la reconstruction.",
    practical: "Utilise l’inspection avant restauration lorsqu’elle existe.",
    pitfalls: "Ne restaure pas un fichier inconnu sans vérifier son origine et sa date.",
  },
  {
    id: "data-restore",
    domain: "data",
    title: "Restauration",
    aliases: ["restauration", "restore donnees"],
    simple: "Restaurer remplace ou réinjecte des données depuis une sauvegarde.",
    deep: "C’est une opération plus risquée qu’un simple export car elle peut modifier l’état courant.",
    practical: "Sauvegarde l’état actuel avant une restauration importante.",
    pitfalls: "Ne commence pas par supprimer les données locales pour « faire de la place ».",
  },
  {
    id: "data-export-json",
    domain: "data",
    title: "Export JSON",
    aliases: ["export json", "fichier json"],
    simple: "Un export JSON transforme des données structurées en fichier lisible par la machine.",
    deep: "Il sert au transfert, diagnostic ou archivage selon le format exporté.",
    practical: "Conserve le fichier original jusqu’à avoir vérifié l’import sur la destination.",
    pitfalls: "Éditer le JSON manuellement peut le rendre incompatible.",
  },
  {
    id: "data-import-json",
    domain: "data",
    title: "Import JSON",
    aliases: ["import json", "importer fichier"],
    simple: "Un import JSON lit un fichier structuré et tente de l’intégrer à l’application.",
    deep: "Un bon import doit valider le schéma, gérer doublons et signaler ce qui a été ignoré.",
    practical: "Lis le rapport d’import avant de supprimer le fichier source.",
    pitfalls: "N’importe pas un fichier provenant d’une source non fiable.",
  },
  {
    id: "data-schema",
    domain: "data",
    title: "Schéma de données",
    aliases: ["schema donnees", "structure base"],
    simple: "Le schéma décrit les champs et relations attendus dans les données persistantes.",
    deep: "Quand l’application évolue, une migration peut adapter un ancien schéma à la nouvelle version.",
    practical: "Un message de champ manquant peut indiquer une donnée ancienne ou incomplète.",
    pitfalls: "Modifier le schéma à la main sans migration peut casser l’historique.",
  },
  {
    id: "data-migration",
    domain: "data",
    title: "Migration de données",
    aliases: ["migration donnees", "mise a niveau base"],
    simple: "Une migration transforme les données existantes vers une structure plus récente.",
    deep: "Elle doit être idempotente ou correctement versionnée pour ne pas retraiter plusieurs fois la même donnée.",
    practical: "Après migration, vérifie profils, historique et stats sur plusieurs modes.",
    pitfalls: "Une migration ne doit pas supprimer silencieusement des champs inconnus sans stratégie.",
  },
  {
    id: "data-integrity",
    domain: "data",
    title: "Intégrité des données",
    aliases: ["integrite donnees", "data integrity"],
    simple: "L’intégrité signifie que les données restent cohérentes, complètes et reliées correctement.",
    deep: "Exemples : un match référence des joueurs existants, les scores correspondent au résultat, les IDs ne se collisionnent pas.",
    practical: "Les tests d’intégrité détectent les incohérences avant qu’elles ne deviennent des stats fausses.",
    pitfalls: "Une interface qui affiche bien n’est pas une preuve suffisante d’intégrité.",
  },
  {
    id: "data-hash",
    domain: "data",
    title: "Hash",
    aliases: ["hash fichier", "empreinte fichier"],
    simple: "Un hash est une empreinte calculée à partir d’un contenu.",
    deep: "Il sert à détecter une modification ou corruption : si le contenu change, l’empreinte change généralement aussi.",
    practical: "Compare les empreintes avant/après transfert lorsqu’un mécanisme le prévoit.",
    pitfalls: "Un hash seul ne chiffre pas le fichier.",
  },
  {
    id: "data-checksum",
    domain: "data",
    title: "Checksum",
    aliases: ["checksum", "somme controle"],
    simple: "Un checksum est une valeur de contrôle destinée à détecter des erreurs de transmission ou stockage.",
    deep: "Selon l’algorithme, il est plus ou moins robuste ; il ne remplace pas nécessairement un hash cryptographique.",
    practical: "Utilise-le comme signal d’intégrité, pas comme mécanisme de confidentialité.",
    pitfalls: "Checksum valide ne signifie pas forcément contenu authentique.",
  },
  {
    id: "data-compression",
    domain: "data",
    title: "Compression",
    aliases: ["compression sauvegarde", "zip donnees"],
    simple: "La compression réduit la taille des données pour stockage ou transfert.",
    deep: "Elle ne change pas l’information utile lorsqu’elle est sans perte.",
    practical: "Compresse les gros exports si le parcours le prévoit.",
    pitfalls: "Compression et chiffrement sont deux choses différentes.",
  },
  {
    id: "data-encryption",
    domain: "data",
    title: "Chiffrement",
    aliases: ["chiffrement", "encryption sauvegarde"],
    simple: "Le chiffrement rend un contenu illisible sans la clé appropriée.",
    deep: "Il protège la confidentialité d’une sauvegarde, contrairement à la compression ou au hash.",
    practical: "Conserve la clé ou le secret de récupération de façon sûre.",
    pitfalls: "Perdre la clé peut rendre une sauvegarde définitivement inutilisable.",
  },
  {
    id: "data-nas",
    domain: "data",
    title: "NAS",
    aliases: ["nas sauvegarde", "serveur nas"],
    simple: "Un NAS est un stockage réseau personnel accessible depuis le réseau ou via un service configuré.",
    deep: "Il peut servir de destination de sauvegarde sans dépendre d’un cloud public.",
    practical: "Teste d’abord une sauvegarde manuelle puis une restauration de contrôle.",
    pitfalls: "Un NAS hors ligne ou inaccessible ne doit pas bloquer le fonctionnement local de l’application.",
  },
  {
    id: "data-r2",
    domain: "data",
    title: "Cloudflare R2",
    aliases: ["r2 cloud", "cloudflare r2"],
    simple: "R2 est un stockage d’objets cloud.",
    deep: "Dans l’application il peut servir à certaines sauvegardes cloud lorsqu’elles sont autorisées par le produit et le compte.",
    practical: "Vérifie l’état du compte, le coût et la politique de conservation avant d’automatiser.",
    pitfalls: "Une sauvegarde cloud payante doit rester clairement contrôlée et ne pas s’exécuter à l’insu de l’utilisateur.",
  },
  {
    id: "data-sync",
    domain: "data",
    title: "Synchronisation",
    aliases: ["sync", "synchronisation donnees"],
    simple: "Synchroniser aligne des données entre deux emplacements ou appareils.",
    deep: "La difficulté est de décider quoi faire si les deux côtés ont changé : fusion, priorité, conflit ou duplication.",
    practical: "Avant une première sync importante, crée une sauvegarde de sécurité.",
    pitfalls: "La synchronisation peut propager une suppression ; ce n’est donc pas une sauvegarde historique.",
  },
  {
    id: "data-peer-sync",
    domain: "data",
    title: "Peer Sync",
    aliases: ["peer sync", "sync qr appareil"],
    simple: "Peer Sync relie directement ou quasi-directement deux appareils pour transférer des données.",
    deep: "Le QR peut contenir un code ou lien de session permettant d’associer les appareils.",
    practical: "Vérifie les deux appareils et la session avant de valider le transfert.",
    pitfalls: "Ne scanne pas un QR de synchronisation provenant d’un appareil inconnu.",
  },
  {
    id: "data-merge",
    domain: "data",
    title: "Fusion de données",
    aliases: ["merge donnees", "fusion import"],
    simple: "Fusionner combine des ensembles de données au lieu d’en remplacer un par l’autre.",
    deep: "Une bonne fusion utilise des identifiants stables et une stratégie de conflit pour éviter doublons et pertes.",
    practical: "Après fusion, contrôle nombre de profils et de matchs.",
    pitfalls: "Deux éléments ayant le même nom ne sont pas forcément le même enregistrement.",
  },
  {
    id: "data-duplicate",
    domain: "data",
    title: "Doublon",
    aliases: ["doublon donnees", "duplicate match"],
    simple: "Un doublon est un enregistrement répété qui représente la même réalité.",
    deep: "Il peut fausser compteurs, win rates et historiques si le même match est importé deux fois.",
    practical: "Utilise IDs, dates et signatures pour distinguer vrai doublon et deux matchs similaires.",
    pitfalls: "Ne supprime pas au nom seulement : deux parties peuvent avoir le même score.",
  },
  {
    id: "data-offline-first",
    domain: "data",
    title: "Offline-first",
    aliases: ["offline first", "fonctionnement hors ligne"],
    simple: "Offline-first signifie que l’application reste utile sans connexion et synchronise seulement ce qui doit l’être.",
    deep: "Cette architecture privilégie les données locales et réduit la dépendance au réseau pendant une partie.",
    practical: "Tu peux continuer à scorer localement même si un service distant tombe, lorsque le mode le permet.",
    pitfalls: "Les fonctions Online/Cloud restent naturellement dépendantes du réseau.",
  },
  {
    id: "data-signed-url",
    domain: "data",
    title: "URL signée",
    aliases: ["signed url", "url signee"],
    simple: "Une URL signée accorde un accès temporaire à une ressource privée.",
    deep: "Elle contient une autorisation limitée dans le temps au lieu de rendre le fichier public.",
    practical: "Regénère-la si elle a expiré.",
    pitfalls: "Ne publie pas une URL signée encore valide si elle donne accès à des données privées.",
  },
  {
    id: "network-lan",
    domain: "network",
    title: "Réseau local / LAN",
    aliases: ["lan", "reseau local"],
    simple: "Le LAN est le réseau local reliant les appareils d’un même lieu.",
    deep: "Cast, Viewer, caméra compagnon ou bridges peuvent dépendre de la capacité des appareils à communiquer sur ce réseau.",
    practical: "Place les appareils sur un réseau compatible et vérifie qu’un isolement Wi-Fi ne les sépare pas.",
    pitfalls: "Être connecté au même nom de Wi-Fi ne garantit pas toujours la communication si le routeur isole les clients.",
  },
  {
    id: "network-cast",
    domain: "network",
    title: "Google Cast",
    aliases: ["google cast", "chromecast", "cast tv"],
    simple: "Google Cast permet à un appareil sender de piloter un receiver sur Chromecast/Google TV.",
    deep: "L’application démarre une session puis envoie des états/snapshots au receiver.",
    practical: "Crée la session avant la partie et utilise Ping/diagnostics si l’écran reste vide.",
    pitfalls: "Modifier l’App ID au hasard peut empêcher le receiver de démarrer.",
  },
  {
    id: "network-receiver",
    domain: "network",
    title: "Receiver Cast",
    aliases: ["receiver cast", "application receiver"],
    simple: "Le receiver est l’application exécutée côté TV/Chromecast pour afficher les données envoyées.",
    deep: "Le sender ne « filme » pas forcément l’écran : il peut transmettre un modèle de score que le receiver rend proprement.",
    practical: "Si la TV se connecte mais reste vide, diagnostique receiver et snapshots.",
    pitfalls: "Un receiver personnalisé doit correspondre à l’App ID configuré.",
  },
  {
    id: "network-sender",
    domain: "network",
    title: "Sender Cast",
    aliases: ["sender cast", "appareil emetteur cast"],
    simple: "Le sender est l’appareil qui contrôle la session Cast.",
    deep: "Il choisit le receiver, établit la session et publie les mises à jour.",
    practical: "Garde l’application active et la session connectée pendant le match.",
    pitfalls: "Fermer la session sender peut arrêter l’affichage même si la TV reste sur le receiver.",
  },
  {
    id: "network-app-id",
    domain: "network",
    title: "Cast App ID",
    aliases: ["app id cast", "receiver application id"],
    simple: "L’App ID identifie le receiver Cast à lancer.",
    deep: "Il doit correspondre au receiver enregistré/attendu ; l’ID par défaut de l’application est normalement celui à conserver.",
    practical: "Ne le change que pour un receiver volontairement différent.",
    pitfalls: "Un mauvais App ID provoque souvent un receiver introuvable ou qui ne s’ouvre pas.",
  },
  {
    id: "network-viewer",
    domain: "network",
    title: "Viewer tablette",
    aliases: ["viewer tablette", "second ecran"],
    simple: "Le Viewer affiche un scoreboard live sur un second navigateur/tablette sans utiliser Chromecast.",
    deep: "L’hôte crée une session, la tablette rejoint par QR/code/lien, puis des snapshots sont publiés.",
    practical: "Laisse la session active et la publication automatique activée.",
    pitfalls: "Le Viewer n’est pas une sauvegarde de l’Historique.",
  },
  {
    id: "network-host",
    domain: "network",
    title: "Hôte / host",
    aliases: ["host viewer", "appareil hote"],
    simple: "L’hôte est l’appareil qui possède l’état principal et publie vers les clients.",
    deep: "Dans Viewer, c’est généralement le téléphone qui score la partie.",
    practical: "Crée la session sur l’hôte puis connecte les clients.",
    pitfalls: "Si l’hôte s’arrête ou perd le réseau, les viewers peuvent figer.",
  },
  {
    id: "network-client",
    domain: "network",
    title: "Client",
    aliases: ["client viewer", "appareil client"],
    simple: "Un client reçoit des données d’un hôte ou service.",
    deep: "La tablette Viewer est un client : elle affiche mais ne possède pas nécessairement la source de vérité du match.",
    practical: "En cas d’écran figé, vérifie d’abord si l’hôte continue à publier.",
    pitfalls: "Ne restaure pas les données depuis un client d’affichage si ce n’est pas prévu.",
  },
  {
    id: "network-ping",
    domain: "network",
    title: "Ping applicatif",
    aliases: ["ping receiver", "ping viewer"],
    simple: "Un Ping applicatif est un message de test pour vérifier qu’une liaison répond.",
    deep: "Il confirme une partie du chemin réseau mais pas forcément tout le flux métier.",
    practical: "Utilise Ping avant de modifier une configuration complexe.",
    pitfalls: "Ping réussi ne garantit pas que les snapshots de score sont correctement traités.",
  },
  {
    id: "network-latency",
    domain: "network",
    title: "Latence",
    aliases: ["latence", "delai reseau"],
    simple: "La latence est le délai entre une action et sa réception/affichage.",
    deep: "Elle peut venir du réseau, d’un polling, d’un traitement ou du rendu.",
    practical: "Mesure si le retard est constant, aléatoire ou seulement sur un appareil.",
    pitfalls: "Des clics répétés pendant une latence peuvent créer des doublons.",
  },
  {
    id: "network-polling",
    domain: "network",
    title: "Polling",
    aliases: ["polling http", "rafraichissement periodique"],
    simple: "Le polling interroge périodiquement une source pour savoir si des données ont changé.",
    deep: "Plus l’intervalle est court, plus l’affichage paraît réactif mais plus il consomme de requêtes et d’énergie.",
    practical: "Choisis un intervalle raisonnable pour Viewer/bridge lorsque l’option existe.",
    pitfalls: "Réduire l’intervalle n’améliore pas un réseau déjà saturé.",
  },
  {
    id: "network-websocket",
    domain: "network",
    title: "WebSocket",
    aliases: ["websocket", "ws wss"],
    simple: "WebSocket maintient une connexion bidirectionnelle pour échanger rapidement des événements.",
    deep: "Il convient aux scores live, rooms online ou bridges parce qu’il évite de recréer une requête HTTP pour chaque événement.",
    practical: "Vérifie ws:// ou wss://, adresse, port et certificat.",
    pitfalls: "Une connexion ouverte ne garantit pas que le format des messages est compatible.",
  },
  {
    id: "network-http",
    domain: "network",
    title: "HTTP",
    aliases: ["http api", "requete http"],
    simple: "HTTP est le protocole classique de requête/réponse utilisé par les APIs et pages web.",
    deep: "Il peut être utilisé en polling pour récupérer périodiquement des scores ou états.",
    practical: "Regarde le code de réponse et le contenu lorsque le diagnostic le permet.",
    pitfalls: "Une URL correcte peut quand même répondre 401, 403, 404 ou 500.",
  },
  {
    id: "network-https",
    domain: "network",
    title: "HTTPS / TLS",
    aliases: ["https", "tls", "certificat"],
    simple: "HTTPS chiffre la connexion HTTP avec TLS.",
    deep: "Il protège les données en transit et authentifie le serveur via un certificat.",
    practical: "Préfère https/wss pour les services accessibles hors réseau local.",
    pitfalls: "Un certificat expiré ou invalide peut bloquer une connexion pourtant joignable.",
  },
  {
    id: "network-qr",
    domain: "network",
    title: "QR code",
    aliases: ["qr code", "scanner qr"],
    simple: "Un QR code encode rapidement un texte, lien ou code de session.",
    deep: "Dans l’app, il peut simplifier Viewer, caméra compagnon ou Peer Sync sans recopier une longue valeur.",
    practical: "Vérifie l’écran source avant de scanner.",
    pitfalls: "Un QR code est juste un transport d’information : ne scanne pas une source inconnue.",
  },
  {
    id: "network-session-code",
    domain: "network",
    title: "Code de session",
    aliases: ["code session", "code viewer"],
    simple: "Un code de session identifie temporairement une room ou liaison.",
    deep: "Il permet à un autre appareil de rejoindre le bon contexte sans connaître toute l’architecture réseau.",
    practical: "Recopie-le exactement ou utilise le QR associé.",
    pitfalls: "Un code expiré doit être recréé ; ne force pas un ancien code.",
  },
  {
    id: "network-reconnect",
    domain: "network",
    title: "Reconnexion",
    aliases: ["reconnexion", "reconnect viewer cast"],
    simple: "La reconnexion tente de rétablir une session interrompue.",
    deep: "Une bonne stratégie conserve l’état local et renvoie le dernier snapshot nécessaire après retour du réseau.",
    practical: "Après reconnexion, vérifie que le score n’a pas sauté ou été dupliqué.",
    pitfalls: "Ne redémarre pas toute la partie avant d’avoir testé la reconnexion.",
  },
  {
    id: "devices-camera-local",
    domain: "devices",
    title: "Caméra locale",
    aliases: ["camera locale", "camera appareil"],
    simple: "La caméra locale utilise la caméra du même appareil que l’application.",
    deep: "Elle simplifie la liaison mais impose de positionner cet appareil de façon stable face à la cible.",
    practical: "Fixe l’appareil puis calibre sans le déplacer.",
    pitfalls: "Une bonne image ne suffit pas : perspective et calibration doivent rester cohérentes.",
  },
  {
    id: "devices-companion",
    domain: "devices",
    title: "Téléphone compagnon",
    aliases: ["telephone compagnon", "camera second telephone"],
    simple: "Le téléphone compagnon filme la cible pendant que l’appareil principal garde l’interface de score.",
    deep: "La liaison se fait via un parcours QR/lien puis la calibration doit être faite sur l’appareil qui filme.",
    practical: "Place le téléphone dans sa position définitive avant de calibrer.",
    pitfalls: "Déplacer le compagnon après calibration peut décaler les zones.",
  },
  {
    id: "devices-calibration",
    domain: "devices",
    title: "Calibration caméra",
    aliases: ["calibration camera", "calibrer cible"],
    simple: "La calibration associe des points visibles de la cible à la géométrie attendue par le scoring.",
    deep: "Le parcours actuel utilise des repères comme centre du BULL, bord extérieur et segment 20 pour orienter la cible.",
    practical: "Clique précisément les repères avec la caméra stable.",
    pitfalls: "Une calibration approximative produit des erreurs systématiques même avec une image nette.",
  },
  {
    id: "devices-framing",
    domain: "devices",
    title: "Cadrage",
    aliases: ["cadrage camera", "cible dans image"],
    simple: "Le cadrage est la position et la taille de la cible dans l’image.",
    deep: "Un cadrage stable, complet et suffisamment grand facilite toute détection ou interaction.",
    practical: "Évite de couper le bord de la cible et limite les mouvements de caméra.",
    pitfalls: "Zoomer numériquement après calibration peut modifier la géométrie.",
  },
  {
    id: "devices-lighting",
    domain: "devices",
    title: "Éclairage caméra",
    aliases: ["eclairage cible", "lumiere camera"],
    simple: "Un éclairage régulier améliore la lisibilité des secteurs et réduit ombres/reflets.",
    deep: "Les changements brusques d’exposition peuvent gêner la détection ou la vérification visuelle.",
    practical: "Éclaire la cible de façon homogène et évite un spot frontal très réfléchissant.",
    pitfalls: "Une cible bien éclairée mais surexposée peut perdre ses détails.",
  },
  {
    id: "devices-occlusion",
    domain: "devices",
    title: "Occlusion",
    aliases: ["occlusion camera", "flechette cache secteur"],
    simple: "Une occlusion se produit lorsqu’une fléchette, une main ou un objet masque une partie de la cible.",
    deep: "Plusieurs fléchettes groupées peuvent rendre certaines zones difficiles à lire visuellement.",
    practical: "Garde la caméra avec un angle clair et retire les fléchettes au moment prévu par le mode.",
    pitfalls: "Ne confonds pas occlusion ponctuelle et mauvaise calibration globale.",
  },
  {
    id: "devices-confidence",
    domain: "devices",
    title: "Confiance de détection",
    aliases: ["confiance detection", "score confiance camera"],
    simple: "La confiance est une estimation de la fiabilité d’une détection automatique lorsqu’un moteur en fournit une.",
    deep: "Une confiance faible doit inciter à vérifier plutôt qu’à accepter silencieusement.",
    practical: "Si une valeur semble faible, améliore cadrage/éclairage puis reteste.",
    pitfalls: "Une confiance élevée n’est jamais une preuve mathématique absolue.",
  },
  {
    id: "devices-bridge",
    domain: "devices",
    title: "Bridge de scoring",
    aliases: ["bridge scoring", "passerelle scoring"],
    simple: "Un bridge traduit les événements d’un appareil/service externe vers le format compris par MULTISPORTS SCORING.",
    deep: "Il peut utiliser WebSocket ou HTTP et doit mapper segment, multiplicateur et ordre des tirs.",
    practical: "Teste un S20, D20, T20 et BULL/DBULL avant une vraie partie.",
    pitfalls: "Connexion réseau réussie ne signifie pas mapping correct.",
  },
  {
    id: "devices-scolia",
    domain: "devices",
    title: "Scolia",
    aliases: ["scolia x01", "scoring scolia"],
    simple: "Scolia est traité comme une source externe nécessitant une passerelle/API compatible avec l’intégration.",
    deep: "Le bouton de source ne peut pas inventer une API absente : il faut une liaison réellement opérationnelle.",
    practical: "Teste la réception d’un tir avant de lancer X01.",
    pitfalls: "Si rien n’arrive, diagnostique d’abord bridge/API et format des événements.",
  },
  {
    id: "devices-grandarts",
    domain: "devices",
    title: "Grandarts",
    aliases: ["grandarts x01", "scoring grandarts"],
    simple: "Grandarts peut être utilisé comme source si une interface compatible fournit les tirs à l’application.",
    deep: "Le point critique est le protocole de transport et le mapping des événements.",
    practical: "Valide segment/multiplicateur sur quelques tirs de test.",
    pitfalls: "Ne suppose pas qu’un périphérique Grandarts expose automatiquement l’API attendue.",
  },
  {
    id: "devices-bluetooth",
    domain: "devices",
    title: "Bluetooth",
    aliases: ["bluetooth scoring", "bluetooth android"],
    simple: "Bluetooth permet une liaison radio courte portée avec un périphérique.",
    deep: "La compatibilité dépend des services/characteristics exposés et des permissions Android.",
    practical: "Active Bluetooth, permissions, proximité puis teste un événement.",
    pitfalls: "Appairé ne signifie pas protocole de scoring compatible.",
  },
  {
    id: "devices-uuid",
    domain: "devices",
    title: "UUID Bluetooth",
    aliases: ["uuid bluetooth", "service uuid"],
    simple: "Un UUID identifie un service ou une caractéristique Bluetooth.",
    deep: "L’application doit écouter l’UUID correspondant au périphérique/protocole attendu.",
    practical: "Utilise la valeur documentée par le matériel ou le bridge.",
    pitfalls: "Un UUID pris au hasard ne peut pas deviner le flux de données.",
  },
  {
    id: "devices-pairing",
    domain: "devices",
    title: "Appairage",
    aliases: ["appairage bluetooth", "pairing"],
    simple: "L’appairage établit une relation de confiance entre appareils Bluetooth.",
    deep: "Il peut être distinct de la connexion applicative à un service BLE.",
    practical: "Vérifie que le périphérique est visible et autorisé.",
    pitfalls: "Être appairé dans Android ne garantit pas que l’app a trouvé le bon service.",
  },
  {
    id: "devices-manual-fallback",
    domain: "devices",
    title: "Fallback manuel",
    aliases: ["fallback manuel", "saisie manuelle secours"],
    simple: "Le fallback manuel permet de continuer une partie si une source automatique tombe.",
    deep: "C’est important pour ne pas perdre un match à cause d’un problème de caméra, bridge ou réseau.",
    practical: "Avant le match, vérifie qu’une méthode de saisie manuelle reste accessible.",
    pitfalls: "Évite de saisir manuellement un tir déjà reçu automatiquement.",
  },
  {
    id: "stats-kpi",
    domain: "stats",
    title: "KPI",
    aliases: ["kpi statistique", "indicateur cle"],
    simple: "Un KPI est un indicateur synthétique choisi pour résumer une performance.",
    deep: "Il doit être accompagné de son unité, période et volume pour être interprétable.",
    practical: "Lis un KPI avec son contexte plutôt que seul.",
    pitfalls: "Un KPI élevé n’est pas toujours « meilleur » selon ce qu’il mesure.",
  },
  {
    id: "stats-avg3",
    domain: "stats",
    title: "AVG3",
    aliases: ["avg3", "moyenne 3 darts"],
    simple: "AVG3 est la moyenne de points ramenée à trois fléchettes en X01.",
    deep: "Une formule usuelle est points marqués ÷ fléchettes lancées × 3.",
    practical: "Compare des AVG3 sur des volumes suffisants.",
    pitfalls: "Une petite partie peut produire une moyenne spectaculaire mais peu stable.",
  },
  {
    id: "stats-winrate",
    domain: "stats",
    title: "Win rate",
    aliases: ["win rate", "taux victoire"],
    simple: "Le win rate est le pourcentage de matchs gagnés.",
    deep: "Victoires ÷ matchs × 100 ; il doit être lu avec le nombre de matchs et la force des adversaires.",
    practical: "Affiche le volume à côté du pourcentage.",
    pitfalls: "100 % sur 1 match ne vaut pas 70 % sur 100 matchs.",
  },
  {
    id: "stats-median",
    domain: "stats",
    title: "Médiane",
    aliases: ["mediane statistique", "median"],
    simple: "La médiane coupe les observations en deux moitiés.",
    deep: "Elle résiste mieux aux valeurs extrêmes que la moyenne et peut mieux représenter une performance typique.",
    practical: "Compare moyenne et médiane pour détecter des gros écarts.",
    pitfalls: "La médiane ignore l’amplitude exacte des extrêmes.",
  },
  {
    id: "stats-variance",
    domain: "stats",
    title: "Variance",
    aliases: ["variance statistique", "dispersion"],
    simple: "La variance mesure la dispersion autour de la moyenne.",
    deep: "Une faible dispersion traduit plus de régularité ; une forte dispersion indique des performances très variables.",
    practical: "Pour un joueur, combine niveau moyen et régularité.",
    pitfalls: "Deux joueurs peuvent avoir la même moyenne avec des variances très différentes.",
  },
  {
    id: "stats-stddev",
    domain: "stats",
    title: "Écart-type",
    aliases: ["ecart type", "standard deviation"],
    simple: "L’écart-type est la racine de la variance et s’exprime dans la même unité que la donnée.",
    deep: "Il donne une idée intuitive de la dispersion des performances.",
    practical: "Utilise-le pour comparer la régularité sur des séries comparables.",
    pitfalls: "Sur très peu de matchs, l’écart-type est instable.",
  },
  {
    id: "stats-sample",
    domain: "stats",
    title: "Taille d’échantillon",
    aliases: ["taille echantillon", "sample size"],
    simple: "La taille d’échantillon est le nombre d’observations utilisées pour une statistique.",
    deep: "Plus elle est petite, plus un résultat peut être dominé par le hasard ou une soirée atypique.",
    practical: "Affiche toujours matchs/legs/darts avec les pourcentages importants.",
    pitfalls: "Ne surinterprète pas un classement basé sur deux parties.",
  },
  {
    id: "stats-trend",
    domain: "stats",
    title: "Tendance",
    aliases: ["tendance stats", "trend"],
    simple: "Une tendance décrit l’évolution dans le temps plutôt qu’une valeur isolée.",
    deep: "Elle peut être estimée par comparaison de périodes ou moyenne mobile.",
    practical: "Compare période récente et référence plus longue.",
    pitfalls: "Une tendance courte peut être juste du bruit.",
  },
  {
    id: "stats-moving-average",
    domain: "stats",
    title: "Moyenne mobile",
    aliases: ["moyenne mobile", "moving average"],
    simple: "Une moyenne mobile lisse les dernières observations pour suivre la forme.",
    deep: "Elle réagit plus vite qu’une moyenne historique mais reste sensible à la fenêtre choisie.",
    practical: "Utilise plusieurs tailles de fenêtre si tu analyses sérieusement une progression.",
    pitfalls: "Changer la fenêtre peut changer fortement l’impression visuelle.",
  },
  {
    id: "stats-h2h",
    domain: "stats",
    title: "Head-to-head",
    aliases: ["h2h", "head to head", "face a face"],
    simple: "Le head-to-head compare directement deux joueurs ou équipes.",
    deep: "Il révèle une opposition particulière mais ne résume pas leur niveau général contre tous les adversaires.",
    practical: "Lis H2H avec dates et nombre de rencontres.",
    pitfalls: "Un H2H ancien peut ne plus représenter la forme actuelle.",
  },
  {
    id: "stats-outlier",
    domain: "stats",
    title: "Valeur aberrante",
    aliases: ["outlier", "valeur aberrante"],
    simple: "Un outlier est une observation très éloignée du reste.",
    deep: "Il peut être une performance réelle exceptionnelle ou une erreur de saisie.",
    practical: "Vérifie la partie source avant de l’exclure.",
    pitfalls: "Supprimer les valeurs extrêmes sans justification peut biaiser les stats.",
  },
  {
    id: "stats-filter",
    domain: "stats",
    title: "Filtre statistique",
    aliases: ["filtre stats", "periode stats"],
    simple: "Un filtre limite les données analysées : joueur, mode, période, adversaire ou contexte.",
    deep: "Il est indispensable pour comparer des ensembles cohérents.",
    practical: "Quand un écran semble vide, vérifie les filtres avant tout diagnostic stockage.",
    pitfalls: "Un filtre resté actif peut donner l’impression que l’historique a disparu.",
  },
  {
    id: "stats-leaderboard",
    domain: "stats",
    title: "Leaderboard",
    aliases: ["leaderboard", "classement stats"],
    simple: "Un leaderboard classe des joueurs/équipes selon un critère.",
    deep: "Le critère doit être explicite : victoires, win rate, moyenne, points, etc., avec règles d’éligibilité.",
    practical: "Vérifie le critère et le minimum de matchs.",
    pitfalls: "Un classement au win rate sans minimum favorise les petits échantillons.",
  },
  {
    id: "stats-bestof",
    domain: "stats",
    title: "Best Of",
    aliases: ["best of", "bo3 bo5 bo7"],
    simple: "Best Of N signifie qu’on joue au maximum N manches et que le premier à plus de la moitié gagne.",
    deep: "BO3 demande 2 victoires, BO5 en demande 3, BO7 en demande 4.",
    practical: "Awéna peut calculer automatiquement le nombre de manches nécessaires.",
    pitfalls: "Ne confonds pas Best Of avec First To.",
  },
  {
    id: "stats-firstto",
    domain: "stats",
    title: "First To",
    aliases: ["first to", "premier a"],
    simple: "First To N signifie que le premier participant à atteindre N manches/legs gagne.",
    deep: "Le nombre maximal de manches peut être 2N−1 si aucun nul n’est possible.",
    practical: "Utilise-le quand tu veux exprimer directement le nombre de victoires nécessaires.",
    pitfalls: "First To 3 et BO5 sont souvent équivalents en structure, mais pas dans la façon de le présenter.",
  },
  {
    id: "stats-roundrobin",
    domain: "stats",
    title: "Round-robin",
    aliases: ["round robin", "toutes rondes"],
    simple: "En round-robin, chaque participant rencontre les autres selon le calendrier prévu.",
    deep: "Il produit davantage de matchs qu’une élimination directe et nécessite des règles de classement/tie-break.",
    practical: "Vérifie égalités et nombre de rencontres avant de lancer.",
    pitfalls: "Un résultat manquant peut fausser tout le classement.",
  },
  {
    id: "stats-knockout",
    domain: "stats",
    title: "Élimination directe",
    aliases: ["elimination directe", "knockout bracket"],
    simple: "En élimination directe, une défaite élimine généralement le participant du tableau principal.",
    deep: "Le bracket progresse par tours jusqu’à la finale.",
    practical: "Vérifie les byes et le nombre de participants.",
    pitfalls: "Modifier un résultat ancien peut avoir des conséquences sur tous les tours suivants.",
  },
  {
    id: "stats-seed",
    domain: "stats",
    title: "Tête de série",
    aliases: ["tete de serie", "seed tournoi"],
    simple: "Une tête de série sert à répartir les favoris dans le tableau pour éviter certaines rencontres trop tôt.",
    deep: "Le seeding peut être basé sur classement, niveau ou décision de l’organisateur.",
    practical: "Définis la règle avant le tirage.",
    pitfalls: "Changer les seeds après génération du tableau peut rendre le bracket incohérent.",
  },
  {
    id: "stats-bye",
    domain: "stats",
    title: "Bye",
    aliases: ["bye tournoi", "exempt premier tour"],
    simple: "Un bye qualifie automatiquement un participant pour le tour suivant lorsqu’un tableau n’est pas plein.",
    deep: "Il est courant avec des nombres non puissances de deux en élimination directe.",
    practical: "Vérifie la répartition des byes avant de démarrer.",
    pitfalls: "Un bye n’est pas une victoire jouée et doit être compté correctement.",
  },
  {
    id: "stats-tiebreak",
    domain: "stats",
    title: "Tie-break",
    aliases: ["tie break classement", "departage egalite"],
    simple: "Un tie-break départage des participants à égalité selon une règle définie.",
    deep: "Exemples possibles : confrontation directe, différence, points pour/contre, manche supplémentaire selon le sport et le tournoi.",
    practical: "Affiche la règle de départage avant la compétition.",
    pitfalls: "Ne change pas la règle après avoir vu le classement final.",
  },
  {
    id: "awena-wakeword",
    domain: "awena",
    title: "Wake word Awéna",
    aliases: ["wake word", "mot reveil awena", "awena ecoute"],
    simple: "Le wake word est le mot ou prénom qui indique qu’une commande s’adresse à l’assistante.",
    deep: "Le système tolère plusieurs transcriptions proches d’Awéna afin de mieux fonctionner avec la reconnaissance vocale.",
    practical: "Prononce « Awéna » puis la demande dans une phrase courte.",
    pitfalls: "La reconnaissance peut confondre un nom proche dans un environnement bruyant.",
  },
  {
    id: "awena-speech-recognition",
    domain: "awena",
    title: "Reconnaissance vocale",
    aliases: ["speech recognition", "reconnaissance vocale"],
    simple: "La reconnaissance vocale transforme la parole en texte.",
    deep: "Sur Android, l’application peut utiliser SpeechRecognizer et préférer un moteur sur l’appareil lorsqu’il est disponible.",
    practical: "Parle clairement, vérifie le texte compris et confirme les actions importantes.",
    pitfalls: "Ce n’est pas un micro ouvert 24/24 conçu comme un assistant système complet.",
  },
  {
    id: "awena-tts",
    domain: "awena",
    title: "Synthèse vocale",
    aliases: ["tts", "text to speech", "synthese vocale"],
    simple: "La synthèse vocale transforme le texte d’Awéna en parole.",
    deep: "Elle est distincte de la reconnaissance : l’une écoute, l’autre parle.",
    practical: "Le micro doit être suspendu pendant qu’Awéna parle pour éviter l’auto-déclenchement.",
    pitfalls: "Une voix disponible dépend du moteur et de la langue installée.",
  },
  {
    id: "awena-ondevice",
    domain: "awena",
    title: "Reconnaissance sur l’appareil",
    aliases: ["on device speech", "reconnaissance locale"],
    simple: "La reconnaissance sur l’appareil traite la parole localement lorsqu’un moteur compatible est disponible.",
    deep: "Elle peut améliorer confidentialité et fonctionnement hors ligne, mais les capacités dépendent d’Android et des packs de langue.",
    practical: "Active la préférence locale dans les réglages Awéna quand elle fonctionne bien sur ton appareil.",
    pitfalls: "Tous les téléphones ne proposent pas les mêmes langues/modèles hors ligne.",
  },
  {
    id: "awena-intent",
    domain: "awena",
    title: "Intention vocale",
    aliases: ["intent commande", "intention awena"],
    simple: "Une intention représente ce que l’utilisateur veut faire : lancer X01, demander une règle, ouvrir Stats, etc.",
    deep: "Le routeur vocal sépare l’intention des détails nécessaires à l’action.",
    practical: "Formule d’abord le verbe et l’objet : « lance X01 », « ouvre Stats », « explique Double Out ».",
    pitfalls: "Une phrase ambiguë peut nécessiter une confirmation.",
  },
  {
    id: "awena-slot",
    domain: "awena",
    title: "Paramètre vocal / slot",
    aliases: ["slot filling", "parametre commande vocale"],
    simple: "Un slot est une information nécessaire à une intention, par exemple score de départ, joueur ou mode de sortie.",
    deep: "Le dialogue vocal peut demander les slots manquants un par un.",
    practical: "Réponds simplement à la question courante pour limiter les erreurs.",
    pitfalls: "Ne mélange pas plusieurs réponses si Awéna demande une seule valeur.",
  },
  {
    id: "awena-confirmation",
    domain: "awena",
    title: "Confirmation vocale",
    aliases: ["confirmation awena", "confirmer commande"],
    simple: "La confirmation protège les actions importantes contre une mauvaise reconnaissance.",
    deep: "Avant de lancer une partie, Awéna peut résumer les choix et attendre un oui explicite.",
    practical: "Écoute le récapitulatif et corrige avant de confirmer.",
    pitfalls: "Ne valide pas si un nom ou réglage a été mal reconnu.",
  },
  {
    id: "awena-context-memory",
    domain: "awena",
    title: "Mémoire de contexte Awéna",
    aliases: ["memoire contexte awena", "et ensuite awena"],
    simple: "La mémoire de contexte conserve le sujet du tutoriel ou de la question pendant les relances.",
    deep: "Elle permet « étape 3 », « et ensuite ? » ou « ça ne marche pas » sans répéter Cast, Viewer ou Sync.",
    practical: "Reste dans le même panneau/contexte pour les relances courtes.",
    pitfalls: "Si tu changes complètement de sujet, nomme le nouveau sujet explicitement.",
  },
  {
    id: "awena-voice-scoring",
    domain: "awena",
    title: "Commande Awéna vs scoring vocal",
    aliases: ["scoring vocal vs awena", "voix x01 commande"],
    simple: "Les commandes adressées à Awéna et la saisie vocale des scores X01 sont deux fonctions différentes.",
    deep: "« Awéna, lance X01 » pilote l’application ; la méthode VOICE pendant le jeu sert à saisir des scores/tirs selon le mode prévu.",
    practical: "Choisis clairement la méthode de saisie dans la configuration X01.",
    pitfalls: "Évite d’utiliser le wake word dans une phrase de score si tu veux uniquement saisir la volée.",
  },
  {
    id: "awena-mic-permission",
    domain: "awena",
    title: "Permission micro",
    aliases: ["permission micro", "micro refuse awena"],
    simple: "La permission micro est nécessaire pour écouter les commandes vocales.",
    deep: "Android peut conserver un refus ; il faut parfois l’autoriser depuis les réglages système.",
    practical: "Active la permission puis relance l’écoute.",
    pitfalls: "L’absence de permission ne doit pas empêcher l’usage tactile de l’application.",
  },
  {
    id: "awena-aab",
    domain: "awena",
    title: "AAB Android",
    aliases: ["aab", "android app bundle"],
    simple: "Un AAB est le format Android App Bundle destiné notamment à Google Play.",
    deep: "Google Play génère ensuite des APK optimisés pour les appareils à partir du bundle.",
    practical: "Pour une mise à jour testeurs, génère l’AAB de la bonne version puis envoie-le sur la piste appropriée.",
    pitfalls: "Installer un ancien build peut venir d’un versionCode/piste mal mis à jour, pas du contenu du ZIP source.",
  },
  {
    id: "awena-apk",
    domain: "awena",
    title: "APK",
    aliases: ["apk android", "fichier apk"],
    simple: "Un APK est un paquet installable Android.",
    deep: "Il peut être généré directement pour test local ou produit par Google Play à partir d’un AAB.",
    practical: "Vérifie versionName/versionCode de l’application installée lors d’un diagnostic.",
    pitfalls: "Un APK de debug n’est pas équivalent à la version signée Play.",
  },
  {
    id: "awena-versioncode",
    domain: "awena",
    title: "versionCode",
    aliases: ["versioncode android", "code version"],
    simple: "versionCode est le numéro entier utilisé par Android/Google Play pour ordonner les versions.",
    deep: "Chaque mise à jour publiée doit normalement utiliser un code supérieur à celui déjà diffusé sur la piste concernée.",
    practical: "Avant de générer un AAB, vérifie le code prévu.",
    pitfalls: "Changer seulement versionName sans augmenter versionCode peut empêcher une mise à jour.",
  },
  {
    id: "awena-versionname",
    domain: "awena",
    title: "versionName",
    aliases: ["versionname android", "nom version"],
    simple: "versionName est le libellé lisible par l’utilisateur, par exemple 1.0.0-rc7.",
    deep: "Il n’est pas le critère principal utilisé par Play pour décider qu’un build est plus récent.",
    practical: "Affiche-le dans les diagnostics pour savoir quel build est installé.",
    pitfalls: "Deux builds peuvent avoir des noms proches mais des versionCode différents.",
  },
  {
    id: "awena-capacitor",
    domain: "awena",
    title: "Capacitor",
    aliases: ["capacitor android", "bridge natif"],
    simple: "Capacitor relie l’application web React aux capacités natives Android/iOS via des plugins.",
    deep: "Il permet d’utiliser des APIs natives comme SpeechRecognizer tout en conservant l’interface web.",
    practical: "Après ajout d’un plugin natif, synchronise/recompile le projet Android selon le workflow du repo.",
    pitfalls: "Une fonctionnalité native ne sera pas testée complètement par le typecheck TypeScript seul.",
  },
  {
    id: "awena-webview",
    domain: "awena",
    title: "WebView",
    aliases: ["webview android", "application web embarquee"],
    simple: "WebView est le moteur web intégré dans l’application Android qui affiche l’interface React/PWA.",
    deep: "Le code web s’exécute dans ce conteneur tandis que Capacitor donne accès au natif.",
    practical: "Un bug présent seulement Android peut venir du WebView, des permissions ou du bridge natif.",
    pitfalls: "Ne suppose pas qu’un comportement Chrome desktop sera identique au WebView Android.",
  },
  {
    id: "awena-pwa",
    domain: "awena",
    title: "PWA",
    aliases: ["pwa", "progressive web app"],
    simple: "Une PWA est une application web installable qui peut utiliser manifest, cache et service worker.",
    deep: "MULTISPORTS SCORING combine une base web/PWA avec une version Android via Capacitor.",
    practical: "Le mode PWA permet des mises à jour web rapides, tandis que certaines fonctions natives exigent un build Android.",
    pitfalls: "Un cache PWA peut parfois conserver une ancienne ressource si la stratégie de mise à jour n’est pas correcte.",
  },
  {
    id: "awena-service-worker",
    domain: "awena",
    title: "Service Worker",
    aliases: ["service worker", "cache pwa"],
    simple: "Un service worker peut intercepter des requêtes et gérer cache/offline dans une PWA.",
    deep: "Il permet de servir des ressources sans réseau mais doit être versionné correctement pour éviter des fichiers obsolètes.",
    practical: "Lors d’un diagnostic PWA, vérifie si une ancienne version est servie depuis le cache.",
    pitfalls: "Forcer des suppressions de cache utilisateur sans besoin peut dégrader l’expérience offline.",
  },
  {
    id: "troubleshooting-safe-diagnosis",
    domain: "troubleshooting",
    title: "Diagnostic sans perte de données",
    aliases: ["diagnostic sans perte", "ne pas perdre donnees"],
    simple: "Un diagnostic sûr commence par observer, reproduire et sauvegarder avant toute action destructive.",
    deep: "L’ordre conseillé est : relever le symptôme, vérifier contexte/version, tester une action réversible, sauvegarder, puis seulement envisager reset/restauration.",
    practical: "Donne à Awéna le message exact et l’étape où ça bloque.",
    pitfalls: "Effacer IndexedDB, profils ou application ne doit jamais être la première réponse à un bug.",
  },
  {
    id: "troubleshooting-double-click",
    domain: "troubleshooting",
    title: "Double saisie",
    aliases: ["double clic", "double saisie score"],
    simple: "Une double saisie survient quand deux actions sont enregistrées pour une seule intention.",
    deep: "Elle apparaît souvent si l’interface est lente et que l’utilisateur retape avant le retour visuel.",
    practical: "Attends l’état affiché ; utilise Undo si une saisie a été doublée.",
    pitfalls: "Compenser avec un faux score supplémentaire rend l’historique incohérent.",
  },
  {
    id: "troubleshooting-stale-ui",
    domain: "troubleshooting",
    title: "Interface obsolète",
    aliases: ["stale ui", "affichage pas a jour"],
    simple: "Une interface obsolète affiche un état plus ancien que la donnée réelle.",
    deep: "Cela peut venir d’un cache, d’une subscription non rafraîchie ou d’un écran qui n’a pas reçu la dernière mise à jour.",
    practical: "Compare l’Historique/source persistante et recharge seulement l’écran si possible.",
    pitfalls: "Ne conclus pas immédiatement que la donnée a disparu.",
  },
  {
    id: "troubleshooting-race-condition",
    domain: "troubleshooting",
    title: "Condition de course",
    aliases: ["race condition", "etat ecrase"],
    simple: "Une condition de course se produit quand plusieurs opérations asynchrones se terminent dans un ordre inattendu.",
    deep: "Un chargement lent peut alors écraser une modification plus récente ou faire apparaître/disparaître une image.",
    practical: "Les correctifs robustes utilisent annulation, version/timestamp ou priorité d’état.",
    pitfalls: "Ajouter simplement un délai artificiel masque souvent le problème au lieu de le résoudre.",
  },
  {
    id: "troubleshooting-debounce",
    domain: "troubleshooting",
    title: "Debounce",
    aliases: ["debounce clic", "anti double clic"],
    simple: "Le debounce attend une courte période avant d’exécuter une action ou ignore des répétitions rapprochées.",
    deep: "Il peut réduire double clic, recherche trop fréquente ou rafales d’événements.",
    practical: "Utile pour recherche/filtre ou boutons sensibles si le design le prévoit.",
    pitfalls: "Un debounce trop long rend l’application molle.",
  },
  {
    id: "troubleshooting-throttle",
    domain: "troubleshooting",
    title: "Throttle",
    aliases: ["throttle", "limiter frequence"],
    simple: "Le throttle limite la fréquence maximale d’exécution d’une action.",
    deep: "Il est utile pour scroll, resize, snapshots ou événements très fréquents.",
    practical: "Choisis une fréquence compatible avec la réactivité voulue.",
    pitfalls: "Trop throttler un score live peut donner une impression de retard.",
  },
  {
    id: "troubleshooting-idempotent",
    domain: "troubleshooting",
    title: "Idempotence",
    aliases: ["idempotent", "operation idempotente"],
    simple: "Une opération idempotente peut être rejouée sans produire d’effet supplémentaire indésirable.",
    deep: "C’est précieux pour imports, migrations et requêtes susceptibles d’être répétées après un timeout.",
    practical: "Utilise des IDs stables pour éviter de créer deux fois le même match.",
    pitfalls: "Une simple répétition de POST n’est pas automatiquement idempotente.",
  },
  {
    id: "troubleshooting-logs",
    domain: "troubleshooting",
    title: "Logs de diagnostic",
    aliases: ["logs", "journal diagnostic"],
    simple: "Les logs enregistrent les étapes importantes d’un processus pour comprendre un échec.",
    deep: "Ils sont particulièrement utiles pour Cast, Viewer, Sync, réseau et opérations natives.",
    practical: "Copie les dernières lignes pertinentes avec l’heure et l’action réalisée.",
    pitfalls: "Évite de partager des tokens, emails ou secrets présents dans des logs.",
  },
  {
    id: "troubleshooting-fallback",
    domain: "troubleshooting",
    title: "Fallback",
    aliases: ["fallback", "solution de repli"],
    simple: "Un fallback est une méthode de secours utilisée quand la méthode principale est indisponible.",
    deep: "Exemples : reconnaissance vocale système si on-device absent, saisie manuelle si scoring externe tombe.",
    practical: "Prépare le fallback avant une compétition importante.",
    pitfalls: "Un fallback ne doit pas modifier silencieusement les règles du match.",
  },
  {
    id: "concept-official-vs-app",
    domain: "concept",
    title: "Règle officielle vs variante application",
    aliases: ["regle officielle vs application", "variante app"],
    simple: "Une règle officielle de sport est une référence externe ; une variante de l’application peut volontairement adapter le format.",
    deep: "Awéna doit toujours privilégier les paramètres réellement actifs de la partie lorsqu’ils diffèrent d’une règle de référence.",
    practical: "Demande « règle officielle » si tu veux la référence générale, ou « dans cette partie » pour le preset actif.",
    pitfalls: "Ne mélange pas une variante fun avec une règle fédérale.",
  },
  {
    id: "concept-score-entry",
    domain: "concept",
    title: "Saisie de score",
    aliases: ["saisie score", "entrer score"],
    simple: "La saisie transforme une action réelle en donnée de partie.",
    deep: "Selon le mode elle peut être par score total, fléchette, cible visuelle, bouton d’événement, voix ou source externe.",
    practical: "Choisis la méthode qui conserve le niveau de détail statistique dont tu as besoin.",
    pitfalls: "Saisir seulement un total peut empêcher de reconstruire les S/D/T exacts si le mode ne les enregistre pas autrement.",
  },
  {
    id: "concept-undo",
    domain: "concept",
    title: "Undo / annuler",
    aliases: ["undo", "annuler derniere action"],
    simple: "Undo annule la dernière action enregistrée lorsque le mode le supporte.",
    deep: "Il doit restaurer score, joueur actif et statistiques liées, pas seulement l’affichage.",
    practical: "Utilise Undo immédiatement après une erreur.",
    pitfalls: "Une correction manuelle à la place d’Undo peut laisser des statistiques fausses.",
  },
  {
    id: "concept-history",
    domain: "concept",
    title: "Historique",
    aliases: ["historique parties", "match history"],
    simple: "L’Historique conserve les parties terminées et leurs données utiles aux statistiques.",
    deep: "Il est la base pour reconstruire classements, records et tendances si les modes enregistrent suffisamment de détails.",
    practical: "Après une partie importante, vérifie qu’elle apparaît dans l’Historique.",
    pitfalls: "Effacer l’Historique supprime la matière première des statistiques locales.",
  },
  {
    id: "concept-record",
    domain: "concept",
    title: "Record",
    aliases: ["record statistique", "meilleure perf"],
    simple: "Un record est une meilleure performance selon un critère bien défini.",
    deep: "Il faut préciser mode, période, format et minimum de données pour qu’un record soit comparable.",
    practical: "Clique le record pour ouvrir la partie source quand l’interface le permet.",
    pitfalls: "Un record sans provenance ou période est difficile à vérifier.",
  },
];


function rememberedId(topic?: string) { return String(topic || "").startsWith("guidepro:") ? String(topic).slice(9) : ""; }
function scoreEntry(entry: GuideProEntry, q: string, rememberedTopic?: string) {
  let score = rememberedId(rememberedTopic) === entry.id ? 10 : 0;
  const qt = new Set(tokens(q));
  const names = [entry.title, ...entry.aliases];
  for (const raw of names) {
    const a = norm(raw); if (!a) continue;
    if (q === a) score += 40;
    else if (a.length >= 3 && q.includes(a)) score += 17;
    const at = tokens(a); let match = 0;
    for (const t of at) if (qt.has(t)) { match++; score += t.length >= 6 ? 3.4 : 2; }
    if (at.length >= 2 && match === at.length) score += 7;
  }
  return score;
}
function full(entry: GuideProEntry, q: string) {
  const wantsProblem = /marche pas|fonctionne pas|erreur|probleme|problème|bloque|bloqué|bug/.test(q);
  const wantsHow = /comment|utiliser|configurer|mettre en place|faire pour/.test(q);
  const wantsWhy = /pourquoi|a quoi sert|à quoi sert|interet|intérêt/.test(q);
  const wantsDeep = /detail|détail|technique|expert|precis|précis|approfond|complet|complexe/.test(q);
  let text = `## ${entry.title.toUpperCase()}\n${entry.simple}`;
  if (wantsWhy || wantsDeep || (!wantsHow && !wantsProblem && q.length > 45)) text += `\n\n## POUR COMPRENDRE PLUS LOIN\n${entry.deep}`;
  if ((wantsHow || wantsDeep) && entry.practical) text += `\n\n## EN PRATIQUE\n${entry.practical}`;
  if ((wantsProblem || wantsDeep) && entry.pitfalls) text += `\n\n## POINTS DE VIGILANCE\n${entry.pitfalls}`;
  if (!wantsDeep && !wantsProblem && !wantsHow && entry.practical) text += `\n\n**À retenir :** ${entry.practical}`;
  return text;
}

export function answerAwenaGuidePro(question: string, context: AwenaRuntimeContext, rememberedTopic?: string): AwenaReply | null {
  const q = norm(question); if (!q) return null;
  const follow = /^(?:plus de details|plus de détails|approfondis|explique davantage|pourquoi|comment|et en pratique|a quoi sert|à quoi sert|ca ne marche pas|ça ne marche pas)$/i.test(String(question || "").trim());
  const rid = rememberedId(rememberedTopic);
  if (follow && rid) {
    const entry = ENTRIES.find((e) => e.id === rid);
    if (entry) return { text: full(entry, `${q} detail`), knowledgeTopic: `guidepro:${entry.id}`, modeId: context.mode || null };
  }
  let best: { entry: GuideProEntry; score: number } | null = null;
  for (const entry of ENTRIES) { const score = scoreEntry(entry, q, rememberedTopic); if (!best || score > best.score) best = { entry, score }; }
  if (!best || best.score < 12) return null;
  return { text: full(best.entry, q), knowledgeTopic: `guidepro:${best.entry.id}`, modeId: context.mode || null };
}
export function awenaGuideProCount() { return ENTRIES.length; }
export function awenaGuideProDomainCount() { return new Set(ENTRIES.map((e) => e.domain)).size; }
export function awenaGuideProAliasCount() { return ENTRIES.reduce((sum, e) => sum + e.aliases.length, 0); }
