import type { AwenaAction, AwenaReply } from "./awena.types";

type RouteEntry = {
  id: string;
  label: string;
  category: string;
  purpose: string;
  aliases: string[];
};

function norm(value: string) {
  return String(value || "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[’']/g, " ")
    .replace(/[_./\\-]+/g, " ")
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

const STOP = new Set(["le","la","les","un","une","des","de","du","dans","sur","a","au","aux","et","ou","je","tu","il","elle","on","nous","vous","pour","comment","ou","est","sont","trouver","ouvrir","aller","ecran","page"]);

function tokens(value: string) {
  return norm(value).split(" ").filter((token) => token.length > 1 && !STOP.has(token));
}

const ROUTES: RouteEntry[] = [
  {
    id: "account_start",
    label: "Compte · Start",
    category: "Compte",
    purpose: "Étape de compte / authentification : **Compte · Start**.",
    aliases: ["Compte", "Compte Start", "account start"],
  },
  {
    id: "auth_start",
    label: "Compte · Start",
    category: "Compte",
    purpose: "Étape de compte / authentification : **Compte · Start**.",
    aliases: ["Compte", "Compte Start", "auth start"],
  },
  {
    id: "auth_forgot",
    label: "Compte · Forgot",
    category: "Compte",
    purpose: "Étape de compte / authentification : **Compte · Forgot**.",
    aliases: ["auth forgot", "Compte", "Compte Forgot"],
  },
  {
    id: "auth_v7_login",
    label: "Compte · V7 · Login",
    category: "Compte",
    purpose: "Étape de compte / authentification : **Compte · V7 · Login**.",
    aliases: ["Compte V7 Login", "Compte", "auth v7 login"],
  },
  {
    id: "auth_v7_signup",
    label: "Compte · V7 · Signup",
    category: "Compte",
    purpose: "Étape de compte / authentification : **Compte · V7 · Signup**.",
    aliases: ["Compte V7 Signup", "Compte", "auth v7 signup"],
  },
  {
    id: "home",
    label: "Accueil",
    category: "Fléchettes / Jeu",
    purpose: "Accueil global et synthèse de l'activité.",
    aliases: ["Accueil", "home"],
  },
  {
    id: "gameSelect",
    label: "Choix du sport",
    category: "Fléchettes / Jeu",
    purpose: "Menu de sélection / navigation : **Choix du sport**.",
    aliases: ["gameSelect", "Choix du sport"],
  },
  {
    id: "games",
    label: "Games",
    category: "Fléchettes / Jeu",
    purpose: "Menu de sélection / navigation : **Games**.",
    aliases: ["Games", "games"],
  },
  {
    id: "cast_join",
    label: "Cast · Join",
    category: "Écrans externes",
    purpose: "Écran d'affichage externe ou spectateur : **Cast · Join**.",
    aliases: ["Cast", "cast join", "Cast Join"],
  },
  {
    id: "cast_host",
    label: "Cast · Host",
    category: "Écrans externes",
    purpose: "Écran d'affichage externe ou spectateur : **Cast · Host**.",
    aliases: ["Cast Host", "Cast", "cast host"],
  },
  {
    id: "cast_room",
    label: "Cast · Room",
    category: "Écrans externes",
    purpose: "Écran d'affichage externe ou spectateur : **Cast · Room**.",
    aliases: ["cast room", "Cast", "Cast Room"],
  },
  {
    id: "viewer_host",
    label: "Viewer · Host",
    category: "Écrans externes",
    purpose: "Écran d'affichage externe ou spectateur : **Viewer · Host**.",
    aliases: ["Viewer Host", "viewer host", "Viewer"],
  },
  {
    id: "viewer_join",
    label: "Viewer · Join",
    category: "Écrans externes",
    purpose: "Écran d'affichage externe ou spectateur : **Viewer · Join**.",
    aliases: ["viewer join", "Viewer Join", "Viewer"],
  },
  {
    id: "viewer_display",
    label: "Viewer · Display",
    category: "Écrans externes",
    purpose: "Écran d'affichage externe ou spectateur : **Viewer · Display**.",
    aliases: ["Viewer Display", "Viewer", "viewer display"],
  },
  {
    id: "mode_not_ready",
    label: "Mode · Not · Ready",
    category: "Fléchettes / Jeu",
    purpose: "Écran de l'application : **Mode · Not · Ready**.",
    aliases: ["Mode", "Mode Not Ready", "mode not ready"],
  },
  {
    id: "petanque_menu",
    label: "Pétanque · Menu",
    category: "Pétanque",
    purpose: "Menu de sélection / navigation : **Pétanque · Menu**.",
    aliases: ["Pétanque", "petanque menu", "Pétanque Menu"],
  },
  {
    id: "petanque_config",
    label: "Pétanque · Configuration",
    category: "Pétanque",
    purpose: "Écran de configuration de **Pétanque** : participants et réglages avant le lancement.",
    aliases: ["Pétanque", "Pétanque Configuration", "petanque config"],
  },
  {
    id: "petanque_play",
    label: "Pétanque · Partie",
    category: "Pétanque",
    purpose: "Écran de **partie active** pour Pétanque.",
    aliases: ["Pétanque", "petanque play", "Pétanque Partie"],
  },
  {
    id: "babyfoot_menu",
    label: "Baby-foot · Menu",
    category: "Baby-foot",
    purpose: "Menu de sélection / navigation : **Baby-foot · Menu**.",
    aliases: ["babyfoot menu", "Baby-foot Menu", "Baby-foot"],
  },
  {
    id: "babyfoot_config",
    label: "Baby-foot · Configuration",
    category: "Baby-foot",
    purpose: "Écran de configuration de **Baby-foot** : participants et réglages avant le lancement.",
    aliases: ["babyfoot config", "Baby-foot", "Baby-foot Configuration"],
  },
  {
    id: "babyfoot_play",
    label: "Baby-foot · Partie",
    category: "Baby-foot",
    purpose: "Écran de **partie active** pour Baby-foot.",
    aliases: ["babyfoot play", "Baby-foot", "Baby-foot Partie"],
  },
  {
    id: "babyfoot_end",
    label: "Baby-foot · Fin",
    category: "Baby-foot",
    purpose: "Écran de l'application : **Baby-foot · Fin**.",
    aliases: ["babyfoot end", "Baby-foot", "Baby-foot Fin"],
  },
  {
    id: "babyfoot_stats_history",
    label: "Baby-foot · Stats · Historique",
    category: "Statistiques",
    purpose: "Écran de statistiques / analyse : **Baby-foot · Stats · Historique**.",
    aliases: ["Baby-foot", "babyfoot stats history", "Baby-foot Stats Historique"],
  },
  {
    id: "babyfoot_stats_center",
    label: "Baby-foot · Stats · Center",
    category: "Statistiques",
    purpose: "Écran de statistiques / analyse : **Baby-foot · Stats · Center**.",
    aliases: ["babyfoot stats center", "Baby-foot", "Baby-foot Stats Center"],
  },
  {
    id: "pingpong_menu",
    label: "Ping-Pong · Menu",
    category: "Ping-Pong",
    purpose: "Menu de sélection / navigation : **Ping-Pong · Menu**.",
    aliases: ["Ping-Pong", "Ping-Pong Menu", "pingpong menu"],
  },
  {
    id: "pingpong_config",
    label: "Ping-Pong · Configuration",
    category: "Ping-Pong",
    purpose: "Écran de configuration de **Ping-Pong** : participants et réglages avant le lancement.",
    aliases: ["Ping-Pong Configuration", "Ping-Pong", "pingpong config"],
  },
  {
    id: "pingpong_play",
    label: "Ping-Pong · Partie",
    category: "Ping-Pong",
    purpose: "Écran de **partie active** pour Ping-Pong.",
    aliases: ["Ping-Pong", "Ping-Pong Partie", "pingpong play"],
  },
  {
    id: "pingpong_training",
    label: "Ping-Pong · Training",
    category: "Ping-Pong",
    purpose: "Écran de l'application : **Ping-Pong · Training**.",
    aliases: ["pingpong training", "Ping-Pong Training", "Ping-Pong"],
  },
  {
    id: "pingpong_stats_history",
    label: "Ping-Pong · Stats · Historique",
    category: "Statistiques",
    purpose: "Écran de statistiques / analyse : **Ping-Pong · Stats · Historique**.",
    aliases: ["Ping-Pong", "pingpong stats history", "Ping-Pong Stats Historique"],
  },
  {
    id: "pingpong_match_detail",
    label: "Ping-Pong · Match · Détail",
    category: "Statistiques",
    purpose: "Écran de l'application : **Ping-Pong · Match · Détail**.",
    aliases: ["Ping-Pong", "pingpong match detail", "Ping-Pong Match Détail"],
  },
  {
    id: "petanque_teams",
    label: "Pétanque · Équipes",
    category: "Pétanque",
    purpose: "Écran de l'application : **Pétanque · Équipes**.",
    aliases: ["Pétanque", "petanque teams", "Pétanque Équipes"],
  },
  {
    id: "petanque_team_edit",
    label: "Pétanque · Équipe · Edit",
    category: "Pétanque",
    purpose: "Écran de l'application : **Pétanque · Équipe · Edit**.",
    aliases: ["Pétanque", "petanque team edit", "Pétanque Équipe Edit"],
  },
  {
    id: "petanque_stats_players",
    label: "Pétanque · Stats · Players",
    category: "Statistiques",
    purpose: "Écran de statistiques / analyse : **Pétanque · Stats · Players**.",
    aliases: ["Pétanque", "petanque stats players", "Pétanque Stats Players"],
  },
  {
    id: "petanque_stats_teams",
    label: "Pétanque · Stats · Équipes",
    category: "Statistiques",
    purpose: "Écran de statistiques / analyse : **Pétanque · Stats · Équipes**.",
    aliases: ["Pétanque", "petanque stats teams", "Pétanque Stats Équipes"],
  },
  {
    id: "petanque_stats_leaderboards",
    label: "Pétanque · Stats · Classements",
    category: "Statistiques",
    purpose: "Écran de statistiques / analyse : **Pétanque · Stats · Classements**.",
    aliases: ["Pétanque", "petanque stats leaderboards", "Pétanque Stats Classements"],
  },
  {
    id: "petanque_stats_matches",
    label: "Pétanque · Stats · Matches",
    category: "Statistiques",
    purpose: "Écran de statistiques / analyse : **Pétanque · Stats · Matches**.",
    aliases: ["Pétanque", "petanque stats matches", "Pétanque Stats Matches"],
  },
  {
    id: "petanque_stats_history",
    label: "Pétanque · Stats · Historique",
    category: "Statistiques",
    purpose: "Écran de statistiques / analyse : **Pétanque · Stats · Historique**.",
    aliases: ["Pétanque", "Pétanque Stats Historique", "petanque stats history"],
  },
  {
    id: "petanque_tournaments",
    label: "Pétanque · Tournois",
    category: "Compétitions",
    purpose: "Étape du module de compétition : **Pétanque · Tournois**.",
    aliases: ["Pétanque", "Pétanque Tournois", "petanque tournaments"],
  },
  {
    id: "petanque_tournament_create",
    label: "Pétanque · Tournoi · Création",
    category: "Compétitions",
    purpose: "Étape du module de compétition : **Pétanque · Tournoi · Création**.",
    aliases: ["Pétanque", "Pétanque Tournoi Création", "petanque tournament create"],
  },
  {
    id: "petanque_tournament_view",
    label: "Pétanque · Tournoi · View",
    category: "Compétitions",
    purpose: "Étape du module de compétition : **Pétanque · Tournoi · View**.",
    aliases: ["Pétanque", "Pétanque Tournoi View", "petanque tournament view"],
  },
  {
    id: "petanque_tournament_match_score",
    label: "Pétanque · Tournoi · Match · Score",
    category: "Compétitions",
    purpose: "Étape du module de compétition : **Pétanque · Tournoi · Match · Score**.",
    aliases: ["Pétanque", "petanque tournament match score", "Pétanque Tournoi Match Score"],
  },
  {
    id: "petanque.menu",
    label: "Pétanque · Menu",
    category: "Pétanque",
    purpose: "Menu de sélection / navigation : **Pétanque · Menu**.",
    aliases: ["Pétanque", "petanque.menu", "Pétanque Menu"],
  },
  {
    id: "petanque.config",
    label: "Pétanque · Configuration",
    category: "Pétanque",
    purpose: "Écran de configuration de **Pétanque** : participants et réglages avant le lancement.",
    aliases: ["Pétanque", "petanque.config", "Pétanque Configuration"],
  },
  {
    id: "petanque.play",
    label: "Pétanque · Partie",
    category: "Pétanque",
    purpose: "Écran de **partie active** pour Pétanque.",
    aliases: ["Pétanque", "Pétanque Partie", "petanque.play"],
  },
  {
    id: "tournaments",
    label: "Tournois",
    category: "Compétitions",
    purpose: "Étape du module de compétition : **Tournois**.",
    aliases: ["Tournois", "tournaments"],
  },
  {
    id: "tournament_create",
    label: "Tournoi · Création",
    category: "Compétitions",
    purpose: "Étape du module de compétition : **Tournoi · Création**.",
    aliases: ["tournament create", "Tournoi Création", "Tournoi"],
  },
  {
    id: "tournament_list",
    label: "Tournoi · Liste",
    category: "Compétitions",
    purpose: "Étape du module de compétition : **Tournoi · Liste**.",
    aliases: ["Tournoi", "tournament list", "Tournoi Liste"],
  },
  {
    id: "tournament_compose_teams",
    label: "Tournoi · Compose · Équipes",
    category: "Compétitions",
    purpose: "Étape du module de compétition : **Tournoi · Compose · Équipes**.",
    aliases: ["Tournoi Compose Équipes", "Tournoi", "tournament compose teams"],
  },
  {
    id: "tournament_view",
    label: "Tournoi · View",
    category: "Compétitions",
    purpose: "Étape du module de compétition : **Tournoi · View**.",
    aliases: ["Tournoi", "tournament view", "Tournoi View"],
  },
  {
    id: "tournament_match_play",
    label: "Tournoi · Match · Partie",
    category: "Compétitions",
    purpose: "Écran de **partie active** pour Tournoi · Match.",
    aliases: ["Tournoi", "Tournoi Match Partie", "tournament match play"],
  },
  {
    id: "tournament_roadmap",
    label: "Tournoi · Feuille de route",
    category: "Compétitions",
    purpose: "Étape du module de compétition : **Tournoi · Feuille de route**.",
    aliases: ["Tournoi", "Tournoi Feuille de route", "tournament roadmap"],
  },
  {
    id: "profiles",
    label: "Profils",
    category: "Profils / Social",
    purpose: "Gestion et consultation des **profils joueurs**.",
    aliases: ["Profils", "profiles"],
  },
  {
    id: "profiles_bots",
    label: "BOTS IA",
    category: "Profils / Social",
    purpose: "Gestion des **BOTS IA** et adversaires virtuels.",
    aliases: ["BOTS IA", "profiles bots"],
  },
  {
    id: "friends",
    label: "Amis",
    category: "Profils / Social",
    purpose: "Gestion des amis et relations sociales.",
    aliases: ["friends", "Amis"],
  },
  {
    id: "online",
    label: "Online",
    category: "Profils / Social",
    purpose: "Espace Online : présence, parties et fonctions réseau.",
    aliases: ["Online", "online"],
  },
  {
    id: "messages",
    label: "Messages",
    category: "Profils / Social",
    purpose: "Messagerie de l'application.",
    aliases: ["messages", "Messages"],
  },
  {
    id: "spectator",
    label: "Spectateur",
    category: "Écrans externes",
    purpose: "Écran d'affichage externe ou spectateur : **Spectateur**.",
    aliases: ["Spectateur", "spectator"],
  },
  {
    id: "settings",
    label: "Réglages",
    category: "Outils",
    purpose: "Réglages généraux de l'application.",
    aliases: ["Réglages", "settings"],
  },
  {
    id: "stats",
    label: "Stats",
    category: "Statistiques",
    purpose: "Écran de statistiques / analyse : **Stats**.",
    aliases: ["stats", "Stats"],
  },
  {
    id: "statsHub",
    label: "Stats Hub",
    category: "Statistiques",
    purpose: "Écran de statistiques / analyse : **Stats Hub**.",
    aliases: ["statsHub", "Stats Hub"],
  },
  {
    id: "stats_online",
    label: "Stats · Online",
    category: "Statistiques",
    purpose: "Écran de statistiques / analyse : **Stats · Online**.",
    aliases: ["stats online", "Stats Online", "Stats"],
  },
  {
    id: "cricket_stats",
    label: "Cricket · Stats",
    category: "Statistiques",
    purpose: "Écran de statistiques / analyse : **Cricket · Stats**.",
    aliases: ["cricket stats", "Cricket Stats", "Cricket"],
  },
  {
    id: "cricket_match_detail",
    label: "Cricket · Match · Détail",
    category: "Statistiques",
    purpose: "Écran de l'application : **Cricket · Match · Détail**.",
    aliases: ["Cricket", "Cricket Match Détail", "cricket match detail"],
  },
  {
    id: "statsDetail",
    label: "Détail statistiques",
    category: "Statistiques",
    purpose: "Écran de statistiques / analyse : **Détail statistiques**.",
    aliases: ["statsDetail", "Détail statistiques"],
  },
  {
    id: "stats_leaderboards",
    label: "Stats · Classements",
    category: "Statistiques",
    purpose: "Écran de statistiques / analyse : **Stats · Classements**.",
    aliases: ["stats leaderboards", "Stats Classements", "Stats"],
  },
  {
    id: "x01setup",
    label: "X01 · Configuration legacy",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **X01 legacy** : participants et réglages avant le lancement.",
    aliases: ["x01setup", "X01", "X01 Configuration legacy"],
  },
  {
    id: "x01_online_setup",
    label: "X01 · Online · Setup",
    category: "Fléchettes / Jeu",
    purpose: "Écran de l'application : **X01 · Online · Setup**.",
    aliases: ["X01", "x01 online setup", "X01 Online Setup"],
  },
  {
    id: "x01",
    label: "X01",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour X01.",
    aliases: ["X01", "x01"],
  },
  {
    id: "x01_end",
    label: "X01 · Fin de partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de l'application : **X01 · Fin de partie**.",
    aliases: ["X01", "x01 end", "X01 Fin de partie"],
  },
  {
    id: "cricket",
    label: "Cricket",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Cricket.",
    aliases: ["Cricket", "cricket"],
  },
  {
    id: "killer",
    label: "Killer",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Killer.",
    aliases: ["Killer", "killer"],
  },
  {
    id: "killer_config",
    label: "Killer · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Killer** : participants et réglages avant le lancement.",
    aliases: ["Killer", "Killer Configuration", "killer config"],
  },
  {
    id: "killer_play",
    label: "Killer · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Killer.",
    aliases: ["Killer", "Killer Partie", "killer play"],
  },
  {
    id: "killer_summary",
    label: "Killer · Résumé",
    category: "Fléchettes / Jeu",
    purpose: "Écran de l'application : **Killer · Résumé**.",
    aliases: ["Killer", "killer summary", "Killer Résumé"],
  },
  {
    id: "five_lives_config",
    label: "Les 5 vies · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Les 5 vies** : participants et réglages avant le lancement.",
    aliases: ["Les 5 vies Configuration", "Les 5 vies", "five lives config"],
  },
  {
    id: "five_lives_play",
    label: "Les 5 vies · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Les 5 vies.",
    aliases: ["Les 5 vies Partie", "Les 5 vies", "five lives play"],
  },
  {
    id: "shanghai",
    label: "Shanghai",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Shanghai.",
    aliases: ["shanghai", "Shanghai"],
  },
  {
    id: "shanghai_play",
    label: "Shanghai · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Shanghai.",
    aliases: ["Shanghai", "Shanghai Partie", "shanghai play"],
  },
  {
    id: "warfare_config",
    label: "Warfare · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Warfare** : participants et réglages avant le lancement.",
    aliases: ["warfare config", "Warfare Configuration", "Warfare"],
  },
  {
    id: "warfare_play",
    label: "Warfare · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Warfare.",
    aliases: ["warfare play", "Warfare", "Warfare Partie"],
  },
  {
    id: "battle_royale",
    label: "Battle · Royale",
    category: "Fléchettes / Jeu",
    purpose: "Écran de l'application : **Battle · Royale**.",
    aliases: ["Battle Royale", "battle royale", "Battle"],
  },
  {
    id: "battle_royale_play",
    label: "Battle · Royale · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Battle · Royale.",
    aliases: ["Battle Royale Partie", "battle royale play", "Battle"],
  },
  {
    id: "training",
    label: "Training",
    category: "Training",
    purpose: "Menu de sélection / navigation : **Training**.",
    aliases: ["Training", "training"],
  },
  {
    id: "training_x01",
    label: "Training · X01",
    category: "Training",
    purpose: "Écran de l'application : **Training · X01**.",
    aliases: ["Training X01", "training x01", "Training"],
  },
  {
    id: "training_x01_play",
    label: "Training · X01 · Partie",
    category: "Training",
    purpose: "Écran de **partie active** pour Training · X01.",
    aliases: ["Training", "training x01 play", "Training X01 Partie"],
  },
  {
    id: "training_stats",
    label: "Training · Stats",
    category: "Statistiques",
    purpose: "Écran de statistiques / analyse : **Training · Stats**.",
    aliases: ["Training", "training stats", "Training Stats"],
  },
  {
    id: "training_clock",
    label: "Training · Clock",
    category: "Training",
    purpose: "Écran de l'application : **Training · Clock**.",
    aliases: ["training clock", "Training Clock", "Training"],
  },
  {
    id: "training_mode",
    label: "Training · Mode",
    category: "Training",
    purpose: "Écran de l'application : **Training · Mode**.",
    aliases: ["Training Mode", "Training", "training mode"],
  },
  {
    id: "avatar",
    label: "Avatar",
    category: "Profils / Social",
    purpose: "Écran de l'application : **Avatar**.",
    aliases: ["Avatar", "avatar"],
  },
  {
    id: "x01_config_v3",
    label: "X01 · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **X01** : participants et réglages avant le lancement.",
    aliases: ["x01 config v3", "X01", "X01 Configuration"],
  },
  {
    id: "x01_play_v3",
    label: "X01 · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour X01.",
    aliases: ["X01", "X01 Partie", "x01 play v3"],
  },
  {
    id: "camera_scoring_setup",
    label: "Scoring caméra",
    category: "Outils",
    purpose: "Écran de l'application : **Scoring caméra**.",
    aliases: ["Scoring caméra", "camera scoring setup"],
  },
  {
    id: "camera_scoring_calibration",
    label: "Calibration caméra",
    category: "Outils",
    purpose: "Écran de l'application : **Calibration caméra**.",
    aliases: ["camera scoring calibration", "Calibration caméra"],
  },
  {
    id: "x01_device_camera",
    label: "Téléphone compagnon X01",
    category: "Outils",
    purpose: "Écran de l'application : **Téléphone compagnon X01**.",
    aliases: ["Téléphone compagnon X01", "x01 device camera"],
  },
  {
    id: "sync_center",
    label: "Synchronisation",
    category: "Outils",
    purpose: "Centre de synchronisation, sauvegarde et restauration.",
    aliases: ["sync center", "Synchronisation"],
  },
  {
    id: "auth_callback",
    label: "Compte · Callback",
    category: "Compte",
    purpose: "Étape de compte / authentification : **Compte · Callback**.",
    aliases: ["auth callback", "Compte", "Compte Callback"],
  },
  {
    id: "darts_mode_config",
    label: "Darts · Mode · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Darts · Mode** : participants et réglages avant le lancement.",
    aliases: ["darts mode config", "Darts", "Darts Mode Configuration"],
  },
  {
    id: "darts_mode_play",
    label: "Darts · Mode · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Darts · Mode.",
    aliases: ["darts mode play", "Darts Mode Partie", "Darts"],
  },
  {
    id: "darts_mode_summary",
    label: "Darts · Mode · Résumé",
    category: "Fléchettes / Jeu",
    purpose: "Écran de l'application : **Darts · Mode · Résumé**.",
    aliases: ["Darts Mode Résumé", "Darts", "darts mode summary"],
  },
  {
    id: "halve_it_config",
    label: "Halve · It · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Halve · It** : participants et réglages avant le lancement.",
    aliases: ["Halve It Configuration", "halve it config", "Halve"],
  },
  {
    id: "halve_it_play",
    label: "Halve · It · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Halve · It.",
    aliases: ["Halve", "halve it play", "Halve It Partie"],
  },
  {
    id: "count_up_config",
    label: "Count · Up · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Count · Up** : participants et réglages avant le lancement.",
    aliases: ["Count", "Count Up Configuration", "count up config"],
  },
  {
    id: "count_up_play",
    label: "Count · Up · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Count · Up.",
    aliases: ["Count Up Partie", "Count", "count up play"],
  },
  {
    id: "prisoner_config",
    label: "Prisoner · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Prisoner** : participants et réglages avant le lancement.",
    aliases: ["Prisoner", "Prisoner Configuration", "prisoner config"],
  },
  {
    id: "prisoner_play",
    label: "Prisoner · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Prisoner.",
    aliases: ["Prisoner", "prisoner play", "Prisoner Partie"],
  },
  {
    id: "super_bull_config",
    label: "Super · Bull · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Super · Bull** : participants et réglages avant le lancement.",
    aliases: ["super bull config", "Super", "Super Bull Configuration"],
  },
  {
    id: "super_bull_play",
    label: "Super · Bull · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Super · Bull.",
    aliases: ["Super", "super bull play", "Super Bull Partie"],
  },
  {
    id: "shooter_config",
    label: "Shooter · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Shooter** : participants et réglages avant le lancement.",
    aliases: ["Shooter Configuration", "Shooter", "shooter config"],
  },
  {
    id: "shooter_play",
    label: "Shooter · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Shooter.",
    aliases: ["shooter play", "Shooter", "Shooter Partie"],
  },
  {
    id: "darts_racer_config",
    label: "Darts · Racer · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Darts · Racer** : participants et réglages avant le lancement.",
    aliases: ["Darts Racer Configuration", "Darts", "darts racer config"],
  },
  {
    id: "darts_racer_play",
    label: "Darts · Racer · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Darts · Racer.",
    aliases: ["darts racer play", "Darts", "Darts Racer Partie"],
  },
  {
    id: "tic_tac_toe_config",
    label: "Tic · Tac · Toe · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Tic · Tac · Toe** : participants et réglages avant le lancement.",
    aliases: ["Tic", "tic tac toe config", "Tic Tac Toe Configuration"],
  },
  {
    id: "tic_tac_toe_play",
    label: "Tic · Tac · Toe · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Tic · Tac · Toe.",
    aliases: ["Tic", "Tic Tac Toe Partie", "tic tac toe play"],
  },
  {
    id: "knockout_config",
    label: "Knockout · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Knockout** : participants et réglages avant le lancement.",
    aliases: ["Knockout Configuration", "Knockout", "knockout config"],
  },
  {
    id: "knockout_play",
    label: "Knockout · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Knockout.",
    aliases: ["Knockout", "Knockout Partie", "knockout play"],
  },
  {
    id: "bobs_27_config",
    label: "Bob's · 27 · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Bob's · 27** : participants et réglages avant le lancement.",
    aliases: ["Bob's", "Bob's 27 Configuration", "bobs 27 config"],
  },
  {
    id: "bobs_27_play",
    label: "Bob's · 27 · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Bob's · 27.",
    aliases: ["Bob's", "Bob's 27 Partie", "bobs 27 play"],
  },
  {
    id: "bowling_config",
    label: "Bowling · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Bowling** : participants et réglages avant le lancement.",
    aliases: ["Bowling", "Bowling Configuration", "bowling config"],
  },
  {
    id: "bowling_play",
    label: "Bowling · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Bowling.",
    aliases: ["bowling play", "Bowling", "Bowling Partie"],
  },
  {
    id: "scram_config",
    label: "Scram · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Scram** : participants et réglages avant le lancement.",
    aliases: ["scram config", "Scram Configuration", "Scram"],
  },
  {
    id: "scram_play",
    label: "Scram · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Scram.",
    aliases: ["Scram", "scram play", "Scram Partie"],
  },
  {
    id: "golf_config",
    label: "Golf · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Golf** : participants et réglages avant le lancement.",
    aliases: ["golf config", "Golf Configuration", "Golf"],
  },
  {
    id: "golf_play",
    label: "Golf · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Golf.",
    aliases: ["Golf", "Golf Partie", "golf play"],
  },
  {
    id: "baseball_config",
    label: "Baseball · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Baseball** : participants et réglages avant le lancement.",
    aliases: ["Baseball", "Baseball Configuration", "baseball config"],
  },
  {
    id: "baseball_play",
    label: "Baseball · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Baseball.",
    aliases: ["Baseball", "Baseball Partie", "baseball play"],
  },
  {
    id: "attrape_moi_config",
    label: "Attrape-moi si tu peux · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Attrape-moi si tu peux** : participants et réglages avant le lancement.",
    aliases: ["Attrape-moi si tu peux Configuration", "Attrape-moi si tu peux", "attrape moi config"],
  },
  {
    id: "attrape_moi_play",
    label: "Attrape-moi si tu peux · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Attrape-moi si tu peux.",
    aliases: ["Attrape-moi si tu peux Partie", "Attrape-moi si tu peux", "attrape moi play"],
  },
  {
    id: "president_config",
    label: "Président · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Président** : participants et réglages avant le lancement.",
    aliases: ["Président Configuration", "president config", "Président"],
  },
  {
    id: "president_play",
    label: "Président · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Président.",
    aliases: ["Président Partie", "president play", "Président"],
  },
  {
    id: "game_170_config",
    label: "170 · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **170** : participants et réglages avant le lancement.",
    aliases: ["170 Configuration", "game 170 config", "170"],
  },
  {
    id: "game_170_play",
    label: "170 · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour 170.",
    aliases: ["170", "170 Partie", "game 170 play"],
  },
  {
    id: "foot_menu",
    label: "Football · Menu",
    category: "Football",
    purpose: "Menu de sélection / navigation : **Football · Menu**.",
    aliases: ["foot menu", "Football Menu", "Football"],
  },
  {
    id: "foot_config",
    label: "Football · Configuration",
    category: "Football",
    purpose: "Écran de configuration de **Football** : participants et réglages avant le lancement.",
    aliases: ["Football Configuration", "foot config", "Football"],
  },
  {
    id: "foot_play",
    label: "Football · Partie",
    category: "Football",
    purpose: "Écran de **partie active** pour Football.",
    aliases: ["Football", "Football Partie", "foot play"],
  },
  {
    id: "football_config",
    label: "Football · Configuration",
    category: "Football",
    purpose: "Écran de configuration de **Football** : participants et réglages avant le lancement.",
    aliases: ["football config", "Football Configuration", "Football"],
  },
  {
    id: "football_play",
    label: "Football · Partie",
    category: "Football",
    purpose: "Écran de **partie active** pour Football.",
    aliases: ["Football Partie", "football play", "Football"],
  },
  {
    id: "batard_config",
    label: "Batard · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Batard** : participants et réglages avant le lancement.",
    aliases: ["batard config", "Batard", "Batard Configuration"],
  },
  {
    id: "batard_play",
    label: "Batard · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Batard.",
    aliases: ["Batard", "Batard Partie", "batard play"],
  },
  {
    id: "fun_gages_config",
    label: "Fun · Gages · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Fun · Gages** : participants et réglages avant le lancement.",
    aliases: ["fun gages config", "Fun Gages Configuration", "Fun"],
  },
  {
    id: "fun_gages_play",
    label: "Fun · Gages · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Fun · Gages.",
    aliases: ["Fun Gages Partie", "fun gages play", "Fun"],
  },
  {
    id: "capital_config",
    label: "Capital · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Capital** : participants et réglages avant le lancement.",
    aliases: ["capital config", "Capital", "Capital Configuration"],
  },
  {
    id: "capital_play",
    label: "Capital · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Capital.",
    aliases: ["capital play", "Capital", "Capital Partie"],
  },
  {
    id: "loterie_config",
    label: "Loterie · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Loterie** : participants et réglages avant le lancement.",
    aliases: ["loterie config", "Loterie Configuration", "Loterie"],
  },
  {
    id: "loterie_play",
    label: "Loterie · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Loterie.",
    aliases: ["Loterie Partie", "loterie play", "Loterie"],
  },
  {
    id: "happy_mille_config",
    label: "Happy · Mille · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Happy · Mille** : participants et réglages avant le lancement.",
    aliases: ["Happy", "Happy Mille Configuration", "happy mille config"],
  },
  {
    id: "happy_mille_play",
    label: "Happy · Mille · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Happy · Mille.",
    aliases: ["Happy", "happy mille play", "Happy Mille Partie"],
  },
  {
    id: "rugby_config",
    label: "Rugby · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Rugby** : participants et réglages avant le lancement.",
    aliases: ["Rugby", "Rugby Configuration", "rugby config"],
  },
  {
    id: "rugby_play",
    label: "Rugby · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Rugby.",
    aliases: ["rugby play", "Rugby Partie", "Rugby"],
  },
  {
    id: "departements_config",
    label: "Departements · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Departements** : participants et réglages avant le lancement.",
    aliases: ["Departements Configuration", "departements config", "Departements"],
  },
  {
    id: "departements_play",
    label: "Departements · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Departements.",
    aliases: ["departements play", "Departements Partie", "Departements"],
  },
  {
    id: "darts_firefighter_config",
    label: "Darts Firefighter · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Darts Firefighter** : participants et réglages avant le lancement.",
    aliases: ["Darts Firefighter Configuration", "darts firefighter config", "Darts Firefighter"],
  },
  {
    id: "darts_firefighter_play",
    label: "Darts Firefighter · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Darts Firefighter.",
    aliases: ["Darts Firefighter", "darts firefighter play", "Darts Firefighter Partie"],
  },
  {
    id: "darts_poker_config",
    label: "Darts Poker · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Darts Poker** : participants et réglages avant le lancement.",
    aliases: ["Darts Poker", "Darts Poker Configuration", "darts poker config"],
  },
  {
    id: "darts_poker_play",
    label: "Darts Poker · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Darts Poker.",
    aliases: ["darts poker play", "Darts Poker", "Darts Poker Partie"],
  },
  {
    id: "cargo_config",
    label: "CARGO · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **CARGO** : participants et réglages avant le lancement.",
    aliases: ["CARGO", "cargo config", "CARGO Configuration"],
  },
  {
    id: "cargo_play",
    label: "CARGO · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour CARGO.",
    aliases: ["CARGO", "cargo play", "CARGO Partie"],
  },
  {
    id: "ocean_control_config",
    label: "Ocean Control · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Ocean Control** : participants et réglages avant le lancement.",
    aliases: ["Ocean Control Configuration", "Ocean Control", "ocean control config"],
  },
  {
    id: "ocean_control_play",
    label: "Ocean Control · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Ocean Control.",
    aliases: ["ocean control play", "Ocean Control", "Ocean Control Partie"],
  },
  {
    id: "enculette_config",
    label: "Enculette · Configuration",
    category: "Fléchettes / Jeu",
    purpose: "Écran de configuration de **Enculette** : participants et réglages avant le lancement.",
    aliases: ["Enculette", "enculette config", "Enculette Configuration"],
  },
  {
    id: "enculette_play",
    label: "Enculette · Partie",
    category: "Fléchettes / Jeu",
    purpose: "Écran de **partie active** pour Enculette.",
    aliases: ["Enculette", "enculette play", "Enculette Partie"],
  },
  {
    id: "auth_reset",
    label: "Compte · Réinitialisation",
    category: "Compte",
    purpose: "Étape de compte / authentification : **Compte · Réinitialisation**.",
    aliases: ["auth reset", "Compte", "Compte Réinitialisation"],
  },
  // AWENA V8.3 — routes ajoutées dans App.tsx après la génération précédente.
  {
    id: 'babyfoot_league',
    label: 'Baby-foot · Ligue',
    category: 'Baby-foot',
    purpose: 'Module Ligue Baby-foot : saison, matchs et classement local.',
    aliases: ['babyfoot_league', 'Baby-foot · Ligue', 'Baby-foot Ligue'],
  },
  {
    id: 'babyfoot_teams',
    label: 'Baby-foot · Équipes',
    category: 'Baby-foot',
    purpose: 'Gestion des équipes Baby-foot enregistrées.',
    aliases: ['babyfoot_teams', 'Baby-foot · Équipes', 'Baby-foot Équipes'],
  },
  {
    id: 'babyfoot_team_edit',
    label: 'Baby-foot · Équipe · Édition',
    category: 'Baby-foot',
    purpose: 'Création / modification d’une équipe Baby-foot et de sa composition.',
    aliases: ['babyfoot_team_edit', 'Baby-foot · Équipe · Édition', 'Baby-foot Équipe Édition'],
  },
  {
    id: 'molkky_menu',
    label: 'Mölkky · Menu',
    category: 'Mölkky',
    purpose: 'Menu de sélection des modes Mölkky.',
    aliases: ['molkky_menu', 'Mölkky · Menu', 'Mölkky Menu'],
  },
  {
    id: 'molkky_config',
    label: 'Mölkky · Configuration',
    category: 'Mölkky',
    purpose: 'Configuration Mölkky : participants, objectif et règles de dépassement / MISS.',
    aliases: ['molkky_config', 'Mölkky · Configuration', 'Mölkky Configuration'],
  },
  {
    id: 'molkky_play',
    label: 'Mölkky · Partie',
    category: 'Mölkky',
    purpose: 'Écran de partie active Mölkky.',
    aliases: ['molkky_play', 'Mölkky · Partie', 'Mölkky Partie'],
  },
  {
    id: 'dice_menu',
    label: 'Dés · Menu',
    category: 'Dés',
    purpose: 'Menu des jeux de dés : Duel, Race, 10 000, YAM, Farkle, 421 et Poker Dice.',
    aliases: ['dice_menu', 'Dés · Menu', 'Dés Menu'],
  },
  {
    id: 'dice_config',
    label: 'Dés · Configuration',
    category: 'Dés',
    purpose: 'Configuration générique de Dice Duel, Dice Race et 10 000.',
    aliases: ['dice_config', 'Dés · Configuration', 'Dés Configuration'],
  },
  {
    id: 'dice_play',
    label: 'Dés · Partie',
    category: 'Dés',
    purpose: 'Écran de partie pour les modes de dés génériques.',
    aliases: ['dice_play', 'Dés · Partie', 'Dés Partie'],
  },
  {
    id: 'dice_yams_config',
    label: 'YAM · Configuration',
    category: 'Dés',
    purpose: 'Configuration YAM : joueurs, dés, relances, rounds / catégories et sets.',
    aliases: ['dice_yams_config', 'YAM · Configuration', 'YAM Configuration'],
  },
  {
    id: 'dice_yams_play',
    label: 'YAM · Partie',
    category: 'Dés',
    purpose: 'Écran de partie YAM et scorecard.',
    aliases: ['dice_yams_play', 'YAM · Partie', 'YAM Partie'],
  },
  {
    id: 'dice_farkle_config',
    label: 'Farkle · Configuration',
    category: 'Dés',
    purpose: 'Configuration Farkle : cible, dés, sets et options expérimentales.',
    aliases: ['dice_farkle_config', 'Farkle · Configuration', 'Farkle Configuration'],
  },
  {
    id: 'dice_421_config',
    label: '421 · Configuration',
    category: 'Dés',
    purpose: 'Configuration 421 : rounds, sets et options d’annonce / pénalité.',
    aliases: ['dice_421_config', '421 · Configuration', '421 Configuration'],
  },
  {
    id: 'dice_poker_config',
    label: 'Poker Dice · Configuration',
    category: 'Dés',
    purpose: 'Configuration Poker Dice : rounds, relances, sets et options de combinaison.',
    aliases: ['dice_poker_config', 'Poker Dice · Configuration', 'Poker Dice Configuration'],
  },
  {
    id: 'dice_soon_play',
    label: 'Dés · Mode en préparation',
    category: 'Dés',
    purpose: 'Écran utilisé pour un mode de dés dont certaines mécaniques restent à finaliser.',
    aliases: ['dice_soon_play', 'Dés · Mode en préparation', 'Dés Mode en préparation'],
  },
  {
    id: 'molkky_stats',
    label: 'Mölkky · Stats',
    category: 'Statistiques',
    purpose: 'Centre de statistiques Mölkky.',
    aliases: ['molkky_stats', 'Mölkky · Stats', 'Mölkky Stats'],
  },
  {
    id: 'molkky_stats_history',
    label: 'Mölkky · Stats · Historique',
    category: 'Statistiques',
    purpose: 'Historique des parties Mölkky enregistrées.',
    aliases: ['molkky_stats_history', 'Mölkky · Stats · Historique', 'Mölkky Stats Historique'],
  },
  {
    id: 'molkky_stats_leaderboards',
    label: 'Mölkky · Stats · Classements',
    category: 'Statistiques',
    purpose: 'Classements / leaderboards Mölkky.',
    aliases: ['molkky_stats_leaderboards', 'Mölkky · Stats · Classements', 'Mölkky Stats Classements'],
  },
  {
    id: 'molkky_stats_players',
    label: 'Mölkky · Stats · Joueurs',
    category: 'Statistiques',
    purpose: 'Statistiques Mölkky par joueur.',
    aliases: ['molkky_stats_players', 'Mölkky · Stats · Joueurs', 'Mölkky Stats Joueurs'],
  },
  {
    id: 'molkky_stats_locals',
    label: 'Mölkky · Stats · Locales',
    category: 'Statistiques',
    purpose: 'Vue locale des statistiques Mölkky.',
    aliases: ['molkky_stats_locals', 'Mölkky · Stats · Locales', 'Mölkky Stats Locales'],
  },
  {
    id: 'online_clubs',
    label: 'Online · Clubs',
    category: 'Online',
    purpose: 'Espace des clubs Online.',
    aliases: ['online_clubs', 'Online · Clubs', 'Online Clubs'],
  },
  {
    id: 'babyfoot_stats_teams',
    label: 'Baby-foot · Stats · Équipes',
    category: 'Statistiques',
    purpose: 'Statistiques Baby-foot par équipe.',
    aliases: ['babyfoot_stats_teams', 'Baby-foot · Stats · Équipes', 'Baby-foot Stats Équipes'],
  },
  {
    id: 'storage_vault',
    label: 'Coffre · Stockage',
    category: 'Stockage',
    purpose: 'Coffre de stockage / sauvegardes et gestion des données.',
    aliases: ['storage_vault', 'Coffre · Stockage', 'Coffre Stockage'],
  },
  {
    id: 'tournament_match_result',
    label: 'Tournoi · Résultat de match',
    category: 'Compétitions',
    purpose: 'Saisie / validation du résultat d’un match de tournoi.',
    aliases: ['tournament_match_result', 'Tournoi · Résultat de match', 'Tournoi Résultat de match'],
  },
  {
    id: 'shanghai_end',
    label: 'Shanghai · Fin',
    category: 'Fléchettes / Jeu',
    purpose: 'Écran de fin de partie Shanghai avec résultat / résumé.',
    aliases: ['shanghai_end', 'Shanghai · Fin', 'Shanghai Fin'],
  },

];

function scoreRoute(question: string, entry: RouteEntry) {
  const q = norm(question);
  let score = 0;
  const candidates = [entry.id, entry.label, ...entry.aliases].map(norm).filter(Boolean);
  for (const alias of candidates) {
    if (q === alias) score = Math.max(score, 100);
    else if (alias.length >= 3 && q.includes(alias)) score = Math.max(score, 68 + Math.min(20, alias.length / 2));
  }
  const qTokens = new Set(tokens(q));
  const eTokens = new Set(tokens(candidates.join(" ")));
  let overlap = 0;
  for (const token of qTokens) if (eTokens.has(token)) overlap += 1;
  score += overlap * 10;
  return score;
}

function navigationIntent(q: string) {
  return /ou (?:est|sont)|ou trouver|ou aller|comment ouvrir|comment acceder|comment accéder|comment aller|emmene moi|amene moi|ouvre|lance|quelle page|quel ecran|quel écran|a quoi sert cette page|à quoi sert cette page/.test(norm(q));
}

export function answerAwenaRouteAtlas(question: string): AwenaReply | null {
  const q = norm(question);
  if (!q) return null;
  let best: { entry: RouteEntry; score: number } | null = null;
  for (const entry of ROUTES) {
    const score = scoreRoute(q, entry);
    if (!best || score > best.score) best = { entry, score };
  }
  if (!best || best.score < (navigationIntent(q) ? 28 : 72)) return null;

  const action: AwenaAction = {
    id: `route-atlas-${best.entry.id}`,
    label: `Ouvrir ${best.entry.label}`,
    kind: "navigate",
    route: best.entry.id,
  };

  return {
    knowledgeTopic: `route:${best.entry.id}`,
    text: `## ${best.entry.label.toUpperCase()}
${best.entry.purpose}

## OÙ LE TROUVER
Je peux ouvrir directement cet écran avec le bouton ci-dessous.

> Cet index est construit à partir des routes réellement présentes dans l'application actuelle.`,
    actions: [action],
  };
}

export function awenaRouteAtlasCount() {
  return ROUTES.length;
}
