import type { AwenaReply, AwenaRuntimeContext } from "./awena.types";

type DiagnosticV90Entry = {
  id: string; domain: string; title: string; aliases: string[];
  causes: string[]; checks: string[]; fixes: string[]; avoid: string[];
};

const STOP = new Set(["a","au","aux","avec","ce","ces","cette","de","des","du","dans","et","est","en","je","la","le","les","ma","mes","mon","ne","nous","on","ou","pour","que","quel","quelle","qui","quoi","se","son","sur","ta","te","tes","ton","tu","un","une","vos","votre","comment","faire","moi","awena","application","appli","probleme","problème","marche","fonctionne"]);
function norm(v: string) { return String(v||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[’']/g," ").replace(/[_/\\.-]+/g," ").replace(/[^a-z0-9+%\s]/g," ").replace(/\s+/g," ").trim(); }
function toks(v: string) { return norm(v).split(" ").filter(t=>t.length>1 && !STOP.has(t)); }
function bullets(v:string[]) { return v.map(x=>`- ${x}`).join("\n"); }
function numbered(v:string[]) { return v.map((x,i)=>`${i+1}. ${x}`).join("\n"); }
const ENTRIES: DiagnosticV90Entry[] = [
  {
    id: "v90-app-freeze-nav",
    domain: "performance",
    title: "Navigation lente ou écran qui fige",
    aliases: ["navigation lente", "ecran fige", "app freeze", "tap retard", "navigation lente ou écran qui fige"],
    causes: ["Rendu React trop coûteux ou boucle de rerenders.", "Chargement IndexedDB ou médias déclenché sur le thread principal.", "Listener/timer dupliqué après plusieurs navigations."],
    checks: ["Reproduis sur le même parcours et note l’écran exact.", "Vérifie si le retard apparaît avant ou après l’affichage visuel.", "Observe si le problème augmente après plusieurs allers-retours."],
    fixes: ["Tester une navigation fraîche après redémarrage.", "Comparer avec médias/avatars déjà en cache.", "Profiler les rerenders et accès données avant de supprimer des fonctions."],
    avoid: ["Ne vide pas les données utilisateur pour tester un simple problème de rendu."],
  },
  {
    id: "v90-double-input",
    domain: "performance",
    title: "Appui enregistré deux fois ou saisie retardée",
    aliases: ["double clic", "double saisie", "deux fois", "tap double", "score double", "appui enregistré deux fois ou saisie retardée"],
    causes: ["Deux handlers écoutent le même événement.", "Un clic est rejoué après un rendu ou une reconnexion.", "Absence de debounce/verrou pendant une action asynchrone."],
    checks: ["Vérifie si deux événements sont enregistrés dans l’historique.", "Teste avec un seul appui lent.", "Compare après navigation vers l’écran puis retour."],
    fixes: ["Ajouter une garde/idempotence sur l’action.", "Désactiver temporairement le contrôle pendant validation.", "Nettoyer les listeners lors du démontage."],
    avoid: ["Ne compense pas en supprimant arbitrairement une ligne d’historique sans comprendre la source."],
  },
  {
    id: "v90-profiles-disappear",
    domain: "data",
    title: "Profils visibles puis disparus",
    aliases: ["profils disparaissent", "avatars apparaissent puis disparaissent", "liste profils vide", "profils visibles puis disparus"],
    causes: ["Une réhydratation tardive remplace un état déjà chargé par un tableau vide.", "Deux sources locales sont fusionnées dans le mauvais ordre.", "Un filtre de profil actif masque involontairement les autres."],
    checks: ["Observe si les profils apparaissent juste après ouverture.", "Compare Profils et sélecteur X01.", "Vérifie si changer de filtre ou de profil actif modifie la liste."],
    fixes: ["Conserver la source locale valide pendant la réhydratation.", "Fusionner sans écraser par une réponse vide.", "Rendre le cache stable entre écrans."],
    avoid: ["Ne réinitialise pas IndexedDB tant qu’une sauvegarde n’est pas vérifiée."],
  },
  {
    id: "v90-avatar-missing-one-screen",
    domain: "data",
    title: "Avatar visible sur un écran mais absent sur un autre",
    aliases: ["avatar manquant", "photo profil absente", "avatar pas partout", "avatar visible sur un écran mais absent sur un autre"],
    causes: ["Les écrans utilisent deux résolveurs d’avatar différents.", "L’URL blob/cache n’est plus valide après navigation.", "Une copie de profil ne transporte pas la référence média."],
    checks: ["Compare le même profil sur deux écrans.", "Vérifie si le fallback initiales apparaît.", "Recharge uniquement l’écran concerné."],
    fixes: ["Centraliser la résolution d’avatar.", "Conserver une référence média stable.", "Précharger ou mettre en cache l’asset avant affichage."],
    avoid: ["Évite de dupliquer les images pour masquer le problème."],
  },
  {
    id: "v90-dartset-slow",
    domain: "performance",
    title: "Dartsets lents à charger",
    aliases: ["dartset lent", "images flechettes lentes", "set darts met du temps", "dartsets lents à charger"],
    causes: ["Images trop lourdes ou décodées à chaque rendu.", "Accès IndexedDB répété pour chaque carte.", "Absence de cache mémoire ou miniature."],
    checks: ["Teste avec la liste déjà ouverte une seconde fois.", "Compare nombre de dartsets.", "Observe si le ralentissement vient de l’image ou de toute la page."],
    fixes: ["Créer des miniatures optimisées.", "Charger les métadonnées en lot.", "Réutiliser le cache entre Profils et X01Config."],
    avoid: ["Ne remplace pas les assets sans mettre à jour toutes leurs références."],
  },
  {
    id: "v90-stats-empty",
    domain: "stats",
    title: "Statistiques vides malgré des parties jouées",
    aliases: ["stats vides", "aucune statistique", "historique existe mais stats vide", "statistiques vides malgré des parties jouées"],
    causes: ["Le filtre de mode/période exclut les parties.", "Les événements nécessaires n’ont pas été enregistrés.", "La page lit une ancienne source de données."],
    checks: ["Vérifie l’Historique brut.", "Retire les filtres temporaires.", "Compare le mode exact enregistré dans la partie."],
    fixes: ["Reconstruire les stats depuis la source historique si possible.", "Harmoniser les identifiants de modes.", "Afficher clairement lorsqu’une ancienne partie ne contient pas assez de détails."],
    avoid: ["Ne fabrique pas de statistiques manquantes à partir de suppositions."],
  },
  {
    id: "v90-stats-inconsistent",
    domain: "stats",
    title: "Deux écrans affichent des statistiques différentes",
    aliases: ["stats incoherentes", "moyenne differente", "deux valeurs differentes", "deux écrans affichent des statistiques différentes"],
    causes: ["Définition différente de la métrique.", "Période ou filtre différent.", "Agrégation par match, leg ou volée non alignée."],
    checks: ["Note les deux valeurs et leurs filtres.", "Vérifie population, mode et période.", "Compare la formule utilisée."],
    fixes: ["Définir une source/formule commune.", "Afficher les unités et périmètres.", "Ajouter un test de non-régression sur une partie connue."],
    avoid: ["Une moyenne différente n’est pas forcément un bug si le périmètre diffère."],
  },
  {
    id: "v90-history-not-saved",
    domain: "data",
    title: "Partie terminée mais absente de l’historique",
    aliases: ["partie pas enregistree", "historique manque match", "fin non sauvegardee", "partie terminée mais absente de l’historique"],
    causes: ["Écriture interrompue avant la fin.", "Navigation quitte l’écran avant validation.", "Erreur de schéma ou transaction locale."],
    checks: ["Vérifie si le résumé de fin a été affiché.", "Cherche une trace dans la base locale.", "Teste une petite partie de reproduction."],
    fixes: ["Rendre la sauvegarde idempotente.", "Attendre la confirmation avant navigation finale.", "Journaliser l’échec sans bloquer le joueur."],
    avoid: ["Ne rejoue pas manuellement une partie réelle sans l’identifier comme correction."],
  },
  {
    id: "v90-language-reset",
    domain: "app",
    title: "La langue revient toute seule à une autre valeur",
    aliases: ["langue revient francais", "language reset", "anglais repasse francais", "la langue revient toute seule à une autre valeur"],
    causes: ["Settings et profil actif stockent deux préférences concurrentes.", "Une réhydratation tardive écrase le choix récent.", "Une valeur par défaut est appliquée à chaque navigation."],
    checks: ["Change la langue puis navigue vers Profils et Settings.", "Vérifie la préférence du profil actif.", "Redémarre l’app pour distinguer état mémoire et persistance."],
    fixes: ["Définir une source de vérité.", "Synchroniser explicitement Settings ↔ profil.", "Ne jamais réappliquer le défaut si une préférence valide existe."],
    avoid: ["Évite de supprimer les préférences utilisateur pour corriger la synchronisation."],
  },
  {
    id: "v90-theme-reset",
    domain: "app",
    title: "Le thème revient à la valeur précédente",
    aliases: ["theme reset", "theme revient", "couleurs changent seules", "le thème revient à la valeur précédente"],
    causes: ["Préférence globale et profil actif divergent.", "Pack premium non chargé au moment du rendu.", "Réhydratation tardive remplace l’état."],
    checks: ["Change le thème et navigue plusieurs écrans.", "Vérifie le profil actif.", "Teste après redémarrage."],
    fixes: ["Centraliser la préférence.", "Appliquer un fallback visuel sans écraser le choix stocké.", "Précharger les assets du thème."],
    avoid: ["Ne confonds pas fallback temporaire et perte de licence."],
  },
  {
    id: "v90-x01-config-invalid",
    domain: "app",
    title: "Configuration X01 impossible à lancer",
    aliases: ["x01 ne demarre pas", "config x01 bloquee", "bouton lancer inactif", "configuration x01 impossible à lancer"],
    causes: ["Paramètre obligatoire manquant.", "Format sets/legs incohérent avec le nombre de joueurs.", "Joueur/équipe non valide ou méthode de saisie indisponible."],
    checks: ["Vérifie les messages de validation visibles.", "Reviens aux valeurs guidées par défaut.", "Contrôle joueurs, score, IN/OUT et format."],
    fixes: ["Corriger uniquement le paramètre invalide.", "Utiliser la configuration guidée pour isoler le problème.", "Conserver les autres choix déjà valides."],
    avoid: ["Ne force pas la navigation vers Play en contournant la validation."],
  },
  {
    id: "v90-play-old-version",
    domain: "android",
    title: "Google Play installe une ancienne version",
    aliases: ["ancienne version installee", "play installe rc5", "pas derniere version", "google play installe une ancienne version"],
    causes: ["Le testeur est inscrit à une autre piste.", "La nouvelle release n’est pas encore disponible pour ce compte/appareil.", "Le versionCode de la build attendue n’est pas supérieur."],
    checks: ["Vérifie la version réellement installée dans l’app.", "Vérifie la piste où le compte testeur est inscrit.", "Compare versionCode des releases."],
    fixes: ["Publier la bonne release sur la bonne piste.", "Attendre uniquement l’état Play nécessaire puis forcer une recherche de mise à jour.", "Désinscrire/réinscrire le testeur seulement si la piste est incorrecte."],
    avoid: ["Ne télécharge pas un APK aléatoire qui casserait la signature ou le parcours de test."],
  },
  {
    id: "v90-android-launch-crash",
    domain: "android",
    title: "L’application Android crashe au lancement",
    aliases: ["crash demarrage android", "app se ferme direct", "startup crash", "l’application android crashe au lancement"],
    causes: ["Erreur native/plugin au démarrage.", "Asset ou configuration Capacitor manquante.", "Exception JavaScript avant l’écran initial."],
    checks: ["Récupère Logcat au moment exact du lancement.", "Vérifie le premier stack trace utile.", "Compare avec le build web si celui-ci démarre."],
    fixes: ["Corriger la première exception réelle.", "Resynchroniser Capacitor si les assets web ont changé.", "Rebuilder proprement avant retest."],
    avoid: ["Ne masque pas le crash avec un try/catch global sans corriger la cause."],
  },
  {
    id: "v90-webview-black",
    domain: "android",
    title: "Écran noir Android / WebView",
    aliases: ["ecran noir android", "webview noire", "page blanche android", "écran noir android / webview"],
    causes: ["Bundle web non copié ou route initiale cassée.", "Erreur JavaScript précoce.", "WebView/asset incompatible."],
    checks: ["Vérifie Logcat et console WebView.", "Confirme que le build web est présent dans android/app/src/main/assets/public.", "Teste la route de départ."],
    fixes: ["Relancer build puis cap sync/copy.", "Corriger l’erreur JS de bootstrap.", "Mettre à jour WebView système si le problème est spécifique à l’appareil."],
    avoid: ["Effacer les données peut masquer le symptôme sans résoudre le build."],
  },
  {
    id: "v90-aab-versioncode",
    domain: "android",
    title: "AAB refusé pour versionCode déjà utilisé",
    aliases: ["versioncode utilise", "aab refuse version", "code version deja", "aab refusé pour versioncode déjà utilisé"],
    causes: ["Google Play exige un versionCode strictement nouveau.", "Le build a été généré avant modification du numéro."],
    checks: ["Lis le message exact Play Console.", "Compare versionCode dans la config Android et le bundle généré."],
    fixes: ["Incrémenter versionCode.", "Rebuilder l’AAB après modification.", "Uploader le nouveau bundle."],
    avoid: ["VersionName seule ne suffit pas pour Google Play."],
  },
  {
    id: "v90-closed-test-install",
    domain: "android",
    title: "Un testeur fermé ne peut pas installer l’application",
    aliases: ["testeur ne peut pas installer", "closed test inaccessible", "opt in erreur", "un testeur fermé ne peut pas installer l’application"],
    causes: ["Compte Google non inscrit.", "Mauvais lien/piste.", "Release non disponible pour le pays/appareil."],
    checks: ["Vérifie l’adresse Google du Play Store.", "Ouvre le lien d’opt-in avec ce même compte.", "Vérifie compatibilité appareil et état de release."],
    fixes: ["Ajouter le bon testeur/groupe.", "Utiliser le lien d’opt-in de la piste concernée.", "Corriger disponibilité si nécessaire."],
    avoid: ["Ne partage pas un lien d’une autre piste en pensant qu’il donne le même accès."],
  },
  {
    id: "v90-admob-no-fill",
    domain: "ads",
    title: "AdMob affiche No Fill ou aucune publicité",
    aliases: ["admob no fill", "pub ne charge pas", "aucune annonce", "admob affiche no fill ou aucune publicité"],
    causes: ["Aucune annonce disponible à cet instant.", "ID d’unité incorrect ou environnement de test mal configuré.", "Consentement/réseau empêche la demande."],
    checks: ["Teste d’abord avec un ID de test officiel dans le build de test.", "Vérifie consentement UMP et connexion.", "Lis les callbacks d’erreur."],
    fixes: ["Séparer problème d’intégration et absence d’inventaire.", "Conserver les emplacements sans bloquer l’UI.", "Repasser aux IDs réels seulement après validation."],
    avoid: ["No Fill n’est pas automatiquement un bug de code."],
  },
  {
    id: "v90-ump-missing",
    domain: "ads",
    title: "Le consentement UMP ne s’affiche pas",
    aliases: ["ump ne s affiche pas", "consentement pub absent", "gdpr admob", "le consentement ump ne s’affiche pas"],
    causes: ["Formulaire non disponible pour la région/config.", "État de consentement déjà enregistré.", "Initialisation UMP non appelée au bon moment."],
    checks: ["Réinitialise le consentement uniquement en environnement de test.", "Vérifie la région de debug si utilisée.", "Observe le statut UMP retourné."],
    fixes: ["Appeler la mise à jour des informations de consentement avant chargement d’annonces.", "Afficher le formulaire seulement si requis.", "Prévoir l’accès aux options de confidentialité."],
    avoid: ["Ne force pas un formulaire inutile à chaque démarrage."],
  },
  {
    id: "v90-premium-locked",
    domain: "billing",
    title: "Achat Premium payé mais fonctionnalités encore verrouillées",
    aliases: ["premium bloque apres achat", "achat paye verrouille", "pro non active", "achat premium payé mais fonctionnalités encore verrouillées"],
    causes: ["Entitlement local non rafraîchi.", "Produit acheté avec un autre compte Play.", "Validation serveur ou restauration non terminée."],
    checks: ["Vérifie le compte Play utilisé.", "Lance la restauration d’achats.", "Contrôle le Product ID et l’état d’achat reconnu."],
    fixes: ["Rafraîchir l’entitlement après achat/restauration.", "Ne déverrouiller qu’après preuve d’achat valide.", "Conserver un mode de récupération si réseau temporairement absent."],
    avoid: ["Ne demande jamais à l’utilisateur de repayer avant d’avoir tenté la restauration."],
  },
  {
    id: "v90-restore-purchase-fail",
    domain: "billing",
    title: "La restauration d’achat ne retrouve rien",
    aliases: ["restauration achat vide", "restore purchases fail", "achat introuvable", "la restauration d’achat ne retrouve rien"],
    causes: ["Mauvais compte Google Play.", "Produit consommable/non restaurable selon modèle.", "Product ID différent entre versions."],
    checks: ["Vérifie l’historique d’achat du compte Play.", "Compare le Product ID courant.", "Teste la requête de produits/achats."],
    fixes: ["Reconnecter le bon compte.", "Aligner les IDs produits.", "Traiter correctement l’état already-owned."],
    avoid: ["Ne crée pas un second entitlement manuel sans trace vérifiable."],
  },
  {
    id: "v90-backup-duplicates",
    domain: "data",
    title: "Import ou restauration crée des doublons",
    aliases: ["doublons apres import", "restore duplicates", "profils dupliques", "import ou restauration crée des doublons"],
    causes: ["Import non idempotent.", "Identifiants recréés au lieu d’être préservés.", "Même sauvegarde importée plusieurs fois."],
    checks: ["Inspecte le rapport d’import.", "Compare IDs et timestamps des doublons.", "Teste un dry run si disponible."],
    fixes: ["Dédupliquer sur identifiant stable.", "Marquer/importer une seule fois chaque objet.", "Sauvegarder avant nettoyage."],
    avoid: ["Ne supprime pas les doublons au hasard s’ils contiennent des historiques différents."],
  },
  {
    id: "v90-restore-media-missing",
    domain: "data",
    title: "Restauration réussie mais avatars ou médias manquent",
    aliases: ["restore sans avatars", "images manquantes sauvegarde", "media absent apres import", "restauration réussie mais avatars ou médias manquent"],
    causes: ["La sauvegarde contient les métadonnées mais pas les blobs/assets.", "Les chemins locaux ont changé.", "Les médias sont dans un stockage séparé."],
    checks: ["Vérifie si les profils existent avec fallback.", "Inspecte le contenu de l’archive.", "Compare références média avant/après."],
    fixes: ["Inclure les médias dans le format Recovery lorsqu’ils doivent être portables.", "Reconstruire les URLs locales.", "Conserver un fallback visuel."],
    avoid: ["Ne considère pas la présence des profils comme preuve que tous les médias ont été sauvegardés."],
  },
  {
    id: "v90-sync-two-devices",
    domain: "data",
    title: "Deux appareils ont modifié les mêmes données",
    aliases: ["conflit deux appareils", "sync conflict", "modifications concurrentes", "deux appareils ont modifié les mêmes données"],
    causes: ["Versions divergentes créées hors ligne.", "Last-write-wins écrase une information utile.", "Horloges appareils peu fiables."],
    checks: ["Compare IDs, versions et contenu plutôt que seulement l’heure.", "Identifie quelles données sont fusionnables.", "Sauvegarde les deux côtés."],
    fixes: ["Fusionner de manière déterministe.", "Conserver les événements uniques.", "Présenter les conflits non résolubles à l’utilisateur."],
    avoid: ["Ne lance pas une synchronisation destructive avant sauvegarde des deux appareils."],
  },
  {
    id: "v90-r2-cost",
    domain: "data",
    title: "Le stockage R2 ou cloud génère plus de coût que prévu",
    aliases: ["r2 cout", "cloud facture", "sauvegardes trop nombreuses", "le stockage r2 ou cloud génère plus de coût que prévu"],
    causes: ["Uploads trop fréquents.", "Anciennes sauvegardes jamais supprimées.", "Médias lourds ou doublonnés."],
    checks: ["Mesure nombre d’objets et volume.", "Vérifie fréquence des sauvegardes.", "Cherche les écritures automatiques inattendues."],
    fixes: ["Gater les sauvegardes premium si prévu.", "Conserver seulement la rétention souhaitée.", "Compresser/dédupliquer."],
    avoid: ["Ne supprime pas tout le bucket sans vérifier la politique de récupération."],
  },
  {
    id: "v90-cloud-session-expired",
    domain: "account",
    title: "Session cloud expirée pendant une opération",
    aliases: ["session cloud expiree", "token expired", "401 sync", "session cloud expirée pendant une opération"],
    causes: ["Access token expiré.", "Refresh token invalide ou révoqué.", "Horloge ou session incohérente."],
    checks: ["Vérifie le code HTTP.", "Tente un refresh contrôlé.", "Confirme le compte actif."],
    fixes: ["Renouveler la session si possible.", "Sinon demander une réauthentification sans effacer les données locales.", "Rejouer l’opération idempotente."],
    avoid: ["Une erreur 401 ne justifie pas une purge locale."],
  },
  {
    id: "v90-signed-url-expired",
    domain: "network",
    title: "Une URL signée de fichier a expiré",
    aliases: ["signed url expiree", "lien cloud expire", "403 fichier", "une url signée de fichier a expiré"],
    causes: ["Durée de validité dépassée.", "URL mise en cache trop longtemps.", "Horloge très décalée."],
    checks: ["Regénère une URL signée.", "Compare l’heure d’expiration.", "Teste le même objet avec un lien neuf."],
    fixes: ["Ne pas persister une URL signée comme référence permanente.", "Stocker l’identifiant d’objet puis générer le lien à la demande."],
    avoid: ["Ne rends pas le bucket public juste pour contourner l’expiration."],
  },
  {
    id: "v90-cast-not-found",
    domain: "network",
    title: "La TV ou le Chromecast n’apparaît pas",
    aliases: ["cast introuvable", "chromecast absent", "tv pas detectee", "la tv ou le chromecast n’apparaît pas"],
    causes: ["Appareils sur réseaux différents.", "Isolation Wi‑Fi ou découverte multicast bloquée.", "Receiver/Google Cast indisponible."],
    checks: ["Vérifie que téléphone et TV sont sur le même LAN.", "Évite le Wi‑Fi invité.", "Teste une autre application Cast pour valider le réseau."],
    fixes: ["Réunir les appareils sur le même réseau.", "Désactiver l’isolation client si possible.", "Redémarrer la découverte Cast."],
    avoid: ["Internet fonctionnel ne prouve pas que la découverte locale fonctionne."],
  },
  {
    id: "v90-cast-score-stale",
    domain: "network",
    title: "Cast connecté mais score figé",
    aliases: ["cast score fige", "tv ne se met pas a jour", "cast stale", "cast connecté mais score figé"],
    causes: ["Session sender/receiver encore ouverte mais événements non transmis.", "Receiver a perdu l’état de partie.", "Reconnexion réseau sans resynchronisation complète."],
    checks: ["Vérifie si la TV reçoit encore heartbeat/ping.", "Change un score et observe les logs.", "Compare l’état local et receiver."],
    fixes: ["À la reconnexion, renvoyer un snapshot complet puis reprendre les deltas.", "Conserver un identifiant de partie/session.", "Prévoir une commande resync."],
    avoid: ["Ne crée pas une nouvelle partie juste pour rafraîchir le Cast."],
  },
  {
    id: "v90-viewer-join-fail",
    domain: "network",
    title: "Viewer ne rejoint pas la session",
    aliases: ["viewer join fail", "code viewer refuse", "qr viewer marche pas", "viewer ne rejoint pas la session"],
    causes: ["Code/session expiré.", "Mauvais réseau ou URL.", "Session host non démarrée."],
    checks: ["Vérifie que l’hôte affiche une session active.", "Rescanne le QR récent.", "Teste le lien sur le même réseau."],
    fixes: ["Régénérer le code si expiré.", "Relancer l’host sans changer la partie.", "Vérifier adresse/port."],
    avoid: ["Ne partage pas un ancien QR après recréation de session."],
  },
  {
    id: "v90-viewer-frozen",
    domain: "network",
    title: "Viewer connecté mais affichage figé",
    aliases: ["viewer fige", "viewer ne bouge plus", "score viewer bloque", "viewer connecté mais affichage figé"],
    causes: ["Polling/WebSocket interrompu.", "Onglet en veille ou réseau changé.", "Host a recréé une session."],
    checks: ["Vérifie l’heure de dernière mise à jour.", "Recharge uniquement le Viewer.", "Compare l’identifiant de session."],
    fixes: ["Reconnecter et renvoyer snapshot.", "Réduire dépendance à l’état mémoire du client.", "Afficher clairement l’état déconnecté."],
    avoid: ["Évite de continuer longtemps avec un Viewer silencieusement désynchronisé."],
  },
  {
    id: "v90-camera-black",
    domain: "camera",
    title: "Caméra noire ou flux absent",
    aliases: ["camera noire", "pas image camera", "preview camera vide", "caméra noire ou flux absent"],
    causes: ["Permission refusée.", "Caméra déjà utilisée par une autre application.", "Contrainte vidéo incompatible."],
    checks: ["Vérifie l’autorisation caméra Android.", "Ferme les autres apps caméra.", "Teste caméra avant."],
    fixes: ["Redemander proprement la permission si possible.", "Choisir un périphérique disponible.", "Relancer le flux après reprise de l’app."],
    avoid: ["Ne demande pas la permission en boucle si elle est refusée définitivement."],
  },
  {
    id: "v90-camera-shift",
    domain: "camera",
    title: "Scoring caméra décalé par rapport aux segments",
    aliases: ["camera score decale", "calibration decalee", "mauvais segment camera", "scoring caméra décalé par rapport aux segments"],
    causes: ["Caméra/cible a bougé.", "Points de calibration imprécis.", "Distorsion/perspective importante."],
    checks: ["Compare position du bull dans l’image avec la calibration précédente.", "Vérifie le segment 20 et le bord extérieur.", "Observe si l’erreur augmente vers les bords."],
    fixes: ["Refixer le support.", "Recalibrer précisément.", "Corriger distorsion si nécessaire."],
    avoid: ["Une recalibration ne compense pas durablement un support qui bouge."],
  },
  {
    id: "v90-companion-pair-fail",
    domain: "network",
    title: "Téléphone compagnon X01 ne se connecte pas",
    aliases: ["telephone compagnon ne connecte pas", "pair camera x01", "qr companion fail", "téléphone compagnon x01 ne se connecte pas"],
    causes: ["Appareils sur réseaux différents.", "QR/session expirée.", "Permissions réseau/caméra absentes."],
    checks: ["Vérifie même Wi‑Fi.", "Regénère le QR.", "Teste l’ouverture de la session depuis le second téléphone."],
    fixes: ["Recréer la session de pairing.", "Valider permissions sur le compagnon.", "Éviter réseau invité."],
    avoid: ["Ne passe pas sur données mobiles pour l’un des appareils si le lien dépend du LAN."],
  },
  {
    id: "v90-camera-lag",
    domain: "camera",
    title: "Flux caméra ou détection en retard",
    aliases: ["camera lag", "detection lente", "video retard", "flux caméra ou détection en retard"],
    causes: ["Résolution/FPS trop élevés.", "Traitement image lourd.", "Réseau compagnon instable."],
    checks: ["Compare caméra locale et compagnon.", "Réduis temporairement résolution/FPS.", "Observe CPU et latence."],
    fixes: ["Traiter seulement la ROI utile.", "Limiter fréquence d’analyse.", "Stabiliser le réseau."],
    avoid: ["Ne réduis pas aveuglément la qualité sous le seuil nécessaire à la détection."],
  },
  {
    id: "v90-bluetooth-missing",
    domain: "network",
    title: "Périphérique Bluetooth non détecté",
    aliases: ["bluetooth introuvable", "device bluetooth absent", "grandarts bluetooth", "périphérique bluetooth non détecté"],
    causes: ["Bluetooth/permission désactivé.", "Périphérique non en mode appairage.", "Filtre UUID trop strict."],
    checks: ["Vérifie Bluetooth système et permissions.", "Mets le périphérique en pairing.", "Teste détection système."],
    fixes: ["Redémarrer le scan après permissions.", "Vérifier UUID/service attendu.", "Oublier/reappairer seulement si nécessaire."],
    avoid: ["La proximité ne garantit pas que le périphérique annonce le bon service."],
  },
  {
    id: "v90-external-device-connect",
    domain: "network",
    title: "Scolia, Grandarts ou bridge externe ne se connecte pas",
    aliases: ["scolia ne connecte pas", "grandarts ne connecte pas", "bridge erreur", "scolia, grandarts ou bridge externe ne se connecte pas"],
    causes: ["Adresse/port incorrect.", "Service externe non démarré.", "Format d’événement incompatible."],
    checks: ["Teste l’adresse du bridge.", "Vérifie que le service répond.", "Capture un événement brut."],
    fixes: ["Corriger endpoint.", "Aligner protocole/format.", "Conserver fallback manuel."],
    avoid: ["Ne bloque pas la partie si le périphérique tombe en panne."],
  },
  {
    id: "v90-websocket-drop",
    domain: "network",
    title: "WebSocket se déconnecte régulièrement",
    aliases: ["websocket coupe", "socket disconnect", "bridge websocket", "websocket se déconnecte régulièrement"],
    causes: ["Wi‑Fi instable.", "Serveur ferme les connexions inactives.", "Absence de heartbeat/reconnect."],
    checks: ["Observe code de fermeture.", "Mesure fréquence des coupures.", "Teste sur réseau stable."],
    fixes: ["Ajouter heartbeat et reconnexion avec backoff.", "Renvoyer état complet après reconnexion.", "Limiter doublons d’abonnements."],
    avoid: ["Une reconnexion sans resynchronisation peut afficher un état faux."],
  },
  {
    id: "v90-guest-wifi-isolation",
    domain: "network",
    title: "Appareils sur le même Wi‑Fi mais incapables de se voir",
    aliases: ["meme wifi mais pas connexion", "wifi invite", "ap isolation", "appareils sur le même wi‑fi mais incapables de se voir"],
    causes: ["Le SSID invité isole les clients.", "Mesh/VLAN sépare les appareils.", "Pare-feu bloque découverte locale."],
    checks: ["Compare IP/sous-réseau.", "Teste un ping/service local si possible.", "Essaie le réseau principal."],
    fixes: ["Passer sur le même LAN non isolé.", "Autoriser multicast/local si le routeur le permet."],
    avoid: ["Même nom Wi‑Fi ne signifie pas toujours même segment réseau."],
  },
  {
    id: "v90-speech-no-result",
    domain: "assistant",
    title: "Reconnaissance vocale n’entend ou ne comprend rien",
    aliases: ["speech no result", "awena entend pas", "reconnaissance vocale vide", "reconnaissance vocale n’entend ou ne comprend rien"],
    causes: ["Permission micro absente.", "Recognizer indisponible/langue incorrecte.", "Bruit ou parole trop faible."],
    checks: ["Vérifie l’icône micro et permission.", "Teste une phrase courte.", "Vérifie langue système/app."],
    fixes: ["Redémarrer l’écoute.", "Choisir le recognizer disponible.", "Afficher une saisie manuelle de secours."],
    avoid: ["Ne garde pas le micro actif quand Awéna parle."],
  },
  {
    id: "v90-wakeword-miss",
    domain: "assistant",
    title: "Le mot Awéna n’est pas reconnu",
    aliases: ["awena mot cle marche pas", "wake word ignore", "avena pas reconnue", "le mot awéna n’est pas reconnu"],
    causes: ["Transcription produit une variante non prévue.", "Écoute pas active.", "Phrase commence trop vite."],
    checks: ["Regarde la transcription brute si disponible.", "Teste « Awéna » puis une courte pause.", "Vérifie mode mains-libres."],
    fixes: ["Tolérer variantes phonétiques.", "Relancer écoute après TTS.", "Prévoir bouton micro manuel."],
    avoid: ["Ne déclenche pas une action sensible sur une transcription trop incertaine."],
  },
  {
    id: "v90-awena-hears-self",
    domain: "assistant",
    title: "Awéna entend sa propre voix et boucle",
    aliases: ["awena s ecoute", "boucle vocale", "tts retrigger", "awéna entend sa propre voix et boucle"],
    causes: ["Micro reste actif pendant TTS.", "Reprise d’écoute trop précoce."],
    checks: ["Observe si la transcription reprend le texte prononcé par Awéna.", "Teste avec volume bas."],
    fixes: ["Suspendre reconnaissance pendant TTS.", "Reprendre après événement de fin de parole plus petite marge."],
    avoid: ["Évite un simple filtre par texte qui pourrait bloquer une vraie question identique."],
  },
  {
    id: "v90-tts-silent",
    domain: "assistant",
    title: "Awéna affiche une réponse mais ne parle pas",
    aliases: ["awena muette", "tts pas de voix", "reponse sans audio", "awéna affiche une réponse mais ne parle pas"],
    causes: ["TTS désactivé.", "Moteur/langue indisponible.", "Volume média nul."],
    checks: ["Vérifie réglage voix Awéna.", "Teste un son média.", "Teste une phrase courte."],
    fixes: ["Sélectionner un moteur/langue disponible.", "Fallback sur voix Android si modèle local absent.", "Conserver toujours le texte à l’écran."],
    avoid: ["La voix ne doit jamais être la seule façon d’obtenir l’information."],
  },
  {
    id: "v90-mic-denied",
    domain: "assistant",
    title: "Permission microphone refusée",
    aliases: ["micro refuse", "permission micro", "awena micro bloque", "permission microphone refusée"],
    causes: ["Refus simple ou refus définitif.", "Permission retirée depuis réglages Android."],
    checks: ["Vérifie l’état de permission.", "Si refus définitif, ouvre les réglages système."],
    fixes: ["Expliquer pourquoi le micro est nécessaire.", "Permettre de continuer en texte.", "Redemander seulement quand c’est pertinent."],
    avoid: ["Ne bloque pas l’application entière pour une permission vocale optionnelle."],
  },
  {
    id: "v90-low-memory",
    domain: "performance",
    title: "Application ralentie après longue utilisation",
    aliases: ["ram augmente", "app lente apres longtemps", "memory pressure", "application ralentie après longue utilisation"],
    causes: ["Fuite de listeners/timers.", "Images lourdes conservées.", "Caches non bornés."],
    checks: ["Compare mémoire après démarrage et après navigation répétée.", "Observe si revenir à l’accueil libère la mémoire.", "Cherche composants qui restent abonnés."],
    fixes: ["Nettoyer effets/listeners.", "Limiter cache média.", "Libérer URL blobs inutiles."],
    avoid: ["Ne désactive pas toutes les images sans mesurer leur impact réel."],
  },
  {
    id: "v90-app-size",
    domain: "android",
    title: "Application Android devenue très volumineuse",
    aliases: ["app 350 mo", "taille application", "aab trop gros", "application android devenue très volumineuse"],
    causes: ["Assets images/vidéos/audio non compressés.", "Doublons de médias.", "Bibliothèques natives lourdes."],
    checks: ["Mesure taille par catégorie.", "Cherche doublons exacts.", "Inspecte le bundle AAB/APK."],
    fixes: ["Convertir images compatibles vers WebP/AVIF selon usage.", "Compresser audio/vidéo.", "Supprimer seulement les doublons prouvés et mettre à jour toutes les références."],
    avoid: ["Ne supprime aucune ressource utilisée sans rechercher ses imports/chemins."],
  },
  {
    id: "v90-signature-mismatch",
    domain: "android",
    title: "Mise à jour Android impossible à cause de la signature",
    aliases: ["signature mismatch", "app non installee conflit", "update incompatible signature", "mise à jour android impossible à cause de la signature"],
    causes: ["APK installé signé avec une autre clé.", "Application ID identique mais certificat différent."],
    checks: ["Compare source de l’installation actuelle.", "Vérifie certificat/signature des builds."],
    fixes: ["Utiliser la chaîne de signature officielle.", "Désinstallation uniquement si aucune migration de données n’est nécessaire ou après sauvegarde."],
    avoid: ["Désinstaller peut supprimer les données locales."],
  },
  {
    id: "v90-indexeddb-corrupt",
    domain: "data",
    title: "Stockage local semble corrompu",
    aliases: ["indexeddb corrompu", "base locale erreur", "donnees illisibles", "stockage local semble corrompu"],
    causes: ["Migration interrompue.", "Écriture partielle ou objet ancien incompatible.", "Erreur logique interprétée à tort comme corruption."],
    checks: ["Créer une sauvegarde/export si lecture partielle possible.", "Inspecter l’erreur exacte.", "Tester un profil/objet précis."],
    fixes: ["Réparer/migrer les enregistrements ciblés.", "Restaurer depuis Recovery vérifiée si nécessaire.", "Purger seulement en dernier recours."],
    avoid: ["Ne vide pas IndexedDB comme première réponse."],
  },
  {
    id: "v90-tournament-bracket",
    domain: "competition",
    title: "Tableau de tournoi incohérent",
    aliases: ["bracket faux", "tournoi incoherent", "matchs tournoi mauvais", "tableau de tournoi incohérent"],
    causes: ["Résultat corrigé sans recalcul aval.", "Seed/bye mal appliqué.", "Match déjà verrouillé."],
    checks: ["Vérifie les résultats source de chaque ronde.", "Contrôle format et nombre de participants.", "Repère le premier match où la progression devient fausse."],
    fixes: ["Recalculer depuis ce point avec règles déterministes.", "Protéger les résultats déjà joués en demandant confirmation.", "Conserver une trace de correction."],
    avoid: ["Modifier un match amont peut invalider plusieurs matchs aval."],
  },
  {
    id: "v90-tournament-result-not-reflected",
    domain: "competition",
    title: "Résultat saisi mais classement non mis à jour",
    aliases: ["classement pas actualise", "resultat tournoi ignore", "standing stale", "résultat saisi mais classement non mis à jour"],
    causes: ["Cache classement non invalidé.", "Résultat non marqué final.", "Agrégation lit une autre source."],
    checks: ["Ouvre le détail du match.", "Vérifie statut final.", "Recharge le classement."],
    fixes: ["Invalider/recalculer après résultat final.", "Unifier source tournoi.", "Afficher la date de mise à jour."],
    avoid: ["Ne saisis pas le résultat une seconde fois si le premier existe déjà."],
  },
  {
    id: "v90-stars-weird",
    domain: "stats",
    title: "Étoiles ou niveau d’un profil semblent incohérents",
    aliases: ["etoiles profil incoherentes", "rating bizarre", "marjo etoiles", "étoiles ou niveau d’un profil semblent incohérents"],
    causes: ["Les étoiles peuvent agréger plusieurs modes ou une ancienne métrique.", "Historique incomplet/mal filtré.", "Valeur de cache non recalculée."],
    checks: ["Demande la définition exacte des étoiles.", "Compare le profil avec ses matchs réellement enregistrés.", "Vérifie si seuls certains modes comptent."],
    fixes: ["Documenter la formule.", "Recalculer depuis la bonne source.", "Afficher la période/modes pris en compte."],
    avoid: ["Ne déduis pas le niveau d’un joueur uniquement à partir d’une étoile sans connaître sa formule."],
  },
  {
    id: "v90-spectator-fail",
    domain: "network",
    title: "Mode spectateur ne rejoint pas ou ne suit pas la partie",
    aliases: ["spectateur ne marche pas", "spectator fail", "viewer online absent", "mode spectateur ne rejoint pas ou ne suit pas la partie"],
    causes: ["Session non publique/expirée.", "Code ou identifiant faux.", "Mise à jour temps réel interrompue."],
    checks: ["Vérifie que la partie autorise les spectateurs.", "Regénère le lien/code.", "Teste une nouvelle connexion."],
    fixes: ["Rouvrir la session spectateur.", "Resynchroniser snapshot.", "Afficher clairement l’état hors ligne."],
    avoid: ["Ne révèle pas d’informations privées à un spectateur non autorisé."],
  },
];

function rememberedId(topic?: string) { return String(topic||"").startsWith("diagv90:") ? String(topic).slice(8) : ""; }
function score(e:DiagnosticV90Entry,q:string,remembered?:string) {
  let s=rememberedId(remembered)===e.id?12:0; const qt=new Set(toks(q));
  for(const raw of [e.title,...e.aliases]){const a=norm(raw); if(q===a)s+=48; else if(a.length>=4&&q.includes(a))s+=21; const at=toks(a); let m=0; for(const t of at)if(qt.has(t)){m++;s+=t.length>=6?4:2.3} if(at.length>=2&&m===at.length)s+=9;}
  if(/marche pas|fonctionne pas|bug|erreur|bloque|bloqué|fige|figé|lent|lente|manque|absent|incoherent|incohérent|diagnostic|pourquoi/.test(q))s+=3;
  return s;
}
function full(e:DiagnosticV90Entry) {
  return `## DIAGNOSTIC · ${e.title.toUpperCase()}\nJe vais commencer par les causes les plus probables et les vérifications les moins risquées.\n\n## CAUSES PROBABLES\n${bullets(e.causes)}\n\n## À VÉRIFIER DANS CET ORDRE\n${numbered(e.checks)}\n\n## CORRECTIONS / SUITE\n${numbered(e.fixes)}${e.avoid.length?`\n\n## À ÉVITER\n${bullets(e.avoid)}`:""}\n\n> Donne-moi le résultat d’une vérification ou le message d’erreur exact : je garde ce diagnostic en mémoire.`;
}
function follow(e:DiagnosticV90Entry,q:string) {
  if(/cause|pourquoi/.test(q)) return `## CAUSES · ${e.title.toUpperCase()}\n${bullets(e.causes)}`;
  if(/commence|premier|d abord|d'abord|verif|vérif|check/.test(q)) return `## PREMIÈRES VÉRIFICATIONS · ${e.title.toUpperCase()}\n${numbered(e.checks)}`;
  if(/corrig|solution|reparer|réparer|quoi faire/.test(q)) return `## CORRECTIONS · ${e.title.toUpperCase()}\n${numbered(e.fixes)}`;
  if(/eviter|éviter|danger|risque/.test(q)) return `## À ÉVITER · ${e.title.toUpperCase()}\n${bullets(e.avoid)}`;
  return full(e);
}
export function answerAwenaDiagnosticV90(question:string, context:AwenaRuntimeContext, rememberedTopic?:string):AwenaReply|null {
  const q=norm(question); if(!q)return null;
  const rid=rememberedId(rememberedTopic);
  const shortFollow=/^(?:pourquoi|quelle cause|quelles causes|par quoi commencer|quoi verifier|quoi vérifier|quelle solution|quoi faire|et maintenant|et ensuite|ca ne marche toujours pas|ça ne marche toujours pas)$/i.test(String(question||"").trim());
  if(shortFollow&&rid){const e=ENTRIES.find(x=>x.id===rid); if(e)return {text:follow(e,q),knowledgeTopic:`diagv90:${e.id}`,modeId:context.mode||null};}
  let best:{e:DiagnosticV90Entry;s:number}|null=null; for(const e of ENTRIES){const s=score(e,q,rememberedTopic);if(!best||s>best.s)best={e,s}}
  if(!best||best.s<15)return null;
  return {text:full(best.e),knowledgeTopic:`diagv90:${best.e.id}`,modeId:context.mode||null};
}
export function awenaDiagnosticV90Count(){return ENTRIES.length;}
export function awenaDiagnosticV90AliasCount(){return ENTRIES.reduce((s,e)=>s+e.aliases.length,0);}
export function awenaDiagnosticV90CheckCount(){return ENTRIES.reduce((s,e)=>s+e.checks.length,0);}
export function awenaDiagnosticV90FixCount(){return ENTRIES.reduce((s,e)=>s+e.fixes.length,0);}
