import type { AwenaProcedureEntry } from "./AwenaProceduralAcademy";

export const AWENA_V90_PROCEDURES: AwenaProcedureEntry[] = [
  {
    id: "v90-cast-first-time", domain: "network", title: "Préparer un Cast TV pour la première fois",
    aliases: ["premier cast tv", "installer cast", "configurer chromecast pour app"], route: "cast_host",
    purpose: "Mettre en place une session Cast propre avant une vraie partie.",
    prerequisites: ["Téléphone et TV/Chromecast connectés au même réseau local.", "Google Cast fonctionnel sur la TV."],
    steps: ["Ouvre l’écran Cast depuis l’application.", "Vérifie que la TV apparaît dans la liste des appareils.", "Sélectionne la TV et attends la confirmation de connexion.", "Lance une session de test avant la partie réelle.", "Change une valeur de test et vérifie que l’écran TV se met à jour.", "Ferme proprement la session puis relance-la une fois pour vérifier la reconnexion."],
    verify: ["La TV affiche le bon écran et suit les mises à jour sans décalage visible."],
    troubleshooting: ["TV absente : vérifie réseau principal, isolation Wi‑Fi et disponibilité Cast.", "Connexion OK mais écran figé : relance la synchronisation de session, pas la partie."],
    warnings: ["Ne teste pas sur un Wi‑Fi invité si les clients y sont isolés."],
    related: ["Cast TV", "Viewer", "Réseau local"],
  },
  {
    id: "v90-viewer-first-time", domain: "network", title: "Configurer un Viewer sur un second écran",
    aliases: ["premier viewer", "configurer viewer tablette", "deuxieme ecran viewer"], route: "viewer_host",
    purpose: "Afficher une partie sur une tablette ou un second écran via le Viewer.",
    prerequisites: ["Appareil hôte et Viewer accessibles sur le réseau prévu.", "Session de partie ou d’affichage prête."],
    steps: ["Ouvre Viewer Host sur l’appareil principal.", "Crée une session et affiche le QR/code/lien.", "Sur le second appareil, ouvre Viewer Join.", "Scanne le QR ou saisis le code récent.", "Vérifie que le Viewer charge le bon match.", "Effectue une mise à jour test et confirme qu’elle apparaît.", "Garde le QR de la session courante seulement."],
    verify: ["Le Viewer suit le score et affiche le même identifiant/session que l’hôte."],
    troubleshooting: ["Code refusé : recrée une session fraîche.", "Viewer figé : recharge le Viewer puis resynchronise le snapshot."],
    warnings: ["Ne réutilise pas un ancien QR après création d’une nouvelle session."],
    related: ["Viewer", "Cast", "Spectateur"],
  },
  {
    id: "v90-network-same-lan", domain: "network", title: "Vérifier que deux appareils sont vraiment sur le même réseau",
    aliases: ["meme reseau local", "verifier lan", "deux appareils wifi"], route: "settings",
    purpose: "Confirmer une condition indispensable à Cast, Viewer, caméra compagnon et certains bridges.",
    prerequisites: ["Accès aux informations Wi‑Fi des deux appareils."],
    steps: ["Vérifie le nom du réseau sur les deux appareils.", "Évite les réseaux invités ou isolés.", "Compare les adresses IP si l’application ou le système les affiche.", "Vérifie qu’elles appartiennent au même sous-réseau logique.", "Coupe temporairement les données mobiles sur le second appareil si elles perturbent le test.", "Relance la découverte locale."],
    verify: ["Les appareils peuvent découvrir ou joindre le même service local."],
    troubleshooting: ["Même SSID mais aucun lien : suspecte isolation client, mesh/VLAN ou pare-feu.", "Un appareil en 4G/5G n’est pas automatiquement sur le LAN."],
    warnings: ["Ne change pas plusieurs réglages routeur à la fois sans noter l’état initial."],
    related: ["LAN", "Wi‑Fi invité", "Cast"],
  },
  {
    id: "v90-camera-install", domain: "camera", title: "Installer physiquement la caméra de scoring",
    aliases: ["installer camera scoring", "placer camera cible", "support camera darts"], route: "camera_scoring_setup",
    purpose: "Obtenir un cadrage stable avant toute calibration.",
    prerequisites: ["Support caméra stable.", "Cible complètement visible.", "Éclairage suffisant."],
    steps: ["Place la caméra de manière à voir toute la cible utile.", "Fixe le support pour qu’il ne bouge pas au toucher ou aux vibrations.", "Évite un angle extrême si un placement plus frontal est possible.", "Vérifie que mains et corps ne masquent pas durablement la cible.", "Stabilise l’éclairage sans reflets agressifs.", "Lance l’aperçu et confirme que le bull, les doubles et le 20 sont nets.", "Seulement ensuite, passe à la calibration."],
    verify: ["L’image reste identique lorsque tu quittes puis reviens à l’aperçu."],
    troubleshooting: ["Image floue : verrouille la mise au point ou éloigne légèrement la caméra.", "Bords très déformés : évite le grand-angle excessif."],
    warnings: ["Toute modification du support après calibration peut imposer une nouvelle calibration."],
    related: ["Calibration caméra", "Éclairage", "Téléphone compagnon"],
  },
  {
    id: "v90-camera-lighting", domain: "camera", title: "Optimiser l’éclairage pour le scoring caméra",
    aliases: ["regler lumiere camera", "eclairage cible camera", "ombre detection"], route: "camera_scoring_setup",
    purpose: "Réduire ombres, reflets et erreurs de détection.",
    prerequisites: ["Caméra déjà cadrée sur la cible."],
    steps: ["Observe la cible sans fléchette et repère les zones trop sombres.", "Ajoute une lumière diffuse et régulière plutôt qu’un point très violent.", "Évite les reflets directs sur fils, cible ou pointes.", "Vérifie l’exposition automatique après quelques secondes.", "Lance un test avec plusieurs fléchettes dans des zones différentes.", "Compare les résultats près du bull et des bords."],
    verify: ["La cible reste lisible et les secteurs gardent un contraste stable."],
    troubleshooting: ["Image qui pompe en luminosité : stabilise l’exposition si possible.", "Ombre de la main : déplace la source lumineuse plutôt que la caméra calibrée."],
    warnings: ["Ne recalibre pas pour compenser uniquement une mauvaise lumière."],
    related: ["Caméra", "Calibration", "Faux positif"],
  },
  {
    id: "v90-camera-recalibrate", domain: "camera", title: "Recalibrer après déplacement de la caméra",
    aliases: ["recalibrer camera", "camera bougee", "refaire calibration"], route: "camera_scoring_calibration",
    purpose: "Restaurer la correspondance géométrique après mouvement du support ou de la cible.",
    prerequisites: ["Caméra refixée définitivement.", "Cible dans sa position finale."],
    steps: ["Ouvre la calibration depuis le scoring caméra.", "Recentre précisément le BULL.", "Renseigne le bord extérieur demandé.", "Indique le repère du segment 20.", "Enregistre la nouvelle calibration.", "Teste plusieurs secteurs éloignés les uns des autres.", "Si l’erreur augmente vers les bords, recontrôle angle et distorsion."],
    verify: ["Les impacts de test correspondent aux secteurs réels sur toute la cible."],
    troubleshooting: ["Erreur uniforme : repères probablement décalés.", "Erreur surtout sur les bords : perspective/distorsion à revoir."],
    warnings: ["Ne déplace plus la caméra après validation."],
    related: ["Calibration caméra", "Homographie", "Perspective"],
  },
  {
    id: "v90-companion-pair", domain: "network", title: "Associer un téléphone compagnon pour X01",
    aliases: ["associer telephone compagnon", "pair x01 camera", "connecter deuxieme telephone"], route: "x01_device_camera",
    purpose: "Utiliser un second téléphone comme source caméra ou compagnon X01.",
    prerequisites: ["Deux appareils sur le même réseau lorsque le mode l’exige.", "Permissions caméra et réseau disponibles sur le compagnon."],
    steps: ["Ouvre le parcours téléphone compagnon depuis X01.", "Crée une nouvelle session de liaison.", "Affiche le QR/code.", "Sur le second téléphone, ouvre le lien ou scanne le QR.", "Accepte la permission caméra.", "Vérifie que l’aperçu arrive sur l’appareil principal.", "Teste une reconnexion avant de lancer une vraie partie."],
    verify: ["Le flux compagnon est visible et reste lié après un court changement d’écran."],
    troubleshooting: ["QR expiré : génère-en un nouveau.", "Flux absent : vérifie permissions et même LAN."],
    warnings: ["Évite de basculer un appareil sur données mobiles pendant une session LAN."],
    related: ["Téléphone compagnon", "Caméra", "QR"],
  },
  {
    id: "v90-bluetooth-pair", domain: "network", title: "Connecter un périphérique Bluetooth de scoring",
    aliases: ["appairer bluetooth scoring", "connecter grandarts bluetooth", "peripherique bluetooth"], route: "x01_config_v3",
    purpose: "Associer un périphérique compatible sans bloquer la partie si la liaison échoue.",
    prerequisites: ["Bluetooth activé.", "Permission Bluetooth accordée.", "Périphérique en mode appairage."],
    steps: ["Active la méthode de saisie externe concernée.", "Lance la détection des périphériques.", "Sélectionne le périphérique attendu plutôt qu’un appareil au nom similaire.", "Attends la confirmation de connexion.", "Effectue un événement de test.", "Vérifie que l’événement est reconnu une seule fois.", "Prépare le retour au scoring manuel si la liaison tombe."],
    verify: ["Un événement test modifie l’état attendu sans duplication."],
    troubleshooting: ["Appareil absent : vérifie pairing et permissions.", "Connexion sans événements : contrôle service/UUID/protocole attendu."],
    warnings: ["Ne rends pas la partie dépendante d’une connexion externe sans fallback."],
    related: ["Bluetooth", "Grandarts", "Fallback manuel"],
  },
  {
    id: "v90-websocket-bridge", domain: "network", title: "Configurer un Bridge WebSocket de scoring",
    aliases: ["configurer bridge websocket", "bridge scoring x01", "websocket externe"], route: "x01_config_v3",
    purpose: "Relier une source externe qui publie des événements de score.",
    prerequisites: ["Adresse et port du bridge connus.", "Bridge démarré et joignable depuis l’appareil."],
    steps: ["Renseigne l’URL WebSocket exacte.", "Teste la connexion avant la partie.", "Observe un message ou événement brut de test.", "Vérifie que le format correspond au parser attendu.", "Lance une petite partie de test.", "Coupe puis rétablis le bridge pour vérifier la reconnexion.", "Confirme qu’un snapshot cohérent est repris après reconnexion."],
    verify: ["Les événements arrivent dans l’ordre et aucune saisie n’est dupliquée."],
    troubleshooting: ["Connexion refusée : teste adresse/port.", "Connexion OK sans score : inspecte le format des messages."],
    warnings: ["Ne désactive pas la saisie manuelle de secours."],
    related: ["WebSocket", "Bridge", "Reconnexion"],
  },
  {
    id: "v90-scolia-check", domain: "network", title: "Vérifier une intégration Scolia avant une partie",
    aliases: ["tester scolia", "configurer scolia", "scolia avant match"], route: "x01_config_v3",
    purpose: "Valider la chaîne externe avant de dépendre d’elle pendant X01.",
    prerequisites: ["Scolia/bridge accessible.", "Paramètres de connexion connus."],
    steps: ["Sélectionne la source Scolia prévue.", "Teste la connexion sans partie importante.", "Provoque un événement de score simple.", "Vérifie joueur actif, score et détail de fléchette.", "Teste Undo/correction selon le flux prévu.", "Coupe la connexion puis confirme le fallback manuel."],
    verify: ["Un test simple produit exactement le même résultat que la saisie manuelle équivalente."],
    troubleshooting: ["Événement absent : contrôle endpoint/bridge.", "Joueur incorrect : vérifie association des participants."],
    warnings: ["Ne découvre pas le mapping en plein match officiel."],
    related: ["Scolia", "Bridge", "X01"],
  },
  {
    id: "v90-grandarts-check", domain: "network", title: "Vérifier Grandarts avant une partie X01",
    aliases: ["tester grandarts", "grandarts setup", "grandarts avant match"], route: "x01_config_v3",
    purpose: "Valider la détection et le mapping de score avant le début réel.",
    prerequisites: ["Périphérique sous tension et disponible.", "Méthode Grandarts activée dans la configuration."],
    steps: ["Connecte le périphérique.", "Effectue un lancer ou événement connu.", "Compare segment/multiplicateur détecté avec le résultat réel.", "Teste plusieurs zones dont simple, double et triple.", "Vérifie qu’un seul événement est enregistré par action.", "Teste la reconnexion.", "Conserve le keypad/cible comme secours."],
    verify: ["Les événements de test sont exacts et non dupliqués."],
    troubleshooting: ["Doubles/triples mal lus : inspecte mapping protocole.", "Événements doubles : cherche deux abonnements actifs."],
    warnings: ["Ne lance pas une compétition avant ces tests."],
    related: ["Grandarts", "Bluetooth", "X01"],
  },
  {
    id: "v90-voice-permission", domain: "assistant", title: "Activer correctement le microphone d’Awéna",
    aliases: ["activer micro awena", "permission voix", "autoriser reconnaissance vocale"], route: "settings",
    purpose: "Permettre la commande vocale sans bloquer l’usage texte.",
    prerequisites: ["Appareil Android avec microphone disponible."],
    steps: ["Ouvre Settings puis la section Awéna.", "Active les commandes vocales.", "Accepte la permission microphone lorsqu’elle est demandée.", "Prononce une phrase courte de test.", "Vérifie la transcription ou la réaction d’Awéna.", "Si la permission est bloquée définitivement, ouvre les réglages Android de l’application.", "Reviens dans l’app et reteste."],
    verify: ["Awéna reçoit une phrase test et l’interface texte reste disponible."],
    troubleshooting: ["Aucune demande de permission : vérifie l’état système.", "Permission accordée mais silence : teste le micro dans une autre application."],
    warnings: ["Ne force pas la permission en boucle."],
    related: ["Awéna Voice", "Microphone", "SpeechRecognizer"],
  },
  {
    id: "v90-voice-x01-recovery", domain: "assistant", title: "Reprendre une configuration vocale X01 mal comprise",
    aliases: ["awena x01 mal compris", "corriger config vocale", "recommencer voix x01"], route: "x01_config_v3",
    purpose: "Corriger un paramètre vocal sans devoir abandonner toute la configuration.",
    prerequisites: ["Dialogue vocal X01 déjà lancé."],
    steps: ["Dis clairement le paramètre à corriger : score, joueurs, IN/OUT, format ou méthode de saisie.", "Attends qu’Awéna reformule le nouveau choix.", "Vérifie que le contrôle visible de l’écran change aussi.", "Demande le récapitulatif complet.", "Corrige les autres éléments si nécessaire.", "Valide seulement lorsque le récapitulatif est exact."],
    verify: ["L’écran et le résumé vocal montrent les mêmes valeurs."],
    troubleshooting: ["Awéna reste sur l’ancien sujet : dis « recommence la configuration » puis reprends.", "Valeur non disponible : passe temporairement à l’écran tactile."],
    warnings: ["Ne confirme pas une partie si le résumé vocal ne correspond pas à l’écran."],
    related: ["Voice X01", "Configuration guidée", "Confirmation"],
  },
  {
    id: "v90-backup-before-update", domain: "data", title: "Créer un point de retour avant une mise à jour importante",
    aliases: ["backup avant mise a jour", "securiser maj", "point retour"], route: "sync_center",
    purpose: "Pouvoir revenir à un état de données connu avant installation d’une nouvelle version.",
    prerequisites: ["Version actuelle encore fonctionnelle."],
    steps: ["Crée une sauvegarde Recovery complète.", "Vérifie que l’archive n’est pas vide et qu’elle contient les catégories attendues.", "Conserve une copie hors de l’application si possible.", "Note la version actuelle de l’app.", "Effectue la mise à jour.", "Vérifie profils, historique, stats, thèmes et médias.", "Conserve l’ancienne sauvegarde jusqu’à plusieurs tests réussis."],
    verify: ["Les données importantes sont lisibles après mise à jour et une sauvegarde antérieure reste disponible."],
    troubleshooting: ["Nouvelle version vide : n’écris pas beaucoup de nouvelles données avant diagnostic.", "Import impossible : vérifie compatibilité du format avant toute purge."],
    warnings: ["Ne désinstalle pas avant d’avoir sécurisé les données locales."],
    related: ["Recovery", "Mise à jour Android", "Migration"],
  },
  {
    id: "v90-recovery-dryrun", domain: "data", title: "Inspecter une sauvegarde avant restauration",
    aliases: ["inspecter backup", "verifier recovery avant restore", "dry run sauvegarde"], route: "sync_center",
    purpose: "Éviter une restauration destructive ou incohérente.",
    prerequisites: ["Archive Recovery disponible."],
    steps: ["Sélectionne l’archive sans confirmer immédiatement une restauration totale.", "Lis le résumé des catégories et volumes.", "Vérifie date, version et identité de la sauvegarde.", "Compare avec les données actuellement présentes.", "Choisis la stratégie prévue : fusion, remplacement ou récupération ciblée.", "Crée une sauvegarde de l’état actuel avant application.", "Lance seulement ensuite la restauration."],
    verify: ["Le contenu attendu est identifié avant toute écriture."],
    troubleshooting: ["Archive illisible : garde le fichier intact et teste une autre copie.", "Dates incohérentes : compare le contenu plutôt que l’horloge seule."],
    warnings: ["Ne remplace jamais une base plus récente sans sauvegarder celle-ci."],
    related: ["Recovery", "Dry run", "Import"],
  },
  {
    id: "v90-import-merge", domain: "data", title: "Fusionner un import sans créer de doublons",
    aliases: ["fusionner import", "merge json", "import sans doublon"], route: "sync_center",
    purpose: "Ajouter des données externes tout en préservant les enregistrements déjà présents.",
    prerequisites: ["Sauvegarde de l’état courant.", "Fichier d’import valide."],
    steps: ["Inspecte le rapport préalable de l’import.", "Repère les IDs déjà présents.", "Distingue nouveaux enregistrements, mises à jour et conflits.", "Choisis une politique de fusion déterministe.", "Lance l’import une seule fois.", "Relis le rapport final.", "Contrôle quelques profils, matchs et médias."],
    verify: ["Le nombre d’éléments ajoutés correspond au rapport et aucun doublon évident n’apparaît."],
    troubleshooting: ["Doublons : compare IDs et provenance.", "Conflit : garde les deux versions en sauvegarde avant arbitrage."],
    warnings: ["Ne relance pas le même import plusieurs fois pour « voir si ça passe »."],
    related: ["Import JSON", "Déduplication", "Fusion"],
  },
  {
    id: "v90-sync-two-device-safe", domain: "data", title: "Synchroniser deux appareils sans écraser le plus récent",
    aliases: ["sync deux telephones", "fusion deux appareils", "synchroniser appareils"], route: "sync_center",
    purpose: "Réunir deux historiques ayant évolué séparément.",
    prerequisites: ["Accès aux deux appareils.", "Sauvegarde Recovery de chaque appareil."],
    steps: ["Crée une sauvegarde indépendante sur chaque appareil.", "Compare volumes et dates par catégorie.", "Choisis l’appareil de référence uniquement pour les données réellement communes.", "Lance la synchronisation avec politique de fusion.", "Contrôle le rapport de conflits.", "Vérifie les parties uniques de chaque appareil.", "Refais une sauvegarde après fusion réussie."],
    verify: ["Les événements uniques des deux appareils sont présents."],
    troubleshooting: ["Une catégorie a disparu : arrête les écritures et restaure depuis la sauvegarde du côté concerné.", "Conflits nombreux : traite par lots."],
    warnings: ["Ne choisis pas « remplacer » uniquement parce qu’un appareil a une date plus récente."],
    related: ["Peer Sync", "Conflit de version", "Recovery"],
  },
  {
    id: "v90-cloud-offline", domain: "data", title: "Continuer à jouer lorsque le cloud est indisponible",
    aliases: ["cloud hors ligne jouer", "offline cloud", "pas internet continuer"], route: "sync_center",
    purpose: "Préserver l’expérience locale lorsque les services distants sont momentanément indisponibles.",
    prerequisites: ["Stockage local fonctionnel."],
    steps: ["Vérifie que l’écran principal et les modes locaux restent accessibles.", "Évite de répéter une synchronisation en boucle.", "Joue et enregistre localement si le mode le permet.", "Marque mentalement ou dans l’UI l’état non synchronisé.", "Quand le réseau revient, relance une seule synchronisation.", "Vérifie le rapport et les conflits éventuels."],
    verify: ["Les parties locales restent disponibles et la synchronisation reprend ensuite."],
    troubleshooting: ["App bloquée par cloud : distinguer authentification et données locales.", "Sync répétée : attendre un réseau stable."],
    warnings: ["Ne purge pas les données locales parce qu’un service cloud renvoie une erreur."],
    related: ["Offline-first", "Cloud", "Synchronisation"],
  },
  {
    id: "v90-r2-retention", domain: "data", title: "Configurer une rétention cloud raisonnable",
    aliases: ["retention r2", "garder dernier backup", "nettoyer cloud"], route: "sync_center",
    purpose: "Limiter le volume cloud sans perdre le point de restauration utile.",
    prerequisites: ["Politique de sauvegarde décidée."],
    steps: ["Définis combien de sauvegardes doivent réellement être conservées.", "Identifie les objets par date/version.", "Vérifie qu’au moins une sauvegarde récente est restaurable.", "Supprime seulement les versions hors politique.", "Mesure le volume après nettoyage.", "Surveille les nouvelles écritures automatiques.", "Documente la règle de rétention."],
    verify: ["Le bucket contient uniquement le nombre de versions souhaité et la dernière est valide."],
    troubleshooting: ["Le volume remonte vite : cherche un job/upload répété.", "Objets sans métadonnées : ne les supprime pas avant identification."],
    warnings: ["Ne garde pas une seule copie cloud si aucune autre sauvegarde n’existe."],
    related: ["R2", "Rétention", "Recovery"],
  },
  {
    id: "v90-profile-new", domain: "account", title: "Créer un profil local complet",
    aliases: ["creer profil complet", "nouveau joueur profil", "ajouter joueur"], route: "profiles",
    purpose: "Créer un joueur réutilisable dans les modes et les statistiques.",
    prerequisites: ["Écran Profils accessible."],
    steps: ["Crée un nouveau profil.", "Renseigne le nom affiché.", "Ajoute avatar si souhaité.", "Associe un dartset ou préférences si disponibles.", "Enregistre.", "Sélectionne-le comme profil actif uniquement si c’est la personne principale.", "Ouvre un sélecteur X01 pour vérifier qu’il apparaît."],
    verify: ["Le profil est visible à la fois dans Profils et dans les sélecteurs de joueurs."],
    troubleshooting: ["Visible puis disparu : suspecte réhydratation/cache.", "Avatar absent ailleurs : vérifie résolveur média."],
    warnings: ["Ne confonds pas profil local et compte cloud."],
    related: ["Profils", "Profil actif", "Dartsets"],
  },
  {
    id: "v90-profile-active", domain: "account", title: "Changer de profil actif sans modifier les autres joueurs",
    aliases: ["changer profil actif", "selection profil principal", "profil courant"], route: "profiles",
    purpose: "Définir la personne associée aux préférences principales sans supprimer ni remplacer les autres profils.",
    prerequisites: ["Plusieurs profils existants."],
    steps: ["Ouvre Profils.", "Choisis le profil à rendre actif.", "Vérifie l’indicateur de profil actif.", "Ouvre Settings et contrôle langue/thème/préférences associées.", "Reviens aux sélecteurs de partie et vérifie que les autres profils restent disponibles.", "Redémarre l’app pour confirmer la persistance."],
    verify: ["Le bon profil reste actif après redémarrage et les autres profils existent toujours."],
    troubleshooting: ["Langue/thème basculent : vérifier la règle de synchronisation Settings ↔ profil.", "Autres profils masqués : vérifier filtre plutôt que données."],
    warnings: ["Activer un profil ne doit pas supprimer les autres."],
    related: ["Profil actif", "Settings", "Préférences"],
  },
  {
    id: "v90-avatar-repair", domain: "data", title: "Réparer un avatar manquant sans recréer le profil",
    aliases: ["reparer avatar", "avatar disparu", "photo profil manquante"], route: "profiles",
    purpose: "Restaurer le média tout en conservant historique et identifiant du profil.",
    prerequisites: ["Profil existant identifiable."],
    steps: ["Ouvre le profil concerné.", "Vérifie si l’avatar apparaît dans l’éditeur.", "S’il est absent, sélectionne ou recrée uniquement le média.", "Enregistre sans recréer le profil.", "Vérifie dans Profils, X01Config et Stats.", "Si l’image n’apparaît que sur certains écrans, signale un problème de résolution/cache plutôt que de recommencer."],
    verify: ["Le même profil garde son historique et affiche l’avatar partout."],
    troubleshooting: ["Image visible dans l’éditeur seulement : cache/résolveur différent.", "URL blob morte : recréer la référence média."],
    warnings: ["Ne crée pas un nouveau profil juste pour récupérer une photo."],
    related: ["Avatar", "Profil", "Cache média"],
  },
  {
    id: "v90-dartset-optimize", domain: "performance", title: "Ajouter un dartset sans ralentir les sélecteurs",
    aliases: ["ajouter dartset optimise", "image dartset performante", "set flechettes image"], route: "profiles",
    purpose: "Conserver une bonne qualité visuelle avec un poids et un décodage raisonnables.",
    prerequisites: ["Image du dartset disponible."],
    steps: ["Redimensionne l’image à une définition utile pour l’affichage réel.", "Utilise un format web optimisé compatible avec le projet.", "Conserve un nom de fichier stable.", "Ajoute l’asset et mets à jour toutes ses références.", "Ouvre Profils puis X01Config.", "Vérifie le temps du premier chargement puis du second.", "Contrôle visuellement la netteté sur téléphone."],
    verify: ["Le dartset reste net et le second affichage est quasi immédiat."],
    troubleshooting: ["Lenteur uniquement au premier affichage : décodage/cache.", "Lenteur à chaque fois : accès ou rerenders à profiler."],
    warnings: ["Ne change pas une extension sans rechercher toutes les références au nom précédent."],
    related: ["Dartsets", "WebP", "Performance"],
  },
  {
    id: "v90-stats-audit", domain: "stats", title: "Auditer une statistique avant de conclure qu’elle est fausse",
    aliases: ["verifier stat", "audit stats", "statistique bizarre"], route: "stats",
    purpose: "Déterminer si l’écart vient d’une formule, d’un filtre ou de données manquantes.",
    prerequisites: ["Une valeur suspecte et au moins une partie connue."],
    steps: ["Note le nom exact de la métrique.", "Note la période et le mode sélectionnés.", "Compte manuellement un petit échantillon connu.", "Compare la définition attendue à la formule réelle si disponible.", "Vérifie si les anciennes parties possèdent les champs nécessaires.", "Compare avec l’Historique.", "Seulement ensuite, classe le problème comme calcul, filtre ou stockage."],
    verify: ["Une partie test produit la valeur manuelle attendue."],
    troubleshooting: ["Deux pages diffèrent : vérifier périmètre et formule.", "Anciennes parties incomplètes : afficher l’absence de donnée plutôt qu’inventer."],
    warnings: ["Ne corrige pas l’affichage sans corriger la source de calcul."],
    related: ["Stats", "Historique", "Source de vérité"],
  },
  {
    id: "v90-stats-compare-players", domain: "stats", title: "Comparer deux joueurs de manière équitable",
    aliases: ["comparer joueurs stats", "comparateur joueurs", "head to head equitable"], route: "stats",
    purpose: "Éviter une conclusion trompeuse due à des volumes ou modes très différents.",
    prerequisites: ["Deux profils avec historique."],
    steps: ["Choisis une période commune.", "Filtre le même sport et si possible le même mode.", "Compare nombre de matchs.", "Ajoute win rate et métriques de performance pertinentes.", "Sépare H2H direct et performances globales.", "Observe tendance récente.", "Mentionne les différences de volume d’échantillon."],
    verify: ["La comparaison indique clairement période, modes et nombre de matchs."],
    troubleshooting: ["Échantillons très différents : privilégie ratios et contexte.", "H2H rare : ne le présente pas comme preuve absolue."],
    warnings: ["Ne compare pas deux moyennes calculées sur des règles différentes."],
    related: ["H2H", "Win rate", "Échantillon"],
  },
  {
    id: "v90-tournament-safe-create", domain: "competition", title: "Créer un tournoi avec paramètres vérifiables",
    aliases: ["creer tournoi propre", "tournoi sans erreur", "configurer tournoi"], route: "tournament_create",
    purpose: "Éviter de découvrir un problème de format après plusieurs matchs.",
    prerequisites: ["Participants ou équipes prêts."],
    steps: ["Choisis le type de participants.", "Sélectionne tous les inscrits.", "Choisis le format du tournoi.", "Définis seeding/tirage et éventuels départages.", "Génère le tableau.", "Relis le nombre de matchs et les byes.", "Lance un match de test seulement si le format est confirmé."],
    verify: ["Le nombre de participants et la structure du tableau correspondent au format voulu."],
    troubleshooting: ["Trop de byes : vérifie format et nombre de participants.", "Équipe manquante : reviens à la composition avant de jouer."],
    warnings: ["Après plusieurs matchs, changer le format peut invalider tout le tableau."],
    related: ["Tournoi", "Bracket", "Seeding"],
  },
  {
    id: "v90-tournament-recover", domain: "competition", title: "Récupérer un tournoi interrompu",
    aliases: ["reprendre tournoi", "tournoi interrompu", "continuer competition"], route: "tournament_view",
    purpose: "Reprendre une compétition sans recréer les résultats déjà enregistrés.",
    prerequisites: ["Tournoi existant dans le stockage."],
    steps: ["Ouvre la liste des tournois.", "Sélectionne le tournoi existant.", "Vérifie les matchs déjà finalisés.", "Repère le prochain match non joué.", "Contrôle le classement/tableau avant reprise.", "Lance uniquement ce match.", "Après résultat, vérifie la progression."],
    verify: ["Les anciens résultats restent intacts et le prochain match se débloque correctement."],
    troubleshooting: ["Tournoi absent : vérifier source de stockage/import.", "Tableau incohérent : identifier le premier résultat qui diverge."],
    warnings: ["Ne recrée pas un nouveau tournoi avec les mêmes joueurs si l’ancien est récupérable."],
    related: ["Tournoi", "Historique", "Recovery"],
  },
  {
    id: "v90-x01-voice-start", domain: "assistant", title: "Lancer un X01 entièrement par dialogue Awéna",
    aliases: ["awena lance x01", "configuration vocale x01", "partie x01 voix"], route: "x01_config_v3",
    purpose: "Utiliser Awéna pour remplir la configuration guidée X01.",
    prerequisites: ["Commandes vocales activées et micro autorisé."],
    steps: ["Dis « Awéna, lance-moi une partie de X01 ».", "Réponds au type de partie demandé.", "Choisis joueurs ou équipes.", "Indique le score de départ.", "Réponds pour IN et OUT.", "Choisis format sets/legs et Best Of/First To si demandé.", "Choisis méthode de saisie et options audio.", "Écoute le récapitulatif.", "Dis explicitement de lancer seulement si tout est correct."],
    verify: ["Les contrôles visibles correspondent aux réponses et la partie ouvre X01PlayV3."],
    troubleshooting: ["Question mal comprise : corrige le paramètre plutôt que continuer.", "Micro coupé : repasse au tactile, la configuration visible doit rester exploitable."],
    warnings: ["La validation finale doit rester explicite."],
    related: ["Voice X01", "Awéna", "X01"],
  },
  {
    id: "v90-x01-method-switch", domain: "app", title: "Changer la méthode de saisie X01 avant le lancement",
    aliases: ["changer keypad cible voice", "methode saisie x01", "scoring input x01"], route: "x01_config_v3",
    purpose: "Choisir le canal de score adapté sans changer les autres règles de la partie.",
    prerequisites: ["Configuration X01 ouverte."],
    steps: ["Repère la méthode de saisie actuelle.", "Choisis KEYPAD, CIBLE, PRESETS, VOICE ou méthode externe disponible.", "Si externe, réalise un test de connexion.", "Vérifie que joueurs, score, IN/OUT et format n’ont pas changé.", "Lance une courte partie test si la méthode est nouvelle.", "Confirme le fallback manuel."],
    verify: ["La partie démarre avec la méthode choisie et les autres paramètres sont inchangés."],
    troubleshooting: ["Option grisée : vérifie prérequis/permission.", "Événement absent : repasse au keypad pour isoler la connexion."],
    warnings: ["Ne confonds pas commande vocale Awéna et scoring vocal des fléchettes."],
    related: ["X01", "Scoring", "Voice"],
  },
  {
    id: "v90-x01-correct-dart", domain: "app", title: "Corriger une fléchette mal saisie pendant X01",
    aliases: ["corriger flechette x01", "undo dart", "mauvaise saisie score"], route: "x01_play_v3",
    purpose: "Réparer l’historique de la partie au lieu de compenser avec un score artificiel.",
    prerequisites: ["Partie X01 en cours."],
    steps: ["Utilise Undo pour revenir à l’événement incorrect.", "Vérifie joueur actif et score restauré.", "Ressaisis la bonne fléchette ou volée.", "Contrôle le total de la visite.", "Poursuis la partie.", "À la fin, vérifie que les statistiques reflètent la correction."],
    verify: ["Score, joueur actif et historique de darts correspondent à ce qui s’est réellement passé."],
    troubleshooting: ["Undo retire trop d’actions : arrête avant de ressaisir et vérifie la timeline.", "Stats encore fausses : vérifier que la correction modifie l’événement source."],
    warnings: ["Ne compense pas une erreur en ajoutant un faux score inverse."],
    related: ["Undo", "X01", "Historique"],
  },
  {
    id: "v90-x01-end-read", domain: "stats", title: "Lire correctement l’écran de fin X01",
    aliases: ["comprendre x01 end", "lire resume x01", "stats fin x01"], route: "x01_end",
    purpose: "Interpréter classement et KPI sans confondre score, moyenne et sorties.",
    prerequisites: ["Partie X01 terminée."],
    steps: ["Commence par le classement et le résultat sets/legs.", "Lis nombre de volées et darts.", "Lis AVG3 selon la définition affichée.", "Observe seuils 60+/100+/140+/180.", "Lis meilleure volée et checkout si disponibles.", "Compare les joueurs sur le même périmètre.", "Ouvre les sous-pages de stats pour le détail."],
    verify: ["Les valeurs du résumé correspondent à l’historique de la partie."],
    troubleshooting: ["Scoreline étrange : vérifier structure sets/legs.", "AVG différente ailleurs : vérifier période/formule."],
    warnings: ["Une meilleure volée ne résume pas à elle seule la performance globale."],
    related: ["X01 End", "AVG3", "Checkout"],
  },
  {
    id: "v90-android-version-check", domain: "android", title: "Vérifier exactement quelle version Android est installée",
    aliases: ["voir version installee", "quelle version android app", "versionCode appareil"], route: "settings",
    purpose: "Éviter de tester un bug sur une ancienne build en pensant avoir la dernière.",
    prerequisites: ["Application installée sur l’appareil."],
    steps: ["Ouvre l’écran À propos/Settings si la version y est affichée.", "Note versionName et, si disponible, versionCode.", "Compare avec la release attendue dans Google Play Console.", "Vérifie la piste utilisée par le compte testeur.", "Si les valeurs diffèrent, demande une mise à jour depuis Play Store.", "Relance l’app et recontrôle."],
    verify: ["La version affichée correspond exactement à la release que tu souhaites tester."],
    troubleshooting: ["Play ne propose rien : piste ou propagation à vérifier.", "VersionName identique mais comportement ancien : comparer versionCode/build."],
    warnings: ["Ne suppose pas qu’un bouton « Ouvrir » signifie que la dernière version est installée."],
    related: ["Google Play", "VersionCode", "Test fermé"],
  },
  {
    id: "v90-play-track-audit", domain: "android", title: "Vérifier la bonne piste Google Play pour un testeur",
    aliases: ["verifier piste play", "testeur mauvaise track", "internal closed track"], route: "settings",
    purpose: "Comprendre pourquoi deux testeurs peuvent recevoir des versions différentes.",
    prerequisites: ["Accès Play Console et compte testeur concerné."],
    steps: ["Dans Play Console, note les releases actives par piste.", "Vérifie la liste/groupe de testeurs de la piste voulue.", "Sur le téléphone, confirme le compte Google utilisé par Play Store.", "Ouvre le lien d’opt-in de cette piste.", "Vérifie que le testeur est bien inscrit.", "Compare la version disponible.", "Retire d’anciennes pistes uniquement si cela fait partie du plan de test."],
    verify: ["Le compte testeur est inscrit à la piste qui contient le versionCode attendu."],
    troubleshooting: ["Plusieurs pistes : la distribution peut suivre des règles de priorité.", "Compte différent sur Play Store : corriger avant autre action."],
    warnings: ["Ne modifie pas toutes les pistes pour corriger un seul testeur."],
    related: ["Play Console", "Test fermé", "Version Android"],
  },
  {
    id: "v90-release-preflight", domain: "android", title: "Faire un contrôle pré-publication Android",
    aliases: ["checklist release android", "avant upload aab", "preflight google play"], route: "settings",
    purpose: "Réduire les erreurs évitables avant génération et upload du bundle.",
    prerequisites: ["Code de référence stabilisé.", "Sauvegarde du projet."],
    steps: ["Lance le typecheck/tests prévus.", "Vérifie versionCode supérieur.", "Vérifie versionName lisible.", "Confirme Application ID.", "Build le web.", "Synchronise Capacitor.", "Génère le bundle release signé.", "Teste l’installation sur appareil de test si possible.", "Contrôle les fonctions sensibles : stockage, micro, caméra, achats, pubs.", "Seulement ensuite, upload sur la piste prévue."],
    verify: ["Le bundle est signé, s’installe et les tests critiques passent."],
    troubleshooting: ["Erreur après cap sync : vérifier assets/plugins natifs.", "Erreur Play : lire le message avant de regénérer au hasard."],
    warnings: ["Ne publie pas une build non testée juste parce que Gradle a terminé sans erreur."],
    related: ["AAB", "Capacitor", "Google Play"],
  },
  {
    id: "v90-logcat-capture", domain: "android", title: "Capturer un Logcat utile autour d’un crash",
    aliases: ["capturer logcat", "logs crash android", "stacktrace android"], route: "settings",
    purpose: "Obtenir une trace ciblée plutôt qu’un énorme journal difficile à exploiter.",
    prerequisites: ["Appareil connecté au PC avec débogage disponible."],
    steps: ["Vide ou marque le journal juste avant le test si ton outil le permet.", "Reproduis le crash une seule fois.", "Arrête la capture peu après.", "Cherche FATAL EXCEPTION, AndroidRuntime ou le package de l’application.", "Conserve le stack trace complet autour de la première erreur.", "Ajoute l’action exacte qui provoque le crash.", "Masque tokens et données personnelles avant partage."],
    verify: ["Le rapport contient l’heure, l’action, la première exception et sa pile."],
    troubleshooting: ["Trop de logs : filtre par package/processus.", "Pas de Java crash : inspecter console WebView/JavaScript."],
    warnings: ["Ne partage pas des secrets d’authentification contenus dans les logs."],
    related: ["Logcat", "Crash", "Rapport de bug"],
  },
  {
    id: "v90-cache-vs-data", domain: "android", title: "Choisir entre vider le cache et effacer les données",
    aliases: ["vider cache ou donnees", "clear cache clear data", "reset android"], route: "settings",
    purpose: "Éviter de perdre profils et historique pour résoudre un simple problème d’affichage.",
    prerequisites: ["Comprendre que cache et données n’ont pas le même impact."],
    steps: ["Commence par fermer/réouvrir l’application.", "Si le problème concerne des ressources temporaires, teste le cache seulement.", "Avant « Effacer les données », crée une sauvegarde Recovery si possible.", "Note le compte actif.", "Efface les données uniquement dans un scénario de diagnostic justifié.", "Restaure ou reconnecte ensuite selon le plan.", "Vérifie profils et historique."],
    verify: ["Le problème est résolu sans perte non prévue."],
    troubleshooting: ["Cache vidé sans effet : chercher la vraie source.", "Données effacées par erreur : tenter Recovery/cloud disponible."],
    warnings: ["« Effacer les données » peut supprimer le stockage local complet."],
    related: ["Cache", "Recovery", "Android"],
  },
  {
    id: "v90-webview-update", domain: "android", title: "Diagnostiquer un problème lié à Android System WebView",
    aliases: ["mettre a jour webview", "bug webview", "android system webview"], route: "settings",
    purpose: "Isoler un bug qui apparaît sur un appareil Android mais pas sur le build web ou d’autres téléphones.",
    prerequisites: ["Accès Play Store de l’appareil."],
    steps: ["Note la version Android et WebView.", "Teste le même écran dans une autre installation/appareil si possible.", "Mets à jour Android System WebView via le canal officiel.", "Redémarre l’application.", "Reproduis le scénario.", "Si le bug persiste, récupère console/Logcat.", "Ne conclus à WebView que si les éléments convergent."],
    verify: ["Le comportement est reproductible ou corrigé après mise à jour de WebView."],
    troubleshooting: ["WebView déjà à jour : chercher code/asset/plugin.", "Bug uniquement sur une version Android : vérifier compatibilité ciblée."],
    warnings: ["Ne conseille pas une APK WebView provenant d’une source inconnue."],
    related: ["WebView", "Android", "Crash"],
  },
  {
    id: "v90-admob-test-real", domain: "ads", title: "Passer des annonces test aux vraies unités AdMob",
    aliases: ["passer pub test vraies", "admob production", "ids pub reel"], route: "settings",
    purpose: "Valider l’intégration sans risquer du trafic invalide.",
    prerequisites: ["Bannières/interstitiels fonctionnels avec IDs de test.", "Consentement UMP testé."],
    steps: ["Vérifie les Ad Unit IDs du compte AdMob.", "Remplace uniquement les IDs prévus pour la build release.", "Garde les appareils de développement déclarés comme test si nécessaire.", "Vérifie app-ads.txt.", "Teste que l’UI reste correcte même sans annonce.", "Surveille les erreurs de chargement.", "Ne clique jamais volontairement sur tes propres annonces réelles."],
    verify: ["Les emplacements chargent lorsque l’inventaire existe et l’application fonctionne aussi en No Fill."],
    troubleshooting: ["Aucune pub : distinguer No Fill, consentement et ID incorrect.", "Crash : isoler callback ou cycle de vie du plugin."],
    warnings: ["Ne génère pas de clics réels de test."],
    related: ["AdMob", "UMP", "app-ads.txt"],
  },
  {
    id: "v90-privacy-options", domain: "ads", title: "Rendre les options de confidentialité accessibles après le premier consentement",
    aliases: ["changer consentement pub", "options confidentialite ads", "ump privacy"], route: "settings",
    purpose: "Permettre à l’utilisateur de revoir ses choix lorsque la réglementation ou UMP le requiert.",
    prerequisites: ["UMP intégré et état de consentement connu."],
    steps: ["Ouvre Settings > Confidentialité/Pub.", "Expose l’action de gestion des options si UMP la rend disponible.", "Ouvre le formulaire de confidentialité.", "Enregistre le nouveau choix.", "Rafraîchis l’état publicitaire.", "Vérifie que l’application reste utilisable quel que soit le choix."],
    verify: ["Le statut de consentement reflète le nouveau choix."],
    troubleshooting: ["Option absente : vérifier disponibilité retournée par UMP.", "Annonces inchangées immédiatement : attendre le prochain cycle de demande."],
    warnings: ["Ne simule pas un consentement qui n’a pas été donné."],
    related: ["UMP", "Confidentialité", "AdMob"],
  },
  {
    id: "v90-premium-verify", domain: "billing", title: "Vérifier un entitlement Premium après achat",
    aliases: ["verifier premium", "entitlement achat", "statut pro"], route: "settings",
    purpose: "Confirmer que le droit Premium reconnu correspond à un achat valide.",
    prerequisites: ["Achat effectué ou restauré."],
    steps: ["Vérifie le compte Play actif.", "Rafraîchis les achats détenus.", "Compare Product ID avec celui attendu.", "Vérifie l’état acheté/acknowledged selon l’intégration.", "Mets à jour l’entitlement local seulement après validation.", "Ouvre une fonction Premium de test.", "Redémarre l’app et recontrôle."],
    verify: ["Le droit reste actif après redémarrage avec le bon compte."],
    troubleshooting: ["Achat existe mais droit absent : inspecter mapping Product ID.", "Droit local actif sans achat : ne pas considérer cela comme validation."],
    warnings: ["Ne stocke pas uniquement un booléen local facilement désynchronisé comme preuve définitive."],
    related: ["Billing", "Premium", "Restore"],
  },
  {
    id: "v90-image-convert", domain: "performance", title: "Convertir un asset image sans casser ses références",
    aliases: ["convertir png webp", "changer extension asset", "optimiser image code"], route: "settings",
    purpose: "Réduire le poids du projet tout en conservant tous les usages de l’image.",
    prerequisites: ["Projet sauvegardé.", "Recherche globale disponible."],
    steps: ["Recherche le nom de fichier actuel dans tout le projet.", "Note imports, URLs CSS, JSON et références dynamiques.", "Convertis l’image au format choisi.", "Ajoute le nouveau fichier.", "Remplace toutes les références avec le nouveau nom/extension.", "Relance typecheck/build.", "Ouvre tous les écrans qui utilisaient l’asset.", "Supprime l’ancien fichier uniquement après validation."],
    verify: ["Aucune référence à l’ancien nom ne subsiste et tous les écrans s’affichent."],
    troubleshooting: ["Image absente sur Android uniquement : vérifier casse du chemin et copie des assets.", "Référence dynamique non trouvée : rechercher le basename sans extension."],
    warnings: ["Ne supprime pas l’original avant la recherche complète."],
    related: ["WebP", "Assets", "Optimisation"],
  },
  {
    id: "v90-audio-compress", domain: "performance", title: "Compresser un son sans dégrader l’expérience",
    aliases: ["compresser audio app", "reduire mp3 ogg", "sons trop lourds"], route: "settings",
    purpose: "Réduire la taille des assets audio avec un niveau de qualité adapté à leur usage.",
    prerequisites: ["Fichier source conservé hors build si nécessaire."],
    steps: ["Identifie la durée et le rôle du son.", "Choisis codec/bitrate adapté à voix, jingle ou effet court.", "Encode une version de test.", "Compare volume, attaques et artefacts sur téléphone.", "Remplace le fichier dans le projet.", "Mets à jour les références si l’extension change.", "Teste lecture, boucle et latence.", "Supprime l’ancienne version seulement après validation."],
    verify: ["Le son reste propre et son poids diminue réellement."],
    troubleshooting: ["Latence accrue : choisir un format plus adapté aux effets courts.", "Son trop faible : normaliser sans écrêtage."],
    warnings: ["Ne réencode pas plusieurs fois un fichier déjà fortement compressé."],
    related: ["Audio", "Assets", "Taille app"],
  },
  {
    id: "v90-video-compress", domain: "performance", title: "Compresser une vidéo intégrée sans casser son affichage",
    aliases: ["compresser video app", "reduire mp4", "video intro lourde"], route: "settings",
    purpose: "Réduire la taille tout en gardant une lecture fluide sur Android/PWA.",
    prerequisites: ["Vidéo source disponible."],
    steps: ["Mesure résolution, durée et bitrate actuels.", "Choisis une résolution correspondant à la taille réelle d’affichage.", "Encode une version optimisée.", "Teste démarrage et seek sur téléphone.", "Vérifie poster/fallback.", "Remplace la référence si le nom change.", "Teste INTRO ON/OFF et toute page qui charge la vidéo.", "Contrôle la taille du bundle."],
    verify: ["La lecture reste fluide et la taille baisse sans artefacts gênants."],
    troubleshooting: ["Vidéo noire Android : vérifier codec/profil compatible.", "Démarrage lent : réduire bitrate ou charger plus tard."],
    warnings: ["Ne supprime pas le poster ou fallback utilisé pendant le chargement."],
    related: ["Vidéo", "INTRO", "Optimisation"],
  },
  {
    id: "v90-performance-profile", domain: "performance", title: "Profiler une page lente avant de la modifier",
    aliases: ["profiler page lente", "diagnostic performance react", "trouver cause lenteur"], route: "settings",
    purpose: "Identifier la vraie source de lenteur avant d’optimiser.",
    prerequisites: ["Scénario reproductible."],
    steps: ["Note le temps perçu et l’action exacte.", "Teste à froid puis une seconde fois.", "Observe si le coût vient du réseau, des données ou du rendu.", "Utilise le profiler React/Performance si disponible.", "Repère les composants ou tâches les plus coûteux.", "Formule une hypothèse unique.", "Applique une modification ciblée.", "Mesure à nouveau le même scénario."],
    verify: ["Le gain est mesurable et la fonctionnalité reste identique."],
    troubleshooting: ["Aucun composant coûteux : inspecter IndexedDB/médias.", "Lenteur uniquement après plusieurs navigations : chercher fuite/listeners."],
    warnings: ["Ne supprime pas des fonctionnalités pour gagner du temps sans preuve."],
    related: ["Performance", "React", "Profilage"],
  },
  {
    id: "v90-memory-leak-check", domain: "performance", title: "Chercher une fuite mémoire après plusieurs navigations",
    aliases: ["tester fuite memoire", "ram augmente navigation", "listeners accumules"], route: "settings",
    purpose: "Déterminer si l’application conserve des objets ou abonnements inutilement.",
    prerequisites: ["Scénario de navigation répétable."],
    steps: ["Relève la mémoire après démarrage.", "Fais plusieurs allers-retours sur l’écran suspect.", "Attends un moment pour laisser le garbage collector agir.", "Relève à nouveau la mémoire.", "Cherche listeners, intervals, object URLs et caches non bornés.", "Corrige un type de rétention à la fois.", "Refais exactement le même test."],
    verify: ["La mémoire se stabilise au lieu d’augmenter continuellement."],
    troubleshooting: ["Mémoire varie mais redescend : ce n’est pas forcément une fuite.", "Croissance liée aux images : vérifier cache et blobs."],
    warnings: ["Ne juge pas une fuite sur une seule mesure instantanée."],
    related: ["Memory leak", "useEffect cleanup", "Cache"],
  },
  {
    id: "v90-double-event-debug", domain: "performance", title: "Diagnostiquer un événement enregistré deux fois",
    aliases: ["event double", "handler deux fois", "double score bug"], route: "settings",
    purpose: "Identifier si le doublon vient de l’UI, du réseau ou d’un abonnement.",
    prerequisites: ["Bug reproductible."],
    steps: ["Ajoute ou consulte un identifiant/horodatage d’événement.", "Effectue une seule action.", "Compte le nombre d’handlers appelés.", "Vérifie les listeners montés.", "Si source externe, inspecte les messages bruts.", "Ajoute une garde idempotente.", "Refais le test après navigation aller-retour."],
    verify: ["Une action produit exactement un événement persistant."],
    troubleshooting: ["Un message réseau unique mais deux écritures : problème côté handler.", "Deux messages bruts : problème côté source/reconnexion."],
    warnings: ["Ne masque pas le doublon uniquement à l’affichage."],
    related: ["Idempotence", "Listeners", "Scoring"],
  },
  {
    id: "v90-offline-test", domain: "data", title: "Tester l’application réellement hors ligne",
    aliases: ["test offline", "mode avion app", "pwa hors ligne"], route: "gameSelect",
    purpose: "Vérifier quelles fonctions restent disponibles sans réseau.",
    prerequisites: ["Application déjà chargée au moins une fois.", "Sauvegarde des données importantes."],
    steps: ["Ouvre l’application en ligne et laisse les assets nécessaires se charger.", "Active le mode avion.", "Relance l’app.", "Teste navigation principale.", "Lance une fonction locale courte.", "Vérifie sauvegarde locale.", "Note clairement les fonctions cloud/online indisponibles.", "Rétablis le réseau et vérifie la reprise."],
    verify: ["Les fonctions locales promises restent utilisables et les fonctions réseau signalent proprement leur indisponibilité."],
    troubleshooting: ["Écran blanc hors ligne : vérifier Service Worker/cache des assets.", "Données absentes : distinguer cache PWA et IndexedDB."],
    warnings: ["Ne teste pas la restauration cloud en mode avion."],
    related: ["Offline-first", "PWA", "Service Worker"],
  },
  {
    id: "v90-pwa-update", domain: "android", title: "Vérifier qu’une mise à jour PWA ne sert pas un ancien bundle",
    aliases: ["pwa ancienne version", "service worker cache", "maj web pas visible"], route: "settings",
    purpose: "Éviter de confondre cache PWA et code réellement déployé.",
    prerequisites: ["Nouvelle version web déployée."],
    steps: ["Recharge normalement une première fois.", "Vérifie l’identifiant/version visible dans l’app.", "Ferme puis rouvre l’onglet ou l’application.", "Si l’ancien code persiste, inspecte l’état du Service Worker.", "Vérifie les headers/cache du déploiement.", "Force uniquement le mécanisme de mise à jour prévu.", "Reteste sans effacer les données locales applicatives."],
    verify: ["Le nouveau bundle est servi tout en conservant profils et historique."],
    troubleshooting: ["Nouvelle ressource mais ancien JS : cache/service worker.", "Android natif différent du web : vérifier cap sync/build."],
    warnings: ["Ne mélange pas « effacer cache navigateur » et « effacer IndexedDB » sans sauvegarde."],
    related: ["PWA", "Service Worker", "Cache"],
  },
  {
    id: "v90-app-size-audit", domain: "performance", title: "Faire un audit de taille avant de convertir des centaines d’assets",
    aliases: ["audit poids app", "quels fichiers lourds", "taille projet analyse"], route: "settings",
    purpose: "Prioriser les gains sans casser de nombreuses références pour quelques kilo-octets.",
    prerequisites: ["ZIP/projet actuel disponible."],
    steps: ["Classe les fichiers par taille et type.", "Calcule le poids cumulé images, vidéos, audio et bibliothèques.", "Repère les plus gros fichiers et les doublons exacts.", "Recherche leur fréquence d’utilisation.", "Commence par les gains élevés et peu risqués.", "Convertis un lot limité.", "Rebuild et compare la taille.", "Répète par lots."],
    verify: ["Chaque lot produit un gain mesuré et aucun asset ne manque."],
    troubleshooting: ["Gain faible : le poids vient peut-être des vidéos/libs natives.", "Assets dupliqués sous noms différents : vérifier contenu par hash."],
    warnings: ["Ne fais pas une conversion globale sans tests intermédiaires."],
    related: ["Taille app", "Assets", "Hash"],
  },
  {
    id: "v90-data-export-emergency", domain: "data", title: "Faire un export d’urgence avant une manipulation risquée",
    aliases: ["export urgence", "sauver donnees avant reset", "backup rapide"], route: "sync_center",
    purpose: "Créer une copie de sécurité lorsque l’application fonctionne encore partiellement.",
    prerequisites: ["Accès à Sync/Recovery ou export."],
    steps: ["Arrête les manipulations destructives.", "Exporte les données disponibles.", "Télécharge/partage le fichier hors de l’appareil.", "Vérifie sa taille et sa date.", "Si possible, crée aussi une Recovery complète.", "Note la version de l’application.", "Seulement ensuite, poursuis le diagnostic."],
    verify: ["Au moins une copie externe existe avant toute réinitialisation."],
    troubleshooting: ["Export échoue : tente par catégorie si disponible.", "Fichier vide : ne le considère pas comme sauvegarde."],
    warnings: ["Ne vide pas les données avant d’avoir confirmé une copie exploitable."],
    related: ["Recovery", "Export", "Diagnostic"],
  },
  {
    id: "v90-account-switch-safe", domain: "account", title: "Changer de compte sans mélanger les données locales",
    aliases: ["changer compte proprement", "switch account", "autre compte google app"], route: "settings",
    purpose: "Éviter d’attribuer par erreur l’historique local d’une personne à une autre identité cloud.",
    prerequisites: ["Connaître l’état des données locales et du compte actuel."],
    steps: ["Crée une sauvegarde Recovery.", "Note le compte actuellement connecté.", "Déconnecte-toi sans effacer les données locales sauf si c’est explicitement voulu.", "Connecte le nouveau compte.", "Observe ce que l’application considère comme données locales partagées ou liées.", "N’active une synchronisation qu’après avoir compris la politique de fusion.", "Vérifie profils et historique."],
    verify: ["Le compte affiché est correct et aucune synchronisation inattendue n’a fusionné les historiques."],
    troubleshooting: ["Données locales encore visibles : cela peut être normal si elles ne sont pas scindées par compte.", "Données remplacées : arrêter la sync et restaurer si nécessaire."],
    warnings: ["Ne suppose pas qu’une déconnexion vide automatiquement le stockage local."],
    related: ["Compte", "Synchronisation", "Recovery"],
  },
  {
    id: "v90-password-reset-safe", domain: "account", title: "Réinitialiser un mot de passe sans perdre la session de données locale",
    aliases: ["reset mot de passe sans perte", "password reset propre", "changer mot de passe"], route: "auth_reset",
    purpose: "Modifier l’accès au compte sans toucher inutilement aux données du téléphone.",
    prerequisites: ["Accès à l’adresse e-mail du compte."],
    steps: ["Demande la réinitialisation depuis le parcours officiel.", "Ouvre le lien reçu sur un appareil de confiance.", "Choisis un nouveau mot de passe.", "Reconnecte-toi.", "Vérifie le compte affiché.", "Contrôle que profils et historique locaux sont toujours présents.", "Relance la synchronisation seulement si nécessaire."],
    verify: ["Le compte est accessible avec le nouveau mot de passe et les données locales sont intactes."],
    troubleshooting: ["Lien expiré : redemande un nouveau lien.", "Mauvais compte : ne synchronise pas avant correction."],
    warnings: ["Ne supprime pas l’application pour résoudre un mot de passe oublié."],
    related: ["Compte", "Auth", "Session"],
  },
  {
    id: "v90-tablet-display", domain: "ux", title: "Préparer un second écran lisible pour une partie",
    aliases: ["tablette affichage score", "ecran secondaire lisible", "viewer plein ecran"], route: "viewer_display",
    purpose: "Obtenir un affichage de score clair à distance.",
    prerequisites: ["Viewer ou Cast fonctionnel."],
    steps: ["Place l’écran dans l’orientation adaptée.", "Active le plein écran si disponible.", "Vérifie contraste et taille des noms/scores.", "Évite la mise en veille pendant la partie.", "Teste la distance réelle de lecture.", "Vérifie que les mises à jour sont visibles sans interaction.", "Branche l’alimentation pour une longue session."],
    verify: ["Les joueurs lisent le score depuis la zone de jeu et l’écran reste actif."],
    troubleshooting: ["Texte trop petit : préférer layout Viewer dédié plutôt que zoom navigateur instable.", "Écran dort : ajuster veille système."],
    warnings: ["Ne laisse pas apparaître d’informations privées sur un écran public."],
    related: ["Viewer", "Cast", "Accessibilité"],
  },
  {
    id: "v90-accessibility-check", domain: "ux", title: "Vérifier la lisibilité d’un écran sur téléphone",
    aliases: ["audit lisibilite", "texte trop petit", "interface entassee"], route: "settings",
    purpose: "Repérer rapidement les problèmes de densité, contraste et zones tactiles.",
    prerequisites: ["Écran cible accessible sur un téléphone réel."],
    steps: ["Observe l’écran à taille normale sans zoom.", "Vérifie que les sections importantes respirent visuellement.", "Teste les boutons avec le pouce.", "Vérifie contraste sur le thème courant.", "Passe en petit puis grand téléphone si possible.", "Teste une chaîne de texte plus longue.", "Vérifie que les éléments fixes ne recouvrent rien."],
    verify: ["Toutes les actions principales sont identifiables et faciles à toucher."],
    troubleshooting: ["Contenu entassé : réduire densité ou regrouper en sous-onglets.", "Texte tronqué : rendre la mise en page flexible."],
    warnings: ["Ne règle pas un problème mobile uniquement sur un écran desktop."],
    related: ["Responsive", "Contraste", "Touch target"],
  },
  {
    id: "v90-theme-pack-check", domain: "ux", title: "Valider un thème premium avant publication",
    aliases: ["tester theme premium", "pack theme qualite", "theme arenas validation"], route: "settings",
    purpose: "Vérifier qu’un thème modifie réellement l’ambiance sans nuire à l’usage.",
    prerequisites: ["Pack de thème intégré."],
    steps: ["Teste GameSelect, Config, Play, Stats et Settings.", "Vérifie contraste texte/cartes.", "Contrôle fonds sur téléphone sombre et lumineux.", "Vérifie que textures ne masquent pas les informations.", "Teste les médias et icônes spécifiques.", "Compare temps de chargement avec thème standard.", "Vérifie retour au thème précédent."],
    verify: ["Le thème est distinctif, lisible, performant et réversible."],
    troubleshooting: ["Texte disparaît : ajouter traitement local plutôt que supprimer la texture entière.", "Chargement lent : optimiser les assets du pack."],
    warnings: ["Un thème payant ne doit pas dégrader les fonctions ou la lisibilité."],
    related: ["Thèmes", "Assets", "Performance"],
  },
  {
    id: "v90-intro-toggle-check", domain: "ux", title: "Vérifier le réglage INTRO ON/OFF",
    aliases: ["intro on off", "couper video intro", "tester intro settings"], route: "settings",
    purpose: "Confirmer que l’option contrôle à la fois vidéo et audio d’introduction.",
    prerequisites: ["Accès à Settings."],
    steps: ["Active INTRO.", "Redémarre l’application et vérifie vidéo + audio.", "Désactive INTRO.", "Ferme complètement l’application.", "Rouvre-la.", "Vérifie l’arrivée directe sur GameSelect.", "Réactive ensuite si souhaité."],
    verify: ["OFF saute entièrement l’intro ; ON restaure vidéo et son."],
    troubleshooting: ["Audio coupé mais vidéo visible : les deux branches du réglage ne sont pas liées.", "Réglage oublié après redémarrage : persistance à vérifier."],
    warnings: ["Ne confonds pas INTRO avec les sons de partie."],
    related: ["INTRO", "Settings", "Audio"],
  },
  {
    id: "v90-language-sync-check", domain: "ux", title: "Vérifier la synchronisation langue Settings et Mon Profil",
    aliases: ["sync langue profil", "langue settings profil", "language preference"], route: "settings",
    purpose: "Éviter qu’une navigation réapplique une ancienne préférence.",
    prerequisites: ["Profil actif existant."],
    steps: ["Change la langue dans Settings.", "Vérifie immédiatement Mon Profil.", "Navigue vers Profils puis Games.", "Reviens dans Settings.", "Redémarre l’application.", "Vérifie ticker, titres de jeux et navigation.", "Change ensuite la langue depuis le profil si ce parcours est prévu et contrôle la réciprocité."],
    verify: ["La même langue reste active partout après navigation et redémarrage."],
    troubleshooting: ["Retour au français sur Profils : priorité des sources à corriger.", "Titres de jeux non traduits : catalogue de labels à harmoniser."],
    warnings: ["Ne stocke pas deux préférences indépendantes sans règle de synchronisation."],
    related: ["Langue", "Profil actif", "Settings"],
  },
  {
    id: "v90-online-room-check", domain: "network", title: "Tester une salle Online avant une vraie partie",
    aliases: ["tester room online", "salon online", "partie reseau test"], route: "online",
    purpose: "Valider création, rejoindre, participants et reprise réseau.",
    prerequisites: ["Deux comptes/appareils si le mode l’exige."],
    steps: ["Crée une salle de test.", "Fais rejoindre le second participant.", "Vérifie noms et rôles.", "Lance une action simple.", "Observe la propagation.", "Coupe brièvement le réseau d’un appareil.", "Rétablis-le et vérifie la reconnexion.", "Ferme proprement la salle."],
    verify: ["Les deux appareils affichent le même état après reconnexion."],
    troubleshooting: ["Participant dupliqué : vérifier idempotence join/reconnect.", "État différent : resynchroniser snapshot serveur."],
    warnings: ["Ne teste pas une correction réseau uniquement en solo sur le même appareil."],
    related: ["Online", "Reconnexion", "Session"],
  },
  {
    id: "v90-spectator-privacy", domain: "network", title: "Activer un spectateur sans exposer plus de données que nécessaire",
    aliases: ["spectateur confidentialite", "viewer public securite", "partage match"], route: "spectator",
    purpose: "Partager le score tout en limitant les données personnelles.",
    prerequisites: ["Session spectateur disponible."],
    steps: ["Choisis la partie à exposer.", "Vérifie quelles informations seront visibles.", "Génère le lien/code spectateur.", "Teste-le dans un navigateur non authentifié si le mode doit être public.", "Vérifie qu’aucune donnée de compte privée n’apparaît.", "Révoque/ferme la session après la partie.", "Teste qu’un ancien lien n’affiche plus une session fermée."],
    verify: ["Le spectateur voit uniquement les informations prévues et la session se ferme correctement."],
    troubleshooting: ["Ancien lien encore actif : revoir expiration/révocation.", "Infos privées visibles : réduire le payload du Viewer."],
    warnings: ["Ne transmet pas e-mail, tokens ou données privées dans un écran public."],
    related: ["Spectateur", "Viewer", "Confidentialité"],
  },
  {
    id: "v90-babyfoot-match-check", domain: "app", title: "Configurer une partie Baby-foot sans mélanger équipes et joueurs",
    aliases: ["config babyfoot equipe", "partie babyfoot joueurs", "setup babyfoot"], route: "babyfoot_config",
    purpose: "Créer un match cohérent pour l’historique et les statistiques.",
    prerequisites: ["Profils/équipes prêts si utilisés."],
    steps: ["Choisis le format joueur/équipe.", "Sélectionne les participants.", "Vérifie l’ordre ou les côtés.", "Choisis les paramètres de score disponibles.", "Lance la partie.", "Enregistre un but test si nécessaire.", "Vérifie le résumé final sur une partie courte."],
    verify: ["Les buts et le résultat sont attribués aux bons participants."],
    troubleshooting: ["Stats au mauvais joueur : mapping équipe/profil à vérifier.", "Équipe absente : repasser par l’éditeur d’équipes."],
    warnings: ["Ne recrée pas les mêmes joueurs sous plusieurs profils pour composer une équipe."],
    related: ["Baby-foot", "Équipes", "Stats"],
  },
  {
    id: "v90-petanque-team-match", domain: "app", title: "Préparer une partie de pétanque en équipes",
    aliases: ["petanque equipe config", "triplette doublette app", "match petanque equipe"], route: "petanque_config",
    purpose: "Associer correctement participants, équipes et format avant la première mène.",
    prerequisites: ["Profils disponibles."],
    steps: ["Choisis le type de partie proposé.", "Sélectionne les joueurs de chaque équipe.", "Vérifie qu’un profil n’est pas présent deux fois par erreur.", "Choisis les paramètres de match.", "Lance la partie.", "Vérifie équipe active et score initial.", "Après une mène de test, confirme l’attribution des points."],
    verify: ["Les points de mène s’ajoutent à la bonne équipe."],
    troubleshooting: ["Joueur manquant : revenir à la composition.", "Score attribué à l’autre équipe : vérifier équipe active avant validation."],
    warnings: ["Ne corrige pas un mauvais mapping en inversant artificiellement des points plus tard."],
    related: ["Pétanque", "Équipes", "Mène"],
  },
  {
    id: "v90-pingpong-match", domain: "app", title: "Configurer un match Ping-Pong avec le bon format",
    aliases: ["config ping pong", "match table tennis app", "sets pingpong"], route: "pingpong_config",
    purpose: "Aligner score cible, sets et participants avant jeu.",
    prerequisites: ["Profils sélectionnables."],
    steps: ["Choisis les joueurs ou équipes si disponible.", "Vérifie le nombre de sets/manches.", "Contrôle le score cible et la règle d’écart si paramétrable.", "Vérifie le serveur initial si l’écran le demande.", "Lance la partie.", "Teste quelques points et le changement de service.", "Contrôle la fin d’un set court de test si possible."],
    verify: ["Le service et le score évoluent selon le format choisi."],
    troubleshooting: ["Service incorrect : vérifier logique de rotation/deuce.", "Fin trop tôt : score cible/écart à contrôler."],
    warnings: ["Distingue les règles officielles de référence des variantes proposées par l’application."],
    related: ["Ping-Pong", "Service", "Sets"],
  },
  {
    id: "v90-molkky-score-check", domain: "app", title: "Vérifier une saisie Mölkky autour de 50 points",
    aliases: ["molkky proche 50", "score exact molkky", "retour 25 app"], route: "molkky_play",
    purpose: "Éviter une erreur de fin de partie ou de retour à 25.",
    prerequisites: ["Partie Mölkky en cours."],
    steps: ["Lis le score actuel.", "Calcule le nombre exact nécessaire pour atteindre 50.", "Après le lancer, distingue une quille unique de plusieurs quilles tombées.", "Saisis le score correspondant.", "Vérifie le total.", "Si le total dépasse 50, confirme l’application de la règle de retour prévue.", "Vérifie aussi le compteur d’échecs si aucun point n’est marqué."],
    verify: ["Le total et l’état du joueur correspondent à la règle du mode."],
    troubleshooting: ["Mauvais total : corriger l’événement source si Undo existe.", "Élimination étrange : vérifier compteur de zéros consécutifs."],
    warnings: ["Ne saisis pas le numéro d’une quille si plusieurs quilles sont réellement tombées."],
    related: ["Mölkky", "50 exact", "Trois zéros"],
  },
  {
    id: "v90-dice-probability", domain: "stats", title: "Vérifier une probabilité simple de dés avec Awéna",
    aliases: ["calcul proba des", "awena probabilite", "chance somme 7"], route: "games",
    purpose: "Utiliser les outils de calcul plutôt qu’une intuition erronée.",
    prerequisites: ["Question formulée avec nombre/type de dés et événement souhaité."],
    steps: ["Indique les dés utilisés, par exemple 2D6.", "Précise l’événement : somme, face, au moins un résultat, etc.", "Demande le calcul à Awéna.", "Lis le nombre de cas favorables et la probabilité si elle est disponible.", "Compare avec une énumération simple pour les petits cas.", "Utilise ensuite la valeur pour raisonner sur le risque."],
    verify: ["La probabilité est cohérente avec les issues possibles."],
    troubleshooting: ["Question ambiguë : préciser indépendance et nombre de dés.", "Somme : ne suppose pas toutes les sommes équiprobables."],
    warnings: ["Une probabilité théorique ne garantit pas un résultat sur une seule partie."],
    related: ["Dés", "Probabilités", "Awéna"],
  },
  {
    id: "v90-firefighter-start", domain: "app", title: "Préparer Darts Firefighter avant une mission",
    aliases: ["config firefighter", "lancer darts firefighter", "mission pompier"], route: "darts_firefighter_config",
    purpose: "Comprendre territoire, danger, joueurs et actions avant la première intervention.",
    prerequisites: ["Profils/participants disponibles."],
    steps: ["Ouvre Darts Firefighter.", "Choisis les paramètres de mission disponibles.", "Sélectionne territoire/carte si demandé.", "Vérifie les participants.", "Lis le niveau de danger et les actions conseillées.", "Confirme les règles de score/action.", "Lance la mission.", "Avant la première fléchette, vérifie joueur actif et territoire ciblé."],
    verify: ["Le joueur actif, la carte et les objectifs affichés correspondent à la configuration."],
    troubleshooting: ["Carte noire/absente : problème d’asset/rendu à distinguer de la règle.", "Action non disponible : vérifier état du territoire."],
    warnings: ["Ne force pas une action de mission non proposée par l’état courant."],
    related: ["Darts Firefighter", "Carte", "Actions"],
  },
  {
    id: "v90-firefighter-diagnose", domain: "app", title: "Comprendre pourquoi une action Firefighter n’est pas disponible",
    aliases: ["action firefighter absente", "bouton action pompier", "objectif firefighter"], route: "darts_firefighter_play",
    purpose: "Identifier si la cause vient du territoire, du tour, du niveau de danger ou de la sélection.",
    prerequisites: ["Mission en cours."],
    steps: ["Vérifie le joueur actif.", "Vérifie le territoire réellement sélectionné.", "Lis son état de danger/protection.", "Regarde les actions conseillées disponibles.", "Vérifie qu’une action n’a pas déjà été consommée pour ce tour si la règle le limite.", "Si Canadair, vérifie la condition spéciale prévue.", "Change uniquement la sélection de territoire pour retester."],
    verify: ["Une action cohérente apparaît pour un territoire et un tour valides."],
    troubleshooting: ["Aucune action partout : problème d’état global/rendu.", "Une seule carte concernée : inspecter ses données de danger."],
    warnings: ["Ne modifie pas manuellement les points pour contourner une action absente."],
    related: ["Firefighter", "Territoire", "Canadair"],
  },
  {
    id: "v90-darts-poker-start", domain: "app", title: "Comprendre une main de Darts Poker dans l’application",
    aliases: ["jouer darts poker", "main darts poker", "6 darts poker"], route: "darts_poker_play",
    purpose: "Relier chaque lancer, cible et carte obtenue au déroulement de la main.",
    prerequisites: ["Partie Darts Poker lancée."],
    steps: ["Repère le joueur actif.", "Observe la ligne correspondant au lancer courant.", "Vise la cible autorisée selon le mode.", "Après la fléchette, vérifie la carte/événement obtenu.", "Continue jusqu’au nombre de darts prévu pour la main.", "Lis le résultat de la main.", "Passe ensuite au joueur suivant selon l’alternance affichée."],
    verify: ["Chaque dart génère au plus une ligne/événement et l’alternance respecte le joueur actif."],
    troubleshooting: ["Carte dupliquée ou absente : vérifier mapping cible→carte.", "Joueur ne change pas : inspecter fin de main."],
    warnings: ["Ne corrige pas une carte en modifiant directement le résultat final."],
    related: ["Darts Poker", "Main", "Timeline"],
  },
  {
    id: "v90-cargo-start", domain: "app", title: "Comprendre les objectifs d’une partie CARGO",
    aliases: ["jouer cargo", "config cargo", "objectif cargo darts"], route: "cargo_config",
    purpose: "Lire les objectifs du mode avant de lancer la partie.",
    prerequisites: ["Mode CARGO disponible."],
    steps: ["Ouvre la configuration CARGO.", "Lis l’objectif général et les variantes affichées.", "Sélectionne les participants.", "Vérifie les réglages proposés.", "Lance la partie.", "Observe le ticker/objectif courant.", "Après une première action, vérifie la progression affichée."],
    verify: ["La progression correspond à l’objectif annoncé par le mode."],
    troubleshooting: ["Objectif peu clair : ouvre Awéna depuis l’écran pour une explication contextuelle.", "Progression absente : vérifier événement source."],
    warnings: ["Ne transpose pas automatiquement les règles X01 à un mode original."],
    related: ["CARGO", "Modes originaux", "Awéna"],
  },
  {
    id: "v90-ocean-start", domain: "app", title: "Comprendre les objectifs d’Ocean Control",
    aliases: ["jouer ocean control", "ocean control guide", "config ocean"], route: "ocean_control_config",
    purpose: "Préparer le mode et comprendre ce que l’écran de jeu attend.",
    prerequisites: ["Mode Ocean Control disponible."],
    steps: ["Ouvre la configuration.", "Lis le principe du mode via l’aide Awéna si nécessaire.", "Choisis participants et options.", "Lance la partie.", "Observe zones/objectifs actifs.", "Effectue une action de test.", "Vérifie la conséquence sur la progression.", "Demande à Awéna « et ensuite ? » pour rester dans le contexte."],
    verify: ["L’action test modifie la zone ou le score attendu."],
    troubleshooting: ["Aucun changement : vérifier objectif actif et validation de l’action.", "Écran chargé mais règle inconnue : utiliser le tutoriel contextuel."],
    warnings: ["Ne suppose pas la signification d’une icône sans consulter l’aide du mode."],
    related: ["Ocean Control", "Tutoriel contextuel", "Modes originaux"],
  },
  {
    id: "v90-bot-select", domain: "app", title: "Choisir un BOT IA adapté au niveau souhaité",
    aliases: ["choisir bot ia", "niveau bot darts", "quel bot"], route: "profiles_bots",
    purpose: "Associer difficulté et rôle du bot au type de partie.",
    prerequisites: ["Catalogue Bots IA disponible."],
    steps: ["Ouvre la sélection des Bots.", "Lis niveau/compétence affichés.", "Choisis un bot cohérent avec le niveau des joueurs humains.", "Ajoute-le à la configuration du mode compatible.", "Vérifie qu’il apparaît comme bot et non profil humain.", "Lance une partie test.", "Ajuste la difficulté pour la prochaine partie si nécessaire."],
    verify: ["Le bot participe selon le rôle/niveau attendu sans polluer les stats d’un profil humain."],
    troubleshooting: ["Bot absent dans un mode : vérifier support du mode.", "Niveau trop fort/faible : changer le bot, pas les données du joueur."],
    warnings: ["Ne transforme pas un profil local en bot pour contourner un sélecteur."],
    related: ["Bots IA", "Profils", "Difficulté"],
  },
  {
    id: "v90-message-context", domain: "app", title: "Retrouver le contexte d’un message Online avant de répondre",
    aliases: ["messages online", "conversation ami", "message app"], route: "messages",
    purpose: "Éviter de répondre au mauvais contact ou à une ancienne invitation.",
    prerequisites: ["Compte connecté."],
    steps: ["Ouvre Messages.", "Sélectionne la conversation concernée.", "Lis les derniers messages et l’horodatage.", "Vérifie si une invitation/session liée est encore active.", "Réponds depuis le bon fil.", "Si le message contient un lien/session expirée, demande un nouveau lien.", "Reviens à Online pour vérifier l’état si nécessaire."],
    verify: ["La réponse apparaît dans le bon fil et concerne une session valide."],
    troubleshooting: ["Conversation vide : vérifier compte/réseau.", "Invitation ancienne : ne pas forcer une session expirée."],
    warnings: ["Ne partage pas de tokens ou données techniques sensibles dans un message."],
    related: ["Messages", "Online", "Amis"],
  },
  {
    id: "v90-source-of-truth", domain: "data", title: "Identifier la source de vérité avant une correction",
    aliases: ["quelle source verite", "source donnees app", "corriger bonne base"], route: "stats",
    purpose: "Éviter de réparer un affichage secondaire alors que l’erreur vient du stockage ou de l’agrégation.",
    prerequisites: ["Problème de donnée reproductible."],
    steps: ["Liste les endroits où la valeur apparaît.", "Identifie l’événement ou enregistrement brut d’origine.", "Compare l’historique au cache et à l’UI.", "Détermine quelle couche est censée être autoritative.", "Corrige au plus près de cette source.", "Invalide/reconstruis les caches dépendants.", "Reteste tous les écrans qui lisent la même donnée."],
    verify: ["Les différents écrans convergent sans correction spécifique par page."],
    troubleshooting: ["Une page reste différente : elle utilise probablement une formule/source distincte.", "Historique lui-même faux : corriger capture d’événement."],
    warnings: ["Ne multiplie pas les correctifs d’affichage pour cacher une donnée source incohérente."],
    related: ["Historique", "Stats", "Cache"],
  },
  {
    id: "v90-regression-test", domain: "performance", title: "Créer un test de non-régression après un bug important",
    aliases: ["test regression bug", "ne plus reproduire bug", "automatiser correction"], route: "settings",
    purpose: "Empêcher qu’une correction déjà obtenue disparaisse dans un prochain patch.",
    prerequisites: ["Bug compris et scénario minimal connu."],
    steps: ["Écris le chemin exact qui reproduisait le bug.", "Prépare des données de test minimales.", "Automatise la condition qui échouait lorsque c’est possible.", "Vérifie que le test échoue sur l’ancienne logique.", "Applique la correction.", "Vérifie que le test passe.", "Ajoute-le à la suite de tests pertinente.", "Conserve le nom du bug dans le test ou sa description."],
    verify: ["Une régression future fait échouer automatiquement le test."],
    troubleshooting: ["Test trop fragile : réduire les dépendances visuelles non essentielles.", "Bug non automatisable : créer au moins une checklist manuelle courte."],
    warnings: ["Ne supprime pas un test uniquement parce qu’il révèle un nouveau conflit."],
    related: ["Tests", "Regression", "Maintenance"],
  },
  {
    id: "v90-safe-patch-apply", domain: "performance", title: "Appliquer un patch sur le bon ZIP de référence",
    aliases: ["appliquer patch base actuelle", "rebase patch", "zip reference"], route: "settings",
    purpose: "Éviter d’écraser des évolutions récentes avec des fichiers provenant d’une ancienne base.",
    prerequisites: ["ZIP de référence actuel identifié.", "Patch à rebaser ou appliquer."],
    steps: ["Extrais une copie fraîche de la référence.", "Compare les fichiers que le patch veut modifier.", "Pour chaque fichier divergent, fusionne les changements au lieu de remplacer aveuglément.", "Préserve package.json et dépendances actuelles.", "Applique uniquement les ajouts nécessaires.", "Lance tests/typecheck.", "Compare de nouveau avec la base pour lister les fichiers réellement modifiés.", "Crée le ZIP patch minimal."],
    verify: ["Les évolutions de la base restent présentes et seuls les changements voulus apparaissent dans le diff."],
    troubleshooting: ["Package.json a perdu des scripts : repartir de celui de la référence.", "Gros nombre de fichiers modifiés : suspecter un remplacement trop large."],
    warnings: ["Ne réutilise pas tel quel un patch construit sur une ancienne version si les mêmes fichiers ont évolué."],
    related: ["Patch", "Rebase", "package.json"],
  },
];

export function awenaProceduralV90Count() { return AWENA_V90_PROCEDURES.length; }
export function awenaProceduralV90StepCount() { return AWENA_V90_PROCEDURES.reduce((sum, entry) => sum + entry.steps.length, 0); }
export function awenaProceduralV90TroubleshootingCount() { return AWENA_V90_PROCEDURES.reduce((sum, entry) => sum + entry.troubleshooting.length, 0); }
