import type { AwenaReply, AwenaRuntimeContext } from "./awena.types";

type UserGuideEntry = {
  id: string;
  domain: string;
  title: string;
  aliases: string[];
  short: string;
  details: string;
  steps?: string[];
  checks?: string[];
  troubleshooting?: string[];
  route?: string;
};

const STOP = new Set(["a","au","aux","avec","ce","ces","cette","de","des","du","dans","et","est","en","je","la","le","les","ma","mes","mon","ne","nous","on","ou","pour","que","quel","quelle","quels","quelles","qui","quoi","se","son","sur","ta","te","tes","ton","tu","un","une","vos","votre","comment","pourquoi","faire","sert","signifie","veut","dire","fonctionne","explique","expliquer","moi","application","appli","awena"]);
function norm(v:string){return String(v||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[’']/g," ").replace(/[_/\\.-]+/g," ").replace(/[^a-z0-9+%\s]/g," ").replace(/\s+/g," ").trim();}
function toks(v:string){return norm(v).split(" ").filter(t=>t.length>1&&!STOP.has(t));}

const E: UserGuideEntry[] = [
  {id:"nav-games",domain:"navigation",title:"Jeux",aliases:["onglet jeux","menu jeux","choisir un sport","changer de sport"],short:"L'onglet Jeux sert à choisir le sport puis le mode que tu veux lancer.",details:"Depuis Jeux, choisis d'abord le sport disponible, puis la carte du mode. La plupart des modes passent ensuite par un écran de configuration avant la partie.",steps:["Ouvre Jeux dans la barre du bas.","Choisis le sport.","Appuie sur le mode souhaité.","Règle les options proposées puis lance la partie."],checks:["Le titre de l'écran doit correspondre au sport ou au mode choisi."]},
  {id:"nav-profiles",domain:"navigation",title:"Profils",aliases:["onglet profils","menu profils","mes profils"],short:"Profils regroupe les joueurs locaux, leurs avatars, préférences, statistiques et équipements associés.",details:"Un profil sert à réutiliser le même joueur d'une partie à l'autre. Le profil actif correspond à ton profil principal dans l'application ; les joueurs sélectionnés pour une partie peuvent être différents.",steps:["Ouvre Profils.","Choisis un profil existant ou crée-en un.","Modifie avatar, nom ou préférences si nécessaire.","Utilise ensuite ce profil dans les sélecteurs de joueurs des modes compatibles."]},
  {id:"nav-online",domain:"navigation",title:"Online",aliases:["onglet online","menu online","jouer en ligne"],short:"Online regroupe les fonctions connectées : salons, amis, clubs et parties compatibles en ligne.",details:"Les fonctions Online nécessitent généralement une connexion et un compte ou une session valide. Les parties locales restent distinctes des parties Online.",steps:["Ouvre Online.","Choisis la fonction souhaitée : salon, amis, club ou partie.","Vérifie ton état de connexion.","Rejoins ou crée la session voulue."],troubleshooting:["Si rien ne charge, vérifie d'abord la connexion Internet et l'état du compte dans Réglages > Compte."]},
  {id:"nav-stats",domain:"navigation",title:"Stats",aliases:["onglet stats","statistiques","mes statistiques"],short:"Stats transforme l'historique enregistré en tableaux, records, comparaisons et graphiques.",details:"Les statistiques dépendent des parties réellement enregistrées et des filtres actifs. Un écran vide ne signifie pas forcément que les données ont disparu : un filtre de joueur, de sport, de mode ou de période peut les masquer.",steps:["Ouvre Stats.","Choisis le sport ou le centre statistique voulu.","Vérifie le joueur, le mode et la période sélectionnés.","Ouvre les sous-onglets pour les KPI, graphiques, records ou comparaisons."],troubleshooting:["Si une stat manque, commence par vérifier Historique puis les filtres avant toute restauration de données."]},
  {id:"nav-settings",domain:"navigation",title:"Réglages",aliases:["settings","reglages","parametres application"],short:"Réglages centralise les préférences générales de MULTISPORTS SCORING.",details:"Tu y retrouves notamment le sport préféré, le compte, la langue, les sauvegardes, le thème, Awéna, l'intro, les écrans Cast/Viewer, la publicité et la confidentialité.",steps:["Ouvre Réglages.","Choisis la carte concernée.","Modifie l'option.","Reviens à l'écran précédent et vérifie que le réglage est conservé."]},

  {id:"profile-active",domain:"profiles",title:"Profil actif",aliases:["profil actif","mon profil actif","changer profil actif"],short:"Le profil actif est le profil principal associé à tes préférences dans l'application.",details:"Il peut définir des préférences comme la langue, le thème ou certains choix par défaut. Il ne faut pas le confondre avec le joueur actuellement sélectionné dans une partie.",steps:["Ouvre Profils ou Mon Profil.","Sélectionne le profil voulu.","Active-le si l'option est proposée.","Vérifie ensuite que son nom/avatar apparaît comme profil principal." ]},
  {id:"profile-vs-player",domain:"profiles",title:"Profil actif ou joueur de la partie",aliases:["profil actif ou joueur","difference profil joueur","joueur actif profil actif"],short:"Le profil actif représente ton identité principale ; le joueur de la partie est celui qui participe réellement à la partie en cours.",details:"Tu peux garder ton profil actif tout en lançant une partie avec plusieurs autres profils, un invité ou des bots. Pendant le jeu, le joueur actif est simplement celui dont c'est le tour."},
  {id:"local-profile",domain:"profiles",title:"Créer un profil local",aliases:["creer profil","nouveau profil","ajouter joueur local"],short:"Un profil local permet de conserver le nom, l'avatar et les statistiques d'un joueur régulier.",details:"Créer un profil est utile pour éviter de recréer le même joueur à chaque partie et pour consolider correctement son historique.",steps:["Ouvre Profils.","Choisis Ajouter/Créer un profil.","Renseigne le nom et les informations proposées.","Choisis éventuellement un avatar et un set de fléchettes.","Enregistre."],checks:["Le nouveau profil doit apparaître dans la liste et dans les sélecteurs de joueurs compatibles."]},
  {id:"avatar",domain:"profiles",title:"Avatar",aliases:["changer avatar","photo profil","avatar joueur"],short:"L'avatar sert à identifier visuellement un profil dans les sélecteurs, carrousels et statistiques.",details:"Selon l'écran, tu peux utiliser un avatar fourni, une image personnelle ou un avatar créé par les outils de l'application.",steps:["Ouvre le profil concerné.","Appuie sur l'avatar ou l'option de modification.","Choisis la nouvelle image.","Enregistre puis vérifie son affichage dans Profils et dans un sélecteur de partie." ]},
  {id:"dartset",domain:"profiles",title:"Set de fléchettes",aliases:["dartset","set of darts","mes flechettes","choisir flechettes profil"],short:"Le set de fléchettes associé à un profil est un élément visuel et d'identification du joueur.",details:"Il peut être sélectionné depuis le profil et réutilisé dans les écrans X01 ou autres modes qui affichent les dartsets.",steps:["Ouvre le profil.","Va dans la partie Set de fléchettes.","Choisis le set souhaité.","Enregistre.","Vérifie qu'il apparaît dans le sélecteur du mode concerné." ]},
  {id:"bots",domain:"profiles",title:"Bots IA et Bots CPU",aliases:["bots ia","bot cpu","jouer contre ia","adversaire ia"],short:"Les bots permettent d'ajouter des adversaires contrôlés par l'application quand un mode les accepte.",details:"Les bots IA prédéfinis ont une identité et un niveau ; les bots CPU personnalisés peuvent dépendre des outils de création disponibles. Leur disponibilité varie selon le mode.",steps:["Dans la configuration du mode, ouvre le sélecteur de joueurs.","Choisis l'onglet ou la section Bots.","Sélectionne le bot voulu.","Vérifie son niveau puis valide le participant." ]},
  {id:"teams",domain:"profiles",title:"Équipes",aliases:["creer equipe","equipe joueurs","jouer en equipe"],short:"Les équipes regroupent plusieurs profils pour les modes qui acceptent le jeu collectif.",details:"Une équipe enregistrée peut être réutilisée dans les configurations compatibles. Certains modes permettent aussi une composition temporaire pour une seule partie.",steps:["Ouvre la gestion des équipes ou la configuration du mode.","Choisis une équipe existante ou crée-en une.","Ajoute les joueurs.","Valide la composition puis utilise l'équipe dans la partie." ]},

  {id:"x01-start",domain:"x01",title:"Lancer une partie X01",aliases:["lancer x01","jouer x01","partie 501","partie 301"],short:"X01 consiste à partir d'un score donné et à descendre exactement jusqu'à zéro selon les règles IN/OUT choisies.",details:"La configuration te permet de choisir participants, score de départ, règle d'entrée, règle de sortie, format de match, ordre et méthode de saisie.",steps:["Ouvre Jeux > Fléchettes > X01.","Choisis Configuration guidée ou complète.","Sélectionne les joueurs/équipes.","Choisis 301, 501, 701 ou 901.","Règle IN et OUT.","Choisis legs/sets et l'ordre de départ.","Choisis la méthode de saisie puis lance la partie." ]},
  {id:"x01-guided",domain:"x01",title:"Configuration guidée X01",aliases:["configuration guidee x01","mode guide x01","guidee complete"],short:"La configuration guidée va à l'essentiel pour lancer rapidement un X01.",details:"Elle regroupe les choix indispensables et évite les réglages avancés. La configuration complète reste disponible si tu veux personnaliser davantage la partie.",steps:["Sur l'écran Configuration X01, choisis GUIDÉE.","Règle les participants.","Choisis le score et les règles principales.","Valide le format puis lance." ]},
  {id:"x01-complete",domain:"x01",title:"Configuration complète X01",aliases:["configuration complete x01","reglages avances x01"],short:"La configuration complète donne accès à tous les réglages X01 disponibles.",details:"Utilise-la si tu veux régler finement le format, la méthode de saisie, l'audio ou les sources de comptage externes.",steps:["Sur Configuration X01, choisis COMPLÈTE.","Parcours chaque bloc de réglages.","Vérifie les participants, score, IN/OUT, format et saisie.","Contrôle le récapitulatif avant de lancer." ]},
  {id:"x01-start-score",domain:"x01",title:"Score de départ X01",aliases:["301 501 701 901","score depart x01","quel x01 choisir"],short:"Le score de départ définit la longueur de la partie : 301 est plus court, 501 est le format classique le plus courant, 701/901 allongent la partie.",details:"Le choix n'altère pas le principe : chaque volée est soustraite jusqu'à atteindre exactement zéro en respectant la règle OUT."},
  {id:"x01-in",domain:"x01",title:"Simple / Double / Master IN",aliases:["simple in","double in","master in","regle entree x01"],short:"La règle IN détermine comment un joueur commence réellement à faire diminuer son score.",details:"Simple IN autorise immédiatement les zones valides ordinaires. Double IN demande d'abord un double. Master IN peut accepter les zones prévues par cette variante. L'écran de configuration indique la règle active."},
  {id:"x01-out",domain:"x01",title:"Simple / Double / Master OUT",aliases:["simple out","double out","master out","regle sortie x01"],short:"La règle OUT détermine comment il faut atteindre zéro pour gagner le leg.",details:"En Double OUT, la dernière fléchette doit terminer sur un double valide. Une tentative qui dépasse zéro ou rend la sortie invalide provoque un bust selon la règle du mode."},
  {id:"x01-legs-sets",domain:"x01",title:"Legs et Sets",aliases:["leg set x01","sets legs","difference leg set"],short:"Un leg est une manche X01 complète ; un set regroupe plusieurs legs.",details:"Selon le nombre de joueurs et le format choisi, tu peux jouer directement en legs ou organiser le match en sets contenant eux-mêmes plusieurs legs."},
  {id:"x01-bestof",domain:"x01",title:"Best Of / First To",aliases:["best of","first to","bo3 bo5 bo7"],short:"Best Of fixe un nombre maximal de manches ; First To fixe directement le nombre de victoires nécessaires.",details:"Exemple : un Best Of 5 se gagne dès qu'un joueur atteint 3 manches. Un First To 3 signifie également qu'il faut 3 victoires, sans avoir besoin de réfléchir au nombre maximal."},
  {id:"x01-input",domain:"x01",title:"Méthode de saisie X01",aliases:["keypad x01","cible x01","presets x01","voice x01","saisie score x01"],short:"X01 peut proposer plusieurs méthodes de saisie selon ta configuration : clavier, cible, presets, voix ou source externe.",details:"Choisis surtout la méthode la plus fiable pour ton installation. Tu peux utiliser la saisie manuelle comme solution de secours si une source automatique devient indisponible."},
  {id:"x01-undo",domain:"x01",title:"Corriger une mauvaise saisie X01",aliases:["undo x01","annuler flechette","erreur saisie x01","corriger score x01"],short:"Utilise Undo pour revenir sur une saisie erronée au lieu de modifier les données ailleurs.",details:"L'annulation doit restaurer le score, la volée et l'état du tour de façon cohérente. Vérifie toujours l'écran après l'Undo avant de continuer.",steps:["Appuie sur Undo/Annuler.","Vérifie le score restauré.","Vérifie le joueur actif et le nombre de fléchettes du tour.","Saisis ensuite la bonne valeur." ]},
  {id:"x01-bust",domain:"x01",title:"Bust",aliases:["bust x01","score depasse zero","sortie invalide"],short:"Un bust annule la tentative de fin de volée lorsqu'une sortie devient invalide selon les règles X01 actives.",details:"En Double OUT, par exemple, arriver à zéro sans finir par un double valide ne gagne pas le leg. L'application restaure alors le score prévu par la règle de bust."},
  {id:"x01-checkout",domain:"x01",title:"Checkout",aliases:["checkout","sortie x01","fermer x01","quoi viser pour finir"],short:"Un checkout est une combinaison permettant de terminer exactement le score restant avec les fléchettes disponibles.",details:"Awéna peut proposer une route de sortie en fonction du score restant, du nombre de fléchettes et de la règle OUT active."},

  {id:"cast",domain:"screens",title:"Cast TV",aliases:["cast tv","chromecast","caster partie","afficher sur tele"],short:"Cast TV envoie le scoreboard de la partie vers une TV ou un écran Google Cast compatible.",details:"Le téléphone reste l'appareil de contrôle ; la TV sert d'affichage déporté. Les deux appareils doivent pouvoir communiquer correctement.",steps:["Ouvre Réglages/Écrans > CAST TV.","Appuie sur Lancer.","Choisis la TV ou le Chromecast.","Attends la confirmation de connexion.","Reviens au jeu et lance la partie."],troubleshooting:["Si aucun écran n'apparaît, vérifie que téléphone et TV sont sur un réseau compatible et que la TV est disponible pour Cast.","Si le score se fige, ouvre les diagnostics Cast puis relance la session si nécessaire." ]},
  {id:"viewer",domain:"screens",title:"Viewer tablette",aliases:["viewer tablette","second ecran","qr viewer","score tablette"],short:"Viewer affiche le scoreboard sur une tablette ou un second navigateur à partir d'une session créée par l'appareil principal.",details:"C'est pratique quand tu n'utilises pas Chromecast. Le téléphone hôte crée la session ; le second appareil rejoint avec un QR code, un lien ou un code.",steps:["Ouvre Écrans > VIEWER TABLETTE.","Crée une session.","Sur la tablette, scanne le QR code ou saisis le code.","Attends l'état connecté.","Laisse la session active pendant la partie."],troubleshooting:["Si le score ne bouge plus, vérifie que la session est toujours active et que la publication automatique est activée." ]},
  {id:"cast-vs-viewer",domain:"screens",title:"Cast ou Viewer",aliases:["cast ou viewer","difference cast viewer","choisir cast viewer"],short:"Choisis Cast pour une TV compatible Google Cast ; choisis Viewer pour une tablette ou un navigateur secondaire.",details:"Cast est le plus direct pour une TV. Viewer est plus universel et pratique sur une tablette, un PC ou un second navigateur. Les deux servent à afficher la partie, pas à remplacer une sauvegarde."},

  {id:"camera-local",domain:"camera",title:"Caméra locale X01",aliases:["camera locale x01","utiliser camera telephone","detection flechettes camera"],short:"La caméra locale utilise la caméra de l'appareil qui fait tourner MULTISPORTS SCORING pour aider au scoring compatible.",details:"Elle nécessite l'autorisation caméra, un cadrage stable et une calibration correcte. Une saisie manuelle reste recommandée comme solution de secours."},
  {id:"camera-companion",domain:"camera",title:"Téléphone compagnon",aliases:["telephone compagnon","second telephone camera","camera distante x01","qr camera"],short:"Le téléphone compagnon permet d'utiliser un second téléphone comme caméra pendant que l'appareil principal gère la partie.",details:"L'appareil principal crée la liaison ; le téléphone caméra rejoint généralement via QR/lien. Le téléphone caméra doit rester bien positionné et connecté.",steps:["Choisis Téléphone compagnon dans la source de scoring.","Affiche le QR ou lien de liaison.","Ouvre-le sur le second téléphone.","Autorise sa caméra.","Cadre la cible puis effectue la calibration demandée.","Teste un tir avant la partie." ]},
  {id:"camera-calibration",domain:"camera",title:"Calibration caméra",aliases:["calibrer camera","calibration cible","bull bord 20"],short:"La calibration apprend à l'application où se trouvent les repères importants de la cible dans l'image.",details:"Elle doit être refaite si la caméra, le zoom, l'orientation ou la cible bouge. Une bonne calibration dépend d'une vue nette et stable.",steps:["Fixe la caméra et cadre toute la cible.","Indique le centre du BULL.","Indique le bord extérieur demandé.","Indique le segment 20 ou les repères demandés.","Enregistre.","Teste plusieurs zones de la cible."],troubleshooting:["Si le centre est juste mais les bords sont décalés, recommence la calibration sans déplacer la caméra pendant la procédure." ]},
  {id:"camera-black",domain:"camera",title:"Caméra noire ou refusée",aliases:["camera noire","camera refusee","permission camera","pas image camera"],short:"Si la caméra reste noire, commence par vérifier l'autorisation caméra et qu'aucune autre application ne monopolise l'objectif.",details:"Il est inutile de toucher aux données de jeu. Corrige d'abord l'autorisation et relance seulement le parcours caméra.",steps:["Ouvre les autorisations de MULTISPORTS SCORING si nécessaire.","Autorise la caméra.","Ferme toute autre application utilisant la caméra.","Reviens dans la configuration caméra.","Relance l'aperçu puis la calibration." ]},

  {id:"voice-awena",domain:"awena",title:"Commandes vocales Awéna",aliases:["commande vocale awena","awena voix","dire awena","micro awena"],short:"Les commandes vocales permettent d'appeler Awéna par son prénom puis de lui poser une question ou de lancer une action compatible.",details:"Pour le pilote X01, Awéna peut ouvrir la configuration vocale et demander les réglages nécessaires. Le micro se met en pause lorsqu'Awéna parle afin d'éviter qu'elle s'écoute elle-même.",steps:["Active Commandes vocales Awéna dans Réglages > Awéna.","Autorise le micro.","Dis « Awéna » puis ta demande.","Réponds aux questions de configuration lorsqu'un dialogue guidé est lancé." ]},
  {id:"voice-x01",domain:"awena",title:"Configurer X01 à la voix",aliases:["awena lance x01","configuration vocale x01","x01 par la voix"],short:"Tu peux dire « Awéna, lance-moi une partie de X01 » pour démarrer le parcours vocal X01.",details:"Awéna te demande successivement les participants et principaux réglages, met à jour la configuration affichée puis demande une confirmation avant de lancer.",steps:["Dis « Awéna, lance-moi une partie de X01 ».","Réponds aux questions sur joueurs/équipes et score de départ.","Choisis IN/OUT et format.","Choisis la méthode de saisie et les options proposées.","Écoute le récapitulatif.","Dis oui pour lancer ou annule/recommence si nécessaire." ]},

  {id:"history",domain:"stats",title:"Historique",aliases:["historique parties","voir anciennes parties","retrouver partie"],short:"Historique contient les parties enregistrées et sert de base à une grande partie des statistiques.",details:"Avant de conclure qu'une statistique est perdue, vérifie si la partie concernée existe bien dans Historique et si elle est associée au bon joueur/mode.",steps:["Ouvre Stats ou Historique selon l'accès proposé.","Choisis le sport ou le mode.","Repère la partie par date/joueurs.","Ouvre-la pour vérifier son résumé." ]},
  {id:"stats-empty",domain:"stats",title:"Statistiques vides",aliases:["stats vides","aucune statistique","stats n affichent rien"],short:"Des statistiques vides viennent souvent d'un filtre, d'un mode sans parties enregistrées ou d'une partie absente de l'Historique.",details:"Ne restaure pas ou ne supprime pas des données avant d'avoir vérifié les filtres et l'Historique.",steps:["Vérifie le joueur sélectionné.","Vérifie le sport et le mode.","Élargis la période.","Contrôle que les parties existent dans Historique.","Reviens dans Stats et recharge la vue." ]},
  {id:"stats-difference",domain:"stats",title:"Statistiques différentes entre deux écrans",aliases:["stats incoherentes","moyenne differente","deux stats differentes"],short:"Deux écrans peuvent afficher des indicateurs différents s'ils n'utilisent pas le même périmètre, la même période ou la même définition statistique.",details:"Compare d'abord le joueur, le mode, la période et le nom exact du KPI. Une moyenne de partie, une AVG3 et une moyenne de période ne représentent pas forcément la même chose.",steps:["Note les deux écrans comparés.","Vérifie le joueur et le mode.","Vérifie la période.","Compare le nom exact de l'indicateur.","Contrôle la partie source dans Historique si l'écart concerne un match précis." ]},
  {id:"records",domain:"stats",title:"Records",aliases:["records","meilleur score","record joueur"],short:"Les records mettent en avant les meilleures performances enregistrées pour un joueur, un mode ou une période.",details:"Un record n'est fiable que si les parties correspondantes ont bien été enregistrées avec les bonnes données de scoring."},
  {id:"h2h",domain:"stats",title:"Face-à-face",aliases:["h2h","head to head","face a face joueurs"],short:"Le face-à-face compare les résultats de deux joueurs lorsqu'ils se sont affrontés dans les données disponibles.",details:"Vérifie toujours le sport, le mode et la période avant d'interpréter l'avantage d'un joueur."},

  {id:"backup",domain:"data",title:"Sauvegarde",aliases:["sauvegarder donnees","faire sauvegarde","backup"],short:"Une sauvegarde crée une copie destinée à récupérer tes données en cas de problème ou de changement d'appareil.",details:"C'est différent d'une synchronisation : la sauvegarde protège un état ; la synchronisation essaie de maintenir plusieurs emplacements cohérents.",steps:["Ouvre Réglages > Sauvegarde ou Sync & Partage.","Choisis le type de sauvegarde proposé.","Lance l'export.","Choisis un emplacement que tu retrouveras.","Attends la confirmation de réussite."],checks:["Vérifie que le fichier existe réellement avant de compter dessus." ]},
  {id:"recovery",domain:"data",title:"Sauvegarde Recovery",aliases:["recovery","backup recovery","sauvegarde complete"],short:"Recovery est la sauvegarde à privilégier avant une opération risquée ou un changement important.",details:"Elle est destinée à permettre une restauration plus complète que de simples exports d'affichage ou de partage.",steps:["Ouvre Sauvegarde/Sync & Partage.","Choisis l'export Recovery complet.","Enregistre le fichier dans un emplacement sûr.","Vérifie qu'il est bien créé.","Garde idéalement une copie hors du téléphone." ]},
  {id:"restore",domain:"data",title:"Restaurer une sauvegarde",aliases:["restaurer backup","restauration","recuperer sauvegarde"],short:"La restauration réinjecte les données d'une sauvegarde dans l'application.",details:"Avant de restaurer, protège l'état actuel si tu veux pouvoir revenir en arrière. Vérifie aussi la date et le contenu de l'archive.",steps:["Crée si possible une sauvegarde de l'état actuel.","Ouvre Sauvegarde > Restaurer.","Choisis le fichier ou slot.","Inspecte son contenu si l'aperçu est disponible.","Lance la restauration.","Contrôle ensuite Profils, Historique et Stats." ]},
  {id:"backup-vs-sync",domain:"data",title:"Sauvegarde ou synchronisation",aliases:["sauvegarde ou synchro","backup vs sync","difference sauvegarde synchronisation"],short:"La sauvegarde sert à récupérer un état ; la synchronisation sert à maintenir des données cohérentes entre plusieurs emplacements ou appareils.",details:"Pour une opération risquée, fais d'abord une sauvegarde. La synchronisation seule ne remplace pas forcément un fichier Recovery indépendant."},
  {id:"export-import",domain:"data",title:"Export / Import",aliases:["export json","import json","exporter importer donnees"],short:"Export crée un fichier à partir de données ; Import lit un fichier pour réintégrer ou fusionner les informations prises en charge.",details:"Avant un import important, garde une sauvegarde Recovery. Après import, vérifie le rapport et contrôle les doublons éventuels."},
  {id:"new-phone",domain:"data",title:"Changer de téléphone",aliases:["nouveau telephone","transferer donnees","changer appareil"],short:"Pour changer de téléphone sans perdre tes données, prépare une sauvegarde sur l'ancien appareil puis restaure-la sur le nouveau.",details:"Garde l'ancien téléphone intact tant que tu n'as pas vérifié les profils, historiques, stats et préférences sur le nouveau.",steps:["Sur l'ancien téléphone, crée une sauvegarde Recovery récente.","Copie-la dans un emplacement accessible au nouveau téléphone.","Installe MULTISPORTS SCORING sur le nouvel appareil.","Restaure la sauvegarde.","Vérifie Profils, Historique, Stats et réglages.","Ne supprime l'ancienne copie qu'une fois le transfert validé." ]},

  {id:"language",domain:"settings",title:"Langue",aliases:["changer langue","francais anglais espagnol","langue application"],short:"La langue choisie dans Réglages doit piloter l'interface et les préférences liées au profil actif.",details:"Si l'application revient dans une autre langue, vérifie aussi la préférence du profil actif afin qu'elle soit cohérente.",steps:["Ouvre Réglages > Langue.","Choisis la langue.","Vérifie plusieurs écrans.","Ouvre Mon Profil et confirme que la préférence correspond si elle y est affichée." ]},
  {id:"theme",domain:"settings",title:"Thème",aliases:["changer theme","theme application","pack theme"],short:"Le thème modifie l'apparence de l'application et peut être lié aux préférences du profil actif.",details:"Certains packs premium peuvent modifier davantage que les couleurs : fonds, cartes et ambiance visuelle.",steps:["Ouvre Réglages > Thème.","Parcours les aperçus.","Choisis le thème disponible.","Vérifie son rendu sur plusieurs écrans." ]},
  {id:"intro",domain:"settings",title:"Intro ON/OFF",aliases:["couper intro","desactiver musique intro","video intro"],short:"Le réglage Intro permet de désactiver la séquence vidéo et musicale de démarrage.",details:"Quand Intro est désactivée, l'application doit arriver directement sur la sélection des jeux au démarrage."},
  {id:"privacy",domain:"settings",title:"Confidentialité",aliases:["confidentialite","donnees personnelles","privacy"],short:"La section Confidentialité présente les réglages et informations liés aux données et autorisations de l'application.",details:"Pour une permission comme caméra ou micro, Awéna peut t'expliquer à quoi elle sert dans la fonction concernée avant que tu l'autorises."},
  {id:"ads",domain:"settings",title:"Publicité",aliases:["pub","publicite","admob","banniere pub"],short:"La section Publicité regroupe les préférences et comportements publicitaires disponibles dans l'application.",details:"Le consentement peut influer sur la personnalisation des annonces. L'absence temporaire d'une publicité ne signifie pas forcément un problème de ton compte ou de tes données."},
  {id:"premium",domain:"settings",title:"Premium",aliases:["premium","achat premium","fonction verrouillee","restaurer achat"],short:"Premium déverrouille les fonctions prévues par l'offre lorsque l'achat est reconnu par l'application.",details:"Si un achat déjà effectué apparaît verrouillé, commence par utiliser l'option de restauration des achats avec le même compte de boutique avant toute autre manipulation."},

  {id:"permissions",domain:"android_user",title:"Permissions Android",aliases:["permission micro","permission camera","autorisation android","permission refusee"],short:"Certaines fonctions ont besoin d'une autorisation Android, par exemple la caméra ou le micro.",details:"Si tu refuses une permission, seule la fonction qui en dépend doit être affectée. Tu peux généralement la réactiver dans les réglages Android de l'application.",steps:["Ouvre les informations de l'application dans Android.","Va dans Autorisations.","Active uniquement la permission nécessaire.","Reviens dans MULTISPORTS SCORING et relance la fonction." ]},
  {id:"update-app",domain:"android_user",title:"Mettre l'application à jour",aliases:["mettre a jour application","nouvelle version android","update play store"],short:"Une mise à jour doit être installée depuis la même source de distribution utilisée pour ton accès, par exemple la piste de test Google Play.",details:"Après installation, vérifie la version affichée dans l'application si tu suspectes qu'un ancien build est encore présent.",steps:["Ouvre Google Play avec le compte testeur concerné.","Ouvre la fiche MULTISPORTS SCORING.","Appuie sur Mettre à jour si proposé.","Relance l'application.","Vérifie le numéro/version visible dans les informations de l'application." ]},
  {id:"old-version",domain:"android_user",title:"Ancienne version installée",aliases:["ancienne version","pas derniere version","play installe ancienne version"],short:"Si Google Play installe une ancienne version, vérifie d'abord que le compte utilisé appartient bien à la bonne piste de test et qu'une mise à jour est proposée.",details:"L'utilisateur n'a pas besoin de connaître la fabrication interne de l'application : l'objectif est simplement de confirmer la version réellement distribuée à son compte.",steps:["Vérifie le compte Google utilisé sur le téléphone.","Vérifie qu'il a bien rejoint le test prévu.","Ouvre la fiche Play Store et cherche Mettre à jour.","Compare la version installée avec celle annoncée aux testeurs.","Si elle ne correspond toujours pas, signale la version affichée à l'assistance." ]},

  {id:"competition-create",domain:"competition",title:"Créer une compétition",aliases:["creer tournoi","competition","nouveau tournoi"],short:"Le module Compétitions permet d'organiser un format de tournoi avec participants, équipes et matchs selon les options proposées.",details:"Le parcours dépend du sport et du format choisi. Awéna peut guider écran par écran et expliquer les termes comme round-robin, élimination ou tête de série.",steps:["Ouvre Compétitions.","Choisis Créer/Nouvelle compétition.","Sélectionne sport et format.","Ajoute joueurs ou équipes.","Règle les options du tournoi.","Vérifie le récapitulatif puis crée la compétition." ]},
  {id:"round-robin",domain:"competition",title:"Round-robin",aliases:["round robin","tous contre tous","poule tournoi"],short:"En round-robin, chaque participant affronte les autres du groupe selon le calendrier généré.",details:"Ce format favorise un classement basé sur plusieurs matchs plutôt qu'une élimination immédiate."},
  {id:"knockout",domain:"competition",title:"Élimination directe",aliases:["elimination directe","knockout","tableau tournoi"],short:"En élimination directe, une défaite peut éliminer immédiatement un participant du tableau.",details:"Le format est rapide et lisible mais laisse moins de matchs garantis qu'un round-robin."},

  {id:"online-room",domain:"online",title:"Salon Online",aliases:["salon online","creer salon","rejoindre salon"],short:"Un salon Online sert à réunir des joueurs dans une session connectée compatible.",details:"L'hôte crée généralement la session et partage l'identifiant ou l'invitation ; les autres joueurs rejoignent ensuite avec leur compte/session."},
  {id:"friends",domain:"online",title:"Amis",aliases:["amis","ajouter ami","liste amis"],short:"La section Amis sert à retrouver plus facilement des contacts et certaines interactions Online.",details:"Selon les fonctions disponibles, tu peux rechercher, ajouter ou utiliser un ami pour une invitation ou une comparaison."},
  {id:"clubs",domain:"online",title:"Clubs",aliases:["club","creer club","rejoindre club"],short:"Les Clubs regroupent des joueurs autour d'une structure commune et de fonctions sociales/compétitives compatibles.",details:"Awéna peut guider la création, l'adhésion et les écrans liés lorsqu'ils sont disponibles dans ta version."},

  {id:"loading-slow",domain:"troubleshooting",title:"Écran lent",aliases:["application lente","navigation lente","chargement lent","freeze"],short:"Quand un écran est lent, commence par identifier si le problème touche un seul écran ou toute l'application.",details:"Awéna doit privilégier les vérifications visibles : nombre d'éléments affichés, images qui chargent, opération en cours, changement d'écran et redémarrage simple. Elle ne doit pas demander de manipuler des fichiers internes.",steps:["Attends qu'une éventuelle sauvegarde/synchronisation se termine.","Reviens à l'écran précédent puis rouvre l'écran.","Vérifie si le problème touche aussi un autre écran.","Ferme puis relance l'application si nécessaire.","Si le problème persiste, note l'écran exact et l'action qui déclenche la lenteur." ]},
  {id:"profiles-disappear",domain:"troubleshooting",title:"Profils ou images qui disparaissent",aliases:["profil disparait","avatar disparait","dartset disparait","image apparait puis disparait"],short:"Si un profil ou une image apparaît puis disparaît, ne recrée pas immédiatement les données : vérifie d'abord si le profil existe toujours dans Profils et si le problème est seulement visuel.",details:"Le bon diagnostic consiste à comparer l'écran où l'information existe avec celui où elle manque, puis à revenir/recharger l'écran concerné.",steps:["Ouvre Profils et confirme que le profil existe.","Ouvre sa fiche et vérifie avatar/dartset.","Reviens dans l'écran où l'élément manque.","Rouvre le sélecteur.","Si le problème persiste, note précisément les deux écrans concernés." ]},
  {id:"wrong-language",domain:"troubleshooting",title:"La langue revient toute seule",aliases:["langue revient francais","langue se reinitialise","anglais revient francais"],short:"Si la langue revient toute seule, vérifie que le réglage général et la préférence du profil actif utilisent la même langue.",details:"Après modification, navigue sur plusieurs onglets pour confirmer que la préférence reste stable."},
  {id:"viewer-freeze",domain:"troubleshooting",title:"Viewer figé",aliases:["viewer fige","viewer plus a jour","tablette score bloque"],short:"Si Viewer reste affiché mais ne se met plus à jour, vérifie la session et la publication automatique avant de recréer la session.",details:"Le deuxième écran peut être encore ouvert alors que la session hôte a changé ou expiré.",steps:["Sur l'hôte, vérifie que Viewer indique une session active.","Vérifie Publication automatique.","Provoque un changement de score.","Si rien ne change, recrée la session et reconnecte la tablette avec le nouveau QR/code." ]},
  {id:"cast-freeze",domain:"troubleshooting",title:"Cast figé",aliases:["cast fige","tele score bloque","chromecast score pas a jour"],short:"Si la TV reste connectée mais le score ne bouge plus, vérifie la session Cast et relance-la si le diagnostic ne reçoit plus les mises à jour.",details:"Tu peux continuer la partie sur l'appareil principal ; Cast n'est qu'un affichage déporté."},
  {id:"sync-conflict",domain:"troubleshooting",title:"Conflit de synchronisation",aliases:["conflit synchro","deux versions donnees","sync conflit"],short:"En cas de conflit de synchronisation, protège d'abord la version qui contient les données les plus récentes avant de fusionner ou remplacer quoi que ce soit.",details:"Awéna doit demander à l'utilisateur d'identifier l'appareil ou la copie la plus récente et de créer une sauvegarde avant toute résolution.",steps:["Ne supprime rien.","Identifie l'appareil/copie avec les données les plus récentes.","Crée une sauvegarde Recovery de cette copie.","Lance ensuite seulement l'outil de synchronisation prévu.","Contrôle Profils et Historique après l'opération." ]},
  {id:"import-duplicates",domain:"troubleshooting",title:"Doublons après import",aliases:["doublons import","parties en double","profils en double"],short:"Si un import crée des doublons, ne recommence pas l'import plusieurs fois.",details:"Vérifie le rapport d'import, identifie le type de doublons puis utilise les outils de nettoyage prévus si disponibles. Garde une sauvegarde avant suppression."},
];

function score(entry:UserGuideEntry,q:string){
  const nq=norm(q); const qt=new Set(toks(q)); let s=0;
  for(const a of [entry.title,...entry.aliases]){
    const na=norm(a); if(!na) continue;
    if(nq===na) s=Math.max(s,100); else if(nq.includes(na)) s=Math.max(s,70+Math.min(20,na.length/3));
    const at=toks(a); if(at.length){const hit=at.filter(t=>qt.has(t)).length; if(hit) s=Math.max(s,hit/at.length*55 + hit*3);}
  }
  return s;
}

function intent(q:string){
  const n=norm(q);
  if(/ne marche pas|marche pas|bloque|bloquee|fige|erreur|probleme|impossible|refuse|disparait|lent|lente|vide/.test(n)) return "trouble";
  if(/comment|etape|etapes|tutoriel|guide|faire pour|ou cliquer|ou aller/.test(n)) return "steps";
  if(/plus de detail|detail|explique en detail|approfond/.test(n)) return "details";
  return "short";
}

function format(entry:UserGuideEntry,kind:string):string{
  let out=`## ${entry.title.toUpperCase()}\n${kind==="short"?entry.short:entry.details}`;
  if(kind==="steps" && entry.steps?.length) out+=`\n\n## ÉTAPES\n${entry.steps.map((x,i)=>`${i+1}. ${x}`).join("\n")}`;
  if(kind==="trouble"){
    const list=entry.troubleshooting?.length?entry.troubleshooting:entry.steps;
    if(list?.length) out+=`\n\n## À VÉRIFIER\n${list.map((x,i)=>`${i+1}. ${x}`).join("\n")}`;
  }
  if(entry.checks?.length) out+=`\n\n## COMMENT SAVOIR SI C'EST BON\n${entry.checks.map(x=>`- ${x}`).join("\n")}`;
  return out;
}

export function answerAwenaUserGuideV92(question:string, context:AwenaRuntimeContext, rememberedTopic=""):AwenaReply|null{
  const q=norm(question); if(!q) return null;
  const follow=/^(et ensuite|ensuite|plus de detail|plus de details|detail|details|comment|pourquoi|ca ne marche pas|cela ne marche pas|verifier|comment verifier)$/.test(q);
  if(follow && rememberedTopic.startsWith("v92:")){
    const id=rememberedTopic.slice(4); const e=E.find(x=>x.id===id); if(e) return {text:format(e,intent(q)),knowledgeTopic:`v92:${e.id}`};
  }
  let best:UserGuideEntry|null=null,bestScore=0;
  for(const e of E){const s=score(e,question); if(s>bestScore){best=e;bestScore=s;}}
  if(!best || bestScore<34) return null;
  return {text:format(best,intent(question)),knowledgeTopic:`v92:${best.id}`};
}

export function awenaUserGuideV92Count(){return E.length;}
export function awenaUserGuideV92AliasCount(){return E.reduce((s,e)=>s+e.aliases.length,0);}
export function awenaUserGuideV92DomainCount(){return new Set(E.map(e=>e.domain)).size;}
export function awenaUserGuideV92StepCount(){return E.reduce((s,e)=>s+(e.steps?.length||0),0);}
