// @ts-nocheck
import React from "react";
import { cargoVariantLabel } from "../../lib/gameEngines/cargoEngine";
const ORANGE = "#ff9b42", GOLD = "#f6c256", GREEN = "#62e6a7", BLUE = "#56c9ff", RED = "#ef5261", SOFT = "#aab1bf";
const n = (v: any) => Number.isFinite(Number(v)) ? Number(v) : 0;
const txt = (v: any) => String(v ?? "").trim();
const pct = (a: number,b: number) => b > 0 ? `${Math.round(a/b*1000)/10}%` : "0%";
const playedAt = (r: any) => n(r?.finishedAt || r?.endedAt || r?.updatedAt || r?.createdAt);
function isCargo(r: any) { return [r?.kind,r?.mode,r?.summary?.kind,r?.summary?.mode,r?.payload?.kind,r?.payload?.mode,r?.payload?.stats?.mode].map(v=>txt(v).toLowerCase()).join("|").includes("cargo"); }
function pools(r:any){ return [r?.summary?.perPlayer,r?.payload?.summary?.perPlayer,r?.payload?.stats?.players,r?.summary?.rankings,r?.payload?.players,r?.summary?.players,r?.players].filter(Array.isArray); }
function findRow(r:any,pid:string,pname?:string){ const found:any[]=[]; for(const pool of pools(r)){ const x=pool.find((q:any)=>txt(q?.id||q?.playerId||q?.profileId)===txt(pid)) || (pname?pool.find((q:any)=>txt(q?.name||q?.playerName).toLowerCase()===txt(pname).toLowerCase()):null); if(x) found.push(x); } return found.reduce((a,x)=>({...a,...x}),null); }
function winnerIds(r:any){ return [r?.winnerIds,r?.summary?.winnerIds,r?.payload?.winnerIds,r?.winnerId,r?.summary?.winnerId].flatMap((v:any)=>Array.isArray(v)?v:v?[v]:[]).map(String); }
function Kpi({label,value,detail,color=ORANGE}:any){return <div style={{borderRadius:15,border:"1px solid rgba(255,255,255,.09)",background:"rgba(255,255,255,.035)",padding:10,minWidth:0}}><div style={{color:SOFT,fontSize:8.5,fontWeight:1000,textTransform:"uppercase"}}>{label}</div><div style={{marginTop:3,color,fontSize:20,fontWeight:1100}}>{value}</div>{detail?<div style={{marginTop:3,color:"#81889a",fontSize:8.5}}>{detail}</div>:null}</div>}
function Section({title,children,accent=ORANGE}:any){return <section style={{marginTop:11,borderRadius:18,border:"1px solid rgba(255,255,255,.09)",background:"rgba(255,255,255,.025)",padding:11}}><div style={{color:accent,fontSize:9.5,fontWeight:1000,textTransform:"uppercase",letterSpacing:.65,marginBottom:8}}>{title}</div>{children}</section>}
function Bar({label,value,max,color=ORANGE}:any){const width=max>0?Math.min(100,n(value)/max*100):0;return <div style={{display:"grid",gridTemplateColumns:"115px minmax(0,1fr) 45px",gap:7,alignItems:"center"}}><div style={{color:"#c0c5d1",fontSize:8.8,fontWeight:900}}>{label}</div><div style={{height:8,borderRadius:999,overflow:"hidden",background:"rgba(255,255,255,.07)"}}><div style={{height:"100%",width:`${width}%`,background:`linear-gradient(90deg,${color}99,${color})`}}/></div><div style={{textAlign:"right",color,fontSize:9,fontWeight:1000}}>{value}</div></div>}

export default function CargoStatsTabFull({ records = [], playerId, playerName }: any) {
  const [range,setRange]=React.useState("all"); const now=Date.now(); const ranges:any={day:86400000,week:7*86400000,month:31*86400000,year:366*86400000};
  const matches=(records||[]).filter(isCargo).map((record:any)=>({record,row:findRow(record,playerId,playerName)})).filter((x:any)=>x.row).filter((x:any)=>range==="all"||playedAt(x.record)>=now-ranges[range]).sort((a:any,b:any)=>playedAt(b.record)-playedAt(a.record));
  const rows=matches.map((x:any)=>x.row); const games=matches.length; const wins=matches.filter(({record,row}:any)=>row?.win===true||winnerIds(record).includes(String(playerId))).length;
  const darts=rows.reduce((s:number,r:any)=>s+n(r?.darts),0), hits=rows.reduce((s:number,r:any)=>s+n(r?.hits),0), weight=rows.reduce((s:number,r:any)=>s+n(r?.totalWeight),0), pallets=rows.reduce((s:number,r:any)=>s+n(r?.pallets),0), contracts=rows.reduce((s:number,r:any)=>s+n(r?.completedContracts),0), parcels=rows.reduce((s:number,r:any)=>s+n(r?.parcelsDelivered),0), bonuses=rows.reduce((s:number,r:any)=>s+n(r?.parcelBonuses),0), lost=rows.reduce((s:number,r:any)=>s+n(r?.lostWeight),0), overloads=rows.reduce((s:number,r:any)=>s+n(r?.overloads),0), longest=Math.max(0,...rows.map((r:any)=>n(r?.longestSeries))), bestPallet=Math.max(0,...rows.map((r:any)=>n(r?.bestPalletWeight)));
  const variants:any={}; const series:any={}; rows.forEach((r:any)=>{Object.entries(r?.seriesCompleted||{}).forEach(([k,v])=>series[k]=(series[k]||0)+n(v));}); matches.forEach(({record}:any)=>{const v=record?.summary?.variant||record?.payload?.config?.variant||"cargo_classic";variants[v]=(variants[v]||0)+1;}); const maxSeries=Math.max(1,...Object.values(series).map(n));
  return <div style={{width:"100%",maxWidth:980,margin:"0 auto"}}>
    <div style={{display:"flex",gap:5,flexWrap:"wrap"}}>{[["all","Tout"],["day","24 h"],["week","7 j"],["month","30 j"],["year","1 an"]].map(([key,label])=><button key={key} onClick={()=>setRange(key)} style={{borderRadius:999,padding:"6px 10px",border:`1px solid ${range===key?ORANGE:"rgba(255,255,255,.10)"}`,background:range===key?`${ORANGE}18`:"rgba(255,255,255,.03)",color:range===key?ORANGE:SOFT,fontWeight:1000,fontSize:9}}>{label}</button>)}</div>
    {!games?<div style={{marginTop:16,borderRadius:18,padding:18,textAlign:"center",color:SOFT,border:"1px solid rgba(255,255,255,.08)",background:"rgba(255,255,255,.025)"}}>Aucune partie CARGO exploitable pour ce joueur.</div>:<>
      <div style={{marginTop:10,display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:7}}><Kpi label="Parties" value={games}/><Kpi label="Victoires" value={wins} detail={pct(wins,games)} color={GREEN}/><Kpi label="Poids transporté" value={`${weight} kg`} color={ORANGE}/><Kpi label="Colis livrés" value={parcels} detail={`+${bonuses} bonus`} color={BLUE}/><Kpi label="Palettes" value={pallets} color={GOLD}/><Kpi label="Contrats" value={contracts} color={GREEN}/><Kpi label="Meilleure série" value={longest} color={BLUE}/><Kpi label="Précision" value={pct(hits,darts)} detail={`${hits}/${darts}`} color={GREEN}/></div>
      <Section title="Performance logistique" accent={ORANGE}><div style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:7}}><Kpi label="Meilleure palette" value={`${bestPallet} kg`} color={GOLD}/><Kpi label="Poids perdu" value={`${lost} kg`} color={RED}/><Kpi label="Surcharges" value={overloads} color={RED}/><Kpi label="Poids / partie" value={`${games?Math.round(weight/games):0} kg`} color={ORANGE}/></div></Section>
      <Section title="Paliers de séries" accent={GREEN}><div style={{display:"grid",gap:7}}>{Object.entries(series).sort((a:any,b:any)=>n(a[0])-n(b[0])).map(([key,value]:any)=><Bar key={key} label={`${key} touche${n(key)>1?"s":""}`} value={value} max={maxSeries} color={n(key)>=5?GOLD:n(key)>=4?ORANGE:GREEN}/>)}</div></Section>
      <Section title="Variantes jouées" accent={BLUE}><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{Object.entries(variants).map(([key,value]:any)=><div key={key} style={{borderRadius:12,padding:"8px 10px",border:"1px solid rgba(255,255,255,.09)",background:"rgba(255,255,255,.035)"}}><strong style={{color:BLUE}}>{cargoVariantLabel(key as any)}</strong><span style={{marginLeft:7,color:SOFT,fontSize:9}}>{value} partie{n(value)>1?"s":""}</span></div>)}</div></Section>
      <Section title="Parties récentes"><div style={{display:"grid",gap:7}}>{matches.slice(0,12).map(({record,row}:any,index:number)=>{const won=row?.win===true||winnerIds(record).includes(String(playerId));const variant=record?.summary?.variant||record?.payload?.config?.variant||"cargo_classic";const parcel=variant==="parcel_delivery";return <div key={record?.id||index} style={{display:"grid",gridTemplateColumns:"42px minmax(0,1fr) auto",gap:8,alignItems:"center",padding:9,borderRadius:14,border:`1px solid ${won?ORANGE+"66":"rgba(255,255,255,.08)"}`,background:won?`${ORANGE}0c`:"rgba(255,255,255,.025)"}}><div style={{width:38,height:38,borderRadius:12,display:"grid",placeItems:"center",background:won?ORANGE:"rgba(255,255,255,.06)",color:won?"#111":"#d1d5df",fontSize:9,fontWeight:1100}}>{won?"WIN":`#${n(row?.rank)||"—"}`}</div><div><div style={{fontWeight:1000,fontSize:10}}>{new Date(playedAt(record)||Date.now()).toLocaleDateString("fr-FR")} · {cargoVariantLabel(variant)}</div><div style={{color:SOFT,fontSize:8.8}}>{n(row?.pallets)} palettes · série {n(row?.longestSeries)} · {pct(n(row?.hits),n(row?.darts))}</div></div><strong style={{color:parcel?BLUE:ORANGE,fontSize:17}}>{parcel?n(row?.parcelsDelivered):`${n(row?.totalWeight)} kg`}</strong></div>})}</div></Section>
    </>}
  </div>;
}
